{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"factOrders\",\"dimCalendar\",\"dimPeople\",\"dimReturns\",\"Data Source\",\"KPI\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.119.870.0 (23.07)"
      }
    ],
    "culture": "pt-BR",
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Entities": {
              "dimcalendar.monthabb": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dimCalendar",
                    "ConceptualProperty": "MonthAbb"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Month": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "medidas.indicator": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Medidas",
                    "ConceptualProperty": "@ Indicator"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "KPI": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "medidas.profit_mom": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Medidas",
                    "ConceptualProperty": "Profit MoM"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Profit MoM(%)": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              }
            },
            "Language": "en-US",
            "Version": "2.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Data Source",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "description": "Descreve o caminho do arquivo xls utilizado como fonte de dados",
        "expression": "\"C:\\Users\\richa\\Downloads\\Superstore.xlsx\" meta [IsParameterQuery=true, Type=\"Any\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "a921fb60-1f88-4e03-84e3-377521952ae5"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Dimensions"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Facts"
      }
    ],
    "relationships": [
      {
        "name": "30773edd-548e-43d6-8337-bc337a52748e",
        "fromColumn": "Ship Date",
        "fromTable": "factOrders",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_d57d6a66-d16e-48a7-b9ca-132874ffe94b"
      },
      {
        "name": "d96f154a-3fd3-453d-9a59-159229c34625",
        "fromColumn": "Order Date",
        "fromTable": "factOrders",
        "toColumn": "Date",
        "toTable": "dimCalendar"
      },
      {
        "name": "cd9441b7-df99-4c10-b5d8-eaa8443a06e1",
        "fromColumn": "Order ID",
        "fromTable": "factOrders",
        "toColumn": "Order ID",
        "toTable": "dimReturns"
      },
      {
        "name": "ccbf02aa-237c-4c75-9e5e-b6ac410a2a98",
        "fromColumn": "KeyPersonRegion",
        "fromTable": "factOrders",
        "toColumn": "KeyPersonRegion",
        "toTable": "dimPeople"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "factOrders",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Row ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9ac4be6a-6c47-4882-8df1-2d3da882ae6f",
            "sourceColumn": "Row ID",
            "summarizeBy": "none"
          },
          {
            "name": "Order ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1b81b3f3-e6d3-45d9-a86d-e3bae34dcad7",
            "sourceColumn": "Order ID",
            "summarizeBy": "none"
          },
          {
            "name": "Order Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "9857e727-8f0f-4f78-b4d1-5f62271c8924",
            "sourceColumn": "Order Date",
            "summarizeBy": "none"
          },
          {
            "name": "Ship Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "f89aa3b5-690b-4987-afc4-5e7c21326eef",
            "sourceColumn": "Ship Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_d57d6a66-d16e-48a7-b9ca-132874ffe94b"
                },
                "isDefault": true,
                "relationship": "30773edd-548e-43d6-8337-bc337a52748e"
              }
            ]
          },
          {
            "name": "Ship Mode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6fb2a0a7-a4c5-467a-88b4-0422b1ee14b8",
            "sourceColumn": "Ship Mode",
            "summarizeBy": "none"
          },
          {
            "name": "Customer ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e8cf83d6-a88b-419a-8b3b-a0c247cb1740",
            "sourceColumn": "Customer ID",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c2d33f53-f942-4739-b058-92876f4504f6",
            "sourceColumn": "Customer Name",
            "summarizeBy": "none"
          },
          {
            "name": "Segment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "676b8d38-ce52-4ec2-ba6f-080969fd5e2a",
            "sourceColumn": "Segment",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "40c79ab1-9928-4509-80d0-6ba00d8bb92b",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0eb60687-1336-49fc-99c7-8dda9561d0a6",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "43d896c3-9a2b-46f1-b35b-874d94a94145",
            "sourceColumn": "State",
            "summarizeBy": "none"
          },
          {
            "name": "Postal Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "444dd8e0-e62c-4c73-9892-1713a9786a2f",
            "sourceColumn": "Postal Code",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bd155396-ee31-4fb7-9d4c-dee2dde76462",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Product ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "88f1ae81-f623-4999-82ac-518cf343facc",
            "sourceColumn": "Product ID",
            "summarizeBy": "none"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6f406b06-a533-403a-a3fd-1cbc4014b42f",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "Sub-Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9cc1f78e-4116-40ab-bed0-dfa355f53ee0",
            "sourceColumn": "Sub-Category",
            "summarizeBy": "none"
          },
          {
            "name": "Product Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "83927836-8d7b-44b8-b0a2-935ca681fd70",
            "sourceColumn": "Product Name",
            "summarizeBy": "none"
          },
          {
            "name": "Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "58d54fe5-5f00-4659-8da2-4c44abd1fe48",
            "sourceColumn": "Sales",
            "summarizeBy": "sum"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6cd8a9d6-cfdc-498d-8a57-cb6f3e7dc0ff",
            "sourceColumn": "Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Discount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0082dc3e-566b-4772-8f25-e8d37515be1d",
            "sourceColumn": "Discount",
            "summarizeBy": "sum"
          },
          {
            "name": "Profit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cb70f031-1155-4dd0-89ed-fcc5d5f31aeb",
            "sourceColumn": "Profit",
            "summarizeBy": "sum"
          },
          {
            "name": "KeyPersonRegion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "//Cria uma chave utilizando os campos #Customer Name e #Region da tabela factOrders",
              "",
              "factOrders[Customer Name] & \"|\" & factOrders[Region]"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "1a63df18-bf00-4923-b77e-df6dc3c56e2a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Unit Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "//Retorna o valor unitário do produto",
              "",
              "factOrders[Sales] / factOrders[Quantity] / (1 - factOrders[Discount])"
            ],
            "formatString": "0.00",
            "isDataTypeInferred": true,
            "lineageTag": "1387fa02-ad5d-473e-926d-8b3ed4c2d2f7",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Unit Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "//Retorna o custo unitário do produto",
              "",
              "(factOrders[Sales] - factOrders[Profit]) / factOrders[Quantity]"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "e39b850c-57d0-4063-9367-8b3b42425fbb",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Unit Sale",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "//Retorna o valor da venda por unidade do produto",
              "",
              "factOrders[Unit Price] * (1 - factOrders[Discount])"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "7b7f67de-4e4a-48c1-9099-5d0e3e34a23a",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Ship Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "//Retorna o tempo de envio do produto após a data do pedido, em dias",
              "",
              "factOrders[Ship Date] - factOrders[Order Date]"
            ],
            "lineageTag": "cc68b628-1238-447d-9e99-02aa6c71e119",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "6de4c579-c301-4284-9cc8-a288a3e51a0c",
        "partitions": [
          {
            "name": "factOrders",
            "mode": "import",
            "queryGroup": "Facts",
            "source": {
              "expression": [
                "let",
                "    Fonte = Excel.Workbook(File.Contents(#\"Data Source\"), null, true),",
                "    Orders_Sheet = Fonte{[Item=\"Orders\",Kind=\"Sheet\"]}[Data],",
                "    #\"Linhas em Branco Removidas\" = Table.SelectRows(Orders_Sheet, each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null}))),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(#\"Linhas em Branco Removidas\", [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"Row ID\", type text}, {\"Order ID\", type text}, {\"Order Date\", type date}, {\"Ship Date\", type date}, {\"Ship Mode\", type text}, {\"Customer ID\", type text}, {\"Customer Name\", type text}, {\"Segment\", type text}, {\"Country\", type text}, {\"City\", type text}, {\"State\", type text}, {\"Postal Code\", type text}, {\"Region\", type text}, {\"Product ID\", type text}, {\"Category\", type text}, {\"Sub-Category\", type text}, {\"Product Name\", type text}, {\"Sales\", type number}, {\"Quantity\", Int64.Type}, {\"Discount\", type number}, {\"Profit\", type number}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_914ef77b-da65-48d9-8a10-d3ca970643e2",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ae107a9d-4dc6-4b58-9f81-d678210e105c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "52cf30b9-6506-443e-b578-ab5139017e35",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c0d4ef22-dcb5-4664-8c04-33968e2d6b30",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8af4f52e-b584-48b7-a57d-76a3430b8901",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "1efd4280-a20b-4595-a4e9-9f21c4da1181",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "947d817d-79a8-42e2-94d6-7fcd14686969",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "4965ef43-b2fa-4a67-830a-6fa6c7939480",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "70181fa5-3cf0-46f8-b007-ab5a851dae99",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "72747849-28d6-4d03-9d79-d430371e6b02",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "2a87a85f-f792-4630-ab71-4a3ee0374de4",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "8d24101e-a7b6-4025-96d5-7bbfa2e22bcb",
                "ordinal": 3
              }
            ],
            "lineageTag": "61c9a17e-0ffb-4816-b670-2f8cab75edfa"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "92c4a7f2-1050-4217-9e92-fb0d485487d6",
        "partitions": [
          {
            "name": "DateTableTemplate_914ef77b-da65-48d9-8a10-d3ca970643e2",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_d57d6a66-d16e-48a7-b9ca-132874ffe94b",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "12cb16cf-5813-49f2-a964-57cc5b6542a1",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "34936f0b-1f5f-4e6d-b0c6-3e1c47802f38",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "abc8414c-adfe-4a34-be6f-dafb5685f4c2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "203ced53-d402-46bd-aa49-ff58c8428745",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "32db51c4-26e3-48da-a78e-056b14415007",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b56935b7-6967-4929-9124-a1ed5a33f60e",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b9dd6006-d509-45d2-9d31-c855c367102b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "2cf04b75-403d-4907-ba0c-724ffea4ebbc",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "9e5334b5-2fa1-412a-b974-e2bc3eba9f8d",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "1d85e85b-313f-4f08-8f41-0ea021adcb9d",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "973bcc56-4a22-4fd3-bfc4-52c530053b56",
                "ordinal": 3
              }
            ],
            "lineageTag": "0b6db512-ed5d-4f9f-94e2-e6f570a5e790"
          }
        ],
        "isHidden": true,
        "lineageTag": "3cd84be8-1b2c-440f-b5f5-03e640344d4e",
        "partitions": [
          {
            "name": "LocalDateTable_d57d6a66-d16e-48a7-b9ca-132874ffe94b",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('factOrders'[Ship Date])), 1, 1), Date(Year(MAX('factOrders'[Ship Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "dimPeople",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Person",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "813dc117-9150-443b-a05b-4d0d50933d42",
            "sourceColumn": "Person",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8ab5ea28-9334-43db-a08f-f1af0080c2c0",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "KeyPersonRegion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "//Cria uma chave utilizando os campos #Person e #Region da tabela dimPeople",
              "",
              "dimPeople[Person] & \"|\" & dimPeople[Region]"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "19e8402e-b45f-4862-8180-3ee6ef4d651a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "bc99b66c-39c3-4673-a1a0-7837d18f8860",
        "partitions": [
          {
            "name": "dimPeople",
            "mode": "import",
            "queryGroup": "Dimensions",
            "source": {
              "expression": [
                "let",
                "    Fonte = Excel.Workbook(File.Contents(#\"Data Source\"), null, true),",
                "    People_Sheet = Fonte{[Item=\"People\",Kind=\"Sheet\"]}[Data],",
                "    #\"Linhas em Branco Removidas\" = Table.SelectRows(People_Sheet, each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null}))),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(#\"Linhas em Branco Removidas\", [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"Person\", type text}, {\"Region\", type text}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dimReturns",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Returned",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0bfae586-b017-44ae-afc7-c70e9bbf7851",
            "sourceColumn": "Returned",
            "summarizeBy": "none"
          },
          {
            "name": "Order ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dd5f92cb-d154-4cc9-ac9b-286cf69685f0",
            "sourceColumn": "Order ID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "17e01985-8210-4080-bb05-e687b09ff508",
        "partitions": [
          {
            "name": "dimReturns",
            "mode": "import",
            "queryGroup": "Dimensions",
            "source": {
              "expression": [
                "let",
                "    Fonte = Excel.Workbook(File.Contents(#\"Data Source\"), null, true),",
                "    Returns_Sheet = Fonte{[Item=\"Returns\",Kind=\"Sheet\"]}[Data],",
                "    #\"Linhas em Branco Removidas\" = Table.SelectRows(Returns_Sheet, each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null}))),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(#\"Linhas em Branco Removidas\", [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"Returned\", type text}, {\"Order ID\", type text}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dimCalendar",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isKey": true,
            "lineageTag": "23f0ddf7-0ba0-4ac9-b2b9-d22ec95007ec",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "64c11b98-ec6c-4beb-93d9-9a9fd4a28fca",
            "sortByColumn": "MonthNum",
            "sourceColumn": "Month",
            "summarizeBy": "none"
          },
          {
            "name": "MonthYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "6ec87ee3-d859-4f35-a9bb-c6c18c93c00b",
            "sortByColumn": "MonthYearNum",
            "sourceColumn": "MonthYear",
            "summarizeBy": "none"
          },
          {
            "name": "MonthYearNum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "cabc6c13-1ebc-46f3-9e45-897067cee5dd",
            "sourceColumn": "MonthYearNum",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "89851cf4-4573-45f6-8435-dccb897ebdbd",
            "sourceColumn": "Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "MonthNum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "eb8bbe8c-3cf3-4989-b60a-c2da437bdaef",
            "sourceColumn": "MonthNum",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d89a99b5-7227-4e74-a511-8ec05a9d58eb",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          },
          {
            "name": "MonthAbb",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "84103bfa-77a1-455f-a2a7-e3e6982f7040",
            "sortByColumn": "MonthNum",
            "sourceColumn": "MonthAbb",
            "summarizeBy": "none"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "2ac61a92-53c1-4b1b-9d51-f46ecf3fd9c3",
            "sortByColumn": "DayOfWeekNum",
            "sourceColumn": "Day",
            "summarizeBy": "none"
          },
          {
            "name": "BusinessDay",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "814882cc-3d2d-453c-87b3-53ff55602598",
            "sourceColumn": "BusinessDay",
            "summarizeBy": "none"
          },
          {
            "name": "DayOfWeekNum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4851cc7b-8d37-4171-9cbe-aeb62b89c084",
            "sourceColumn": "DayOfWeekNum",
            "summarizeBy": "none"
          }
        ],
        "dataCategory": "Time",
        "lineageTag": "a3db6081-0f90-43ac-9618-57c94f79fe45",
        "partitions": [
          {
            "name": "dimCalendar",
            "mode": "import",
            "queryGroup": "Dimensions",
            "source": {
              "expression": [
                "let",
                "    StartDate = Date.StartOfYear(List.Min(factOrders[Order Date])),",
                "    StopDate = Date.EndOfYear(List.Max(factOrders[Order Date])),",
                "    Duration = Duration.Days(StopDate-StartDate)+1,",
                "    ListDates = List.Dates(StartDate, Duration, #duration(1, 0, 0, 0)),",
                "    #\"Convertido para Tabela\" = Table.FromList(ListDates, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Convertido para Tabela\",{{\"Column1\", type date}}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Tipo Alterado\",{{\"Column1\", \"Date\"}}),",
                "    #\"Nome do Mês Inserido\" = Table.AddColumn(#\"Colunas Renomeadas\", \"Nome do Mês\", each Date.MonthName([Date]), type text),",
                "    #\"Colunas Renomeadas1\" = Table.RenameColumns(#\"Nome do Mês Inserido\",{{\"Nome do Mês\", \"Month\"}}),",
                "    #\"Nome do Mês Inserido1\" = Table.AddColumn(#\"Colunas Renomeadas1\", \"Nome do Mês\", each Date.MonthName([Date]), type text),",
                "    #\"Colunas Renomeadas6\" = Table.RenameColumns(#\"Nome do Mês Inserido1\",{{\"Nome do Mês\", \"MonthAbb\"}}),",
                "    #\"Primeiros caracteres extraídos\" = Table.TransformColumns(#\"Colunas Renomeadas6\", {{\"MonthAbb\", each Text.Start(_, 3), type text}}),",
                "    #\"Texto em Minúscula\" = Table.TransformColumns(#\"Primeiros caracteres extraídos\",{{\"MonthAbb\", Text.Lower, type text}}),",
                "    #\"Mês Inserido\" = Table.AddColumn(#\"Texto em Minúscula\", \"Mês\", each Date.Month([Date]), Int64.Type),",
                "    #\"Colunas Renomeadas2\" = Table.RenameColumns(#\"Mês Inserido\",{{\"Mês\", \"MonthNum\"}}),",
                "    #\"Coluna Personalizada Adicionada\" = Table.AddColumn(#\"Colunas Renomeadas2\", \"MonthYear\", each Text.Combine({Text.Lower(Date.ToText([Date], \"MMM\")), \"-\", Date.ToText([Date], \"yy\")}), type text),",
                "    #\"Coluna Personalizada Adicionada1\" = Table.AddColumn(#\"Coluna Personalizada Adicionada\", \"MonthYearNum\", each Text.Combine({Date.ToText([Date], \"yyyy\"), Date.ToText([Date], \"MM\")}), type text),",
                "    #\"Trimestre Inserido\" = Table.AddColumn(#\"Coluna Personalizada Adicionada1\", \"Trimestre\", each Date.QuarterOfYear([Date]), Int64.Type),",
                "    #\"Tipo Alterado2\" = Table.TransformColumnTypes(#\"Trimestre Inserido\",{{\"Trimestre\", type text}, {\"MonthYearNum\", Int64.Type}}),",
                "    #\"Sufixo Adicionado\" = Table.TransformColumns(#\"Tipo Alterado2\", {{\"Trimestre\", each _ & \"º qua\", type text}}),",
                "    #\"Colunas Renomeadas3\" = Table.RenameColumns(#\"Sufixo Adicionado\",{{\"Trimestre\", \"Quarter\"}}),",
                "    #\"Ano Inserido\" = Table.AddColumn(#\"Colunas Renomeadas3\", \"Ano\", each Date.Year([Date]), Int64.Type),",
                "    #\"Colunas Renomeadas4\" = Table.RenameColumns(#\"Ano Inserido\",{{\"Ano\", \"Year\"}}),",
                "    #\"Nome do Dia Inserido\" = Table.AddColumn(#\"Colunas Renomeadas4\", \"Nome do Dia\", each Date.DayOfWeekName([Date]), type text),",
                "    #\"Coluna Condicional Adicionada\" = Table.AddColumn(#\"Nome do Dia Inserido\", \"BusinessDay\", each if [Nome do Dia] = \"Sunday\" then 0 else 1, type any),",
                "    #\"Colunas Renomeadas5\" = Table.RenameColumns(#\"Coluna Condicional Adicionada\",{{\"Nome do Dia\", \"Day\"}}),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Colunas Renomeadas5\",{{\"BusinessDay\", Int64.Type}}),",
                "    #\"Dia da Semana Inserido\" = Table.AddColumn(#\"Tipo Alterado1\", \"Dia da Semana\", each Date.DayOfWeek([Date]), Int64.Type),",
                "    #\"Colunas Renomeadas7\" = Table.RenameColumns(#\"Dia da Semana Inserido\",{{\"Dia da Semana\", \"DayOfWeekNum\"}})",
                "in",
                "    #\"Colunas Renomeadas7\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Medidas",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "30c30389cc80472ba891bc029f394705"
          },
          {
            "name": "436ba87b-9c83-4389-a31b-ebd06a36be98",
            "value": "{\"Expression\":\"\"}"
          }
        ],
        "columns": [
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "fba360a9-a299-439e-818c-6451f9f8b772",
            "sourceColumn": "[Column]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "4e0b10fe-8c5c-4ef7-b910-680802e134bb",
        "measures": [
          {
            "name": "Orders",
            "expression": [
              "",
              "//Retorna o volume de ordens de venda",
              "",
              "DISTINCTCOUNT(factOrders[Order ID])"
            ],
            "formatString": "#,0",
            "lineageTag": "61d1018a-0c01-4390-906f-ed4855db32a0"
          },
          {
            "name": "Quantity",
            "expression": [
              "",
              "//Retorna o volume de itens vendidos",
              "",
              "SUM(factOrders[Quantity])"
            ],
            "formatString": "#,0",
            "lineageTag": "aa7f8a71-151e-4661-aead-690feb92cac3"
          },
          {
            "name": "Sales",
            "expression": [
              "",
              "//Retorna o valor arrecadado com as vendas",
              "",
              "SUM(factOrders[Sales])"
            ],
            "formatString": "#,0.00",
            "lineageTag": "68f44b62-b534-4400-902b-e61f4fedb056"
          },
          {
            "name": "Profit",
            "expression": [
              "",
              "//Retorna o lucro com a venda do produto",
              "",
              "SUM(factOrders[Profit])"
            ],
            "formatString": "#,0.00",
            "lineageTag": "392945c2-3ee9-4e18-9b01-a600af5bb875"
          },
          {
            "name": "Customers",
            "expression": [
              "",
              "//Retorna o volume de clientes",
              "",
              "DISTINCTCOUNT(factOrders[Customer ID])"
            ],
            "formatString": "#,0",
            "lineageTag": "6a2b71b3-7f18-4305-9152-a975fb040413"
          },
          {
            "name": "@ Update Date",
            "expression": [
              "",
              "//Retorna a informação da última data de dados atualizados para exibição no card",
              "",
              "\"Data updated up to \" ",
              "&",
              "FORMAT(",
              "    CALCULATE(",
              "        MAX(factOrders[Order Date]),",
              "        ALL(factOrders)",
              "    ),\"dd-MM-yyyy\"",
              ")"
            ],
            "lineageTag": "6e8565f5-82b6-4e26-ab1b-1a36397c69f9"
          },
          {
            "name": "@ Indicator",
            "expression": [
              "",
              "//Retorna o nome do indicador selecionado na tabela KPI",
              "",
              "VAR Indicator = SELECTEDVALUE('KPI'[Indicator], BLANK())",
              "",
              "RETURN",
              "",
              "SWITCH(TRUE(),",
              "        Indicator = \"Orders\", [Orders],",
              "        Indicator = \"Quantity\", [Quantity],",
              "        Indicator = \"Profit\", [Profit],",
              "        Indicator = \"Sales\", [Sales]",
              ")",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "68f5079f-ff35-4837-bab9-ad5d4acb526b"
          },
          {
            "name": "Profit MoM",
            "expression": [
              "",
              "//Compara o lucro do mês com o mês anterior",
              "",
              "var LastMonth = CALCULATE(",
              "                        [Profit],",
              "                        DATEADD(dimCalendar[Date], -1, MONTH)",
              ")",
              "RETURN",
              "",
              "DIVIDE(",
              "    [Profit] - LastMonth,",
              "    LastMonth,",
              "    BLANK()",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "21595dc5-abfb-45a9-ab21-8764722ee955"
          },
          {
            "name": "Unit Price",
            "expression": [
              "",
              "//Retorna o valor unitário do produto (mínimo)",
              "",
              "MIN(factOrders[Unit Price])"
            ],
            "formatString": "#,0.00",
            "lineageTag": "1e271f5d-4cde-42ca-b179-ce0744da264e"
          },
          {
            "name": "Ship Time",
            "expression": [
              "",
              "//Retorna o tempo médio de envio do produto após a data do pedido, em dias",
              "",
              "AVERAGEX(",
              "    VALUES(dimReturns[Order ID]),",
              "    AVERAGE(factOrders[Ship Time])",
              ")"
            ],
            "formatString": "0.0",
            "lineageTag": "8c47be81-ec18-4561-bb87-683229823aed"
          },
          {
            "name": "Cost",
            "expression": [
              "",
              "//Retorna o custo dos produtos",
              "",
              "SUMX(factOrders,",
              "    factOrders[Unit Cost] * factOrders[Quantity]",
              "    )"
            ],
            "formatString": "#,0.00",
            "lineageTag": "a1631d80-6ab3-4de7-ba94-ffe0b0c92f39"
          },
          {
            "name": "@ Indicator Text",
            "expression": [
              "",
              "//Retorna o nome do indicador selecionado na tabela KPI",
              "",
              "VAR Indicator = SELECTEDVALUE('KPI'[Indicator], BLANK())",
              "",
              "RETURN",
              "",
              "SWITCH(TRUE(),",
              "        Indicator = \"Orders\", \"Orders\",",
              "        Indicator = \"Quantity\", \"Quantity\",",
              "        Indicator = \"Profit\", \"Profit\",",
              "        Indicator = \"Sales\", \"Sales\"",
              ")",
              ""
            ],
            "lineageTag": "de2d7d71-1914-4ee8-a3f0-bba533233f7c"
          }
        ],
        "partitions": [
          {
            "name": "Medidas",
            "mode": "import",
            "source": {
              "expression": "Row(\"Column\", BLANK())",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "KPI",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Indicator",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "d89a2c93-3fc0-48fc-add8-8a8dbf790d57",
            "sortByColumn": "Index",
            "sourceColumn": "Indicator",
            "summarizeBy": "none"
          },
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "28857c22-d004-48e1-8a7f-dd3faa74e93e",
            "sourceColumn": "Index",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "isHidden": true,
        "lineageTag": "03a16618-8c3a-4fd7-b72e-90e1c8ec2b2b",
        "partitions": [
          {
            "name": "KPI",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45W8i9KSS0qVorViVYKLE3MK8ksqQRzghNzUiHCAUX5aZklSrGxAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Indicator = _t]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"Indicator\", type text}}),",
                "    #\"Índice Adicionado\" = Table.AddIndexColumn(#\"Tipo Alterado\", \"Índice\", 1, 1, Int64.Type),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Índice Adicionado\",{{\"Índice\", \"Index\"}})",
                "in",
                "    #\"Colunas Renomeadas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fields",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "b37f9e8d05da46f29e5cf004668f0ea7"
          }
        ],
        "columns": [
          {
            "name": "Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "5b45f416-a34a-4d72-aa29-b6174edf326d",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Parâmetro Campos"
                }
              ]
            },
            "sortByColumn": "Parâmetro Pedido",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parâmetro Campos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "accabaa5-c771-4adf-b45b-84ad7626ee9f",
            "sortByColumn": "Parâmetro Pedido",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parâmetro Pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "f1abe961-3380-4828-b523-28ddd893d52c",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "isHidden": true,
        "lineageTag": "d6069e29-c148-4eb4-9265-86027664ab95",
        "partitions": [
          {
            "name": "Fields",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Category\", NAMEOF('factOrders'[Category]), 0),",
                "    (\"Sub-Category\", NAMEOF('factOrders'[Sub-Category]), 1),",
                "    (\"Product Name\", NAMEOF('factOrders'[Product Name]), 2),",
                "    (\"Customer Name\", NAMEOF('factOrders'[Customer Name]), 3),",
                "    (\"Region\", NAMEOF('factOrders'[Region]), 4),",
                "    (\"State\", NAMEOF('factOrders'[State]), 5),",
                "    (\"City\", NAMEOF('factOrders'[City]), 6),",
                "    (\"Ship Mode\", NAMEOF('factOrders'[Ship Mode]), 7)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}