{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.110.1161.0 (22.10)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Facturas\",\"Parameter1\",\"Transform Sample File\",\"Sample File\",\"Transform File\",\"Medidas\",\"Clientes MOB\",\"Intervalos\",\"Terceiros\",\"Terceiros Base\"]"
      }
    ],
    "culture": "pt-PT",
    "cultures": [
      {
        "name": "pt-PT",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Parameter1",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": "#\"Sample File\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Sample File\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "c4e321a9-a3b4-4015-89dc-02191105df34",
        "queryGroup": "Transform File from Query1\\Helper Queries"
      },
      {
        "name": "Transform Sample File",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(Parameter1, null, true),",
          "    Facturas_2020_Sheet = Source{[Item=Source{0}[Item],Kind=\"Sheet\"]}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Facturas_2020_Sheet, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"FechaAsiento\", type date}, {\"FkSeries\", type text}, {\"NumFactura\", type text}, {\"AñoFactura\", type text}, {\"TipoFact\", type text}, {\"Tercero_Pag\", type text}, {\"ValorFactura\", type number}, {\"ImporteEfecto\", type number}, {\"ValorPendiente\", type number}, {\"EstadoEf\", type text}, {\"FechaSaldado\", type date}, {\"FormaPago\", type text}, {\"OrigenFra\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "8c4bd78e-e274-476a-a7ab-7a813368e7f5",
        "queryGroup": "Transform File from Query1"
      },
      {
        "name": "Sample File",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": [
          "let",
          "    Source = SharePoint.Files(\"https://gruposalvadorcaetano.sharepoint.com/sites/rigor/6825_DGAA/\", [ApiVersion = 15]),",
          "    #\"Filtered Rows\" = Table.SelectRows(Source, each [Folder Path] = \"https://gruposalvadorcaetano.sharepoint.com/sites/rigor/6825_DGAA/DGAA/03 - Documentação/33 - Importador/01 - TCAP/05 - PBI/CA/Saldos/\"),",
          "    #\"Filtered Rows1\" = Table.SelectRows(#\"Filtered Rows\", each [Extension] = \".xlsx\"),",
          "    Navigation1 = #\"Filtered Rows1\"{0}[Content]",
          "in",
          "    Navigation1"
        ],
        "kind": "m",
        "lineageTag": "2a8c41c6-4f91-4686-b4c3-e602590b0afc",
        "queryGroup": "Transform File from Query1\\Helper Queries"
      },
      {
        "name": "Transform File",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = (Parameter1 as binary) => let",
          "    Source = Excel.Workbook(Parameter1, null, true),",
          "    Facturas_2020_Sheet = Source{[Item=Source{0}[Item],Kind=\"Sheet\"]}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Facturas_2020_Sheet, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"FechaAsiento\", type date}, {\"FkSeries\", type text}, {\"NumFactura\", type text}, {\"AñoFactura\", type text}, {\"TipoFact\", type text}, {\"Tercero_Pag\", type text}, {\"ValorFactura\", type number}, {\"ImporteEfecto\", type number}, {\"ValorPendiente\", type number}, {\"EstadoEf\", type text}, {\"FechaSaldado\", type date}, {\"FormaPago\", type text}, {\"OrigenFra\", type text}})",
          "in",
          "    #\"Changed Type\"",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "e6c38d6d-9a11-48a3-97ed-f977bfdef079",
        "mAttributes": "[ FunctionQueryBinding = \"{\"\"exemplarFormulaName\"\":\"\"Transform Sample File\"\"}\" ]",
        "queryGroup": "Transform File from Query1\\Helper Queries"
      },
      {
        "name": "Clientes MOB",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(Web.Contents(\"https://gruposalvadorcaetano.sharepoint.com/sites/rigor/6825_DGAA/DGAA/08%20-%20Partilha/CA/Saldos/Clientes%20MOB.xlsx\"), null, true),",
          "    Folha1_Sheet = Source{[Item=\"Folha1\",Kind=\"Sheet\"]}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Folha1_Sheet, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Cód. Terceiro Fatura\", type text}, {\"Nome\", type text}, {\"Mapeamento cliente\", type text}, {\"Nif\", Int64.Type}}),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Nome\", \"Mapeamento cliente\", \"Nif\"})",
          "in",
          "    #\"Removed Columns\""
        ],
        "kind": "m",
        "lineageTag": "a73692cf-bd6a-4b37-8cf7-87a052d63e0f"
      },
      {
        "name": "Terceiros Base",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Sql.Database(\"SCSQLSRV3.sc.pt\\PRD\", \"BI_CA\"),",
          "    dbo_SLR_DtDMS_Accounts = Source{[Schema=\"dbo\",Item=\"SLR_DtDMS_Accounts\"]}[Data],",
          "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_SLR_DtDMS_Accounts,{\"NLR_Code\", \"SLR_Account\", \"Customer\", \"Extra_Column1\", \"SLR_Dim_Customer_Groups_GSC\"}),",
          "    #\"Expanded SLR_Dim_Customer_Groups_GSC\" = Table.ExpandRecordColumn(#\"Removed Other Columns\", \"SLR_Dim_Customer_Groups_GSC\", {\"PT_Customer_Group_Level_1_Desc\", \"PT_Customer_Group_Level_2_Desc\", \"PT_Customer_Group_Desc\", \"Customer_Group_Display_Order\"}, {\"PT_Customer_Group_Level_1_Desc\", \"PT_Customer_Group_Level_2_Desc\", \"PT_Customer_Group_Desc\", \"Customer_Group_Display_Order\"}),",
          "    #\"Grouped Rows\" = Table.Group(#\"Expanded SLR_Dim_Customer_Groups_GSC\", {\"NLR_Code\", \"SLR_Account\"}, {{\"Extra_Column1\", each List.Min([Extra_Column1]), type nullable text}})",
          "in",
          "    #\"Grouped Rows\""
        ],
        "kind": "m",
        "lineageTag": "1e5009c5-a8c9-4cc6-ba76-d0dd5a73c5ef"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transform File from Query1"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transform File from Query1\\Helper Queries"
      }
    ],
    "relationships": [
      {
        "name": "bab2e46d-78bb-486a-b979-b848b020d1f1",
        "fromColumn": "Data Fatura",
        "fromTable": "Facturas",
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "c400ad26-f37b-4893-96d6-135ba5e9e4ba",
        "fromColumn": "Date",
        "fromTable": "Calendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_727a8660-fd1f-48dc-b55a-b872d57facdd"
      },
      {
        "name": "e8e78ba1-8f7a-4703-9c14-540b0dc22085",
        "fromColumn": "Nº Tercero",
        "fromTable": "Facturas",
        "toColumn": "Nº Terceiro",
        "toTable": "Terceiros"
      },
      {
        "name": "d6b31ed4-c8de-4a98-8ac7-cd205b1cfa75",
        "fromColumn": "FechaSaldado",
        "fromTable": "Facturas",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_4eb3e398-2175-4175-bf4e-700eb12fd15d"
      },
      {
        "name": "8039327c-11b6-41a2-9c11-1907a060e681",
        "fromColumn": "Data Valor",
        "fromTable": "Facturas",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_dce65f02-524f-4c4b-b4d3-796d3cf8eaf9"
      }
    ],
    "sourceQueryCulture": "pt-PT",
    "tables": [
      {
        "name": "Facturas",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Data Fatura",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ],
            "dataType": "dateTime",
            "formatString": "yyyy-mm-dd",
            "lineageTag": "d01b9efb-0965-4f50-965e-e1df78de4d67",
            "sourceColumn": "Data Fatura",
            "summarizeBy": "none"
          },
          {
            "name": "Nº Tercero",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8380822b-bc5e-44e3-8929-c2de9efd617e",
            "sourceColumn": "Nº Tercero",
            "summarizeBy": "none"
          },
          {
            "name": "ValorFactura",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a3cd3474-b892-49f1-b539-aac744c0f6d3",
            "sourceColumn": "ValorFactura",
            "summarizeBy": "sum"
          },
          {
            "name": "OrigenFra",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c9b57627-ea13-4961-b73f-f6cc49c345a0",
            "sourceColumn": "OrigenFra",
            "summarizeBy": "none"
          },
          {
            "name": "Fatura",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5c197bdb-e8d9-4530-becb-62f7426af267",
            "sourceColumn": "Fatura",
            "summarizeBy": "none"
          },
          {
            "name": "Estado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "702fa34b-0879-4046-964e-de5bcbfe5e48",
            "sourceColumn": "Estado",
            "summarizeBy": "none"
          },
          {
            "name": "FormaPago",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5c5cea37-3784-4cf0-8a30-d93d41f2c957",
            "sourceColumn": "FormaPago",
            "summarizeBy": "none"
          },
          {
            "name": "Idade Pagamanto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "IF(Facturas[Data Valor] = BLANK(), BLANK(), DATEDIFF(Facturas[Data Fatura], Facturas[Data Valor],DAY))",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "8f931cc0-8cf2-4824-96ea-7b9583e255f9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Source.Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e94ee4c0-cb05-42eb-9bb0-73ad5fd9951c",
            "sourceColumn": "Source.Name",
            "summarizeBy": "none"
          },
          {
            "name": "ImporteEfecto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d65e386b-9bda-4f16-b4e5-8f93e003e39a",
            "sourceColumn": "ImporteEfecto",
            "summarizeBy": "sum"
          },
          {
            "name": "FechaSaldado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ],
            "dataType": "dateTime",
            "formatString": "yyyy-mm-dd",
            "lineageTag": "2832b7a1-7d1d-4578-9e35-5a5e7222f606",
            "sourceColumn": "FechaSaldado",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de Datas",
                  "table": "LocalDateTable_4eb3e398-2175-4175-bf4e-700eb12fd15d"
                },
                "isDefault": true,
                "relationship": "d6b31ed4-c8de-4a98-8ac7-cd205b1cfa75"
              }
            ]
          },
          {
            "name": "Valor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ],
            "dataType": "double",
            "expression": "Facturas[ImporteEfecto]",
            "formatString": "0.00",
            "isDataTypeInferred": true,
            "lineageTag": "ce27e79d-e9b1-411f-b420-9043624af146",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Data Valor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "",
              "IF(Facturas[FechaSaldado] <> BLANK(), ",
              "    Facturas[FechaSaldado],",
              "    IF(Facturas[FormaPago] IN {\"INT\", \"CONT\", \"NU\"} && Facturas[Estado] = \"Saldado\",",
              "        Facturas[Data Fatura],",
              "        BLANK()",
              "    )",
              ")",
              ""
            ],
            "formatString": "yyyy-mm-dd",
            "isDataTypeInferred": true,
            "lineageTag": "c2c22e9b-5cdd-4701-afc7-0275b8f11561",
            "summarizeBy": "none",
            "type": "calculated",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de Datas",
                  "table": "LocalDateTable_dce65f02-524f-4c4b-b4d3-796d3cf8eaf9"
                },
                "isDefault": true,
                "relationship": "8039327c-11b6-41a2-9c11-1907a060e681"
              }
            ]
          },
          {
            "name": "ValorPendiente",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a4c9299f-65d8-488a-ba1a-b720b9bc3af8",
            "sourceColumn": "ValorPendiente",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "bbe05525-eb7d-480b-a817-002d7c2d6c03",
        "partitions": [
          {
            "name": "Facturas-11a045f1-044e-40f0-8c6d-bcaf7fb7bdfe",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = SharePoint.Files(\"https://gruposalvadorcaetano.sharepoint.com/sites/rigor/6825_DGAA/\", [ApiVersion = 15]),",
                "    #\"Filtered Hidden Files1\" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Filtered Hidden Files1\", each [Folder Path] = \"https://gruposalvadorcaetano.sharepoint.com/sites/rigor/6825_DGAA/DGAA/03 - Documentação/33 - Importador/01 - TCAP/05 - PBI/CA/Saldos/\"),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Filtered Rows\", each [Extension] = \".xlsx\"),",
                "    #\"Invoke Custom Function1\" = Table.AddColumn(#\"Filtered Rows1\", \"Transform File\", each #\"Transform File\"([Content])),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Invoke Custom Function1\", {\"Name\", \"Source.Name\"}),",
                "    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Renamed Columns1\", {\"Source.Name\", \"Transform File\"}),",
                "    #\"Expanded Transform File\" = Table.ExpandTableColumn(#\"Removed Other Columns1\", \"Transform File\", {\"FechaAsiento\", \"FkSeries\", \"NumFactura\", \"AñoFactura\", \"TipoFact\", \"Tercero_Pag\", \"ValorFactura\", \"ImporteEfecto\", \"ValorPendiente\", \"EstadoEf\", \"FechaSaldado\", \"FormaPago\", \"OrigenFra\"}, {\"FechaAsiento\", \"FkSeries\", \"NumFactura\", \"AñoFactura\", \"TipoFact\", \"Tercero_Pag\", \"ValorFactura\", \"ImporteEfecto\", \"ValorPendiente\", \"EstadoEf\", \"FechaSaldado\", \"FormaPago\", \"OrigenFra\"}),",
                "    #\"Filtered Rows2\" = Table.SelectRows(#\"Expanded Transform File\", each ([OrigenFra] <> \"CRM_ANTICIPOS\")),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Filtered Rows2\",{{\"FechaAsiento\", type date}, {\"FkSeries\", type text}, {\"NumFactura\", type text}, {\"AñoFactura\", type text}, {\"TipoFact\", type text}, {\"Tercero_Pag\", type text}, {\"ValorFactura\", type number}, {\"ImporteEfecto\", type number}, {\"ValorPendiente\", type number}, {\"EstadoEf\", type text}, {\"FechaSaldado\", type date}, {\"FormaPago\", type text}}),",
                "    #\"Merged Columns\" = Table.CombineColumns(#\"Changed Type\",{\"FkSeries\", \"NumFactura\", \"AñoFactura\"},Combiner.CombineTextByDelimiter(\"/\", QuoteStyle.None),\"Fatura\"),",
                "    #\"Renamed Columns4\" = Table.RenameColumns(#\"Merged Columns\",{{\"FechaAsiento\", \"Data Fatura\"}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Renamed Columns4\",{\"TipoFact\"}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Removed Columns\",\"Dura‡Æo M‚dia\",\"Duração Média\",Replacer.ReplaceText,{\"EstadoEf\"}),",
                "    #\"Filtered Rows3\" = Table.SelectRows(#\"Replaced Value\", each ([EstadoEf] <> \"Eliminado\")),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Filtered Rows3\",{{\"EstadoEf\", \"Estado\"}, {\"Tercero_Pag\", \"Nº Tercero\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Medidas",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "lineageTag": "9338e942-3722-48ad-bb20-06fd6ff84314",
        "measures": [
          {
            "name": "Valor Factura",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ],
            "expression": [
              "",
              "--VAR Faturas = VALUES(Estados[Fatura])",
              "",
              "--RETURN",
              "CALCULATE(",
              "    SUMX(",
              "        SUMMARIZE(",
              "            Facturas,",
              "            Facturas[Fatura],",
              "            \"Val\", MIN(Facturas[ValorFactura])",
              "        ),",
              "        [Val]",
              "    )",
              ")"
            ],
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "7830a129-c5c4-4805-a95b-e4473e24b9b4"
          },
          {
            "name": "Valor Liquidado",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ],
            "expression": [
              "",
              "VAR De = COALESCE(SELECTEDVALUE(Intervalos[De]), 0)",
              "VAR Ate = COALESCE(SELECTEDVALUE(Intervalos[Até]), 999999)",
              "VAR Inter = SELECTEDVALUE(Intervalos[Intervalo])",
              "",
              "",
              "VAR Saldadas =",
              " FILTER(",
              "    SUMMARIZE(",
              "        Facturas,",
              "        Facturas[Fatura],",
              "        Facturas[Idade Pagamanto],",
              "        \"Total Pago\", [Valor Regularizado] + [Valor Saldado]",
              "       ",
              "    ),",
              "    //[Total Fatura] - [Total Pago] <= 0  -- Valores Negativos considera-se Saldado ? ",
              "    //&&",
              "    [Idade Pagamanto] >= De && [Idade Pagamanto] <= Ate",
              " )",
              "",
              "",
              "",
              "RETURN",
              "IF(De = BLANK(), ",
              "    [Valor Saldado]+ [Valor Regularizado],",
              "    SUMX(",
              "        Saldadas,",
              "        [Total Pago]",
              "    )",
              ")",
              ""
            ],
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "e7bddcbb-8d17-475b-8bae-8b540198e658"
          },
          {
            "name": "Dif td",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ],
            "displayFolder": "Old",
            "expression": [
              "",
              "VAR MaxDate = MAX('Calendar'[Date])",
              "",
              "RETURN",
              "CALCULATE(",
              "    [Valor Factura]",
              "    -",
              "    [Valor Liquidado TD],",
              "    'Calendar'[Date] <= MaxDate",
              ")",
              ""
            ],
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "8d1681b4-311a-45ae-98ac-34b25dcdb9bf"
          },
          {
            "name": "Valor Liquidado TD",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ],
            "displayFolder": "Old",
            "expression": [
              "",
              "VAR ValLiq = ",
              "SUMMARIZE(",
              "    Facturas,",
              "    Facturas[Fatura],",
              "    \"Val\", [Valor Liquidado]",
              ")",
              "RETURN",
              "IF(HASONEVALUE(Facturas[Fatura]),",
              "    IF(HASONEVALUE(Facturas[Data Valor]),",
              "        SUMX(",
              "            Facturas,",
              "            VAR DT = Facturas[Data Valor]",
              "            VAR FT = Facturas[Fatura]",
              "            RETURN",
              "            CALCULATE(",
              "                [Valor Liquidado],",
              "                ALL(Facturas),",
              "                Facturas[Data Valor] <= DT,",
              "                Facturas[Fatura] = FT",
              "            )",
              "        ),",
              "        SUM(Facturas[Valor])",
              "    ),",
              "    SUMX(",
              "        ValLiq,",
              "        [Val]",
              "    )",
              ")"
            ],
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "8459144b-644a-4459-93e8-0571e7efeebd"
          },
          {
            "name": "Pagamentos",
            "displayFolder": "Old",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(Facturas),",
              "    Facturas[Valor] <> 0",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "e2d13cc3-8e4b-4c5d-9784-193d7d275a04"
          },
          {
            "name": "Dias até saldar",
            "displayFolder": "Old",
            "expression": [
              "",
              "IF(HASONEVALUE(Facturas[Data Valor]), ",
              "    BLANK(),",
              "    IF([Dif td] = 0,",
              "        DATEDIFF(MIN(Facturas[Data Fatura]), MAX(Facturas[Data Valor]), DAY),",
              "        BLANK()",
              "    )",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "9a54da56-709e-440c-bb66-97cc4ce60b70"
          },
          {
            "name": "Valor Fatura TD",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ],
            "displayFolder": "Old",
            "expression": [
              "",
              "VAR MaxDate = MAX('Calendar'[Date])",
              "RETURN",
              "CALCULATE(",
              "    [Valor Factura],",
              "    'Calendar'[Date] <= MaxDate",
              ")"
            ],
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "0a7f68ee-08cc-4953-a99c-0cc4b3cc6ba8"
          },
          {
            "name": "Valor Fatura Liquidadas por Intervalo",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ],
            "displayFolder": "Old",
            "expression": [
              "",
              "VAR De = COALESCE(SELECTEDVALUE(Intervalos[De]), 0)",
              "VAR Ate = COALESCE(SELECTEDVALUE(Intervalos[Até]), 999999)",
              "VAR Inter = SELECTEDVALUE(Intervalos[Intervalo])",
              "VAR Saldadas =",
              " FILTER(",
              "    SUMMARIZE(",
              "        Facturas,",
              "        Facturas[Fatura],",
              "        \"Total Fatura\", MIN(Facturas[Valor Factura]),",
              "        \"Total Pago\", SUM(Facturas[Valor amortizado]),",
              "        \"Dias\", DATEDIFF(MIN(Facturas[Data Fatura]), MAX(Facturas[Data Pagamento]), DAY)",
              "    ),",
              "    [Total Fatura] - [Total Pago] <= 0  -- Valores Negativos considera-se Saldado ? ",
              "    &&",
              "    [Dias] >= De && [Dias] <= Ate",
              " )",
              "",
              "",
              "",
              "RETURN",
              "IF(De = BLANK(), ",
              "    BLANK(),",
              "    SUMX(",
              "        Saldadas,",
              "        [Total Fatura]",
              "    )",
              ")",
              ""
            ],
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "4331fb41-de5d-4f6f-9693-7e718be7a12e"
          },
          {
            "name": "Valor Fatura por Liquidar por Intervalo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Old",
            "expression": [
              "",
              "VAR De = SELECTEDVALUE(Intervalos[De])",
              "VAR Ate = SELECTEDVALUE(Intervalos[Até])",
              "VAR Inter = SELECTEDVALUE(Intervalos[Intervalo])",
              "VAR Saldadas =",
              " FILTER(",
              "    SUMMARIZE(",
              "        Facturas,",
              "        Facturas[Fatura],",
              "        \"Total Fatura\", MIN(Facturas[Valor Factura]),",
              "        \"Total Pago\", SUM(Facturas[Valor amortizado]),",
              "        \"Dias\", DATEDIFF(MIN(Facturas[Data Fatura]), TODAY() - 1, DAY)",
              "    ),",
              "    [Total Fatura] - [Total Pago] > 0 ",
              "    &&",
              "    [Dias] >= De && [Dias] <= Ate",
              " )",
              "",
              "",
              "",
              "RETURN",
              "IF(De = BLANK(), ",
              "    BLANK(),",
              "    SUMX(",
              "        Saldadas,",
              "        [Total Fatura]",
              "    )",
              ")",
              ""
            ],
            "lineageTag": "50c1ad5b-8cf9-4815-8a22-ee7852ae9dc5"
          },
          {
            "name": "Valor Titulado",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(Facturas[Valor]),",
              "    Facturas[Estado] = \"Titulado\"",
              ")"
            ],
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "470ba2f3-57cf-4f20-9494-22852d66941c"
          },
          {
            "name": "Valor em Contencioso",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(Facturas[Valor]),",
              "    Facturas[Estado] = \"Em contencioso\"",
              ")"
            ],
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "8ec6780a-f7fe-47b5-b603-ec43f3bd58fe"
          },
          {
            "name": "Valor Pendente",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "[Valor Factura] - [Valor Liquidado] - [Valor Titulado] - [Valor em Contencioso] - [Valor Duvidoso] - [Valor Reclamada] - [Valor Duração Média] - [Valor Não Pagado]",
              "",
              "// CALCULATE(",
              "//     SUM(Facturas[Valor]),",
              "//     Facturas[Estado] IN {\"Pendente\"}",
              "// )",
              "// CALCULATE(",
              "//     SUMX(   ",
              "//         Facturas,",
              "//         VAR DT = Facturas[FechaAsiento]",
              "//         VAR FT = Facturas[Fatura]",
              "//         RETURN",
              "//         CALCULATE(",
              "//             SUM(Facturas[Valor amortizado]),",
              "//             ALL(Facturas),",
              "//             Facturas[FechaAsiento] <= DT,",
              "//             Facturas[Fatura] = FT",
              "//         )",
              "//     )",
              "// )"
            ],
            "lineageTag": "9c958ab9-d846-4473-98ef-f15a166366dd"
          },
          {
            "name": "Valor Duvidoso",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(Facturas[Valor]),",
              "    Facturas[Estado] IN {\"Duvidoso\"}",
              ")"
            ],
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "b58b42bb-a2e6-4f66-95bd-dce45b68cfbe"
          },
          {
            "name": "Valor Reclamada",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(Facturas[Valor]),",
              "    Facturas[Estado] IN {\"Reclamada\"}",
              ")"
            ],
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "5d68d8a5-1cc8-4176-ae64-60ab63e279b8"
          },
          {
            "name": "Teste",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Valor Factura] - ([Valor Liquidado] + [Valor Pendente] + [Valor Titulado] + [Valor em Contencioso] + [Valor Duvidoso] + [Valor Reclamada] + [Valor Duração Média] + [Valor Não Pagado])",
            "lineageTag": "f21f306a-04bd-4ad9-a4bf-5bc6f7c0a9bf"
          },
          {
            "name": "Valor Duração Média",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(Facturas[Valor]),",
              "    Facturas[Estado] IN {\"Duração Média\"}",
              ")"
            ],
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "254964db-347a-419d-8ec3-80c945699925"
          },
          {
            "name": "Valor Não Pagado",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(Facturas[Valor]),",
              "    Facturas[Estado] IN {\"Não Pagado\"}",
              ")"
            ],
            "lineageTag": "5c8fa61c-1933-41b2-85fe-32a289b5c38b"
          },
          {
            "name": "Teste2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Valor Factura] - [Valor Liquidado]",
            "lineageTag": "450fe8a1-4e70-45e9-a87c-56ba5815527e"
          },
          {
            "name": "Valor Saldado",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(Facturas[Valor]),",
              "    Facturas[Estado] IN {\"Saldado\"})"
            ],
            "lineageTag": "3593f70c-2ca3-425e-aa62-dcd1ae09db44"
          },
          {
            "name": "Valor Regularizado",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(Facturas[Valor]),",
              "    Facturas[Estado] IN {\"Regularizado\"})"
            ],
            "lineageTag": "06a42564-0606-4c79-bdbe-cb30ee1d89b2"
          },
          {
            "name": "Valor Intervalo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR Tipo = SELECTEDVALUE(Intervalos[Tipo])",
              "VAR NomeMedida = SELECTEDVALUE(Intervalos[Intervalo])",
              "",
              "VAR Result = SWITCH(Tipo, ",
              "\"Intervalo\", [Valor Liquidado],",
              "\"Medida\",",
              "    SWITCH(NomeMedida,",
              "    \"Duvidoso\", [Valor Duvidoso],",
              "    \"Pendente\", [Valor Pendente]",
              "    )",
              ")",
              "",
              "Return",
              "",
              "IF( ROUND(Result, 2) = 0, BLANK(), Result)"
            ],
            "lineageTag": "5ecbf80e-f857-4384-abce-15ea8d91947b"
          }
        ],
        "partitions": [
          {
            "name": "Medidas-3340e44b-f37c-4231-b565-936fb2d2d665",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Calendar",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "b741c4f195c44dd792b93e7359245c5c"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "0aeed5dc-382c-4350-a434-668bb58f460f",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de Datas",
                  "table": "LocalDateTable_727a8660-fd1f-48dc-b55a-b872d57facdd"
                },
                "isDefault": true,
                "relationship": "c400ad26-f37b-4893-96d6-135ba5e9e4ba"
              }
            ]
          }
        ],
        "lineageTag": "fd67e1af-4c65-4cba-86ce-59276cd42fb2",
        "partitions": [
          {
            "name": "Calendar-32d09764-e1cf-4876-8d29-21c5bcdecbef",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "CALENDAR(",
                "    DATE(YEAR(MIN(Facturas[Data Fatura])), 1,1),",
                "    DATE(YEAR(MAX(Facturas[Data Fatura])), 12, 31)",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_5c6493d4-4eda-4cd7-992a-ea2c3a865ccd",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "38047331-a8d8-4196-880e-02096baee645",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2bfd28db-5b88-4765-af9e-86780cb80d44",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3394632a-dd14-4d5b-98fb-7eafbedbb5db",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d7e0977b-4e92-4062-bb98-f771c032a8c6",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a5b58304-4871-47b9-a134-7a9d19fa4d70",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Tri \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "4d8ea5e7-602f-4952-bd4d-11cb82b275a3",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "4611ade4-6753-469f-847a-f8e38744ba86",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de Datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "898aa63f-b08f-4799-bccf-f3f06560c803",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "d9a3b517-cf28-482f-881d-81299cf9a4fb",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "4a03329b-902b-4b6b-adc2-71c90f32443d",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "e90e48d9-f214-494a-a0e8-f104e13a29be",
                "ordinal": 3
              }
            ],
            "lineageTag": "9ce7f38c-a480-4aef-9f16-5d8bd38dc02b"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "26c16f37-4c70-45da-b5c2-17f02abd0bde",
        "partitions": [
          {
            "name": "DateTableTemplate_5c6493d4-4eda-4cd7-992a-ea2c3a865ccd-7d666581-39e0-464b-be89-56b225d099eb",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_727a8660-fd1f-48dc-b55a-b872d57facdd",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "18d530ee-d1df-4352-936d-8a143512d50c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "75cae80f-f048-48cf-82fe-b9267b8e461b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f6fce5ba-9ffa-4f43-b985-c92d9dfa4e42",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2ca66403-794d-4720-9f7a-55a4e2c14fb3",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "7ee032a5-3c46-4e9f-b84c-a5e8ffe375c3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Tri \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "4dd3bbcc-58b6-4750-babb-9baef4622901",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "fa24ac7a-214a-48a8-b606-566e8a514d1e",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de Datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "4f8145c7-abc7-440e-a704-560c8ca21cdd",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "5500d13a-c3cf-4ae1-abac-1b4e09c60f57",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "e1f9b767-4f8b-4d55-927b-66c1c34255b2",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "5cb0dc0b-2f5c-416f-9c9f-3b6fe3483b1c",
                "ordinal": 3
              }
            ],
            "lineageTag": "1efbe141-4150-4c95-9171-ba043b8bb35d"
          }
        ],
        "isHidden": true,
        "lineageTag": "3c11b913-ea0e-441a-9876-a512c0590fd2",
        "partitions": [
          {
            "name": "LocalDateTable_727a8660-fd1f-48dc-b55a-b872d57facdd-dba42cbc-4d50-4087-b046-397d629e6897",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calendar'[Date])), 1, 1), Date(Year(MAX('Calendar'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Intervalos",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "De",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d834faf8-6263-427a-ae91-e68c8dc0f30f",
            "sourceColumn": "De",
            "summarizeBy": "sum"
          },
          {
            "name": "Até",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "97c04867-1649-44df-8387-467c5f4042c5",
            "sourceColumn": "Até",
            "summarizeBy": "sum"
          },
          {
            "name": "Intervalo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"SortByColumn\"]"
              }
            ],
            "dataType": "string",
            "lineageTag": "4943a99d-ed79-4e12-bb3f-fcf1c1e0873e",
            "sortByColumn": "Ordem",
            "sourceColumn": "Intervalo",
            "summarizeBy": "none"
          },
          {
            "name": "Ordem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0c132065-9c21-4b5d-9410-5c3e7d146d85",
            "sourceColumn": "Ordem",
            "summarizeBy": "sum"
          },
          {
            "name": "Tipo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "92e19c4b-60d4-44ed-9bbe-073dedca77e0",
            "sourceColumn": "Tipo",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "41b6a221-edef-4bf6-9a02-ee094807e0de",
        "partitions": [
          {
            "name": "Intervalos-68e62c0c-d797-4d89-9a80-405816131cbc",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(Web.Contents(\"https://gruposalvadorcaetano.sharepoint.com/sites/rigor/6825_DGAA/DGAA/08%20-%20Partilha/CA/Saldos/Intervalos.xlsx\"), null, true),",
                "    Sheet1_Sheet = Source{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"De\", Int64.Type}, {\"Até\", Int64.Type}, {\"Intervalo\", type text}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Changed Type\",{{\"Ordem\", Int64.Type}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type1\", each [Tipo] <> null)",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Terceiros",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Nº Terceiro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "569e7933-2aec-4002-bdd6-8551e818b671",
            "sourceColumn": "Nº Terceiro",
            "summarizeBy": "none"
          },
          {
            "name": "Terceiro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5515a04c-bf49-45c8-8fb0-1664cb60eee2",
            "sourceColumn": "Terceiro",
            "summarizeBy": "none"
          },
          {
            "name": "PT_Customer_Group_Level_1_Desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataType": "string",
            "lineageTag": "91905697-26da-4309-a294-8487432a8472",
            "sourceColumn": "PT_Customer_Group_Level_1_Desc",
            "summarizeBy": "none"
          },
          {
            "name": "PT_Customer_Group_Desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"SortByColumn\",\"IsHidden\"]"
              }
            ],
            "dataType": "string",
            "lineageTag": "cb20b961-e9fc-4d59-a7d5-f5c6ef9bac83",
            "sortByColumn": "Customer_Group_Display_Order",
            "sourceColumn": "PT_Customer_Group_Desc",
            "summarizeBy": "none"
          },
          {
            "name": "Customer_Group_Display_Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "265abb8b-3bd4-4235-a304-c431bfdf101b",
            "sourceColumn": "Customer_Group_Display_Order",
            "summarizeBy": "none"
          },
          {
            "name": "MOB",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d2360fea-c612-4c4e-9247-c6a27a55ef7d",
            "sourceColumn": "MOB",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a2d01330-49ee-4958-9878-ab6c047cc226",
        "partitions": [
          {
            "name": "Terceiros-fea6803a-5a5c-44e3-9a6b-d60350a3cd2d",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"SCSQLSRV3.sc.pt\\PRD\", \"BI_CA\"),",
                "    dbo_SLR_DtDMS_Accounts = Source{[Schema=\"dbo\",Item=\"SLR_DtDMS_Accounts\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_SLR_DtDMS_Accounts,{\"NLR_Code\", \"SLR_Account\", \"Customer\", \"Extra_Column1\", \"SLR_Dim_Customer_Groups_GSC\"}),",
                "    #\"Expanded SLR_Dim_Customer_Groups_GSC\" = Table.ExpandRecordColumn(#\"Removed Other Columns\", \"SLR_Dim_Customer_Groups_GSC\", {\"PT_Customer_Group_Level_1_Desc\", \"PT_Customer_Group_Desc\", \"Customer_Group_Display_Order\"}, {\"PT_Customer_Group_Level_1_Desc\", \"PT_Customer_Group_Desc\", \"Customer_Group_Display_Order\"}),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Expanded SLR_Dim_Customer_Groups_GSC\",{{\"SLR_Account\", Order.Ascending}}),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Sorted Rows\", {\"NLR_Code\", \"SLR_Account\", \"Extra_Column1\"}, #\"Terceiros Base\", {\"NLR_Code\", \"SLR_Account\", \"Extra_Column1\"}, \"Terceiros Base\", JoinKind.Inner),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Merged Queries\",{\"Terceiros Base\"}),",
                "    #\"Merged Queries1\" = Table.NestedJoin(#\"Removed Columns\", {\"SLR_Account\"}, #\"Clientes MOB\", {\"Cód. Terceiro Fatura\"}, \"Clientes MOB\", JoinKind.LeftOuter),",
                "    #\"Expanded Clientes MOB\" = Table.ExpandTableColumn(#\"Merged Queries1\", \"Clientes MOB\", {\"Cód. Terceiro Fatura\"}, {\"Cód. Terceiro Fatura\"}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Expanded Clientes MOB\",null,\"Outros\",Replacer.ReplaceValue,{\"Cód. Terceiro Fatura\"}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Replaced Value\", \"Custom\", each if [Cód. Terceiro Fatura] = \"Outros\" then \"Outros\" else \"MOB\"),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Added Conditional Column\",{\"Cód. Terceiro Fatura\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns1\",{{\"Custom\", \"MOB\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"MOB\", type text}}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Changed Type\",{{\"SLR_Account\", \"Nº Tercero\"}}),",
                "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Renamed Columns1\",{\"NLR_Code\", \"Extra_Column1\"}),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Removed Columns2\",{{\"Customer\", \"Terceiro\"}, {\"Nº Tercero\", \"Nº Terceiro\"}})",
                "in",
                "    #\"Renamed Columns2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_4eb3e398-2175-4175-bf4e-700eb12fd15d",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "5ddb65f8-f5c0-4c4b-9bf3-23c6b9a577d1",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9786a60b-da3b-453e-b076-180583b42081",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "4893f88b-1189-43c4-8cb1-770ad09178e2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f8718014-501d-41b1-8662-f3e563cdc27c",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "19aaad21-63de-42f1-911b-28b7f3bdc090",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Tri \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "4aac7d7b-b435-4e46-9bac-1ec3cb1bad49",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8ce396cd-f83d-4a24-b503-6c39c4009ef9",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de Datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "8b6550c1-fb9f-45d5-806c-bb2b0ba3bccf",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "4f49004f-764b-44f0-90ff-c110fd596443",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "a853f21d-ea69-4147-8a18-5e608f2f05f1",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "8d895577-5386-44d0-bb1c-3bb407ca6718",
                "ordinal": 3
              }
            ],
            "lineageTag": "5bbcc4ae-7b35-4744-84c6-d3ce34bc2fa0"
          }
        ],
        "isHidden": true,
        "lineageTag": "acfa1e00-9f4a-403f-8b36-38c151b0eae1",
        "partitions": [
          {
            "name": "LocalDateTable_4eb3e398-2175-4175-bf4e-700eb12fd15d-cc5d58c4-9c42-4532-a270-0913fe5deb25",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Facturas'[FechaSaldado])), 1, 1), Date(Year(MAX('Facturas'[FechaSaldado])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_dce65f02-524f-4c4b-b4d3-796d3cf8eaf9",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "236e8bd9-85bf-4963-8ba4-aa8bfb315734",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f91b93aa-40ff-418a-9ca8-6be4a6aa013f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c93fcf19-0ba3-43b1-89e0-39271419efb0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5a01a8b1-038e-4dc6-b74b-7a6a599bb1ba",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d430f6de-73de-46fe-bef5-6c6cee955807",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Tri \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f63a121b-d5ab-48df-895f-8aa6fe4529ee",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a091211e-ee8a-4654-bd5d-903bb30cf3df",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de Datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "798f0c29-79e9-4e56-858a-e47ff83c3ce7",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "cf0bec0d-3dcb-476b-96bc-c450ea1188b4",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "40018b16-e829-4e1b-8d49-a23ede147ffb",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "04d546a7-8a04-4a1d-9893-f53818407c43",
                "ordinal": 3
              }
            ],
            "lineageTag": "38f8ac08-4893-45c0-98ba-78933552fee9"
          }
        ],
        "isHidden": true,
        "lineageTag": "0adb7014-f0f2-4a1b-a3e7-9f0e18bc2d76",
        "partitions": [
          {
            "name": "LocalDateTable_dce65f02-524f-4c4b-b4d3-796d3cf8eaf9-c27d9104-d96b-472b-84a5-3821d9ec8662",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Facturas'[Data Valor])), 1, 1), Date(Year(MAX('Facturas'[Data Valor])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}