{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.110.1161.0 (22.10)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Atividade APV\"]"
      }
    ],
    "culture": "pt-PT",
    "cultures": [
      {
        "name": "pt-PT",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "roles": [
      {
        "name": "Lexus",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "4d0a48e231b246efbda7163db33a59fc"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Atividade APV",
            "filterExpression": "[Rede] = \"Lexus\""
          }
        ]
      },
      {
        "name": "Toyota",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "8bf5c03c2c8d4c6ba60e625770a2baf9"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Atividade APV",
            "filterExpression": "[Rede] = \"Toyota\""
          }
        ]
      }
    ],
    "sourceQueryCulture": "pt-PT",
    "tables": [
      {
        "name": "Atividade APV",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Data Abertura Obra",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ],
            "dataType": "dateTime",
            "formatString": "yyyy-mm-dd",
            "lineageTag": "5b7f9264-bada-4a98-b4ef-e29e4bec7cc6",
            "sourceColumn": "Data Abertura Obra",
            "summarizeBy": "none"
          },
          {
            "name": "Rede",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "852cb4cf-ea62-4070-82da-42abac31e9bb",
            "sourceColumn": "Rede",
            "summarizeBy": "none"
          },
          {
            "name": "Classificação",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "57bb01af-1254-41ae-9666-c791a4406736",
            "sourceColumn": "Classificação",
            "summarizeBy": "none"
          },
          {
            "name": "Plataforma",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6534de85-dd4a-4f51-ad1a-47997ef8f5b7",
            "sourceColumn": "Plataforma",
            "summarizeBy": "none"
          },
          {
            "name": "Polo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "df91c6f6-c4ad-4b3c-ad96-69e70d50c971",
            "sourceColumn": "Polo",
            "summarizeBy": "none"
          },
          {
            "name": "Nº Obra",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fbfde4df-7020-4d3b-9fc5-5d50f7c8adfb",
            "sourceColumn": "Nº Obra",
            "summarizeBy": "none"
          },
          {
            "name": "Marca",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0f3d0f71-4e44-4bba-95c0-eff38342a487",
            "sourceColumn": "Marca",
            "summarizeBy": "none"
          },
          {
            "name": "Gama",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3bd82a6f-d6e9-4318-8413-c6db3b2cdaed",
            "sourceColumn": "Gama",
            "summarizeBy": "none"
          },
          {
            "name": "Matrícula",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "40264a41-5bf1-4dfa-a565-832541e9355c",
            "sourceColumn": "Matrícula",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "55141025-dffa-44a4-8587-386845b4be46",
        "partitions": [
          {
            "name": "Atividade APV-58aa246e-b23a-448c-8f07-a60a6821a93d",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"scsbisrv1.sc.pt\", \"TCAP_GERAL\"),",
                "    dbo_TEMP_PAGINATED_REPORTS = Source{[Schema=\"dbo\",Item=\"TEMP_PAGINATED_REPORTS\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_TEMP_PAGINATED_REPORTS, each [Data Abertura Obra] >= #date(2022, 1, 1) and [Data Abertura Obra] <= #date(2023, 12, 31))",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}