{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.102.845.0 (22.02)"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"PSE_Sales\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "pt-PT",
    "tables": [
      {
        "name": "PSE_Sales",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Client_Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4f91a6a9-cd49-4eb3-aa63-b247d6bb0311",
            "sourceColumn": "Client_Id",
            "summarizeBy": "count"
          },
          {
            "name": "NLR_Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "f48d59cb-90f4-44ab-846d-d49e7a2a9fba",
            "sourceColumn": "NLR_Code",
            "summarizeBy": "none"
          },
          {
            "name": "PSE_Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "8754e024-fa51-423e-8394-bb3b46f5cdcf",
            "sourceColumn": "PSE_Code",
            "summarizeBy": "none"
          },
          {
            "name": "Site_Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "dc2bee32-062a-48ab-bd02-d22c384303b4",
            "sourceColumn": "Site_Code",
            "summarizeBy": "count"
          },
          {
            "name": "PoS_Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "88d63be1-61e6-4f56-aa97-f9a045da1c94",
            "sourceColumn": "PoS_Code",
            "summarizeBy": "none"
          },
          {
            "name": "SLR_Document_Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"2070\" Group=\"LongDate\" FormatString=\"D\" /></DateTimes></Format>"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "2372f862-0b47-4378-ba18-98a32df9b3b1",
            "sourceColumn": "SLR_Document_Date",
            "summarizeBy": "none"
          },
          {
            "name": "Dpt_Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "389dbaf2-b95a-4a1c-b96b-edbcf6fedc3f",
            "sourceColumn": "Dpt_Type",
            "summarizeBy": "sum"
          },
          {
            "name": "Line_Posting",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a8766dc7-5811-411c-a4c5-baaa241d9821",
            "sourceColumn": "Line_Posting",
            "summarizeBy": "sum"
          },
          {
            "name": "LabourLine_Type_Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "af0dccda-2914-4f59-91b2-574d486775d0",
            "sourceColumn": "LabourLine_Type_Code",
            "summarizeBy": "count"
          },
          {
            "name": "VHE_Franchise_Code_DW",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "08645699-be4d-49ab-812b-a3e103799e32",
            "sourceColumn": "VHE_Franchise_Code_DW",
            "summarizeBy": "sum"
          },
          {
            "name": "VHE_Model_Code_DW",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1b0c8b2b-1f91-46fc-b292-8387844c166c",
            "sourceColumn": "VHE_Model_Code_DW",
            "summarizeBy": "sum"
          },
          {
            "name": "VHE_Franchise_Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4190eccd-5e29-433d-bbfa-f0018d0524f2",
            "sourceColumn": "VHE_Franchise_Type",
            "summarizeBy": "sum"
          },
          {
            "name": "VHE_Age_Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9c81b78f-bf05-4681-b7ae-2b9130aca642",
            "sourceColumn": "VHE_Age_Code",
            "summarizeBy": "count"
          },
          {
            "name": "VHE_Sell_Location_Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "6dd481d3-68d0-481d-9954-b71352c77c21",
            "sourceColumn": "VHE_Sell_Location_Code",
            "summarizeBy": "none"
          },
          {
            "name": "Kms",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "09118bdd-f7d6-4353-8b5f-97fc8dda4219",
            "sourceColumn": "Kms",
            "summarizeBy": "sum"
          },
          {
            "name": "Sales_Type_Service_Level_1_Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "75a90278-fb81-4c2f-8ece-e1981ee9235d",
            "sourceColumn": "Sales_Type_Service_Level_1_Code",
            "summarizeBy": "count"
          },
          {
            "name": "Sales_Type_Service_Level_2_Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ebc1b12a-ffd5-4561-a695-f629f0604fe5",
            "sourceColumn": "Sales_Type_Service_Level_2_Code",
            "summarizeBy": "count"
          },
          {
            "name": "Sales_Types_Services_DW",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1c44f493-8d93-4b0c-8ee0-e47cc651ba95",
            "sourceColumn": "Sales_Types_Services_DW",
            "summarizeBy": "sum"
          },
          {
            "name": "Customer_Type_Services_DW",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "32ccde4b-ff65-4668-b87b-e5c95a792810",
            "sourceColumn": "Customer_Type_Services_DW",
            "summarizeBy": "sum"
          },
          {
            "name": "CustomerGroup_Services",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "acdc5825-892d-4b7c-a8ed-34851f48990f",
            "sourceColumn": "CustomerGroup_Services",
            "summarizeBy": "none"
          },
          {
            "name": "Customer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "069c545d-46d8-402c-ab7b-103e63077c70",
            "sourceColumn": "Customer",
            "summarizeBy": "none"
          },
          {
            "name": "VAT_Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d6c6d35-12f5-46a5-b12f-6293f616e790",
            "sourceColumn": "VAT_Number",
            "summarizeBy": "none"
          },
          {
            "name": "SLR_Document_Account",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "95fd453e-faa6-4fa8-b156-09dbb51220d1",
            "sourceColumn": "SLR_Document_Account",
            "summarizeBy": "none"
          },
          {
            "name": "Imputation_Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "8f401234-7e8e-43fb-a638-29f8482555ef",
            "sourceColumn": "Imputation_Type",
            "summarizeBy": "none"
          },
          {
            "name": "PSE_User_Reception",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "cdbbf391-e031-4150-8391-90eaef7b9764",
            "sourceColumn": "PSE_User_Reception",
            "summarizeBy": "none"
          },
          {
            "name": "PSE_User_Invoice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "23b9ce6b-5d80-41e0-b584-ccd56682e5bd",
            "sourceColumn": "PSE_User_Invoice",
            "summarizeBy": "none"
          },
          {
            "name": "Operator",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "00218373-76b0-4df1-a896-574168d63013",
            "sourceColumn": "Operator",
            "summarizeBy": "none"
          },
          {
            "name": "AdvPay_ValueIncluded",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a45afada-d2b5-4806-b657-8272286ff5e0",
            "sourceColumn": "AdvPay_ValueIncluded",
            "summarizeBy": "sum"
          },
          {
            "name": "Posting_Sell_Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8542fe32-c191-4d56-b836-5b71497f14d9",
            "sourceColumn": "Posting_Sell_Value",
            "summarizeBy": "sum"
          },
          {
            "name": "Posting_Discount_Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cc573143-8e07-4c7d-822b-20e651772ef7",
            "sourceColumn": "Posting_Discount_Value",
            "summarizeBy": "sum"
          },
          {
            "name": "Cost_Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1675c715-e045-43ac-85ac-b16072077b80",
            "sourceColumn": "Cost_Value",
            "summarizeBy": "sum"
          },
          {
            "name": "Menu_Difference",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cd052ec6-b57e-45df-afbe-296d0aad14e2",
            "sourceColumn": "Menu_Difference",
            "summarizeBy": "sum"
          },
          {
            "name": "Menu_Difference2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f9e81fad-76e7-4290-86a3-212cc769942b",
            "sourceColumn": "Menu_Difference2",
            "summarizeBy": "sum"
          },
          {
            "name": "Invoiced_Hours",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4cb0e0cf-5737-4bca-a4c9-74f3c5944d1d",
            "sourceColumn": "Invoiced_Hours",
            "summarizeBy": "sum"
          },
          {
            "name": "Real_Hours",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e6568d95-e30c-4207-8410-b141abca0143",
            "sourceColumn": "Real_Hours",
            "summarizeBy": "sum"
          },
          {
            "name": "Clocking",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "35696d6a-926f-4dac-8398-3b8949a542d5",
            "sourceColumn": "Clocking",
            "summarizeBy": "sum"
          },
          {
            "name": "Contribution",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "517ddabc-9642-4aab-84c6-3ca25d38db83",
            "sourceColumn": "Contribution",
            "summarizeBy": "sum"
          },
          {
            "name": "Num_Entries",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "83c42869-fd46-4139-8063-430727d84b27",
            "sourceColumn": "Num_Entries",
            "summarizeBy": "sum"
          },
          {
            "name": "Net_Sell_Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7e01425b-c899-4a4f-86b7-4594ebfeab90",
            "sourceColumn": "Net_Sell_Value",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross_Margin_Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c1100783-c039-4f90-a50a-60e320c453c7",
            "sourceColumn": "Gross_Margin_Value",
            "summarizeBy": "sum"
          },
          {
            "name": "Value_Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d9882db3-3f03-4884-ae74-e75a79ceb96b",
            "sourceColumn": "Value_Type",
            "summarizeBy": "sum"
          },
          {
            "name": "PSE_User_LineCreation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "cb04bb9d-a98f-4140-b47c-51b0f4dcee95",
            "sourceColumn": "PSE_User_LineCreation",
            "summarizeBy": "none"
          },
          {
            "name": "CPG_Campaign_Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d6fcd787-d31f-4e92-b2fc-813fcd34fc64",
            "sourceColumn": "CPG_Campaign_Code",
            "summarizeBy": "count"
          },
          {
            "name": "CPG_AdditionalSales_Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6b53b383-d086-4d04-8e5a-e919f9e228df",
            "sourceColumn": "CPG_AdditionalSales_Code",
            "summarizeBy": "count"
          },
          {
            "name": "CPG_Campaign_Desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "a2226f5a-6943-44fb-b300-481df716a17d",
            "sourceColumn": "CPG_Campaign_Desc",
            "summarizeBy": "none"
          },
          {
            "name": "CPG_AdditionalSales_Desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "a3e437a9-aff8-47f5-af02-64231b8927ff",
            "sourceColumn": "CPG_AdditionalSales_Desc",
            "summarizeBy": "none"
          },
          {
            "name": "CPG_Campaign_Included",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "110f0fb4-14c3-4c22-8a75-c9d311c1301c",
            "sourceColumn": "CPG_Campaign_Included",
            "summarizeBy": "sum"
          },
          {
            "name": "CPG_AdditionalSales_Included",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "dd148078-38c6-4b1d-846d-db131747b502",
            "sourceColumn": "CPG_AdditionalSales_Included",
            "summarizeBy": "sum"
          },
          {
            "name": "CPG_Operation_Code_Display",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "ee101263-5927-4bf6-954d-d5330da61bc7",
            "sourceColumn": "CPG_Operation_Code_Display",
            "summarizeBy": "none"
          },
          {
            "name": "CPG_Campaign_Initial_Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "5dfecb3c-bf77-41ab-b2cb-1c373bfc4015",
            "sourceColumn": "CPG_Campaign_Initial_Period",
            "summarizeBy": "none"
          },
          {
            "name": "CPG_Campaign_Final_Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "e1ceb53c-116d-48fb-ab4e-2702bd4d14d4",
            "sourceColumn": "CPG_Campaign_Final_Period",
            "summarizeBy": "none"
          },
          {
            "name": "CPG_AdditionalSales_Initial_Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "ce701b56-611c-464c-a321-f736cd4b1df2",
            "sourceColumn": "CPG_AdditionalSales_Initial_Period",
            "summarizeBy": "none"
          },
          {
            "name": "CPG_AdditionalSales_Final_Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "5b409d5f-8db8-4f13-9873-0abc303f498e",
            "sourceColumn": "CPG_AdditionalSales_Final_Period",
            "summarizeBy": "none"
          },
          {
            "name": "CPG_Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "078ec773-5e59-496f-bed2-068e44944a7c",
            "sourceColumn": "CPG_Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "CPG_Campaign_Commission",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9a5ff4c4-7cbe-44aa-8fd4-a4607912ee6d",
            "sourceColumn": "CPG_Campaign_Commission",
            "summarizeBy": "sum"
          },
          {
            "name": "CPG_AdditionalSales_Commission",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "81599b28-1d58-4600-bc69-5b3c19b8e5f1",
            "sourceColumn": "CPG_AdditionalSales_Commission",
            "summarizeBy": "sum"
          },
          {
            "name": "Currency_Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "47a23d58-c9b2-4042-89f1-5931340d43c6",
            "sourceColumn": "Currency_Rate",
            "summarizeBy": "sum"
          },
          {
            "name": "TMP_Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8f4f5c0b-78c5-4b81-b41d-1937c9e69744",
            "sourceColumn": "TMP_Flag",
            "summarizeBy": "sum"
          },
          {
            "name": "Department_Type_Level_1_Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0396f86d-dec0-4f43-a7f6-8a654371367f",
            "sourceColumn": "Department_Type_Level_1_Code",
            "summarizeBy": "count"
          }
        ],
        "lineageTag": "19d3d3d0-d104-4041-a5ee-db0049091f5d",
        "partitions": [
          {
            "name": "PSE_Sales-f41059fa-467d-429d-976e-84f80614eaea",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"SCSQLSRV3.sc.pt\\PRD\", \"BI_CA\", [CreateNavigationProperties=false]),",
                "    dbo_PSE_CBE_Services_Sales_GSC = Source{[Schema=\"dbo\",Item=\"PSE_CBE_Services_Sales_GSC\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_PSE_CBE_Services_Sales_GSC,{\"SKey_Id\", \"Environment\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Columns\",{{\"SLR_Document_Date\", type date}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}