{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"BI_DEALERS\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.127.1327.0 (24.03)"
      }
    ],
    "culture": "pt-PT",
    "cultures": [
      {
        "name": "pt-PT",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "pt-PT",
    "tables": [
      {
        "name": "BI_DEALERS",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "BRAND",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "043f6c53-a871-4a67-9bf8-48b9624a8051",
            "sourceColumn": "BRAND",
            "sourceProviderType": "varchar(100)",
            "summarizeBy": "none"
          },
          {
            "name": "OID_DEALER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "714e5fd6-9b65-42f4-bf49-561db3949693",
            "sourceColumn": "OID_DEALER",
            "sourceProviderType": "varchar(20)",
            "summarizeBy": "none"
          },
          {
            "name": "OID_PARENT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cbb907a1-5592-42a6-80b1-c2fa11e07052",
            "sourceColumn": "OID_PARENT",
            "sourceProviderType": "varchar(20)",
            "summarizeBy": "none"
          },
          {
            "name": "END",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b3d2d773-8b8e-44fc-b818-1d76951e9962",
            "sourceColumn": "END",
            "sourceProviderType": "varchar(180)",
            "summarizeBy": "none"
          },
          {
            "name": "CPEXT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4129f316-6f6b-4ef1-b1fe-9575b240e2e3",
            "sourceColumn": "CPEXT",
            "sourceProviderType": "varchar(50)",
            "summarizeBy": "none"
          },
          {
            "name": "STATUS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c527323f-04ce-4eeb-8d6b-eabbe595e03e",
            "sourceColumn": "STATUS",
            "sourceProviderType": "char",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "14f961b3-620e-406b-8c7d-2405584215fe",
        "partitions": [
          {
            "name": "BI_DEALERS",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Origem = Sql.Database(\"scsbisrv1.sc.pt\", \"TCAP_GERAL\"),",
                "    dbo_BI_DEALERS = Origem{[Schema=\"dbo\",Item=\"BI_DEALERS\"]}[Data],",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(dbo_BI_DEALERS,{\"BRAND\", \"OID_DEALER\", \"OID_PARENT\", \"END\", \"CPEXT\", \"STATUS\"})",
                "in",
                "    #\"Outras Colunas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}