{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.102.845.0 (22.02)"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"VHE_CBE_Sales_GSC\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "pt-PT",
    "tables": [
      {
        "name": "VHE_CBE_Sales_GSC",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Client_Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6b518aeb-b6c0-4fe8-9032-cb814f816dfb",
            "sourceColumn": "Client_Id",
            "summarizeBy": "count"
          },
          {
            "name": "Environment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "be65e42b-380c-4cc3-b647-abd368bbfd2d",
            "sourceColumn": "Environment",
            "summarizeBy": "sum"
          },
          {
            "name": "NLR_Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "da776e33-e632-49c0-a745-419ab52124a6",
            "sourceColumn": "NLR_Code",
            "summarizeBy": "none"
          },
          {
            "name": "VHE_Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "bbb4d3ef-561b-4b53-99f2-1505375f69e5",
            "sourceColumn": "VHE_Code",
            "summarizeBy": "none"
          },
          {
            "name": "VHE_Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "0e2f245b-b7bf-4822-bc4a-39a48b9aa3a7",
            "sourceColumn": "VHE_Type",
            "summarizeBy": "none"
          },
          {
            "name": "VHE_Type_Original",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "7967284a-ac1c-49f3-add0-62d46e40a496",
            "sourceColumn": "VHE_Type_Original",
            "summarizeBy": "none"
          },
          {
            "name": "VHE_Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "4f38c356-c79f-4fd4-b151-a2116c57d9fb",
            "sourceColumn": "VHE_Number",
            "summarizeBy": "none"
          },
          {
            "name": "SLR_Document",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "17528264-8d1c-4b37-ab54-7480c63dfc81",
            "sourceColumn": "SLR_Document",
            "summarizeBy": "none"
          },
          {
            "name": "SLR_Document_Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"2070\" Group=\"LongDate\" FormatString=\"D\" /></DateTimes></Format>"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "e2c5aa3f-4ee0-4d41-b316-d35f3ea69a87",
            "sourceColumn": "SLR_Document_Date",
            "summarizeBy": "none"
          },
          {
            "name": "SLR_Document_Account",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "18b09a93-2907-448d-b24d-c7733dc4a67e",
            "sourceColumn": "SLR_Document_Account",
            "summarizeBy": "none"
          },
          {
            "name": "Customer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "ca68498e-25f9-48c7-8d8d-a976171e1467",
            "sourceColumn": "Customer",
            "summarizeBy": "none"
          },
          {
            "name": "VAT_Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "24a6ac50-f1f6-450e-8748-c4ccdae793db",
            "sourceColumn": "VAT_Number",
            "summarizeBy": "none"
          },
          {
            "name": "Customer_Email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "78fa094d-50dd-416a-9cde-37fc874ed7fd",
            "sourceColumn": "Customer_Email",
            "summarizeBy": "none"
          },
          {
            "name": "Customer_Post_Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "f562ef50-fafd-46bc-8d53-420e17916882",
            "sourceColumn": "Customer_Post_Code",
            "summarizeBy": "none"
          },
          {
            "name": "Customer_Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "339b0d49-a5fb-4544-84f4-5918b2bdd8a1",
            "sourceColumn": "Customer_Type",
            "summarizeBy": "sum"
          },
          {
            "name": "SLR_Customer_Account",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "1df8dcd2-e1e8-4b2a-a11b-95f6e6919a54",
            "sourceColumn": "SLR_Customer_Account",
            "summarizeBy": "none"
          },
          {
            "name": "PLR_Document_Account",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "ab3e47a0-a4cf-4a9e-a59b-08bf6b414383",
            "sourceColumn": "PLR_Document_Account",
            "summarizeBy": "none"
          },
          {
            "name": "Supplier",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "94f62b21-ef2c-4cec-9774-00a56575b5a4",
            "sourceColumn": "Supplier",
            "summarizeBy": "none"
          },
          {
            "name": "Supplier_Display",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "f4bb5e77-09a5-4d2e-bb1e-65853f0aafa8",
            "sourceColumn": "Supplier_Display",
            "summarizeBy": "none"
          },
          {
            "name": "CRM_Customer_Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ad8dc43d-a378-4176-bc06-134d680353b0",
            "sourceColumn": "CRM_Customer_Code",
            "summarizeBy": "count"
          },
          {
            "name": "CRM_Customer_Desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "a4a3156f-769f-4f2f-95ac-2adff3b0d465",
            "sourceColumn": "CRM_Customer_Desc",
            "summarizeBy": "none"
          },
          {
            "name": "CRM_Customer_Email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "8dbde3c8-a5e9-4639-a616-391b90f5576a",
            "sourceColumn": "CRM_Customer_Email",
            "summarizeBy": "none"
          },
          {
            "name": "Available_Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "5dd8a477-723f-477e-b676-a41e5f3dba27",
            "sourceColumn": "Available_Date",
            "summarizeBy": "none"
          },
          {
            "name": "PLR_Document_Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "26e4fbb6-9f73-44b0-934c-9589d8fd7374",
            "sourceColumn": "PLR_Document_Date",
            "summarizeBy": "none"
          },
          {
            "name": "Delivery_Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "d8595e1a-e1cc-44cf-a843-36a12c6d65af",
            "sourceColumn": "Delivery_Date",
            "summarizeBy": "none"
          },
          {
            "name": "Site_Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "97c2e563-0f30-4350-a654-0d3f718e5cdb",
            "sourceColumn": "Site_Code",
            "summarizeBy": "count"
          },
          {
            "name": "Site_Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ded7f6ee-50ed-4ddb-91ff-167e730aa3dc",
            "sourceColumn": "Site_Group",
            "summarizeBy": "sum"
          },
          {
            "name": "Sell_Location_Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "b3e83355-2046-4d75-a8f3-ade5030ec4bd",
            "sourceColumn": "Sell_Location_Code",
            "summarizeBy": "none"
          },
          {
            "name": "Sell_Location",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "44ab80af-2e69-4787-aac0-1fbadf8d11bc",
            "sourceColumn": "Sell_Location",
            "summarizeBy": "none"
          },
          {
            "name": "Franchise_Code_DW",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8b934aa9-2c36-4cb9-9ab7-e33f76aae33f",
            "sourceColumn": "Franchise_Code_DW",
            "summarizeBy": "sum"
          },
          {
            "name": "Model_Code_DW",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "41f68c79-8fde-4b10-a8b3-2a864b0a8a35",
            "sourceColumn": "Model_Code_DW",
            "summarizeBy": "sum"
          },
          {
            "name": "Variant_Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "bfb776af-83af-4875-a5e6-9ac07ddeed03",
            "sourceColumn": "Variant_Code",
            "summarizeBy": "none"
          },
          {
            "name": "Variant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "a0db3135-d058-4e97-a9af-0775cd268655",
            "sourceColumn": "Variant",
            "summarizeBy": "none"
          },
          {
            "name": "Vehicle_Class",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "b6af8020-8981-43ad-a936-8c6a645ebb10",
            "sourceColumn": "Vehicle_Class",
            "summarizeBy": "none"
          },
          {
            "name": "Vehicle_Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "1c7af33d-7f2a-45bd-9b74-df51ce9cac3c",
            "sourceColumn": "Vehicle_Type",
            "summarizeBy": "none"
          },
          {
            "name": "Vehicle_Class_DW",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "34e46e75-b6cb-4ed8-8260-efb7b7e59e21",
            "sourceColumn": "Vehicle_Class_DW",
            "summarizeBy": "sum"
          },
          {
            "name": "Registration_Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "6e1158a9-f3dd-4c07-9de8-8a4bf517e918",
            "sourceColumn": "Registration_Number",
            "summarizeBy": "none"
          },
          {
            "name": "Registration_Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "c428a7cb-3b56-4c59-808d-b5fd499d0afc",
            "sourceColumn": "Registration_Date",
            "summarizeBy": "none"
          },
          {
            "name": "Chassis_Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "0b1881a1-487f-4913-a831-b7a542021551",
            "sourceColumn": "Chassis_Number",
            "summarizeBy": "none"
          },
          {
            "name": "Commission",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "29e764d3-6861-4aca-aa30-63c934553606",
            "sourceColumn": "Commission",
            "summarizeBy": "none"
          },
          {
            "name": "Sales_Type_Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "cf99e734-529e-41c2-8a72-06bba4a07a2d",
            "sourceColumn": "Sales_Type_Code",
            "summarizeBy": "none"
          },
          {
            "name": "Sales_Type_Code_DW",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "28f778b6-b0c0-47aa-a48d-34d87db56fdd",
            "sourceColumn": "Sales_Type_Code_DW",
            "summarizeBy": "sum"
          },
          {
            "name": "Source_Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "19911875-f3bc-480f-aa36-edd9c24f69ff",
            "sourceColumn": "Source_Code",
            "summarizeBy": "none"
          },
          {
            "name": "Source_Code_DW",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c343adf7-7d09-4a92-8229-66e08143d5eb",
            "sourceColumn": "Source_Code_DW",
            "summarizeBy": "sum"
          },
          {
            "name": "Generic_Colour_Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "b479d69d-cba6-4aea-b1cf-26cad5c34315",
            "sourceColumn": "Generic_Colour_Code",
            "summarizeBy": "none"
          },
          {
            "name": "Generic_Colour_Code_DW",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "30ab466e-4eeb-4a55-b2fe-c25bf2125a81",
            "sourceColumn": "Generic_Colour_Code_DW",
            "summarizeBy": "sum"
          },
          {
            "name": "Accounting_Reflect_Code_DW",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "576ad15e-6eae-413b-8d9e-0501f27adf38",
            "sourceColumn": "Accounting_Reflect_Code_DW",
            "summarizeBy": "sum"
          },
          {
            "name": "Account_Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "f910727e-8b17-4d30-a164-8c7e42420311",
            "sourceColumn": "Account_Status",
            "summarizeBy": "none"
          },
          {
            "name": "Salesman",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "03f9eadc-eb1e-43da-9b58-9e28da33630b",
            "sourceColumn": "Salesman",
            "summarizeBy": "none"
          },
          {
            "name": "Salesman_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "41cae216-c966-46c4-96ac-bfb82f6dcaa4",
            "sourceColumn": "Salesman_Name",
            "summarizeBy": "none"
          },
          {
            "name": "Salesman_Position",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "efcc0b4f-b0cf-48fd-991d-e6f55a3faac9",
            "sourceColumn": "Salesman_Position",
            "summarizeBy": "none"
          },
          {
            "name": "Sales_Executive",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "e86ead81-add5-4ac4-a29f-242cf7f4e41b",
            "sourceColumn": "Sales_Executive",
            "summarizeBy": "none"
          },
          {
            "name": "Sales_Executive_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "1991f7e6-c3f6-421e-9387-c75ab25cac1a",
            "sourceColumn": "Sales_Executive_Name",
            "summarizeBy": "none"
          },
          {
            "name": "Salesman_Unique",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "3a50e63c-13f3-4784-aec2-6d9ea1ac5651",
            "sourceColumn": "Salesman_Unique",
            "summarizeBy": "none"
          },
          {
            "name": "Reserved_By",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "40db3d69-825f-400b-9f9c-9f77de489aba",
            "sourceColumn": "Reserved_By",
            "summarizeBy": "none"
          },
          {
            "name": "Reserved_By_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "d4e1817b-3070-4396-b234-24cdf651cc26",
            "sourceColumn": "Reserved_By_Name",
            "summarizeBy": "none"
          },
          {
            "name": "SLR_Driver_Account",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "1df58848-6040-4a13-901e-af627b4fc203",
            "sourceColumn": "SLR_Driver_Account",
            "summarizeBy": "none"
          },
          {
            "name": "SLR_Driver_Account_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "32be8a31-d36f-4edd-85fa-77c521de0133",
            "sourceColumn": "SLR_Driver_Account_Name",
            "summarizeBy": "none"
          },
          {
            "name": "Initial_Reserved_Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "452d494c-54b0-44ee-8d15-818c7271e611",
            "sourceColumn": "Initial_Reserved_Date",
            "summarizeBy": "none"
          },
          {
            "name": "Customer_Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "04bfe3a9-5f48-445d-82d3-0d6861460298",
            "sourceColumn": "Customer_Order",
            "summarizeBy": "none"
          },
          {
            "name": "Stock_Age",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3184e471-ab2a-406d-9fdf-cf3360c6f7f8",
            "sourceColumn": "Stock_Age",
            "summarizeBy": "sum"
          },
          {
            "name": "Registration_Age",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "42985207-4f9b-4db4-adc4-982b7e9d1038",
            "sourceColumn": "Registration_Age",
            "summarizeBy": "sum"
          },
          {
            "name": "DaysInStock",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "33fc68ca-be13-4fd1-9700-fdbb1f7d6a87",
            "sourceColumn": "DaysInStock",
            "summarizeBy": "sum"
          },
          {
            "name": "DaysWithUser",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f87a8e69-aa37-4242-beb9-9e7c967b4577",
            "sourceColumn": "DaysWithUser",
            "summarizeBy": "sum"
          },
          {
            "name": "Measure_Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3bf13b85-4969-4584-99d3-642a8b2a0ab3",
            "sourceColumn": "Measure_Type",
            "summarizeBy": "sum"
          },
          {
            "name": "Posting_Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "262a594c-7e8c-484f-a95d-4a7ff66d0415",
            "sourceColumn": "Posting_Code",
            "summarizeBy": "none"
          },
          {
            "name": "Cost_Centre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "7d07f238-a19e-469c-9eb3-cea4c136974a",
            "sourceColumn": "Cost_Centre",
            "summarizeBy": "none"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9cdcbac6-de05-47b8-a542-bd20135ab221",
            "sourceColumn": "Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Variable_Margin_Divisor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "39f01a68-f8a9-4cac-9b5e-6bd18a19aa39",
            "sourceColumn": "Variable_Margin_Divisor",
            "summarizeBy": "sum"
          },
          {
            "name": "VAT_Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6f04b530-14e0-4a5a-bddb-089e46141c5d",
            "sourceColumn": "VAT_Cost",
            "summarizeBy": "sum"
          },
          {
            "name": "NRecov_Costs_1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "affa5d41-1476-4688-94b6-4dcfcdf2ea66",
            "sourceColumn": "NRecov_Costs_1",
            "summarizeBy": "sum"
          },
          {
            "name": "NRecov_Costs_2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4e9b47eb-1b64-4e3e-bf2e-f522abd9f919",
            "sourceColumn": "NRecov_Costs_2",
            "summarizeBy": "sum"
          },
          {
            "name": "NRecov_Costs_3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "56cf87c1-54df-4ee2-8f56-4ec2fe34fe5d",
            "sourceColumn": "NRecov_Costs_3",
            "summarizeBy": "sum"
          },
          {
            "name": "Consig_Adjustments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7a9e6049-54ee-44c5-a220-679525f89eec",
            "sourceColumn": "Consig_Adjustments",
            "summarizeBy": "sum"
          },
          {
            "name": "Purchase_Adjustments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "70af0fa7-edb1-4b57-81b8-c166750a5d6c",
            "sourceColumn": "Purchase_Adjustments",
            "summarizeBy": "sum"
          },
          {
            "name": "Measure_1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f7d36c9a-c8d1-4391-9036-c0339fd3c519",
            "sourceColumn": "Measure_1",
            "summarizeBy": "sum"
          },
          {
            "name": "Measure_2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b9b65587-c22e-4b8d-887a-a4866e747cce",
            "sourceColumn": "Measure_2",
            "summarizeBy": "sum"
          },
          {
            "name": "Measure_3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3d32555e-34c6-4798-9329-b00b937756ec",
            "sourceColumn": "Measure_3",
            "summarizeBy": "sum"
          },
          {
            "name": "Measure_4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "81d7e33a-d400-4c61-ada9-ba42f72815f3",
            "sourceColumn": "Measure_4",
            "summarizeBy": "sum"
          },
          {
            "name": "Measure_5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0471dc58-90ae-47c6-82d0-22e02d0e511f",
            "sourceColumn": "Measure_5",
            "summarizeBy": "sum"
          },
          {
            "name": "Measure_6",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9dd645ba-2ef6-49ad-8044-eb156206e615",
            "sourceColumn": "Measure_6",
            "summarizeBy": "sum"
          },
          {
            "name": "Measure_7",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8c6705f1-013c-4616-9b1c-56da52f3e7a0",
            "sourceColumn": "Measure_7",
            "summarizeBy": "sum"
          },
          {
            "name": "Measure_8",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ec72aff1-f1ef-47c6-8c74-181dbf45d6b8",
            "sourceColumn": "Measure_8",
            "summarizeBy": "sum"
          },
          {
            "name": "Measure_9",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c5862eeb-151a-4125-860d-ef508e5314ca",
            "sourceColumn": "Measure_9",
            "summarizeBy": "sum"
          },
          {
            "name": "Measure_10",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "68477e78-c895-43e4-9975-49339d6c3968",
            "sourceColumn": "Measure_10",
            "summarizeBy": "sum"
          },
          {
            "name": "Measure_11",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d2363058-2c6b-4a51-9a71-74130c6814ce",
            "sourceColumn": "Measure_11",
            "summarizeBy": "sum"
          },
          {
            "name": "Measure_12",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "67127f7f-8852-44b1-97ba-2c7cf7454f40",
            "sourceColumn": "Measure_12",
            "summarizeBy": "sum"
          },
          {
            "name": "Measure_13",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "093f1dc2-5fa8-4121-91d8-1b26bbe7b50e",
            "sourceColumn": "Measure_13",
            "summarizeBy": "sum"
          },
          {
            "name": "Measure_14",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a337b022-40bf-477f-8962-1b83c5b79a33",
            "sourceColumn": "Measure_14",
            "summarizeBy": "sum"
          },
          {
            "name": "Measure_15",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "aa6c2086-22d6-47b1-bacd-cc740cf9c069",
            "sourceColumn": "Measure_15",
            "summarizeBy": "sum"
          },
          {
            "name": "Measure_16",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "23008e94-beb1-4c2c-966b-b42bf7fc32e1",
            "sourceColumn": "Measure_16",
            "summarizeBy": "sum"
          },
          {
            "name": "Measure_17",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "db27b66a-1571-454f-9786-31342aca10b8",
            "sourceColumn": "Measure_17",
            "summarizeBy": "sum"
          },
          {
            "name": "Measure_18",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d2546656-ceac-412d-bb13-602ad837dd69",
            "sourceColumn": "Measure_18",
            "summarizeBy": "sum"
          },
          {
            "name": "Measure_19",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b89bdbc1-a99d-419a-976a-c806f35f229c",
            "sourceColumn": "Measure_19",
            "summarizeBy": "sum"
          },
          {
            "name": "Measure_20",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a914ad03-e72e-4e4a-8f23-c5688f556c2c",
            "sourceColumn": "Measure_20",
            "summarizeBy": "sum"
          },
          {
            "name": "Measure_21",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "972ee733-f230-4912-8ec9-bd8f1d5e3a1a",
            "sourceColumn": "Measure_21",
            "summarizeBy": "sum"
          },
          {
            "name": "Measure_22",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "677168f4-577a-4d94-b245-9e0fc455ac8c",
            "sourceColumn": "Measure_22",
            "summarizeBy": "sum"
          },
          {
            "name": "Measure_23",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "37d7a6ac-ea7e-49a9-bf87-1101166f7c68",
            "sourceColumn": "Measure_23",
            "summarizeBy": "sum"
          },
          {
            "name": "Measure_24",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bc071480-0a08-4052-b462-edd8fa8d70f4",
            "sourceColumn": "Measure_24",
            "summarizeBy": "sum"
          },
          {
            "name": "Measure_25",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7e2a1dc3-e2e4-4194-aaab-c1e5744695a9",
            "sourceColumn": "Measure_25",
            "summarizeBy": "sum"
          },
          {
            "name": "Measure_26",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f44b8e63-5efe-42ec-abb5-f246eb6f9614",
            "sourceColumn": "Measure_26",
            "summarizeBy": "sum"
          },
          {
            "name": "Measure_27",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "86060c7c-946f-4811-ab0a-c0bd4444fdc0",
            "sourceColumn": "Measure_27",
            "summarizeBy": "sum"
          },
          {
            "name": "Measure_28",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "362c41ba-db3f-4a08-9937-551d0a16bb00",
            "sourceColumn": "Measure_28",
            "summarizeBy": "sum"
          },
          {
            "name": "Measure_29",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c9b0af67-4e0f-4ed1-bb1e-c87806a094dc",
            "sourceColumn": "Measure_29",
            "summarizeBy": "sum"
          },
          {
            "name": "Measure_30",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4a482147-17a3-4445-a36e-93598339815e",
            "sourceColumn": "Measure_30",
            "summarizeBy": "sum"
          },
          {
            "name": "Measure_31",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f2c8e1e4-7897-4255-a286-afe5c7ca059f",
            "sourceColumn": "Measure_31",
            "summarizeBy": "sum"
          },
          {
            "name": "Measure_32",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b9613af6-3da9-4f39-a460-4f11efc500ad",
            "sourceColumn": "Measure_32",
            "summarizeBy": "sum"
          },
          {
            "name": "Measure_33",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4908ab00-ab9a-4000-bc18-7d2a8c954678",
            "sourceColumn": "Measure_33",
            "summarizeBy": "sum"
          },
          {
            "name": "Measure_34",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b1fd1d52-50e6-4a8e-a5f9-93333b80ce62",
            "sourceColumn": "Measure_34",
            "summarizeBy": "sum"
          },
          {
            "name": "Measure_35",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "093fd46c-97a2-443e-8fb0-7c5871da8d5f",
            "sourceColumn": "Measure_35",
            "summarizeBy": "sum"
          },
          {
            "name": "Other_Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "06e1a390-af3e-4c21-a2ee-957f6c1a26dd",
            "sourceColumn": "Other_Sales",
            "summarizeBy": "sum"
          },
          {
            "name": "Total_Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0722b0d0-521c-4863-8d22-883b53d14587",
            "sourceColumn": "Total_Sales",
            "summarizeBy": "sum"
          },
          {
            "name": "Net_Discount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "81db9172-206a-4d8c-848b-70fa7e02d30e",
            "sourceColumn": "Net_Discount",
            "summarizeBy": "sum"
          },
          {
            "name": "Total_Invoice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ee919e07-d912-404a-b41e-34b0a08a4fec",
            "sourceColumn": "Total_Invoice",
            "summarizeBy": "sum"
          },
          {
            "name": "Campaign_Bonuses",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "73554324-e2cc-4209-bae5-77e6f9d74c6d",
            "sourceColumn": "Campaign_Bonuses",
            "summarizeBy": "sum"
          },
          {
            "name": "Bonuses",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bdca8298-f3c6-4442-b94c-3f5f111e135d",
            "sourceColumn": "Bonuses",
            "summarizeBy": "sum"
          },
          {
            "name": "Base_Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d95c4e00-2e02-4484-aa83-e7be0d68e9b9",
            "sourceColumn": "Base_Cost",
            "summarizeBy": "sum"
          },
          {
            "name": "Optional_Costs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e66ca3c8-de34-452a-b6c6-13eda79a4238",
            "sourceColumn": "Optional_Costs",
            "summarizeBy": "sum"
          },
          {
            "name": "Other_Costs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9145ed34-42a8-476a-b91f-382728128870",
            "sourceColumn": "Other_Costs",
            "summarizeBy": "sum"
          },
          {
            "name": "Total_Costs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ed4b36dd-b668-4bcd-994f-c51afa0ce6db",
            "sourceColumn": "Total_Costs",
            "summarizeBy": "sum"
          },
          {
            "name": "Sales_Commissions",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e6009100-6bc1-4cd5-b788-24bccabba856",
            "sourceColumn": "Sales_Commissions",
            "summarizeBy": "sum"
          },
          {
            "name": "Fixed_Margin",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2e084138-055d-471b-8b79-c8537a198f84",
            "sourceColumn": "Fixed_Margin",
            "summarizeBy": "sum"
          },
          {
            "name": "Variable_Margin",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "90f89dc6-e01a-4e0d-a55a-10f42cb3549d",
            "sourceColumn": "Variable_Margin",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross_Margin",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "74eeba3a-15ff-47d3-b356-b1fda7b39deb",
            "sourceColumn": "Gross_Margin",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross_Margin_With_Commissions",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fdf1b185-410f-43b2-8a44-5885813eb9e3",
            "sourceColumn": "Gross_Margin_With_Commissions",
            "summarizeBy": "sum"
          },
          {
            "name": "Financing_Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d88bf9d5-df22-4848-925b-98cedd719727",
            "sourceColumn": "Financing_Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Total_Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e2b771ad-66ea-4a92-8aaf-aa823cb24997",
            "sourceColumn": "Total_Revenue",
            "summarizeBy": "sum"
          },
          {
            "name": "Insurances_Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8b9fa85b-3e5d-400c-84e2-520a06dfe8d2",
            "sourceColumn": "Insurances_Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Commissions_Fin",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "dd41fb6c-ff79-4f2d-9bc1-d7d75549fca2",
            "sourceColumn": "Commissions_Fin",
            "summarizeBy": "sum"
          },
          {
            "name": "Commissions_SA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5c3bccd9-98ca-427b-a81e-2663351deea7",
            "sourceColumn": "Commissions_SA",
            "summarizeBy": "sum"
          },
          {
            "name": "Commissions_SC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9e82f6aa-7039-40ec-ad90-7b7c61625178",
            "sourceColumn": "Commissions_SC",
            "summarizeBy": "sum"
          },
          {
            "name": "Costs_ByPurchaseRate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6aa4295f-4ca0-43df-b077-f143f5e8bf20",
            "sourceColumn": "Costs_ByPurchaseRate",
            "summarizeBy": "sum"
          },
          {
            "name": "Costs_BySalesRate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b7d31f11-5858-4f85-97da-226b1d683646",
            "sourceColumn": "Costs_BySalesRate",
            "summarizeBy": "sum"
          },
          {
            "name": "Purchase_Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ab32a904-e508-4ae9-8c8a-b98487681c95",
            "sourceColumn": "Purchase_Rate",
            "summarizeBy": "sum"
          },
          {
            "name": "Sales_Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e0eaa2e6-4191-4bda-992b-cdaf4f317251",
            "sourceColumn": "Sales_Rate",
            "summarizeBy": "sum"
          },
          {
            "name": "Margin_EUR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f0f6a358-9979-4a29-82ef-55fcf709fffb",
            "sourceColumn": "Margin_EUR",
            "summarizeBy": "sum"
          },
          {
            "name": "Source_Type_Code_DW",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8ab4421f-0bcb-49dc-9569-3a63e61d0b1c",
            "sourceColumn": "Source_Type_Code_DW",
            "summarizeBy": "sum"
          },
          {
            "name": "Kms",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0de8b5b8-e76a-4cd0-a54d-839f36cf8a9c",
            "sourceColumn": "Kms",
            "summarizeBy": "sum"
          },
          {
            "name": "Fuel_Type_Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "af6cb4be-0914-4d7d-971f-d01a30a9a6a0",
            "sourceColumn": "Fuel_Type_Code",
            "summarizeBy": "count"
          },
          {
            "name": "Value_Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9ba7bfdb-815e-4345-b93e-c557575a20f8",
            "sourceColumn": "Value_Type",
            "summarizeBy": "sum"
          },
          {
            "name": "Extra_Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "9eba577b-fba0-4dd1-9fd7-de5a45353051",
            "sourceColumn": "Extra_Column1",
            "summarizeBy": "none"
          },
          {
            "name": "TMP_Record_Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "5b643cd6-e183-48e1-829d-d75938523b0c",
            "sourceColumn": "TMP_Record_Flag",
            "summarizeBy": "none"
          },
          {
            "name": "Currency_Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b1d42867-976c-40da-ad24-6632d40164be",
            "sourceColumn": "Currency_Rate",
            "summarizeBy": "sum"
          },
          {
            "name": "Special_Program",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "23455839-0a81-4496-9989-3bd8fe63bab1",
            "sourceColumn": "Special_Program",
            "summarizeBy": "none"
          },
          {
            "name": "Owner_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "772f74be-0b11-4fa1-805b-60aeb0f805b6",
            "sourceColumn": "Owner_Name",
            "summarizeBy": "none"
          },
          {
            "name": "Owner_VAT_Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "d5103cfc-6d54-45ed-8e03-eea0f5359c5a",
            "sourceColumn": "Owner_VAT_Number",
            "summarizeBy": "none"
          },
          {
            "name": "Owner_Email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "8437c42f-67c2-47a7-957b-0ff78d0895b6",
            "sourceColumn": "Owner_Email",
            "summarizeBy": "none"
          },
          {
            "name": "Owner_Post_Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "7adac3be-94da-49e4-baf6-92f3f0630a4d",
            "sourceColumn": "Owner_Post_Code",
            "summarizeBy": "none"
          },
          {
            "name": "Destination_Usage_Code_DMS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "26c7db8f-dff2-424e-a2af-a1a981ce10b8",
            "sourceColumn": "Destination_Usage_Code_DMS",
            "summarizeBy": "none"
          },
          {
            "name": "Destination_Usage_Desc_DMS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ],
            "dataType": "string",
            "lineageTag": "ca837898-dd50-4bf0-9266-5c8810c4de4f",
            "sourceColumn": "Destination_Usage_Desc_DMS",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f9075562-5f68-4de8-8fb5-b07970c169c9",
        "partitions": [
          {
            "name": "VHE_CBE_Sales_GSC-9caa878e-907f-48b7-96fa-8805c96506d7",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"SCSQLSRV3.sc.pt\\PRD\", \"BI_CA\", [CreateNavigationProperties=false]),",
                "    dbo_VHE_CBE_Sales_GSC = Source{[Schema=\"dbo\",Item=\"VHE_CBE_Sales_GSC\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_VHE_CBE_Sales_GSC,{\"SKey_Id\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Columns\",{{\"SLR_Document_Date\", type date}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}