table MEASURES_TABLE
	excludeFromModelRefresh
	lineageTag: 96d07bfe-8914-4d3e-934f-b3d98a749ae4

	measure 'PL Balance' =
			
			
			CALCULATE(
			    ABS(SUM(VIEW_NLR_FACT_BI_TRANS_PL[BALANCE])),
			    SIGNAL[PL_Code_Source_Signal_ForCalculations] = 1
			)
			-
			CALCULATE(
			    ABS(SUM(VIEW_NLR_FACT_BI_TRANS_PL[BALANCE])),
			    SIGNAL[PL_Code_Source_Signal_ForCalculations] = -1
			)
		formatString: #,0.00
		displayFolder: TransPL
		lineageTag: 66dc4b64-35ab-4435-ab58-6f03867b4ac4

	measure 'PL Balance (EUR)' =
			
			
			CALCULATE(
			    ABS(SUMX(
			    VIEW_NLR_FACT_BI_TRANS_PL,
			        DIVIDE(
			            VIEW_NLR_FACT_BI_TRANS_PL[BALANCE],
			            VIEW_NLR_FACT_BI_TRANS_PL[CURRENCY_RATE]
			        )
			    )
			    ),
			    SIGNAL[PL_Code_Source_Signal_ForCalculations] = 1
			)
			-
			CALCULATE(
			    ABS(SUMX(
			    VIEW_NLR_FACT_BI_TRANS_PL,
			        DIVIDE(
			            VIEW_NLR_FACT_BI_TRANS_PL[BALANCE],
			            VIEW_NLR_FACT_BI_TRANS_PL[CURRENCY_RATE]
			        )
			    )
			    ),
			    SIGNAL[PL_Code_Source_Signal_ForCalculations] = -1
			)
		formatString: #,0.00
		isHidden
		displayFolder: TransPL\EUR
		lineageTag: 6863130c-6e84-49dc-b173-5811aef44816

		changedProperty = IsHidden

	measure 'BL Balance' =
			
			
			SUM(VIEW_NLR_FACT_DW_TRANSBL[BALANCE])
		formatString: #,0.00
		displayFolder: TransBL
		lineageTag: 06169343-f35a-49bf-b1e7-f407fee1e502

	measure 'BL Budget Balance' =
			
			
			SUM(VIEW_NLR_FACT_BI_BL_BUDGET[BALANCE])
		formatString: #,0.00
		displayFolder: TransBL
		lineageTag: c87a8f48-178a-4e52-b578-963f702b1c30

	measure 'PL Balance (%)' =
			
			
			DIVIDE(
			    [PL Balance],
			    CALCULATE(
			        [PL Balance],
			        ALL(VIEW_NLR_DIM_PL_GSC_WITH_LANG),
			        VIEW_NLR_DIM_PL_GSC_WITH_LANG[PL_LEVEL_1_CODE] = 16
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: TransPL
		lineageTag: cd3d73d7-618d-4501-a463-0a5ba24b11d8

	measure 'PL Budget Admin' =
			
			
			CALCULATE(
			    ABS(SUM(VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[BALANCE])),
			    SIGNAL[PL_Code_Source_Signal_ForCalculations] = 1,
			    VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE_TYPE_CODE] = 4
			    )
			-
			CALCULATE(
			    ABS(SUM(VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[BALANCE])),
			    SIGNAL[PL_Code_Source_Signal_ForCalculations] = -1,
			    VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE_TYPE_CODE] = 4
			    )
		formatString: #,0.00
		displayFolder: TransPL
		lineageTag: bdc78585-9c70-4b92-8733-f9d9c1d67734

	measure 'PL Budget' =
			
			
			CALCULATE(
			    ABS(SUM(VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[BALANCE])),
			    SIGNAL[PL_Code_Source_Signal_ForCalculations] = 1,
			    VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE_TYPE_CODE] = 3
			    )
			-
			CALCULATE(
			    ABS(SUM(VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[BALANCE])),
			    SIGNAL[PL_Code_Source_Signal_ForCalculations] = -1,
			    VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE_TYPE_CODE] = 3
			    )
		formatString: #,0.00
		displayFolder: TransPL
		lineageTag: d8f81269-b588-4330-8a1a-71c01f514b33

	measure 'PL Budget (EUR)' =
			
			
			CALCULATE(
			    ABS(SUMX(
			        VIEW_NLR_FACT_BI_TRANS_PL_BUDGET,
			        DIVIDE(
			            VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[BALANCE],
			            VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[CURRENCY_RATE]
			        )
			    )
			),
			    SIGNAL[PL_Code_Source_Signal_ForCalculations] = 1,
			    VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE_TYPE_CODE] = 3
			)
			-
			CALCULATE(
			    ABS(SUMX(
			    VIEW_NLR_FACT_BI_TRANS_PL_BUDGET,
			        DIVIDE(
			            VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[BALANCE],
			            VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[CURRENCY_RATE]
			        )
			    )
			),
			    SIGNAL[PL_Code_Source_Signal_ForCalculations] = -1,
			    VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE_TYPE_CODE] = 3
			)
		formatString: #,0.00
		isHidden
		displayFolder: TransPL\EUR
		lineageTag: 4d5e5690-a711-43a4-ae3d-6a0a7619bc27

		changedProperty = IsHidden

	measure 'PL Budget Admin (EUR)' = ```
			
			
			CALCULATE(
			    ABS(SUMX(
			        VIEW_NLR_FACT_BI_TRANS_PL_BUDGET,
			        DIVIDE(
			            VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[BALANCE],
			            VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[CURRENCY_RATE]
			        )
			    )
			),
			    SIGNAL[PL_Code_Source_Signal_ForCalculations] = 1, 
			    VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE_TYPE_CODE] = 4
			)
			-
			CALCULATE(
			    ABS(SUMX(
			    VIEW_NLR_FACT_BI_TRANS_PL_BUDGET,
			        DIVIDE(
			            VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[BALANCE],
			            VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[CURRENCY_RATE]
			        )
			    )
			),
			    SIGNAL[PL_Code_Source_Signal_ForCalculations] = -1, 
			    VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE_TYPE_CODE] = 4
			)
			```
		formatString: #,0.00
		isHidden
		displayFolder: TransPL\EUR
		lineageTag: ee9e50ab-cb8d-41d5-9619-d703e48c8f3b

		changedProperty = IsHidden

	measure 'Last Year' = ```
			
			
			CALCULATE(
			    [PL Balance], 
			    SAMEPERIODLASTYEAR(VIEW_GBL_DIM_CALENDAR_WITH_LANG_BRIDGE[DATE])
			    )
			```
		formatString: #,0.00
		displayFolder: TransPL
		lineageTag: 23274b7e-e579-44b6-8f02-4244acd22ac8

	measure 'Last Year (EUR)' = ```
			
			
			CALCULATE(
			    [PL Balance (EUR)], 
			    SAMEPERIODLASTYEAR(VIEW_GBL_DIM_CALENDAR_WITH_LANG_BRIDGE[DATE])
			    )
			```
		formatString: #,0.00
		isHidden
		displayFolder: TransPL\EUR
		lineageTag: 62b2402b-aaf4-497d-8ccc-787997e49be6

		changedProperty = IsHidden

	measure 'Deviation N/N-1' =
			
			
			[PL Balance] - [Last Year]
		formatString: #,0.00
		displayFolder: TransPL
		lineageTag: 0ae3feb7-7fad-4629-8343-203506c03bef

	measure 'Deviation N/N-1 (EUR)' =
			
			
			[PL Balance (EUR)] - [Last Year]
		formatString: #,0.00
		isHidden
		displayFolder: TransPL\EUR
		lineageTag: 1998e057-ee5e-430c-a9e9-68a3f25e793e

		changedProperty = IsHidden

	measure 'Deviation N/N Budget' =
			
			
			[PL Balance] - [PL Budget]
		formatString: #,0.00
		displayFolder: TransPL
		lineageTag: d2bdbf60-f62e-4ae0-ac06-5f0f5991e674

	measure 'Deviation N/N Budget (EUR)' =
			
			
			[PL Balance (EUR)] - [PL Budget (EUR)]
		formatString: #,0.00
		isHidden
		displayFolder: TransPL\EUR
		lineageTag: 454fd25e-c7ba-457c-92b4-618097b6ab07

		changedProperty = IsHidden

	measure 'Deviation N/N Budget Admin' =
			
			
			[PL Balance] - [PL Budget Admin]
		formatString: #,0.00
		displayFolder: TransPL
		lineageTag: 4dae6208-fa0f-4797-b1b8-ac950e44d7f4

	measure 'Deviation N/N Budget Admin (EUR)' =
			
			
			[PL Balance (EUR)] - [PL Budget Admin (EUR)]
		formatString: #,0.00
		isHidden
		displayFolder: TransPL\EUR
		lineageTag: 2b2de285-0729-4c2f-ab88-51a0e4559c77

		changedProperty = IsHidden

	measure 'Deviation N/N Budget (%)' =
			
			
			DIVIDE(
			    [Deviation N/N Budget],
			    CALCULATE(
			        [PL Budget],
			        ALL(VIEW_NLR_DIM_PL_GSC_WITH_LANG),
			        VIEW_NLR_DIM_PL_GSC_WITH_LANG[PL_LEVEL_1_CODE] = 16
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: TransPL
		lineageTag: 3a0e75cb-54a4-47cf-819f-3dd814b2f869

	measure 'Deviation N/N Budget Admin (%)' =
			
			
			DIVIDE(
			    [Deviation N/N Budget Admin],
			    CALCULATE(
			        [PL Budget Admin],
			        ALL(VIEW_NLR_DIM_PL_GSC_WITH_LANG),
			        VIEW_NLR_DIM_PL_GSC_WITH_LANG[PL_LEVEL_1_CODE] = 16
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: TransPL
		lineageTag: 9f72bd8e-2252-4132-b920-ba83ec8f0423

	measure 'Deviation N/N-1 (%)' =
			
			
			DIVIDE(
			    [Deviation N/N-1],
			    CALCULATE(
			        [PL Budget],
			        ALL(VIEW_NLR_DIM_PL_GSC_WITH_LANG),
			        VIEW_NLR_DIM_PL_GSC_WITH_LANG[PL_LEVEL_1_CODE] = 16
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: TransPL
		lineageTag: f0d5c5a8-e7ef-4605-8ca7-3f81a577d358

	measure 'Last Year (%)' =
			
			
			DIVIDE(
			    [Last Year],
			    CALCULATE(
			        [Last Year],
			        ALL(VIEW_NLR_DIM_PL_GSC_WITH_LANG),
			        VIEW_NLR_DIM_PL_GSC_WITH_LANG[PL_LEVEL_1_CODE] = 16
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: TransPL
		lineageTag: 2338a5ca-d648-4a38-be3a-673b84edaa28

	measure 'PL Budget (%)' =
			
			
			DIVIDE(
			    [PL Budget],
			    CALCULATE(
			        [PL Budget],
			        ALL(VIEW_NLR_DIM_PL_GSC_WITH_LANG),
			        VIEW_NLR_DIM_PL_GSC_WITH_LANG[PL_LEVEL_1_CODE] = 16
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: TransPL
		lineageTag: ff43e8d2-9287-4684-b3e8-3ef23e46dabe

	measure 'PL Budget Admin (%)' =
			
			
			DIVIDE(
			    [PL Budget Admin],
			    CALCULATE(
			        [PL Budget Admin],
			        ALL(VIEW_NLR_DIM_PL_GSC_WITH_LANG),
			        VIEW_NLR_DIM_PL_GSC_WITH_LANG[PL_LEVEL_1_CODE] = 16
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: TransPL
		lineageTag: b8f191eb-57b6-4f2f-b23a-6b857282087a

	measure 'Visual Title' =
			
			
			SWITCH(
			    USERCULTURE(),
			    "pt-PT", SELECTEDVALUE(PBI_TABLE_TITULOS[pt-PT]),
			    "en-US", SELECTEDVALUE(PBI_TABLE_TITULOS[en-US]),
			    "es-ES", SELECTEDVALUE(PBI_TABLE_TITULOS[es-ES]),
			    "fr-FR", SELECTEDVALUE(PBI_TABLE_TITULOS[fr-FR])
			)
		displayFolder: UI
		lineageTag: e3c39bbe-87af-40f3-ba1b-623d67d1a112

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Deviation N/N Budget (EUR) (%)' =
			
			
			DIVIDE(
			    [Deviation N/N Budget (EUR)],
			    CALCULATE(
			        [PL Budget (EUR)],
			        ALL(VIEW_NLR_DIM_PL_GSC_WITH_LANG),
			        VIEW_NLR_DIM_PL_GSC_WITH_LANG[PL_LEVEL_1_CODE] = 16
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		isHidden
		displayFolder: TransPL\EUR
		lineageTag: 25b4abb3-82e2-4a1f-bf05-67484f58069b

		changedProperty = IsHidden

	measure 'Deviation N/N Budget Admin (EUR) (%)' =
			
			
			DIVIDE(
			    [Deviation N/N Budget Admin (EUR)],
			    CALCULATE(
			        [PL Budget Admin (EUR)],
			        ALL(VIEW_NLR_DIM_PL_GSC_WITH_LANG),
			        VIEW_NLR_DIM_PL_GSC_WITH_LANG[PL_LEVEL_1_CODE] = 16
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		isHidden
		displayFolder: TransPL\EUR
		lineageTag: 80466f79-7096-4152-a593-3a32fc1fb3b3

		changedProperty = IsHidden

	measure 'Deviation N/N-1 (EUR) (%)' =
			
			
			DIVIDE(
			    [Deviation N/N-1 (EUR)],
			    CALCULATE(
			        [PL Budget (EUR)],
			        ALL(VIEW_NLR_DIM_PL_GSC_WITH_LANG),
			        VIEW_NLR_DIM_PL_GSC_WITH_LANG[PL_LEVEL_1_CODE] = 16
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		isHidden
		displayFolder: TransPL\EUR
		lineageTag: 2ff0fa0e-4011-4ff4-9859-2a5e81944e0c

		changedProperty = IsHidden

	measure 'Last Year (EUR) (%)' =
			
			
			DIVIDE(
			    [Last Year (EUR)],
			    CALCULATE(
			        [Last Year (EUR)],
			        ALL(VIEW_NLR_DIM_PL_GSC_WITH_LANG),
			        VIEW_NLR_DIM_PL_GSC_WITH_LANG[PL_LEVEL_1_CODE] = 16
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		isHidden
		displayFolder: TransPL\EUR
		lineageTag: b04ecdbd-c6f2-4dcb-b449-8dc5d3dce24c

		changedProperty = IsHidden

	measure 'PL Balance (EUR) (%)' =
			
			
			DIVIDE(
			    [PL Balance (EUR)],
			    CALCULATE(
			        [PL Balance (EUR)],
			        ALL(VIEW_NLR_DIM_PL_GSC_WITH_LANG),
			        VIEW_NLR_DIM_PL_GSC_WITH_LANG[PL_LEVEL_1_CODE] = 16
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		isHidden
		displayFolder: TransPL\EUR
		lineageTag: 7c00a8c2-8a24-4838-9ada-f46f049fa5f2

		changedProperty = IsHidden

	measure 'PL Budget (EUR) (%)' =
			
			
			DIVIDE(
			    [PL Budget (EUR)],
			    CALCULATE(
			        [PL Budget (EUR)],
			        ALL(VIEW_NLR_DIM_PL_GSC_WITH_LANG),
			        VIEW_NLR_DIM_PL_GSC_WITH_LANG[PL_LEVEL_1_CODE] = 16
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		isHidden
		displayFolder: TransPL\EUR
		lineageTag: f3558bac-9d1c-4924-92dc-804b18fc1c09

		changedProperty = IsHidden

	measure 'PL Budget Admin (EUR) (%)' =
			
			
			DIVIDE(
			    [PL Budget Admin (EUR)],
			    CALCULATE(
			        [PL Budget Admin (EUR)],
			        ALL(VIEW_NLR_DIM_PL_GSC_WITH_LANG),
			        VIEW_NLR_DIM_PL_GSC_WITH_LANG[PL_LEVEL_1_CODE] = 16
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		isHidden
		displayFolder: TransPL\EUR
		lineageTag: d6dbf9c9-ca03-41bf-ae03-c49ce9586b9a

		changedProperty = IsHidden

	measure 'Pl Display Order' =
			
			
			MIN(VIEW_NLR_DIM_PL_GSC_WITH_LANG[PL_DISPLAY_ORDER])
		formatString: """|"""
		displayFolder: UI
		lineageTag: 9c288134-0ce0-41c5-91d1-973db0bdd7bb

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Selected PL Level 1' =
			
			
			SELECTEDVALUE(VIEW_NLR_DIM_PL_GSC_WITH_LANG[PL_LEVEL_1_DESC])
		displayFolder: UI
		lineageTag: a80dfdf0-47f7-446c-9103-601f6e58e402

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Medidas
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 167a8dd9-92e1-4911-a7f0-34a77e8972eb
		summarizeBy: none
		sourceColumn: Medidas

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition MEASURES_TABLE = m
		mode: import
		source =
				let
				    Source = ""
				in
				    Source

	changedProperty = Name

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Text

