/// DW: PBI.VIEW_NLR_DIM_PL_GSC_WITH_LANG
table VIEW_NLR_DIM_PL_GSC_WITH_LANG
	lineageTag: 5af271cf-e524-484d-b58e-7685c15e9f73

	/// DW:PBI.VIEW_NLR_DIM_PL_GSC_WITH_LANG.PL_CODE
	column PL_CODE
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 0e9d3947-3ef1-4458-8633-2788fa65b74b
		summarizeBy: none
		sourceColumn: PL_CODE

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	/// DW:PBI.VIEW_NLR_DIM_PL_GSC_WITH_LANG.PL_LEVEL_1_CODE
	column PL_LEVEL_1_CODE
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 9dd76fed-1cf1-402c-9133-a307a06610f3
		summarizeBy: none
		sourceColumn: PL_LEVEL_1_CODE

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	/// DW:PBI.VIEW_NLR_DIM_PL_GSC_WITH_LANG.PL_LEVEL_2_CODE
	column PL_LEVEL_2_CODE
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 938d517f-4f33-4198-8d47-40a2d7182ff5
		summarizeBy: none
		sourceColumn: PL_LEVEL_2_CODE

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	/// DW:PBI.VIEW_NLR_DIM_PL_GSC_WITH_LANG.PL_LEVEL_3_CODE
	column PL_LEVEL_3_CODE
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 692af18a-573b-4756-ba4a-511c16a47cc0
		summarizeBy: none
		sourceColumn: PL_LEVEL_3_CODE

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	/// DW:PBI.VIEW_NLR_DIM_PL_GSC_WITH_LANG.PL_LEVEL_4_CODE
	column PL_LEVEL_4_CODE
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 7ef832fd-b2db-4e7d-8d01-2c5f40ad957a
		summarizeBy: none
		sourceColumn: PL_LEVEL_4_CODE

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	/// DW:PBI.VIEW_NLR_DIM_PL_GSC_WITH_LANG.PL_LEVEL_5_CODE
	column PL_LEVEL_5_CODE
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: c5e3e530-645c-4cf7-b0da-ab418c3cd7de
		summarizeBy: none
		sourceColumn: PL_LEVEL_5_CODE

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	/// DW:PBI.VIEW_NLR_DIM_PL_GSC_WITH_LANG.PL_LEVEL_6_CODE
	column PL_LEVEL_6_CODE
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: df1b1918-40a6-423e-a95d-13b817c6c249
		summarizeBy: none
		sourceColumn: PL_LEVEL_6_CODE

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	/// DW:PBI.VIEW_NLR_DIM_PL_GSC_WITH_LANG.PL_LEVEL_7_CODE
	column PL_LEVEL_7_CODE
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 35e05f8b-aeb9-4fdf-86cb-38195d7c4c8e
		summarizeBy: none
		sourceColumn: PL_LEVEL_7_CODE

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	/// DW:PBI.VIEW_NLR_DIM_PL_GSC_WITH_LANG.PL_LEVEL_1_DESC
	column PL_LEVEL_1_DESC
		dataType: string
		lineageTag: c5bcc8c1-84ab-4a1e-8e27-f8d2fd5634fb
		summarizeBy: none
		sourceColumn: PL_LEVEL_1_DESC
		sortByColumn: PL_Level_1_Display_Order

		changedProperty = SortByColumn

		annotation SummarizationSetBy = User

	/// DW:PBI.VIEW_NLR_DIM_PL_GSC_WITH_LANG.PL_LEVEL_2_DESC
	column PL_LEVEL_2_DESC
		dataType: string
		lineageTag: db229656-90b5-44db-a5f5-5efff56f438c
		summarizeBy: none
		sourceColumn: PL_LEVEL_2_DESC

		annotation SummarizationSetBy = User

	/// DW:PBI.VIEW_NLR_DIM_PL_GSC_WITH_LANG.PL_LEVEL_3_DESC
	column PL_LEVEL_3_DESC
		dataType: string
		lineageTag: 7e81cb97-34ce-46bb-9d55-4c82f11fa092
		summarizeBy: none
		sourceColumn: PL_LEVEL_3_DESC

		annotation SummarizationSetBy = User

	/// DW:PBI.VIEW_NLR_DIM_PL_GSC_WITH_LANG.PL_LEVEL_4_DESC
	column PL_LEVEL_4_DESC
		dataType: string
		lineageTag: b5988a71-aec1-4c4b-a595-fde87aba3781
		summarizeBy: none
		sourceColumn: PL_LEVEL_4_DESC

		annotation SummarizationSetBy = User

	/// DW:PBI.VIEW_NLR_DIM_PL_GSC_WITH_LANG.PL_LEVEL_5_DESC
	column PL_LEVEL_5_DESC
		dataType: string
		lineageTag: f3a41eeb-5422-4310-914c-9f624a82f3ba
		summarizeBy: none
		sourceColumn: PL_LEVEL_5_DESC

		annotation SummarizationSetBy = User

	/// DW:PBI.VIEW_NLR_DIM_PL_GSC_WITH_LANG.PL_LEVEL_6_DESC
	column PL_LEVEL_6_DESC
		dataType: string
		lineageTag: 8160705b-6a5d-43db-9d40-91fc0fc067d5
		summarizeBy: none
		sourceColumn: PL_LEVEL_6_DESC

		annotation SummarizationSetBy = User

	/// DW:PBI.VIEW_NLR_DIM_PL_GSC_WITH_LANG.PL_LEVEL_7_DESC
	column PL_LEVEL_7_DESC
		dataType: string
		lineageTag: d94a78ae-4f33-4e81-9a0a-e109f7ad1cae
		summarizeBy: none
		sourceColumn: PL_LEVEL_7_DESC

		annotation SummarizationSetBy = User

	/// DW:PBI.VIEW_NLR_DIM_PL_GSC_WITH_LANG.PL_DESC
	column PL_DESC
		dataType: string
		lineageTag: 95c58cb3-853a-460d-a708-90067ff52e87
		summarizeBy: none
		sourceColumn: PL_DESC

		annotation SummarizationSetBy = User

	/// DW:PBI.VIEW_NLR_DIM_PL_GSC_WITH_LANG.ISCALCULATED
	column ISCALCULATED
		dataType: int64
		formatString: 0
		lineageTag: 46e641ae-b7c5-4a1e-814e-a9b9aed34b48
		summarizeBy: none
		sourceColumn: ISCALCULATED

		annotation SummarizationSetBy = User

	/// DW:PBI.VIEW_NLR_DIM_PL_GSC_WITH_LANG.QTY_FLAG
	column QTY_FLAG
		dataType: int64
		formatString: 0
		lineageTag: 1d0e7d3e-e42a-49c2-bf0f-31a72453c11c
		summarizeBy: none
		sourceColumn: QTY_FLAG

		annotation SummarizationSetBy = User

	/// DW:PBI.VIEW_NLR_DIM_PL_GSC_WITH_LANG.SALES_FLAG
	column SALES_FLAG
		dataType: int64
		formatString: 0
		lineageTag: 178e9ab8-128e-4057-a8b9-33ddbd7548f1
		summarizeBy: none
		sourceColumn: SALES_FLAG

		annotation SummarizationSetBy = User

	/// DW:PBI.VIEW_NLR_DIM_PL_GSC_WITH_LANG.VALUE_MEASURE
	column VALUE_MEASURE
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8a83dfc0-00be-4600-8641-430ad5dac4df
		summarizeBy: none
		sourceColumn: VALUE_MEASURE

		annotation SummarizationSetBy = User

	/// DW:PBI.VIEW_NLR_DIM_PL_GSC_WITH_LANG.POLARITY
	column POLARITY
		dataType: string
		lineageTag: b71427af-222d-4214-a859-856e115041db
		summarizeBy: none
		sourceColumn: POLARITY

		annotation SummarizationSetBy = User

	/// DW:PBI.VIEW_NLR_DIM_PL_GSC_WITH_LANG.PL_DISPLAY_ORDER
	column PL_DISPLAY_ORDER
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2c37a87c-4385-43f3-a814-e2a1cf001b57
		summarizeBy: none
		sourceColumn: PL_DISPLAY_ORDER

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	/// DW:PBI.VIEW_NLR_DIM_PL_GSC_WITH_LANG.SALES_TYPE_CODE_DEFAULT
	column SALES_TYPE_CODE_DEFAULT
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 8e4b0e25-2041-424d-9f1c-e26313e27df2
		summarizeBy: none
		sourceColumn: SALES_TYPE_CODE_DEFAULT

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	/// DW:PBI.VIEW_NLR_DIM_PL_GSC_WITH_LANG.INFO_FLAG
	column INFO_FLAG
		dataType: int64
		formatString: 0
		lineageTag: a42cb56e-63e6-4216-86cc-528aff597630
		summarizeBy: none
		sourceColumn: INFO_FLAG

		annotation SummarizationSetBy = User

	/// DW:PBI.VIEW_NLR_DIM_PL_GSC_WITH_LANG.CODE_TOPNG
	column CODE_TOPNG
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: ba16cc04-69f7-4782-8170-ae488bfc59be
		summarizeBy: none
		sourceColumn: CODE_TOPNG

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	/// DW:PBI.VIEW_NLR_DIM_PL_GSC_WITH_LANG.PNG_ONLY
	column PNG_ONLY
		dataType: int64
		formatString: 0
		lineageTag: 5f22a05f-1257-455a-bcf0-d6ef03092688
		summarizeBy: none
		sourceColumn: PNG_ONLY

		annotation SummarizationSetBy = User

	/// DW:PBI.VIEW_NLR_DIM_PL_GSC_WITH_LANG.PL_LEVEL_1_DESC_PNG
	column PL_LEVEL_1_DESC_PNG
		dataType: string
		lineageTag: e3bf6f96-e8f1-450c-9b12-1ca2b91c1b44
		summarizeBy: none
		sourceColumn: PL_LEVEL_1_DESC_PNG

		annotation SummarizationSetBy = User

	/// DW:PBI.VIEW_NLR_DIM_PL_GSC_WITH_LANG.PL_LEVEL_2_DESC_PNG
	column PL_LEVEL_2_DESC_PNG
		dataType: string
		lineageTag: ac8df239-d8f1-4d45-8d9a-4c4314dc1996
		summarizeBy: none
		sourceColumn: PL_LEVEL_2_DESC_PNG

		annotation SummarizationSetBy = User

	/// DW:PBI.VIEW_NLR_DIM_PL_GSC_WITH_LANG.PL_LEVEL_3_DESC_PNG
	column PL_LEVEL_3_DESC_PNG
		dataType: string
		lineageTag: 7b06322f-366d-4399-9aad-c78077c28cba
		summarizeBy: none
		sourceColumn: PL_LEVEL_3_DESC_PNG

		annotation SummarizationSetBy = User

	/// DW:PBI.VIEW_NLR_DIM_PL_GSC_WITH_LANG.PL_LEVEL_4_DESC_PNG
	column PL_LEVEL_4_DESC_PNG
		dataType: string
		lineageTag: 27a67787-f8f6-4edc-a27e-ce2609fddcb5
		summarizeBy: none
		sourceColumn: PL_LEVEL_4_DESC_PNG

		annotation SummarizationSetBy = User

	/// DW:PBI.VIEW_NLR_DIM_PL_GSC_WITH_LANG.PL_LEVEL_5_DESC_PNG
	column PL_LEVEL_5_DESC_PNG
		dataType: string
		lineageTag: 6275e6da-66f9-4184-a874-7ddc2985670c
		summarizeBy: none
		sourceColumn: PL_LEVEL_5_DESC_PNG

		annotation SummarizationSetBy = User

	/// DW:PBI.VIEW_NLR_DIM_PL_GSC_WITH_LANG.PL_LEVEL_6_DESC_PNG
	column PL_LEVEL_6_DESC_PNG
		dataType: string
		lineageTag: a35d8b67-4d97-42da-9126-ddafc38bf38d
		summarizeBy: none
		sourceColumn: PL_LEVEL_6_DESC_PNG

		annotation SummarizationSetBy = User

	/// DW:PBI.VIEW_NLR_DIM_PL_GSC_WITH_LANG.PL_LEVEL_7_DESC_PNG
	column PL_LEVEL_7_DESC_PNG
		dataType: string
		lineageTag: 7ebaab4e-388e-45c5-b3e6-52c7bb484358
		summarizeBy: none
		sourceColumn: PL_LEVEL_7_DESC_PNG

		annotation SummarizationSetBy = User

	/// DW:PBI.VIEW_NLR_DIM_PL_GSC_WITH_LANG.PL_DESC_PNG
	column PL_DESC_PNG
		dataType: string
		lineageTag: 1beda820-d609-4d4e-923e-d4144d0edad2
		summarizeBy: none
		sourceColumn: PL_DESC_PNG

		annotation SummarizationSetBy = User

	/// DW:PBI.VIEW_NLR_DIM_PL_GSC_WITH_LANG.USER_CULTURE
	column USER_CULTURE
		dataType: string
		lineageTag: 075d639a-d6f2-49bb-af9b-69594c483c04
		summarizeBy: none
		sourceColumn: USER_CULTURE

		annotation SummarizationSetBy = Automatic

	/// DW:PBI.VIEW_NLR_DIM_PL_GSC_WITH_LANG.PL_Level_1_Display_Order
	column PL_Level_1_Display_Order =
			
			
			CALCULATE(
			    MIN(VIEW_NLR_DIM_PL_GSC_WITH_LANG[PL_DISPLAY_ORDER]),
			    ALLEXCEPT(VIEW_NLR_DIM_PL_GSC_WITH_LANG, VIEW_NLR_DIM_PL_GSC_WITH_LANG[PL_LEVEL_1_DESC_2])
			)
		dataType: int64
		formatString: 0
		lineageTag: 3f2fdefd-32d6-491e-b2a9-18d29bb4cbc0
		summarizeBy: sum
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	/// DW:PBI.VIEW_NLR_DIM_PL_GSC_WITH_LANG.PL_LEVEL_1_DESC_2
	column PL_LEVEL_1_DESC_2
		dataType: string
		lineageTag: b49c6baf-2651-4298-916b-e547323cd614
		summarizeBy: none
		sourceColumn: PL_LEVEL_1_DESC_2

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition VIEW_NLR_DIM_PL_GSC_WITH_LANG = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = Sql.Database(Server, DatabaseDim),
				    PBI_VIEW_NLR_DIM_PL_GSC_WITH_LANG = Source{[Schema="PBI",Item="VIEW_NLR_DIM_PL_GSC_WITH_LANG"]}[Data],
				    #"Coluna Duplicada" = Table.DuplicateColumn(PBI_VIEW_NLR_DIM_PL_GSC_WITH_LANG, "PL_LEVEL_1_DESC", "PL_LEVEL_1_DESC - Cópia"),
				    #"Colunas com Nome Mudado" = Table.RenameColumns(#"Coluna Duplicada",{{"PL_LEVEL_1_DESC - Cópia", "PL_LEVEL_1_DESC_2"}})
				in
				    #"Colunas com Nome Mudado"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

