{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"PBI_COL_VIATURAS_Teste\",\"Grupo 1\",\"Grupo 2\",\"Grupo 3\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.131.1203.0 (24.07)"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      },
      {
        "name": "TabularEditor_SerializeOptions",
        "value": "{\"IgnoreInferredObjects\":true,\"IgnoreInferredProperties\":true,\"IgnoreTimestamps\":true,\"SplitMultilineStrings\":true,\"PrefixFilenames\":false,\"LocalTranslations\":false,\"LocalPerspectives\":false,\"LocalRelationships\":false,\"Levels\":[\"Data Sources\",\"Shared Expressions\",\"Perspectives\",\"Relationships\",\"Roles\",\"Tables\",\"Tables/Columns\",\"Tables/Hierarchies\",\"Tables/Measures\",\"Tables/Partitions\",\"Tables/Calculation Items\",\"Translations\"]}"
      }
    ],
    "culture": "pt-PT",
    "cultures": [
      {
        "name": "pt-PT",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Grupo 1",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"1. Regular Rede\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "c980c351-b4c0-4ce6-b401-185bd1133c5d"
      },
      {
        "name": "Grupo 2",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"2. Irregular Rede\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "49066136-e3dc-4741-b80f-5b82e91b87ce"
      },
      {
        "name": "Grupo 3",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"3. TCAP\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "945e24f4-95d0-4858-991c-4c3659a41f94"
      }
    ],
    "relationships": [
      {
        "name": "6453a886-5bf4-41c9-9cef-43f535be84af",
        "fromColumn": "Data",
        "fromTable": "PBI_COL_VIATURAS_Teste",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_2d867c95-5413-496d-a762-9b4b334fce26"
      }
    ],
    "sourceQueryCulture": "pt-PT",
    "tables": [
      {
        "name": "PBI_COL_VIATURAS_Teste",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "ID_PRODUTO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b60417b6-d11a-491c-b8d0-7984cc2d6498",
            "sourceColumn": "ID_PRODUTO",
            "summarizeBy": "sum"
          },
          {
            "name": "VIN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7c29dfac-aa6d-4c4d-84ad-e952b71e240b",
            "sourceColumn": "VIN",
            "summarizeBy": "none"
          },
          {
            "name": "Grupo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0cc0e13e-bf8b-4ff7-8d00-d9dc1407de99",
            "sourceColumn": "Grupo",
            "summarizeBy": "none"
          },
          {
            "name": "ID_DEALER_VENDEDOR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1f781401-f9f0-400f-a77a-c6517cdeeae2",
            "sourceColumn": "ID_DEALER_VENDEDOR",
            "summarizeBy": "sum"
          },
          {
            "name": "ID_DEALER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c4cfeb51-42ee-48c2-b0b1-6a57e6f1973a",
            "sourceColumn": "ID_DEALER",
            "summarizeBy": "sum"
          },
          {
            "name": "ID_VEND",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "eb91ca68-8d0c-4ac4-9b9e-4156c11fc687",
            "sourceColumn": "ID_VEND",
            "summarizeBy": "sum"
          },
          {
            "name": "Venda Efetiva",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0992e144-099c-45d9-9256-9ef0e5925131",
            "sourceColumn": "Venda Efetiva",
            "summarizeBy": "sum"
          },
          {
            "name": "Unidades_2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7d5ea939-7012-4acb-9d0b-d981974d7d8d",
            "sourceColumn": "Unidades",
            "summarizeBy": "sum"
          },
          {
            "name": "Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "33b353de-3b0e-4c8c-9dc2-ebf8ca517644",
            "sourceColumn": "Data",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variação",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de Datas",
                  "table": "LocalDateTable_2d867c95-5413-496d-a762-9b4b334fce26"
                },
                "isDefault": true,
                "relationship": "6453a886-5bf4-41c9-9cef-43f535be84af"
              }
            ]
          },
          {
            "name": "Com Kinto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fcaa2295-a1d5-4066-a80b-e71c0fee62de",
            "sourceColumn": "Com Kinto",
            "summarizeBy": "none"
          },
          {
            "name": "Kinto Canal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "64c0869b-b8c5-4047-a35b-4e4cd709106b",
            "sourceColumn": "Kinto Canal",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8b5f79a3-8b96-4859-862f-3454187ceb3d",
        "partitions": [
          {
            "name": "Grupo 1",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origem = Sql.Database(\"scsbisrv1.sc.pt\", \"TCAP_DMV\"),",
                "    dbo_PBI_COL_VIATURAS_Teste = Origem{[Schema=\"dbo\",Item=\"PBI_COL_VENDAS_TESTEMC\"]}[Data],",
                "    #\"Linhas Filtradas\" = Table.SelectRows(dbo_PBI_COL_VIATURAS_Teste, each [Grupo] = #\"Grupo 1\")",
                "in",
                "    #\"Linhas Filtradas\""
              ],
              "type": "m"
            }
          },
          {
            "name": "Grupo 2",
            "source": {
              "expression": [
                "let",
                "    Origem = Sql.Database(\"scsbisrv1.sc.pt\", \"TCAP_DMV\"),",
                "    dbo_PBI_COL_VIATURAS_Teste = Origem{[Schema=\"dbo\",Item=\"PBI_COL_VENDAS_TESTEMC\"]}[Data],",
                "    #\"Linhas Filtradas\" = Table.SelectRows(dbo_PBI_COL_VIATURAS_Teste, each [Grupo] = #\"Grupo 2\")",
                "in",
                "    #\"Linhas Filtradas\""
              ],
              "type": "m"
            }
          },
          {
            "name": "Grupo 3",
            "source": {
              "expression": [
                "let",
                "    Origem = Sql.Database(\"scsbisrv1.sc.pt\", \"TCAP_DMV\"),",
                "    dbo_PBI_COL_VIATURAS_Teste = Origem{[Schema=\"dbo\",Item=\"PBI_COL_VENDAS_TESTEMC\"]}[Data],",
                "    #\"Linhas Filtradas\" = Table.SelectRows(dbo_PBI_COL_VIATURAS_Teste, each [Grupo] = #\"Grupo 3\")",
                "in",
                "    #\"Linhas Filtradas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_15126d86-5180-42a8-8806-998288c9c9d6",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "8a5a8bac-f1d0-404c-b326-4c02ec8396d4",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8c5aed20-bb6e-469a-aba0-a2ca36e31b71",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4b430447-bd3c-4589-a81d-429262ce32cb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "dfe645f0-cca3-4916-97ca-db3522ab4644",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ef785739-4882-4ac7-b3cf-eeccf84d4694",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Tri \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "c8d0fe17-6d7a-406a-8b02-1d232830ca02",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3d66a0de-4b80-45e7-9716-28c80c14cc5c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de Datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "c29771c4-edc3-4599-bd0b-be171734dbf9",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "6efb58e3-0280-4cd1-b136-fc44a7675b05",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "3867a02c-9871-4f9a-b1e6-edc47110ecba",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "fc275dcf-93e6-49c6-860f-bd0fa76ccb48",
                "ordinal": 3
              }
            ],
            "lineageTag": "e8484b51-0450-4b51-866b-edfff2b3d970"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "91863e95-4e98-464a-9b60-07283deddfcd",
        "partitions": [
          {
            "name": "DateTableTemplate_15126d86-5180-42a8-8806-998288c9c9d6",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_2d867c95-5413-496d-a762-9b4b334fce26",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c9ccf44c-af7e-4a46-8919-c2022852c503",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "43132008-0873-42fc-8102-1af6391a39b3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4ab70ca5-3c2f-4a47-983a-749f3af9d0d7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "6e3e51ea-c52c-44d1-bbb4-75bd1608d198",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "fc5affac-f192-4337-b748-afb35f68595c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Tri \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "9399e457-4c16-4c08-8b18-cfee49bf0af7",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "51595d77-4c6b-499a-98f7-ae50dabf144b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de Datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "6c58eab7-2751-45a9-a11e-9edc7af7e8bd",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "67c5c874-a5be-41ce-ac54-174182b4ba03",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "b2fbe3f1-a084-4940-a585-fb0cddce7e7c",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "fb05cdfe-2d72-4a3a-a38e-645fb0fc9934",
                "ordinal": 3
              }
            ],
            "lineageTag": "ce02fa0a-2eaf-41d9-a127-28bc20e880c0"
          }
        ],
        "isHidden": true,
        "lineageTag": "4c9ab483-fb54-4869-8bb5-11fa73614d18",
        "partitions": [
          {
            "name": "LocalDateTable_2d867c95-5413-496d-a762-9b4b334fce26",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('PBI_COL_VIATURAS_Teste'[Data])), 1, 1), Date(Year(MAX('PBI_COL_VIATURAS_Teste'[Data])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}