{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"FACT_Orders\",\"DIM_People\",\"DIM_Returns\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.118.1063.0 (23.06)"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "9a50c153-71c8-4285-9029-647069e2dd3c",
        "fromColumn": "Order Date",
        "fromTable": "FACT_Orders",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_74523e2e-0f89-4134-a26d-7884ea4272d8"
      },
      {
        "name": "be6e8c64-74e9-4725-a22f-a139aa0e1d82",
        "fromColumn": "Ship Date",
        "fromTable": "FACT_Orders",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_81bb9cc1-656b-4ea8-8bdb-45d433fa5035"
      },
      {
        "name": "cfd95448-a789-4269-9119-355de9271adc",
        "fromColumn": "Region",
        "fromTable": "FACT_Orders",
        "toColumn": "Region",
        "toTable": "DIM_People"
      },
      {
        "name": "3b15fb37-787f-4260-bf85-a33b7638a96f",
        "fromColumn": "Order ID",
        "fromTable": "FACT_Orders",
        "toColumn": "Order ID",
        "toTable": "DIM_Returns"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "FACT_Orders",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Row ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2b369f5f-f9ed-42e1-b7ec-fed658eb3523",
            "sourceColumn": "Row ID",
            "summarizeBy": "none"
          },
          {
            "name": "Order ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a38fee06-9137-442f-b2eb-ac1344c8e0f2",
            "sourceColumn": "Order ID",
            "summarizeBy": "none"
          },
          {
            "name": "Order Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "fbb99231-6628-4fc0-8ea5-adeb32b2de0a",
            "sourceColumn": "Order Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_74523e2e-0f89-4134-a26d-7884ea4272d8"
                },
                "isDefault": true,
                "relationship": "9a50c153-71c8-4285-9029-647069e2dd3c"
              }
            ]
          },
          {
            "name": "Ship Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "39d76484-4b20-48ff-b784-18e178967ea1",
            "sourceColumn": "Ship Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_81bb9cc1-656b-4ea8-8bdb-45d433fa5035"
                },
                "isDefault": true,
                "relationship": "be6e8c64-74e9-4725-a22f-a139aa0e1d82"
              }
            ]
          },
          {
            "name": "Ship Mode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "75f6e031-02f5-4dcc-adbc-66bac3fa81ce",
            "sourceColumn": "Ship Mode",
            "summarizeBy": "none"
          },
          {
            "name": "Customer ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "99d35db8-72b5-400c-9f16-54dce7e92bcc",
            "sourceColumn": "Customer ID",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ec73f2ac-5318-473f-8510-980ea55e2e13",
            "sourceColumn": "Customer Name",
            "summarizeBy": "none"
          },
          {
            "name": "Segment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d9dda51b-bfd2-4d9b-b9ae-536ecfbf106e",
            "sourceColumn": "Segment",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "Country",
            "dataType": "string",
            "lineageTag": "6a8661ef-4bf8-4910-9797-0bf648ba8dbf",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "City",
            "dataType": "string",
            "lineageTag": "5f386ae7-79f6-4d3f-ad11-57631fed9e97",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "StateOrProvince",
            "dataType": "string",
            "lineageTag": "57882abd-44be-42cc-b17a-375e15dbfd0f",
            "sourceColumn": "State",
            "summarizeBy": "none"
          },
          {
            "name": "Postal Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PostalCode",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5848862e-7978-43d4-923d-d137beaeb34d",
            "sourceColumn": "Postal Code",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8818cca1-44fb-4595-a280-97484c785c4e",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Product ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6c06e246-fc59-4e76-abc4-2e3f230b6fdd",
            "sourceColumn": "Product ID",
            "summarizeBy": "none"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cb1f32fe-ee62-46f0-bea4-ff0737d47a2a",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "Sub-Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bdc56274-1fdd-4441-bf74-4a0cf93c2328",
            "sourceColumn": "Sub-Category",
            "summarizeBy": "none"
          },
          {
            "name": "Product Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "15e77ebb-f9be-4884-8af1-f6bab970238a",
            "sourceColumn": "Product Name",
            "summarizeBy": "none"
          },
          {
            "name": "Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "isHidden": true,
            "lineageTag": "f0313ce6-0fe4-402f-88bc-a52545389f86",
            "sourceColumn": "Sales",
            "summarizeBy": "sum"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4fa01135-a528-49da-bfaf-0036ea31e1b2",
            "sourceColumn": "Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Discount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "dd8061ab-8600-463f-a473-7d62fc2cb13b",
            "sourceColumn": "Discount",
            "summarizeBy": "sum"
          },
          {
            "name": "Profit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "isHidden": true,
            "lineageTag": "0a5e67c0-0fbf-4baf-ab49-a8c11e93756b",
            "sourceColumn": "Profit",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "d0490c35-e041-408b-b838-1f76d386d3d9",
        "measures": [
          {
            "name": "Total Sales",
            "expression": "SUM(FACT_Orders[Sales])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "4e813efd-6c23-4f6f-9637-6dde0a220406"
          },
          {
            "name": "Total Profit",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": "SUM(FACT_Orders[Profit])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "c3c0e00d-9f73-444f-b3f8-769b7026a048"
          },
          {
            "name": "Average Order Value",
            "expression": "DIVIDE(SUM('FACT_Orders'[Sales]), COUNT('FACT_Orders'[Order ID]))",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "97f881a4-da64-4863-99de-cdc0745b528f"
          },
          {
            "name": "Total Customers",
            "expression": "DISTINCTCOUNT('FACT_Orders'[Customer ID])",
            "formatString": "0",
            "lineageTag": "4a816657-3183-467b-b763-3e0cdcd9d493"
          },
          {
            "name": "Return Rate",
            "expression": "DIVIDE(COUNT('DIM_Returns'[Order ID]), COUNT('FACT_Orders'[Order ID]), 0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "98527d2e-21ce-41da-97c3-2f29d8be3771"
          },
          {
            "name": "Current Year Sales",
            "expression": "CALCULATE(SUM('FACT_Orders'[Sales]), YEAR('FACT_Orders'[Order Date]) = YEAR(MAX('FACT_Orders'[Order Date])))",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "b0244daa-db1a-4ed1-9120-8c9d1b968f32"
          },
          {
            "name": "Previous Year Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR SelectedYear = MAX('FACT_Orders'[Order Date].[Year])",
              "VAR Previous = SelectedYear - 1",
              "VAR PreviousYearSales = CALCULATE(SUM('FACT_Orders'[Sales]), 'FACT_Orders'[Order Date].[Year] = Previous)",
              "RETURN",
              "    IF(ISBLANK(PreviousYearSales), BLANK(), PreviousYearSales)",
              ""
            ],
            "lineageTag": "bb832ff9-cb5c-49c3-82c8-7f10b6ecb4f1"
          },
          {
            "name": "Average Sales per Unit",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": "DIVIDE(SUM('FACT_Orders'[Sales]), SUM('FACT_Orders'[Quantity]))",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "7f21d72f-c532-4436-b1a7-0e5bcd590543"
          },
          {
            "name": "YoY Sales Growth%",
            "expression": [
              "",
              "VAR CurrentYearSales = [Current Year Sales]",
              "VAR PreviousYearSales = [Previous Year Sales]",
              "VAR GrowthPercentage = DIVIDE(CurrentYearSales - PreviousYearSales, PreviousYearSales)",
              "RETURN",
              "    IF(",
              "        GrowthPercentage > 0,",
              "        IF(",
              "            ISBLANK(PreviousYearSales),",
              "            BLANK(),",
              "            FORMAT(GrowthPercentage, \"0.00%\") & \" \" & UNICHAR(9650) -- Green triangle symbol (▲)",
              "        ),",
              "        IF(",
              "            GrowthPercentage < 0,",
              "            IF(",
              "                ISBLANK(PreviousYearSales),",
              "                BLANK(),",
              "                FORMAT(GrowthPercentage, \"0.00%\") & \" \" & UNICHAR(9660) -- Red inverted triangle symbol (▼)",
              "            ),",
              "            FORMAT(GrowthPercentage, \"0.00%\") -- No symbol for zero growth",
              "        )",
              "    )",
              ""
            ],
            "lineageTag": "9b3551b0-4d9c-49be-a857-fc9b2b77560f"
          },
          {
            "name": "Current Year Profit",
            "expression": "CALCULATE(SUM('FACT_Orders'[Profit]), YEAR('FACT_Orders'[Order Date]) = YEAR(MAX('FACT_Orders'[Order Date])))",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "4e952ad2-8066-48f2-80b8-4a092e8679de"
          },
          {
            "name": "Previous Year Profit",
            "expression": [
              "",
              "VAR SelectedYear = MAX('FACT_Orders'[Order Date].[Year])",
              "VAR Previous = SelectedYear - 1",
              "VAR PreviousYearProfit = CALCULATE(SUM('FACT_Orders'[Profit]), 'FACT_Orders'[Order Date].[Year] = Previous)",
              "RETURN",
              "    IF(ISBLANK(PreviousYearProfit), BLANK(), PreviousYearProfit)",
              ""
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "1da2c50f-21e5-4e9a-bcdc-68f24fbbf3c0"
          },
          {
            "name": "Average Profit per Unit",
            "expression": [
              "DIVIDE(SUM('FACT_Orders'[Profit]), SUM('FACT_Orders'[Quantity]))",
              ""
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "4daabbd6-3b61-4c26-b897-89a8b69364bf"
          },
          {
            "name": "YoY Profit Growth%",
            "expression": [
              "",
              "VAR CurrentYearProfit = [Current Year Profit]",
              "VAR PreviousYearProfit = [Previous Year Profit]",
              "VAR GrowthPercentage = DIVIDE(CurrentYearProfit - PreviousYearProfit, PreviousYearProfit)",
              "RETURN",
              "    IF(",
              "        GrowthPercentage > 0,",
              "        IF(",
              "            ISBLANK(PreviousYearProfit),",
              "            BLANK(),",
              "            FORMAT(GrowthPercentage, \"0.00%\") & \" \" & UNICHAR(9650) -- Green triangle symbol (▲)",
              "        ),",
              "        IF(",
              "            GrowthPercentage < 0,",
              "            IF(",
              "                ISBLANK(PreviousYearProfit),",
              "                BLANK(),",
              "                FORMAT(GrowthPercentage, \"0.00%\") & \" \" & UNICHAR(9660) -- Red inverted triangle symbol (▼)",
              "            ),",
              "            FORMAT(GrowthPercentage, \"0.00%\") -- No symbol for zero growth",
              "        )",
              "    )"
            ],
            "lineageTag": "f34ab04c-e474-449a-97fa-514ea1b4eedd"
          },
          {
            "name": "Total Products",
            "expression": [
              "DISTINCTCOUNT('FACT_Orders'[Product ID])",
              ""
            ],
            "formatString": "0",
            "lineageTag": "e5e308c2-4413-4433-991a-2019b9627f72"
          },
          {
            "name": "Total Orders",
            "expression": [
              "COUNT('FACT_Orders'[Order ID])",
              ""
            ],
            "formatString": "0",
            "lineageTag": "57dc7ab5-84ff-4b77-a422-9975fc71c0dd"
          },
          {
            "name": "Average Sales per State",
            "expression": [
              "CALCULATE(AVERAGE('FACT_Orders'[Sales]), ALLEXCEPT('FACT_Orders', 'FACT_Orders'[State]))",
              ""
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "ad7ba17c-79de-4c4c-a5d0-6fcdb178dd68"
          },
          {
            "name": "Average Days to Ship",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "AVERAGEX(",
              "VALUES('FACT_Orders'[Order ID]),",
              "DATEDIFF(",
              "MIN('FACT_Orders'[Order Date]),",
              "MAX('FACT_Orders'[Ship Date]),",
              "DAY",
              ")",
              ")"
            ],
            "lineageTag": "173658d5-e17e-4912-b832-626960ff1a19"
          },
          {
            "name": "Total Quantity",
            "expression": "SUM(FACT_Orders[Quantity])",
            "formatString": "0",
            "lineageTag": "6faafe4e-d57f-4a30-8b04-daaeffedbfd0"
          },
          {
            "name": "Order to Ship Date",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    AVERAGEX(",
              "        'FACT_Orders',",
              "        DATEDIFF(",
              "            'FACT_Orders'[Order Date].[Date],",
              "            'FACT_Orders'[Ship Date].[Date],",
              "            DAY",
              "        )",
              "    )"
            ],
            "lineageTag": "b9634ece-2143-4417-a3d3-fe404635b707"
          }
        ],
        "partitions": [
          {
            "name": "FACT_Orders-f6c273c4-2e45-42f0-8454-f4bc3be43917",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\racac\\Desktop\\Portfolio\\Superstore.xlsx\"), null, true),",
                "    Orders_Sheet = Source{[Item=\"Orders\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Orders_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Row ID\", Int64.Type}, {\"Order ID\", type text}, {\"Order Date\", type date}, {\"Ship Date\", type date}, {\"Ship Mode\", type text}, {\"Customer ID\", type text}, {\"Customer Name\", type text}, {\"Segment\", type text}, {\"Country\", type text}, {\"City\", type text}, {\"State\", type text}, {\"Postal Code\", Int64.Type}, {\"Region\", type text}, {\"Product ID\", type text}, {\"Category\", type text}, {\"Sub-Category\", type text}, {\"Product Name\", type text}, {\"Sales\", type number}, {\"Quantity\", Int64.Type}, {\"Discount\", type number}, {\"Profit\", type number}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_f78ac314-d3f9-40a8-8fdc-9bd9eaebfc20",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "069c38af-33eb-4d7b-9f5b-5daf58d1793c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9402a98e-c4bb-4376-b7d2-fff663aa4ac3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9eb69853-fc47-49ba-a0b8-f324feaf4b0f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "abd20e79-fe50-41ae-9a67-54018f31e240",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a5d4fb3c-55c7-4d5c-94f3-f9745b157ba6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "848eebdc-83f6-4fa7-be16-c7ece00dd1e0",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "48eb9783-15bc-42dd-9c88-aed93c29f76e",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "bbf5d70a-2d14-4961-8489-d18bc3c4dfec",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "b41a6dce-c1cd-47b1-a65f-338be472e555",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "d0fca822-1c88-410c-a311-fa01dc1d6969",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "5f67cb7f-1364-4a76-b3a2-062d63e2c282",
                "ordinal": 3
              }
            ],
            "lineageTag": "42f9ba6e-bee3-4b13-907d-499b9a2da6c3"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "8f07973c-f5c5-4d47-a876-1cc5588da99c",
        "partitions": [
          {
            "name": "DateTableTemplate_f78ac314-d3f9-40a8-8fdc-9bd9eaebfc20-164992e8-8cf0-4954-a127-682b9f60083d",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_74523e2e-0f89-4134-a26d-7884ea4272d8",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "30581885-1055-4020-b934-412625a9b8b3",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "da2dab4a-5ff8-4562-96bd-318304958140",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0fd769d1-4ca1-42d9-933e-b4c9d1a908c9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3ee6c451-d16d-48eb-bf4f-de02d81b303f",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3c07bc9b-8554-454b-bad9-7561fd83c307",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "7584e0da-f8e3-4a36-b15b-8c3341470f72",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0a9bca80-4527-4fcd-9622-aae8e00c3559",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "1d6c6eff-1a8d-41b8-bf3d-f19953569c90",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "c18bcd71-e305-4a7c-ab50-1c6261fab737",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "8ab0907b-1690-4168-8dbc-08db29a9634d",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "95bcde49-aff1-4296-ad3b-01a18b1955d2",
                "ordinal": 3
              }
            ],
            "lineageTag": "9ad648a0-0b28-4659-b80e-4facee2e65cd"
          }
        ],
        "isHidden": true,
        "lineageTag": "0967f24c-d7d1-44f4-8ec7-2302bdd15f4d",
        "partitions": [
          {
            "name": "LocalDateTable_74523e2e-0f89-4134-a26d-7884ea4272d8-82e736d7-d342-4104-94da-f25f8dab414c",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('FACT_Orders'[Order Date])), 1, 1), Date(Year(MAX('FACT_Orders'[Order Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_81bb9cc1-656b-4ea8-8bdb-45d433fa5035",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "866bd929-c6b5-4c71-be3e-9edca15e9e26",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "efd25f3a-6c92-43da-8656-55586a8a82c6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9008e866-17da-4492-82b3-908a98668d34",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "41f42819-c133-49cc-8c56-aad19bc217b1",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "624a2f5c-257e-4f29-abee-d643fc53a9cb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3f423238-bae1-43f3-aceb-f6107a4027ea",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "77c9ebba-a0e4-4126-8d0a-152a4b2e6f04",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "1145dfe7-a549-44e5-8070-9462fbdd8ac6",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "3bf399e7-4155-42f2-b367-2a366feb60f4",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "797b7551-1107-4483-8e34-ae60fb2d5fbd",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "2395ef8f-3b79-42f2-85d4-bed333dbd223",
                "ordinal": 3
              }
            ],
            "lineageTag": "4a2a81e6-ca01-4731-a25c-f6381e22fd10"
          }
        ],
        "isHidden": true,
        "lineageTag": "08988bec-5ce6-49a7-b9a0-225c05e08dfc",
        "partitions": [
          {
            "name": "LocalDateTable_81bb9cc1-656b-4ea8-8bdb-45d433fa5035-990a37c4-230b-4925-9fe0-879e73f42b08",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('FACT_Orders'[Ship Date])), 1, 1), Date(Year(MAX('FACT_Orders'[Ship Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "DIM_People",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Person",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "466121ce-c0f2-467c-8812-41c7e7767e90",
            "sourceColumn": "Person",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a277a904-f6f2-44e8-8d26-91cbe15c6e50",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "15db184b-1d54-4dde-a710-6ab4452172e8",
        "partitions": [
          {
            "name": "DIM_People-ac5f4df0-2124-4879-8e6d-5b4c9f3eda3e",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\racac\\Desktop\\Portfolio\\Superstore.xlsx\"), null, true),",
                "    People_Sheet = Source{[Item=\"People\",Kind=\"Sheet\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(People_Sheet,{{\"Column1\", type text}, {\"Column2\", type text}}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Person\", type text}, {\"Region\", type text}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DIM_Returns",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Returned",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "be4fc8fb-11a6-4baa-95a2-640a222200bd",
            "sourceColumn": "Returned",
            "summarizeBy": "none"
          },
          {
            "name": "Order ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e22816a9-dc57-4096-95a7-568ffaa6c82c",
            "sourceColumn": "Order ID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "349563a8-dfe3-4883-914f-76992836063d",
        "partitions": [
          {
            "name": "DIM_Returns-765037fa-8bf1-45e2-b6e3-d66100055a20",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\racac\\Desktop\\Portfolio\\Superstore.xlsx\"), null, true),",
                "    Returns_Sheet = Source{[Item=\"Returns\",Kind=\"Sheet\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Returns_Sheet,{{\"Column1\", type text}, {\"Column2\", type text}}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Returned\", type text}, {\"Order ID\", type text}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Descriptions",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "d28b6995f6b14fb7acaedd584f3d981c"
          }
        ],
        "columns": [
          {
            "name": "Tab Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "45f222b0-f162-467e-8bbf-7cbb85c0ea57",
            "sourceColumn": "[Tab Name]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Explanation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "4e797b64-8e91-4043-a84f-aed77b483d69",
            "sourceColumn": "[Explanation]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "358c9cb3-4842-4753-a119-e7b46c2bcdb9",
        "partitions": [
          {
            "name": "Descriptions-c282a4f7-c7c0-4c6a-bd18-95821a9597a6",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "DATATABLE (",
                "    \"Tab Name\", STRING,",
                "    \"Explanation\", STRING,",
                "    {",
                "        {\"Sales\", \"Analyze sales trends, identify top-selling products, and track revenue by category and segment. It helps understand sales performance and opportunities for growth.\"},",
                "        {\"Profit\", \"Explore profitability by analyzing profit margins, identifying high-profit and low-profit points. It aids in understanding the financial health of the Superstore.\"},",
                "        {\"Customer\", \"Gain insights into customer behavior, segment customers, and understand their purchasing patterns. It helps in targeting specific customer segments for personalized marketing strategies.\"},",
                "        {\"Orders\", \" Access detailed information about the orders placed in the Superstore. It allows users to analyze and gain insights into various aspects of the order data, such as order dates, customer information, product categories, and sales performance.\"}",
                "            }",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}