{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"PBI View_VHE_Fact_BI_Sales_Detail\",\"PLATAFORMA_CA\",\"PLATAFORMA_AFR\",\"PLATAFORMA_IBE\",\"CHALLANGE_GRPS\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.131.1203.0 (24.07)"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      },
      {
        "name": "BestPracticeAnalyzer_IgnoreRules",
        "value": "{\"RuleIDs\":[\"OBJECTS_WITH_NO_DESCRIPTION\"]}"
      }
    ],
    "culture": "pt-PT",
    "cultures": [
      {
        "name": "pt-PT",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "PLATAFORMA_CA",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"BI_CA\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "f37e9e59-dce9-4b9f-902b-f926c778ba43"
      },
      {
        "name": "PLATAFORMA_AFR",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"BI_AFR\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "486cd7ab-b957-4b95-8018-c83fb1c8f5e5"
      },
      {
        "name": "PLATAFORMA_IBE",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"BI_IBE\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "b14271be-24c0-4c16-9f65-cd9a2af49899"
      }
    ],
    "sourceQueryCulture": "pt-PT",
    "tables": [
      {
        "name": "PBI View_VHE_Fact_BI_Sales_Detail",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Nlr_Code_Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6fd19f94-f81c-4aee-912d-2b2cca34ea6c",
            "sourceColumn": "Nlr_Code_Key",
            "summarizeBy": "none"
          },
          {
            "name": "Site_Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "46989c44-dc9c-4046-ab35-e83d17a4de21",
            "sourceColumn": "Site_Key",
            "summarizeBy": "none"
          },
          {
            "name": "Franchise_Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f0238057-e59b-46fb-a346-67952fb219b0",
            "sourceColumn": "Franchise_Key",
            "summarizeBy": "none"
          },
          {
            "name": "Model_Code_Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f3c4f2d7-bf8c-4331-ba99-b2db8792a599",
            "sourceColumn": "Model_Code_Key",
            "summarizeBy": "none"
          },
          {
            "name": "Sales_Type_Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ea7ec97a-5399-44e3-a0a3-f2b883c2a9bf",
            "sourceColumn": "Sales_Type_Key",
            "summarizeBy": "none"
          },
          {
            "name": "Source_Code_Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0b670e4a-d027-4b5c-9d74-ffdde4050b2c",
            "sourceColumn": "Source_Code_Key",
            "summarizeBy": "none"
          },
          {
            "name": "VHE_Type_Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "967bccda-63db-4da4-b36f-83cd5e05b706",
            "sourceColumn": "VHE_Type_Key",
            "summarizeBy": "none"
          },
          {
            "name": "Customer_Type_Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f57390aa-fb51-40cf-9342-4b6ae36853c8",
            "sourceColumn": "Customer_Type_Key",
            "summarizeBy": "none"
          },
          {
            "name": "Fuel_Type_Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e0be16f3-3783-49d7-8101-abe28d5d9cfd",
            "sourceColumn": "Fuel_Type_Key",
            "summarizeBy": "none"
          },
          {
            "name": "Client_Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4e58ac33-6241-4570-a5bd-01326f90e929",
            "sourceColumn": "Client_Id",
            "summarizeBy": "none"
          },
          {
            "name": "NLR_Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "319ceee4-a9c8-4535-b404-7d32628280ba",
            "sourceColumn": "NLR_Code",
            "summarizeBy": "none"
          },
          {
            "name": "Customer_Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1ce48cd2-96bd-4ae0-b152-531f94090dd2",
            "sourceColumn": "Customer_Type",
            "summarizeBy": "none"
          },
          {
            "name": "Fuel_Type_Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0ee80a02-84f8-40b5-92d4-34cc26395447",
            "sourceColumn": "Fuel_Type_Code",
            "summarizeBy": "none"
          },
          {
            "name": "Source_Code_DW",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b04a5892-6958-4a9e-8d42-40ede91521ac",
            "sourceColumn": "Source_Code_DW",
            "summarizeBy": "none"
          },
          {
            "name": "Model_Code_DW",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5e565b9f-425c-46ba-9810-569199b53d9d",
            "sourceColumn": "Model_Code_DW",
            "summarizeBy": "none"
          },
          {
            "name": "VHE_Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1af03884-9a45-49b0-b5ae-a7547397b566",
            "sourceColumn": "VHE_Type",
            "summarizeBy": "none"
          },
          {
            "name": "Sales_Type_Code_DW",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "dd918a45-75cc-4741-9e61-a8c0a043b3b4",
            "sourceColumn": "Sales_Type_Code_DW",
            "summarizeBy": "none"
          },
          {
            "name": "Franchise_Code_DW",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cfa9284a-ac0c-44ff-b190-07e509072211",
            "sourceColumn": "Franchise_Code_DW",
            "summarizeBy": "none"
          },
          {
            "name": "Site_Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ea6968b3-ec67-40e3-90f9-5be9ec0aae17",
            "sourceColumn": "Site_Code",
            "summarizeBy": "none"
          },
          {
            "name": "SLR_Document_Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mm/dd/yyyy",
            "lineageTag": "73eb04ff-db82-4b3f-9d52-40cef5aa6c62",
            "sourceColumn": "SLR_Document_Date",
            "summarizeBy": "none"
          },
          {
            "name": "Variant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d09a79f4-b606-4cf8-abe8-3562379f4c5b",
            "sourceColumn": "Variant",
            "summarizeBy": "none"
          },
          {
            "name": "Chassis_Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2422b5d4-ae42-4a71-95d6-19997f54389b",
            "sourceColumn": "Chassis_Number",
            "summarizeBy": "none"
          },
          {
            "name": "PLR_Document_Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mm/dd/yyyy",
            "lineageTag": "8f51b86f-ddf6-48f8-976a-bdbeb693673d",
            "sourceColumn": "PLR_Document_Date",
            "summarizeBy": "none"
          },
          {
            "name": "Registration_Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mm/dd/yyyy",
            "lineageTag": "638ea752-4b90-4d11-a263-98872cc38a0b",
            "sourceColumn": "Registration_Date",
            "summarizeBy": "none"
          },
          {
            "name": "Generic_Colour_Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "98a09e77-cdd9-4638-bb7c-98033c95a0af",
            "sourceColumn": "Generic_Colour_Code",
            "summarizeBy": "none"
          },
          {
            "name": "SLR_Driver_Account_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "087e07cf-93a6-4351-82ee-55650ae92f46",
            "sourceColumn": "SLR_Driver_Account_Name",
            "summarizeBy": "none"
          },
          {
            "name": "Kms",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "7ddc50ab-034d-40f9-9f90-1f206dd75870",
            "sourceColumn": "Kms",
            "summarizeBy": "none"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "73fcabf4-5c7a-4b9a-b456-4ca4a69cff83",
            "sourceColumn": "Quantity",
            "summarizeBy": "none"
          },
          {
            "name": "Currency_Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "73b46845-76db-45b5-9e7d-3d9ca2e48148",
            "sourceColumn": "Currency_Rate",
            "summarizeBy": "none"
          },
          {
            "name": "Total_Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "0426124a-e068-4fe7-baa9-bbffde08e78b",
            "sourceColumn": "Total_Sales",
            "summarizeBy": "none"
          },
          {
            "name": "Total_Costs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "5c2a5bb8-3f47-4e43-9303-ba7fdffe6065",
            "sourceColumn": "Total_Costs",
            "summarizeBy": "none"
          },
          {
            "name": "Fixed_Margin",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "af546beb-9b92-4242-a1f9-fc81939698ae",
            "sourceColumn": "Fixed_Margin",
            "summarizeBy": "none"
          },
          {
            "name": "Variable_Margin",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "285bd4bd-d5de-4e47-8f1f-df74dd73b6ab",
            "sourceColumn": "Variable_Margin",
            "summarizeBy": "none"
          },
          {
            "name": "Gross_Margin_With_Commissions",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "67f35f56-fd15-4fbf-a008-05a55c15c3c2",
            "sourceColumn": "Gross_Margin_With_Commissions",
            "summarizeBy": "none"
          },
          {
            "name": "Measure_4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "7ae3d40b-df2c-499a-88db-9ff8341516fc",
            "sourceColumn": "Measure_4",
            "summarizeBy": "none"
          },
          {
            "name": "Vehicle_Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e9f09fc6-8cd0-49ec-9b31-52bb2040ed19",
            "sourceColumn": "Vehicle_Id",
            "summarizeBy": "none"
          },
          {
            "name": "DaysInStock",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b8573411-9492-465c-9cd1-077a73eaaae6",
            "sourceColumn": "DaysInStock",
            "summarizeBy": "none"
          },
          {
            "name": "Net_Discount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "cfc40009-17ae-4942-8d96-f0f4d8117714",
            "sourceColumn": "Net_Discount",
            "summarizeBy": "none"
          },
          {
            "name": "Measure_9",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "be7afdb2-0241-4e80-82bf-59200b3accf0",
            "sourceColumn": "Measure_9",
            "summarizeBy": "none"
          },
          {
            "name": "Campaign_Bonuses",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "01e209bd-a86c-4f2c-807f-5ebe45de4233",
            "sourceColumn": "Campaign_Bonuses",
            "summarizeBy": "none"
          },
          {
            "name": "Measure_20",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "b37f328c-2bf9-4ce9-ba12-4c0d894b414e",
            "sourceColumn": "Measure_20",
            "summarizeBy": "none"
          },
          {
            "name": "Variable_Margin_Divisor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "ec0cf793-3ea9-4b55-801e-5e9b60af23eb",
            "sourceColumn": "Variable_Margin_Divisor",
            "summarizeBy": "none"
          },
          {
            "name": "Sales_Commissions",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "91f1cebf-6608-4903-8701-b2db13417e37",
            "sourceColumn": "Sales_Commissions",
            "summarizeBy": "none"
          },
          {
            "name": "Measure_22",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "53ca56b0-d875-4ebc-ae99-57b698a08cc1",
            "sourceColumn": "Measure_22",
            "summarizeBy": "none"
          },
          {
            "name": "Measure_23",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "4898f227-b53d-47b3-a8de-c5a458f5f955",
            "sourceColumn": "Measure_23",
            "summarizeBy": "none"
          },
          {
            "name": "Measure_27",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "1ecf2289-60fa-4ebc-bdb7-e25bb7731a26",
            "sourceColumn": "Measure_27",
            "summarizeBy": "none"
          },
          {
            "name": "Measure_6",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "816fcbe7-cd43-4204-b3c8-5ab44752e1aa",
            "sourceColumn": "Measure_6",
            "summarizeBy": "none"
          },
          {
            "name": "Measure_7",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "82a1702a-1bb1-4408-a9bf-0a6aaf2a081b",
            "sourceColumn": "Measure_7",
            "summarizeBy": "none"
          },
          {
            "name": "Measure_8",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "b6d0e1b4-dbc9-4df1-8671-b4479aca97ea",
            "sourceColumn": "Measure_8",
            "summarizeBy": "none"
          },
          {
            "name": "Measure_5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "f96eeaf3-2ff8-4cad-8ef3-333deb87d078",
            "sourceColumn": "Measure_5",
            "summarizeBy": "none"
          },
          {
            "name": "Measure_15",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "ad2e19ab-a911-42c5-9278-b519fbe9117e",
            "sourceColumn": "Measure_15",
            "summarizeBy": "none"
          },
          {
            "name": "Measure_16",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "ffd29f16-b48d-42f5-85cb-cfdce8f66b07",
            "sourceColumn": "Measure_16",
            "summarizeBy": "none"
          },
          {
            "name": "Measure_17",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "509326ef-3472-43dc-a875-d6f85cb52e6d",
            "sourceColumn": "Measure_17",
            "summarizeBy": "none"
          },
          {
            "name": "Measure_18",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "204c3021-b829-4cc2-8bc2-261528e85bc2",
            "sourceColumn": "Measure_18",
            "summarizeBy": "none"
          },
          {
            "name": "Measure_26",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "4e7dae51-e9b7-45e1-959b-e70031fb5f6a",
            "sourceColumn": "Measure_26",
            "summarizeBy": "none"
          },
          {
            "name": "Measure_24",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "dcbf12c0-ed09-40d8-91c8-71e1a1178b46",
            "sourceColumn": "Measure_24",
            "summarizeBy": "none"
          },
          {
            "name": "Financing_Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "cd5d43f6-9e3f-4f28-9b2d-3f8e592ec157",
            "sourceColumn": "Financing_Number",
            "summarizeBy": "none"
          },
          {
            "name": "Insurances_Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "04b312f3-3f87-4c91-b8e2-dd8df728445f",
            "sourceColumn": "Insurances_Number",
            "summarizeBy": "none"
          },
          {
            "name": "Total_Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "f906ce2f-f7a3-4be8-b3ba-7aa93b30f475",
            "sourceColumn": "Total_Revenue",
            "summarizeBy": "none"
          },
          {
            "name": "Measure_1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "3f321cb2-97eb-43a7-b17a-ee4c0499b9a5",
            "sourceColumn": "Measure_1",
            "summarizeBy": "none"
          },
          {
            "name": "Measure_2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "27b46ea6-e2e9-48e7-97e0-4f620b16ac94",
            "sourceColumn": "Measure_2",
            "summarizeBy": "none"
          },
          {
            "name": "Measure_3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "67ad5bd1-741c-499e-9acb-33ecd91a58d2",
            "sourceColumn": "Measure_3",
            "summarizeBy": "none"
          },
          {
            "name": "Other_Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "0c40d987-13fa-4099-98ee-1ff51c371372",
            "sourceColumn": "Other_Sales",
            "summarizeBy": "none"
          },
          {
            "name": "Base_Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "5e4425af-48be-47d8-bbae-e3b988fe52b7",
            "sourceColumn": "Base_Cost",
            "summarizeBy": "none"
          },
          {
            "name": "Optional_Costs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "4a6c0fc3-5ee5-48c7-902a-e31b6ba9503d",
            "sourceColumn": "Optional_Costs",
            "summarizeBy": "none"
          },
          {
            "name": "VAT_Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "58798c5e-b8ba-4e06-9a81-0ab8024277e8",
            "sourceColumn": "VAT_Cost",
            "summarizeBy": "none"
          },
          {
            "name": "Measure_12",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "a78a639a-6c3d-4f8e-9925-f9a1faa77f1b",
            "sourceColumn": "Measure_12",
            "summarizeBy": "none"
          },
          {
            "name": "Measure_13",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "9f5b9860-2ae5-44b7-95d3-e572407210f0",
            "sourceColumn": "Measure_13",
            "summarizeBy": "none"
          },
          {
            "name": "Other_Costs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "ed7f3df6-46d5-44ab-9868-b947735ef3c4",
            "sourceColumn": "Other_Costs",
            "summarizeBy": "none"
          },
          {
            "name": "Bonuses",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "cec37707-f365-44fe-8eb3-0f87c82e283e",
            "sourceColumn": "Bonuses",
            "summarizeBy": "none"
          },
          {
            "name": "Measure_14",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "22475468-fddd-41b6-86a2-f29df33eea1f",
            "sourceColumn": "Measure_14",
            "summarizeBy": "none"
          },
          {
            "name": "Total_Invoice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "7832fc18-89a4-4805-aebd-f57756efc22c",
            "sourceColumn": "Total_Invoice",
            "summarizeBy": "none"
          },
          {
            "name": "VHE_Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "21a2e783-5047-44bb-8845-419ecd00503d",
            "sourceColumn": "VHE_Number",
            "summarizeBy": "none"
          },
          {
            "name": "Registration_Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0b8f163c-a955-4c76-bb92-8fe7e71ed2ed",
            "sourceColumn": "Registration_Number",
            "summarizeBy": "none"
          },
          {
            "name": "Customer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c6615e83-ce1d-4bf5-8bbb-635af19b8754",
            "sourceColumn": "Customer",
            "summarizeBy": "none"
          },
          {
            "name": "Customer_Email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "072996cd-ce03-4bc2-9630-d0a4e7248743",
            "sourceColumn": "Customer_Email",
            "summarizeBy": "none"
          },
          {
            "name": "Customer_Post_Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f0f0a9f5-0f19-4d72-9634-2854467e1736",
            "sourceColumn": "Customer_Post_Code",
            "summarizeBy": "none"
          },
          {
            "name": "Owner",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "65e843a6-dbc7-4e99-9ab8-108db6bd6821",
            "sourceColumn": "Owner",
            "summarizeBy": "none"
          },
          {
            "name": "Owner_Email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ed247700-5500-4a8b-9d92-5c199c0fca05",
            "sourceColumn": "Owner_Email",
            "summarizeBy": "none"
          },
          {
            "name": "Owner_Post_Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1ffa1f85-f527-4240-a87c-7e5a476c8eaf",
            "sourceColumn": "Owner_Post_Code",
            "summarizeBy": "none"
          },
          {
            "name": "Seller",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "80d70b90-cc27-4bfd-a97e-3626175015c3",
            "sourceColumn": "Seller",
            "summarizeBy": "none"
          },
          {
            "name": "SLR_Document",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "badded47-da13-45ae-858e-f82e08fdeed5",
            "sourceColumn": "SLR_Document",
            "summarizeBy": "none"
          },
          {
            "name": "VAT_Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "62d89899-7161-4454-9cae-4c92928f4a58",
            "sourceColumn": "VAT_Number",
            "summarizeBy": "none"
          },
          {
            "name": "VHE_Record_Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b9c670d7-6a55-4e41-8bba-daee58e2fd0a",
            "sourceColumn": "VHE_Record_Key",
            "summarizeBy": "none"
          },
          {
            "name": "FNE_Sales_Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4fdcbc07-647b-4404-88df-7b080cb727ea",
            "sourceColumn": "FNE_Sales_Type",
            "summarizeBy": "none"
          },
          {
            "name": "Plataforma",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2bec09ea-e7c6-4cfe-a171-04576144a219",
            "sourceColumn": "Plataforma",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7db6d295-a32c-4d7f-904d-31240145b5ce",
        "partitions": [
          {
            "name": "BI_CA",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origem = Sql.Database(\"SCSQLSRV3.sc.pt\\PRD\", PLATAFORMA_CA),",
                "    PBI_View_VHE_Fact_BI_Sales_Detail = Origem{[Schema=\"PBI\",Item=\"View_VHE_Fact_BI_Sales_Detail\"]}[Data],",
                "    #\"Personalizado Adicionado\" = Table.AddColumn(PBI_View_VHE_Fact_BI_Sales_Detail, \"Plataforma\", each PLATAFORMA_CA, type text)",
                "in",
                "    #\"Personalizado Adicionado\""
              ],
              "type": "m"
            }
          },
          {
            "name": "BI_AFR",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origem = Sql.Database(\"SCSQLSRV3.sc.pt\\PRD\", PLATAFORMA_AFR),",
                "    PBI_View_VHE_Fact_BI_Sales_Detail = Origem{[Schema=\"PBI\",Item=\"View_VHE_Fact_BI_Sales_Detail\"]}[Data],",
                "    #\"Personalizado Adicionado\" = Table.AddColumn(PBI_View_VHE_Fact_BI_Sales_Detail, \"Plataforma\", each PLATAFORMA_AFR, type text)",
                "in",
                "    #\"Personalizado Adicionado\""
              ],
              "type": "m"
            }
          },
          {
            "name": "BI_IBE",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origem = Sql.Database(\"SCSQLSRV3.sc.pt\\PRD\", PLATAFORMA_IBE),",
                "    PBI_View_VHE_Fact_BI_Sales_Detail = Origem{[Schema=\"PBI\",Item=\"View_VHE_Fact_BI_Sales_Detail\"]}[Data],",
                "    #\"Personalizado Adicionado\" = Table.AddColumn(PBI_View_VHE_Fact_BI_Sales_Detail, \"Plataforma\", each PLATAFORMA_IBE, type text)",
                "in",
                "    #\"Personalizado Adicionado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Medidas",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "81d337c189fb4d64a56b418d4f43eed5"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "37eb3b94-e6a6-4992-943c-910e80778401",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "ba30d8bc-526e-47e3-9ed1-3b2db515d54b",
        "measures": [
          {
            "name": "Registos",
            "expression": "COUNTROWS('PBI View_VHE_Fact_BI_Sales_Detail')",
            "formatString": "#,0",
            "lineageTag": "7a6f36c4-8c17-43ab-8dba-142fcda24fa2"
          },
          {
            "name": "Plataformas",
            "expression": "DISTINCTCOUNT('PBI View_VHE_Fact_BI_Sales_Detail'[Plataforma])",
            "formatString": "#,0",
            "lineageTag": "a33b1239-5160-4a9b-a1c3-9d77a39ce839"
          }
        ],
        "partitions": [
          {
            "name": "Medidas",
            "mode": "import",
            "source": {
              "expression": "{BLANK()}",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "CHALLANGE_GRPS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ANO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8d2c44b6-a5db-4a31-ae23-69a769944c49",
            "sourceColumn": "ANO",
            "summarizeBy": "none"
          },
          {
            "name": "MARCA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d3c0f272-4576-4aa4-bdc8-96c355da3ffb",
            "sourceColumn": "MARCA",
            "summarizeBy": "none"
          },
          {
            "name": "GRUPO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "982be162-20f9-4f35-ae97-f746233ed7ed",
            "sourceColumn": "GRUPO",
            "summarizeBy": "none"
          },
          {
            "name": "PLA_COD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d2ddd311-d2be-4a5f-a475-13860939fa13",
            "sourceColumn": "PLA_COD",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "03feb56a-45dd-432f-8a0d-6ec8676ea2a2",
        "partitions": [
          {
            "name": "CHALLANGE_GRPS",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origem = Sql.Database(\"scsbisrv1.sc.pt\", \"TCAP_GERAL\"),",
                "    dbo_CHALLANGE_GRPS = Origem{[Schema=\"dbo\",Item=\"CHALLANGE_GRPS\"]}[Data]",
                "in",
                "    dbo_CHALLANGE_GRPS"
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}