{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.131.1203.0 (24.07)"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Vendas\",\"Medidas\",\"Línguas\",\"Origens PT\",\"Origens EN\",\"Origens\",\"Calendário\",\"GBL_Dim_Site_Types_GSC_PT\",\"GBL_Dim_Site_Types_GSC_ES\",\"GBL_Dim_Site_Types_GSC_EN\",\"GBL_Dim_Site_Types_GSC_FR\",\"GBL_Dim_Site_Types_GSC\"]"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Entities": {
              "GBL_dim_site_types_GSC": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "GBL_Dim_Site_Types_GSC"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "GBL dim site types GSC": {
                      "State": "Generated"
                    }
                  },
                  {
                    "GBL dim site type GSC": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.78
                    }
                  },
                  {
                    "GBL_Dim_Site_Types_GSC": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "GSC": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "types GSC": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "type GSC": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.7566
                    }
                  },
                  {
                    "site types GSC": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "site type GSC": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.7566
                    }
                  },
                  {
                    "dim site types GSC": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "dim site type GSC": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.7566
                    }
                  },
                  {
                    "gbl dim website type gsc": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.624
                    }
                  },
                  {
                    "gbl dim campus type gsc": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.624
                    }
                  },
                  {
                    "gbl dim homepage type gsc": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.624
                    }
                  },
                  {
                    "gbl dim locale type gsc": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.624
                    }
                  },
                  {
                    "dim website type gsc": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.617
                    }
                  },
                  {
                    "dim campus type gsc": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.617
                    }
                  },
                  {
                    "dim homepage type gsc": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.617
                    }
                  },
                  {
                    "dim locale type gsc": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.617
                    }
                  },
                  {
                    "website type gsc": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "campus type gsc": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  }
                ]
              },
              "GBL_dim_site_types_GSC.site_type": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "GBL_Dim_Site_Types_GSC",
                    "ConceptualProperty": "Site_Type"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Site_Type": {
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "site type": {
                      "LastModified": "2024-06-06T13:56:41.013Z",
                      "State": "Deleted"
                    }
                  },
                  {
                    "type": {
                      "LastModified": "2024-06-06T13:56:41.013Z",
                      "State": "Deleted"
                    }
                  },
                  {
                    "site category": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "site genre": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "site manner": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "site variety": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "category": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "genre": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "manner": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "variety": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "site brand": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "site class": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  }
                ]
              },
              "GBL_dim_site_types_GSC.site_type_code": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "GBL_Dim_Site_Types_GSC",
                    "ConceptualProperty": "Site_Type_Code"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "site type code": {
                      "State": "Generated"
                    }
                  },
                  {
                    "Site_Type_Code": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "type code": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "site type id": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "type id": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "site type key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "type key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "website type code": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "campus type code": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "homepage type code": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "locale type code": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "site category code": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "site genre code": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  }
                ]
              },
              "GBL_dim_site_types_GSC.userculture": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "GBL_Dim_Site_Types_GSC",
                    "ConceptualProperty": "USERCULTURE"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "userculture": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "calendário": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Calendário"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "calendário": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "calendário.ano": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Calendário",
                    "ConceptualProperty": "Ano"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "ano": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "calendário.data": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Calendário",
                    "ConceptualProperty": "Data"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "data": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date": {
                      "State": "Generated",
                      "Weight": 0.7
                    }
                  },
                  {
                    "information": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "fact": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "info": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "statistic": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "document": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "figure": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "record": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  }
                ]
              },
              "calendário.mê": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Calendário",
                    "ConceptualProperty": "Mês"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "mê": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "língua": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Línguas"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "língua": {
                      "State": "Generated"
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "língua.língua": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Línguas",
                    "ConceptualProperty": "Língua"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "língua": {
                      "State": "Generated"
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "língua.order": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Línguas",
                    "ConceptualProperty": "Order"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "order": {
                      "State": "Generated"
                    }
                  },
                  {
                    "instruction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "direction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "edict": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "command": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "directive": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "demand": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "mandate": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "imperative": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "stability": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "harmony": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "língua.userculture": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Línguas",
                    "ConceptualProperty": "USERCULTURE"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "userculture": {
                      "State": "Generated"
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "medida": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Medidas"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "medida": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "medida.column_1": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Medidas",
                    "ConceptualProperty": "Column1"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "column 1": {
                      "State": "Generated"
                    }
                  },
                  {
                    "Column1": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "medida.dynamic_label": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Medidas",
                    "ConceptualProperty": "Dynamic_Label"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "dynamic label": {
                      "State": "Generated"
                    }
                  },
                  {
                    "Dynamic_Label": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "label": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "dynamic sticker": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "sticker": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "dynamic tag": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "dynamic decal": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "tag": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "decal": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "dynamic name tag": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.589
                    }
                  },
                  {
                    "name tag": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.571
                    }
                  }
                ]
              },
              "medida.main_title": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Medidas",
                    "ConceptualProperty": "MainTitle"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "main title": {
                      "State": "Generated"
                    }
                  },
                  {
                    "MainTitle": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "title": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "main designation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "designation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "main name": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "main award": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "main call": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "main heading": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "main label": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "award": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "call": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "heading": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  }
                ]
              },
              "medida.unidade": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Medidas",
                    "ConceptualProperty": "Unidades"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "unidade": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "medida.unidades_LY": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Medidas",
                    "ConceptualProperty": "Unidades LY"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "unidades LY": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "medida.user_culture": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Medidas",
                    "ConceptualProperty": "UserCulture"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "user culture": {
                      "State": "Generated"
                    }
                  },
                  {
                    "UserCulture": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "culture": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "user ethos": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "user philosophy": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "user nation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "ethos": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "philosophy": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "nation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "user art, music, and literature": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.475
                    }
                  },
                  {
                    "art, music, and literature": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "user civilization": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.451
                    }
                  },
                  {
                    "user society": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.451
                    }
                  }
                ]
              },
              "medida.visual_title": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Medidas",
                    "ConceptualProperty": "VisualTitle"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "visual title": {
                      "State": "Generated"
                    }
                  },
                  {
                    "VisualTitle": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "title": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "visual designation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "designation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "visual name": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "visual award": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "visual call": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "visual heading": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "visual label": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "award": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "call": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "heading": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  }
                ]
              },
              "medida1": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Medida"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "medida": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "medida1.grupo_medida": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Medida",
                    "ConceptualProperty": "Grupo Medida"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "grupo medida": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "medida1.medida": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Medida",
                    "ConceptualProperty": "Medida"
                  }
                },
                "NameType": "Name",
                "State": "Generated",
                "Terms": [
                  {
                    "medida": {
                      "State": "Generated"
                    }
                  },
                  {
                    "medida name": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "medida1.medida_field": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Medida",
                    "ConceptualProperty": "Medida Fields"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "medida field": {
                      "State": "Generated"
                    }
                  },
                  {
                    "medida arena": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "medida turf": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "medida ground": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "medida pitch": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "medida park": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "medida meadow": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.475
                    }
                  },
                  {
                    "medida grassland": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.475
                    }
                  },
                  {
                    "medida lea": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.475
                    }
                  },
                  {
                    "medida pasture": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  },
                  {
                    "medida countryside": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "medida1.medida_order": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Medida",
                    "ConceptualProperty": "Medida Order"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "medida order": {
                      "State": "Generated"
                    }
                  },
                  {
                    "medida instruction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "medida direction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "medida edict": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "medida command": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "medida directive": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "medida demand": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "medida mandate": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "medida imperative": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "medida stability": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.475
                    }
                  },
                  {
                    "medida harmony": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.475
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "medida1.userculture": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Medida",
                    "ConceptualProperty": "USERCULTURE"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "userculture": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "medidas.column_vendas": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Medidas",
                    "ConceptualProperty": "Valor Vendas"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Vendas": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "valor vendas": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "medidas.vendas_ly": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Medidas",
                    "ConceptualProperty": "Valor Vendas LY"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Vendas LY": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "valor vendas LY": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "origen": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Origens"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "origen": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "origen.id_origem": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Origens",
                    "ConceptualProperty": "ID_ORIGEM"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "id origem": {
                      "State": "Generated"
                    }
                  },
                  {
                    "ID_ORIGEM": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "identification origem": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "identity origem": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "identifier origem": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "credential origem": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "origen.origem": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Origens",
                    "ConceptualProperty": "Origem"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "origem": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "origen.userculture": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Origens",
                    "ConceptualProperty": "USERCULTURE"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "userculture": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "venda": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Vendas"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "venda": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "venda.data": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Vendas",
                    "ConceptualProperty": "Data"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "data": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date": {
                      "State": "Generated",
                      "Weight": 0.7
                    }
                  },
                  {
                    "information": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "fact": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "info": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "statistic": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "document": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "figure": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "record": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "venda.id_origem": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Vendas",
                    "ConceptualProperty": "ID_ORIGEM"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "id origem": {
                      "State": "Generated"
                    }
                  },
                  {
                    "ID_ORIGEM": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "identification origem": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "identity origem": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "identifier origem": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "credential origem": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "venda.unidade": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Vendas",
                    "ConceptualProperty": "Unidades"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "unidade": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "venda.valor_venda": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Vendas",
                    "ConceptualProperty": "Valor Venda"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "valor venda": {
                      "State": "Generated"
                    }
                  }
                ]
              }
            },
            "Language": "en-US",
            "Relationships": {
              "GBL_dim_site_types_GSC_has_língua": {
                "Binding": {
                  "ConceptualEntity": "GBL_Dim_Site_Types_GSC"
                },
                "Roles": {
                  "GBL_dim_site_types_GSC": {
                    "Target": {
                      "Entity": "GBL_dim_site_types_GSC"
                    }
                  },
                  "língua": {
                    "Target": {
                      "Entity": "língua"
                    }
                  }
                },
                "State": "Generated"
              },
              "GBL_dim_site_types_GSC_has_site_type": {
                "Binding": {
                  "ConceptualEntity": "GBL_Dim_Site_Types_GSC"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "GBL_dim_site_types_GSC.site_type"
                      },
                      "Subject": {
                        "Role": "GBL_dim_site_types_GSC"
                      }
                    },
                    "ID": "GBL_dim_site_types_GSCs_have_site_types",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "GBL_dim_site_types_GSC": {
                    "Target": {
                      "Entity": "GBL_dim_site_types_GSC"
                    }
                  },
                  "GBL_dim_site_types_GSC.site_type": {
                    "Target": {
                      "Entity": "GBL_dim_site_types_GSC.site_type"
                    }
                  }
                },
                "State": "Generated"
              },
              "GBL_dim_site_types_GSC_has_site_type_code": {
                "Binding": {
                  "ConceptualEntity": "GBL_Dim_Site_Types_GSC"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "GBL_dim_site_types_GSC.site_type_code"
                      },
                      "Subject": {
                        "Role": "GBL_dim_site_types_GSC"
                      }
                    },
                    "ID": "GBL_dim_site_types_GSCs_have_site_type_codes",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "GBL_dim_site_types_GSC": {
                    "Target": {
                      "Entity": "GBL_dim_site_types_GSC"
                    }
                  },
                  "GBL_dim_site_types_GSC.site_type_code": {
                    "Target": {
                      "Entity": "GBL_dim_site_types_GSC.site_type_code"
                    }
                  }
                },
                "State": "Generated"
              },
              "GBL_dim_site_types_GSC_has_userculture": {
                "Binding": {
                  "ConceptualEntity": "GBL_Dim_Site_Types_GSC"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "GBL_dim_site_types_GSC.userculture"
                      },
                      "Subject": {
                        "Role": "GBL_dim_site_types_GSC"
                      }
                    },
                    "ID": "GBL_dim_site_types_GSCs_have_usercultures",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "GBL_dim_site_types_GSC": {
                    "Target": {
                      "Entity": "GBL_dim_site_types_GSC"
                    }
                  },
                  "GBL_dim_site_types_GSC.userculture": {
                    "Target": {
                      "Entity": "GBL_dim_site_types_GSC.userculture"
                    }
                  }
                },
                "State": "Generated"
              },
              "calendário_has_ano": {
                "Binding": {
                  "ConceptualEntity": "Calendário"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "calendário.ano"
                      },
                      "Subject": {
                        "Role": "calendário"
                      }
                    },
                    "ID": "calendários_have_anos",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "calendário": {
                    "Target": {
                      "Entity": "calendário"
                    }
                  },
                  "calendário.ano": {
                    "Target": {
                      "Entity": "calendário.ano"
                    }
                  }
                },
                "State": "Generated"
              },
              "calendário_has_data": {
                "Binding": {
                  "ConceptualEntity": "Calendário"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "calendário.data"
                      },
                      "Subject": {
                        "Role": "calendário"
                      }
                    },
                    "ID": "calendários_have_data",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "calendário": {
                    "Target": {
                      "Entity": "calendário"
                    }
                  },
                  "calendário.data": {
                    "Target": {
                      "Entity": "calendário.data"
                    }
                  }
                },
                "State": "Generated"
              },
              "calendário_has_mê": {
                "Binding": {
                  "ConceptualEntity": "Calendário"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "calendário.mê"
                      },
                      "Subject": {
                        "Role": "calendário"
                      }
                    },
                    "ID": "calendários_have_mê",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "calendário": {
                    "Target": {
                      "Entity": "calendário"
                    }
                  },
                  "calendário.mê": {
                    "Target": {
                      "Entity": "calendário.mê"
                    }
                  }
                },
                "State": "Generated"
              },
              "medida1_has_grupo_medida": {
                "Binding": {
                  "ConceptualEntity": "Medida"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "medida1.grupo_medida"
                      },
                      "Subject": {
                        "Role": "medida1"
                      }
                    },
                    "ID": "medidas_have_grupo_medidas",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "medida1": {
                    "Target": {
                      "Entity": "medida1"
                    }
                  },
                  "medida1.grupo_medida": {
                    "Target": {
                      "Entity": "medida1.grupo_medida"
                    }
                  }
                },
                "State": "Generated"
              },
              "medida1_has_língua": {
                "Binding": {
                  "ConceptualEntity": "Medida"
                },
                "Roles": {
                  "língua": {
                    "Target": {
                      "Entity": "língua"
                    }
                  },
                  "medida1": {
                    "Target": {
                      "Entity": "medida1"
                    }
                  }
                },
                "State": "Generated"
              },
              "medida1_has_userculture": {
                "Binding": {
                  "ConceptualEntity": "Medida"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "medida1.userculture"
                      },
                      "Subject": {
                        "Role": "medida1"
                      }
                    },
                    "ID": "medidas_have_usercultures",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "medida1": {
                    "Target": {
                      "Entity": "medida1"
                    }
                  },
                  "medida1.userculture": {
                    "Target": {
                      "Entity": "medida1.userculture"
                    }
                  }
                },
                "State": "Generated"
              },
              "medida1_is_named_medida": {
                "Binding": {
                  "ConceptualEntity": "Medida"
                },
                "Phrasings": [
                  {
                    "ID": "medidas_are_names_IDs_of_medidas",
                    "Name": {
                      "Name": {
                        "Role": "medida1.medida"
                      },
                      "Subject": {
                        "Role": "medida1"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "medida1.medida"
                      },
                      "Subject": {
                        "Role": "medida1"
                      }
                    },
                    "ID": "medidas_have_medidas",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "medida1": {
                    "Target": {
                      "Entity": "medida1"
                    }
                  },
                  "medida1.medida": {
                    "Target": {
                      "Entity": "medida1.medida"
                    }
                  }
                },
                "State": "Generated"
              },
              "medida_has_dynamic_label": {
                "Binding": {
                  "ConceptualEntity": "Medidas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "medida.dynamic_label"
                      },
                      "Subject": {
                        "Role": "medida"
                      }
                    },
                    "ID": "medidas_have_dynamic_label",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "medida": {
                    "Target": {
                      "Entity": "medida"
                    }
                  },
                  "medida.dynamic_label": {
                    "Target": {
                      "Entity": "medida.dynamic_label"
                    }
                  }
                },
                "State": "Generated"
              },
              "medida_has_main_title": {
                "Binding": {
                  "ConceptualEntity": "Medidas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "medida.main_title"
                      },
                      "Subject": {
                        "Role": "medida"
                      }
                    },
                    "ID": "medidas_have_main_title",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "medida": {
                    "Target": {
                      "Entity": "medida"
                    }
                  },
                  "medida.main_title": {
                    "Target": {
                      "Entity": "medida.main_title"
                    }
                  }
                },
                "State": "Generated"
              },
              "medida_has_user_culture": {
                "Binding": {
                  "ConceptualEntity": "Medidas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "medida.user_culture"
                      },
                      "Subject": {
                        "Role": "medida"
                      }
                    },
                    "ID": "medidas_have_user_culture",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "medida": {
                    "Target": {
                      "Entity": "medida"
                    }
                  },
                  "medida.user_culture": {
                    "Target": {
                      "Entity": "medida.user_culture"
                    }
                  }
                },
                "State": "Generated"
              },
              "medida_has_visual_title": {
                "Binding": {
                  "ConceptualEntity": "Medidas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "medida.visual_title"
                      },
                      "Subject": {
                        "Role": "medida"
                      }
                    },
                    "ID": "medidas_have_visual_title",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "medida": {
                    "Target": {
                      "Entity": "medida"
                    }
                  },
                  "medida.visual_title": {
                    "Target": {
                      "Entity": "medida.visual_title"
                    }
                  }
                },
                "State": "Generated"
              },
              "origen_has_id_origem": {
                "Binding": {
                  "ConceptualEntity": "Origens"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "origen.id_origem"
                      },
                      "Subject": {
                        "Role": "origen"
                      }
                    },
                    "ID": "origen_have_id_origems",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "origen": {
                    "Target": {
                      "Entity": "origen"
                    }
                  },
                  "origen.id_origem": {
                    "Target": {
                      "Entity": "origen.id_origem"
                    }
                  }
                },
                "State": "Generated"
              },
              "origen_has_língua": {
                "Binding": {
                  "ConceptualEntity": "Origens"
                },
                "Roles": {
                  "língua": {
                    "Target": {
                      "Entity": "língua"
                    }
                  },
                  "origen": {
                    "Target": {
                      "Entity": "origen"
                    }
                  }
                },
                "State": "Generated"
              },
              "origen_has_origem": {
                "Binding": {
                  "ConceptualEntity": "Origens"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "origen.origem"
                      },
                      "Subject": {
                        "Role": "origen"
                      }
                    },
                    "ID": "origen_have_origems",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "origen": {
                    "Target": {
                      "Entity": "origen"
                    }
                  },
                  "origen.origem": {
                    "Target": {
                      "Entity": "origen.origem"
                    }
                  }
                },
                "State": "Generated"
              },
              "origen_has_userculture": {
                "Binding": {
                  "ConceptualEntity": "Origens"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "origen.userculture"
                      },
                      "Subject": {
                        "Role": "origen"
                      }
                    },
                    "ID": "origen_have_usercultures",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "origen": {
                    "Target": {
                      "Entity": "origen"
                    }
                  },
                  "origen.userculture": {
                    "Target": {
                      "Entity": "origen.userculture"
                    }
                  }
                },
                "State": "Generated"
              },
              "venda_has_calendário": {
                "Binding": {
                  "ConceptualEntity": "Vendas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "calendário"
                      },
                      "Subject": {
                        "Role": "venda"
                      }
                    },
                    "ID": "venda_have_calendários",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "venda"
                      },
                      "Subject": {
                        "Role": "calendário"
                      }
                    },
                    "ID": "calendários_have_venda",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "calendário": {
                    "Target": {
                      "Entity": "calendário"
                    }
                  },
                  "venda": {
                    "Target": {
                      "Entity": "venda"
                    }
                  }
                },
                "State": "Generated"
              },
              "venda_has_medida_unidade": {
                "Binding": {
                  "ConceptualEntity": "Vendas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "medida.unidade"
                      },
                      "Subject": {
                        "Role": "venda"
                      }
                    },
                    "ID": "venda_have_unidade",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "medida.unidade": {
                    "Target": {
                      "Entity": "medida.unidade"
                    }
                  },
                  "venda": {
                    "Target": {
                      "Entity": "venda"
                    }
                  }
                },
                "State": "Generated"
              },
              "venda_has_medida_unidades_LY": {
                "Binding": {
                  "ConceptualEntity": "Vendas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "medida.unidades_LY"
                      },
                      "Subject": {
                        "Role": "venda"
                      }
                    },
                    "ID": "venda_have_unidades_LY",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "medida.unidades_LY": {
                    "Target": {
                      "Entity": "medida.unidades_LY"
                    }
                  },
                  "venda": {
                    "Target": {
                      "Entity": "venda"
                    }
                  }
                },
                "State": "Generated"
              },
              "venda_has_medidas_column_vendas": {
                "Binding": {
                  "ConceptualEntity": "Vendas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "medidas.column_vendas"
                      },
                      "Subject": {
                        "Role": "venda"
                      }
                    },
                    "ID": "venda_have_valor_vendas",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "medidas.column_vendas": {
                    "Target": {
                      "Entity": "medidas.column_vendas"
                    }
                  },
                  "venda": {
                    "Target": {
                      "Entity": "venda"
                    }
                  }
                },
                "State": "Generated"
              },
              "venda_has_medidas_vendas_ly": {
                "Binding": {
                  "ConceptualEntity": "Vendas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "medidas.vendas_ly"
                      },
                      "Subject": {
                        "Role": "venda"
                      }
                    },
                    "ID": "venda_have_valor_vendas_LY",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "medidas.vendas_ly": {
                    "Target": {
                      "Entity": "medidas.vendas_ly"
                    }
                  },
                  "venda": {
                    "Target": {
                      "Entity": "venda"
                    }
                  }
                },
                "State": "Generated"
              },
              "venda_has_origen": {
                "Binding": {
                  "ConceptualEntity": "Vendas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "origen"
                      },
                      "Subject": {
                        "Role": "venda"
                      }
                    },
                    "ID": "venda_have_origen",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "origen": {
                    "Target": {
                      "Entity": "origen"
                    }
                  },
                  "venda": {
                    "Target": {
                      "Entity": "venda"
                    }
                  }
                },
                "State": "Generated"
              },
              "venda_has_unidade": {
                "Binding": {
                  "ConceptualEntity": "Vendas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "venda.unidade"
                      },
                      "Subject": {
                        "Role": "venda"
                      }
                    },
                    "ID": "venda_have_unidades",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "venda": {
                    "Target": {
                      "Entity": "venda"
                    }
                  },
                  "venda.unidade": {
                    "Target": {
                      "Entity": "venda.unidade"
                    }
                  }
                },
                "State": "Generated"
              },
              "venda_has_valor_venda": {
                "Binding": {
                  "ConceptualEntity": "Vendas"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "venda.valor_venda"
                      },
                      "Subject": {
                        "Role": "venda"
                      }
                    },
                    "ID": "venda_have_valor_venda",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "venda": {
                    "Target": {
                      "Entity": "venda"
                    }
                  },
                  "venda.valor_venda": {
                    "Target": {
                      "Entity": "venda.valor_venda"
                    }
                  }
                },
                "State": "Generated"
              }
            },
            "Version": "3.5.0"
          },
          "contentType": "json"
        },
        "translations": {
          "model": {
            "name": "Model",
            "tables": [
              {
                "name": "Vendas",
                "columns": [
                  {
                    "name": "Data",
                    "translatedCaption": "Date"
                  }
                ],
                "translatedCaption": "Sales"
              },
              {
                "name": "Medidas",
                "measures": [
                  {
                    "name": "Valor Vendas",
                    "translatedCaption": "Sales Values",
                    "translatedDisplayFolder": "Sales"
                  },
                  {
                    "name": "Valor Vendas LY",
                    "translatedCaption": "Sales Value LY",
                    "translatedDisplayFolder": "Sales"
                  },
                  {
                    "name": "MainTitle",
                    "translatedDisplayFolder": "Titles"
                  },
                  {
                    "name": "Unidades",
                    "translatedCaption": "Units",
                    "translatedDisplayFolder": "Sales\\Units"
                  },
                  {
                    "name": "Unidades LY",
                    "translatedCaption": "Units LY",
                    "translatedDisplayFolder": "Sales\\Units"
                  },
                  {
                    "name": "VisualTitle",
                    "translatedDisplayFolder": "Titles\\Visuals"
                  },
                  {
                    "name": "Dynamic_Label",
                    "translatedDisplayFolder": "Titles"
                  }
                ]
              },
              {
                "name": "Calendário",
                "columns": [
                  {
                    "name": "Data",
                    "translatedCaption": "Date"
                  },
                  {
                    "name": "Ano",
                    "translatedCaption": "Year"
                  },
                  {
                    "name": "Mês",
                    "translatedCaption": "Month"
                  }
                ],
                "hierarchies": [
                  {
                    "name": "Data Hierarquia",
                    "levels": [
                      {
                        "name": "Data",
                        "translatedCaption": "Date"
                      },
                      {
                        "name": "Ano",
                        "translatedCaption": "Year"
                      }
                    ],
                    "translatedCaption": "Data hierarchy"
                  }
                ]
              },
              {
                "name": "GBL_Dim_Site_Types_GSC",
                "columns": [
                  {
                    "name": "Site_Type",
                    "translatedCaption": "Type Site"
                  }
                ]
              }
            ]
          }
        }
      },
      {
        "name": "pt-PT",
        "translations": {
          "model": {
            "name": "Model",
            "tables": [
              {
                "name": "Vendas",
                "columns": [
                  {
                    "name": "Data",
                    "translatedCaption": "Data"
                  }
                ],
                "translatedCaption": "Vendas"
              },
              {
                "name": "Medidas",
                "measures": [
                  {
                    "name": "Valor Vendas",
                    "translatedCaption": "Valor Vendas",
                    "translatedDisplayFolder": "Vendas"
                  },
                  {
                    "name": "Valor Vendas LY",
                    "translatedCaption": "Valor Vendas LY",
                    "translatedDisplayFolder": "Vendas"
                  },
                  {
                    "name": "MainTitle",
                    "translatedDisplayFolder": "Títulos"
                  },
                  {
                    "name": "Unidades",
                    "translatedCaption": "Unidades",
                    "translatedDisplayFolder": "Vendas\\Unidades"
                  },
                  {
                    "name": "Unidades LY",
                    "translatedCaption": "Unidades LY",
                    "translatedDisplayFolder": "Vendas\\Unidades"
                  },
                  {
                    "name": "VisualTitle",
                    "translatedDisplayFolder": "Títulos\\Visuais"
                  },
                  {
                    "name": "Dynamic_Label",
                    "translatedDisplayFolder": "Títulos"
                  }
                ]
              },
              {
                "name": "Calendário",
                "columns": [
                  {
                    "name": "Data",
                    "translatedCaption": "Data"
                  },
                  {
                    "name": "Ano",
                    "translatedCaption": "Ano"
                  },
                  {
                    "name": "Mês",
                    "translatedCaption": "Mês"
                  }
                ],
                "hierarchies": [
                  {
                    "name": "Data Hierarquia",
                    "levels": [
                      {
                        "name": "Data",
                        "translatedCaption": "Data"
                      },
                      {
                        "name": "Ano",
                        "translatedCaption": "Ano"
                      }
                    ],
                    "translatedCaption": "Data Hierarquia"
                  }
                ]
              },
              {
                "name": "GBL_Dim_Site_Types_GSC",
                "columns": [
                  {
                    "name": "Site_Type",
                    "translatedCaption": "Tipo Polo"
                  }
                ]
              }
            ]
          }
        }
      },
      {
        "name": "es-ES",
        "translations": {
          "model": {
            "name": "Model",
            "tables": [
              {
                "name": "Vendas",
                "columns": [
                  {
                    "name": "Data",
                    "translatedCaption": "Fecha"
                  }
                ],
                "translatedCaption": "Ventas"
              },
              {
                "name": "Medidas",
                "measures": [
                  {
                    "name": "Valor Vendas",
                    "translatedCaption": "Valor Ventas",
                    "translatedDisplayFolder": "Ventas"
                  },
                  {
                    "name": "Valor Vendas LY",
                    "translatedCaption": "Valor Ventas LY",
                    "translatedDisplayFolder": "Ventas"
                  },
                  {
                    "name": "MainTitle",
                    "translatedDisplayFolder": "Títulos"
                  },
                  {
                    "name": "Unidades",
                    "translatedCaption": "Unidades ES",
                    "translatedDisplayFolder": "Ventas\\Unidades"
                  },
                  {
                    "name": "Unidades LY",
                    "translatedCaption": "Unidades LY ES",
                    "translatedDisplayFolder": "Ventas\\Unidades"
                  },
                  {
                    "name": "VisualTitle",
                    "translatedDisplayFolder": "Títulos\\Visuais"
                  },
                  {
                    "name": "Dynamic_Label",
                    "translatedDisplayFolder": "Títulos"
                  }
                ]
              },
              {
                "name": "Calendário",
                "columns": [
                  {
                    "name": "Data",
                    "translatedCaption": "Fecha"
                  },
                  {
                    "name": "Ano",
                    "translatedCaption": "Año"
                  },
                  {
                    "name": "Mês",
                    "translatedCaption": "Mes"
                  }
                ],
                "hierarchies": [
                  {
                    "name": "Data Hierarquia",
                    "levels": [
                      {
                        "name": "Data",
                        "translatedCaption": "Fecha"
                      },
                      {
                        "name": "Ano",
                        "translatedCaption": "Año"
                      }
                    ],
                    "translatedCaption": "Jerarquía de datos"
                  }
                ]
              },
              {
                "name": "GBL_Dim_Site_Types_GSC",
                "columns": [
                  {
                    "name": "Site_Type",
                    "translatedCaption": "Tipo Polo ES"
                  }
                ]
              }
            ]
          }
        }
      },
      {
        "name": "fr-FR",
        "translations": {
          "model": {
            "name": "Model",
            "tables": [
              {
                "name": "Vendas",
                "columns": [
                  {
                    "name": "Data",
                    "translatedCaption": "Date"
                  }
                ],
                "translatedCaption": "Vendas FR"
              },
              {
                "name": "Medidas",
                "measures": [
                  {
                    "name": "Valor Vendas",
                    "translatedCaption": "Valor Vendas FR",
                    "translatedDisplayFolder": "VENTES"
                  },
                  {
                    "name": "Valor Vendas LY",
                    "translatedCaption": "Valor Vendas LY FR",
                    "translatedDisplayFolder": "VENTES"
                  },
                  {
                    "name": "MainTitle",
                    "translatedDisplayFolder": "Titres"
                  },
                  {
                    "name": "Unidades",
                    "translatedCaption": "Unidades FR",
                    "translatedDisplayFolder": "VendasFR\\Unidades"
                  },
                  {
                    "name": "Unidades LY",
                    "translatedCaption": "Unidades LY FR",
                    "translatedDisplayFolder": "VendasFR\\Unidades"
                  },
                  {
                    "name": "VisualTitle",
                    "translatedDisplayFolder": "Titres\\Visuais"
                  },
                  {
                    "name": "Dynamic_Label",
                    "translatedDisplayFolder": "Titres"
                  }
                ]
              },
              {
                "name": "Calendário",
                "columns": [
                  {
                    "name": "Data",
                    "translatedCaption": "Date"
                  },
                  {
                    "name": "Ano",
                    "translatedCaption": "Année"
                  },
                  {
                    "name": "Mês",
                    "translatedCaption": "Mois"
                  }
                ],
                "hierarchies": [
                  {
                    "name": "Data Hierarquia",
                    "levels": [
                      {
                        "name": "Data",
                        "translatedCaption": "Date"
                      },
                      {
                        "name": "Ano",
                        "translatedCaption": "Année"
                      }
                    ],
                    "translatedCaption": "Hiérarchie des données"
                  }
                ]
              },
              {
                "name": "GBL_Dim_Site_Types_GSC",
                "columns": [
                  {
                    "name": "Site_Type",
                    "translatedCaption": "Tipo Polo FR"
                  }
                ]
              }
            ]
          }
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Origens PT",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Sql.Database(\"scsbisrv1.sc.pt\", \"TCAP_DMV\"),",
          "    dbo_PBI_SV_ORIGENS = Source{[Schema=\"dbo\",Item=\"PBI_SV_ORIGENS\"]}[Data],",
          "    #\"Removed Columns\" = Table.RemoveColumns(dbo_PBI_SV_ORIGENS,{\"Descrição\"}),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"Origem\", \"OrigemPT\"}}),",
          "    #\"Added Conditional Column\" = Table.AddColumn(#\"Renamed Columns\", \"OrigemEN\", each if [OrigemPT] = \"Reactivo\" then \"Reactive\" else if [OrigemPT] = \"Proactivo\" then \"Proactive\" else [OrigemPT]),",
          "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Added Conditional Column\",{\"OrigemEN\"}),",
          "    #\"Colunas com Nome Mudado\" = Table.RenameColumns(#\"Colunas Removidas\",{{\"OrigemPT\", \"Origem\"}}),",
          "    #\"Personalizado Adicionado\" = Table.AddColumn(#\"Colunas com Nome Mudado\", \"USERCULTURE\", each \"pt-PT\"),",
          "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Personalizado Adicionado\",{{\"USERCULTURE\", type text}})",
          "in",
          "    #\"Tipo Alterado\""
        ],
        "kind": "m",
        "lineageTag": "adf7b037-e844-48b8-b03f-635848a94c88",
        "queryGroup": "Origens"
      },
      {
        "name": "Origens EN",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Sql.Database(\"scsbisrv1.sc.pt\", \"TCAP_DMV\"),",
          "    dbo_PBI_SV_ORIGENS = Source{[Schema=\"dbo\",Item=\"PBI_SV_ORIGENS\"]}[Data],",
          "    #\"Removed Columns\" = Table.RemoveColumns(dbo_PBI_SV_ORIGENS,{\"Descrição\"}),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"Origem\", \"OrigemPT\"}}),",
          "    #\"Added Conditional Column\" = Table.AddColumn(#\"Renamed Columns\", \"OrigemEN\", each if [OrigemPT] = \"Reactivo\" then \"Reactive\" else if [OrigemPT] = \"Proactivo\" then \"Proactive\" else [OrigemPT]),",
          "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Added Conditional Column\",{\"OrigemPT\"}),",
          "    #\"Colunas com Nome Mudado\" = Table.RenameColumns(#\"Colunas Removidas\",{{\"OrigemEN\", \"Origem\"}}),",
          "    #\"Personalizado Adicionado\" = Table.AddColumn(#\"Colunas com Nome Mudado\", \"USERCULTURE\", each \"en-US\")",
          "in",
          "    #\"Personalizado Adicionado\""
        ],
        "kind": "m",
        "lineageTag": "ae421520-6321-428a-b663-0b1ff34ca830",
        "queryGroup": "Origens"
      },
      {
        "name": "GBL_Dim_Site_Types_GSC_PT",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Origem = Sql.Database(\"SCSQLSRV3.sc.pt\\PRD\", \"BI_GSC\"),",
          "    dbo_GBL_Dim_Site_Types_GSC = Origem{[Schema=\"dbo\",Item=\"GBL_Dim_Site_Types_GSC\"]}[Data],",
          "    #\"Colunas Removidas\" = Table.RemoveColumns(dbo_GBL_Dim_Site_Types_GSC,{\"Site_Type_Level_1_Code\", \"Site_Type_Level_2_Code\", \"PT_Site_Type_Level_1_Desc\", \"PT_Site_Type_Level_2_Desc\", \"ES_Site_Type_Level_1_Desc\", \"ES_Site_Type_Level_2_Desc\", \"EN_Site_Type_Level_1_Desc\", \"EN_Site_Type_Level_2_Desc\", \"FR_Site_Type_Level_1_Desc\", \"FR_Site_Type_Level_2_Desc\"}),",
          "    #\"Colunas com Nome Mudado\" = Table.RenameColumns(#\"Colunas Removidas\",{{\"PT_Site_Type_Desc\", \"Site_Type\"}}),",
          "    #\"Colunas Removidas1\" = Table.RemoveColumns(#\"Colunas com Nome Mudado\",{\"ES_Site_Type_Desc\", \"EN_Site_Type_Desc\", \"FR_Site_Type_Desc\", \"Site_Type_Display_Order\"}),",
          "    #\"Personalizado Adicionado\" = Table.AddColumn(#\"Colunas Removidas1\", \"USERCULTURE\", each \"pt-PT\")",
          "in",
          "    #\"Personalizado Adicionado\""
        ],
        "kind": "m",
        "lineageTag": "63c5eaea-4763-46c1-bbce-a52eb1daad46",
        "queryGroup": "Origens"
      },
      {
        "name": "GBL_Dim_Site_Types_GSC_ES",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Origem = Sql.Database(\"SCSQLSRV3.sc.pt\\PRD\", \"BI_GSC\"),",
          "    dbo_GBL_Dim_Site_Types_GSC = Origem{[Schema=\"dbo\",Item=\"GBL_Dim_Site_Types_GSC\"]}[Data],",
          "    #\"Colunas Removidas\" = Table.RemoveColumns(dbo_GBL_Dim_Site_Types_GSC,{\"Site_Type_Level_1_Code\", \"Site_Type_Level_2_Code\", \"PT_Site_Type_Level_1_Desc\", \"PT_Site_Type_Level_2_Desc\", \"ES_Site_Type_Level_1_Desc\", \"ES_Site_Type_Level_2_Desc\", \"EN_Site_Type_Level_1_Desc\", \"EN_Site_Type_Level_2_Desc\", \"FR_Site_Type_Level_1_Desc\", \"FR_Site_Type_Level_2_Desc\"}),",
          "    #\"Colunas com Nome Mudado\" = Table.RenameColumns(#\"Colunas Removidas\",{{\"ES_Site_Type_Desc\", \"Site_Type\"}}),",
          "    #\"Colunas Removidas1\" = Table.RemoveColumns(#\"Colunas com Nome Mudado\",{\"PT_Site_Type_Desc\", \"EN_Site_Type_Desc\", \"FR_Site_Type_Desc\", \"Site_Type_Display_Order\"}),",
          "    #\"Personalizado Adicionado\" = Table.AddColumn(#\"Colunas Removidas1\", \"USERCULTURE\", each \"es-ES\")",
          "in",
          "    #\"Personalizado Adicionado\""
        ],
        "kind": "m",
        "lineageTag": "d30c6a97-189c-4cd2-ae33-33ebe14268b1",
        "queryGroup": "Origens"
      },
      {
        "name": "GBL_Dim_Site_Types_GSC_EN",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Origem = Sql.Database(\"SCSQLSRV3.sc.pt\\PRD\", \"BI_GSC\"),",
          "    dbo_GBL_Dim_Site_Types_GSC = Origem{[Schema=\"dbo\",Item=\"GBL_Dim_Site_Types_GSC\"]}[Data],",
          "    #\"Colunas Removidas\" = Table.RemoveColumns(dbo_GBL_Dim_Site_Types_GSC,{\"Site_Type_Level_1_Code\", \"Site_Type_Level_2_Code\", \"PT_Site_Type_Level_1_Desc\", \"PT_Site_Type_Level_2_Desc\", \"ES_Site_Type_Level_1_Desc\", \"ES_Site_Type_Level_2_Desc\", \"EN_Site_Type_Level_1_Desc\", \"EN_Site_Type_Level_2_Desc\", \"FR_Site_Type_Level_1_Desc\", \"FR_Site_Type_Level_2_Desc\"}),",
          "    #\"Colunas com Nome Mudado\" = Table.RenameColumns(#\"Colunas Removidas\",{{\"EN_Site_Type_Desc\", \"Site_Type\"}}),",
          "    #\"Colunas Removidas1\" = Table.RemoveColumns(#\"Colunas com Nome Mudado\",{\"PT_Site_Type_Desc\", \"ES_Site_Type_Desc\", \"FR_Site_Type_Desc\", \"Site_Type_Display_Order\"}),",
          "    #\"Personalizado Adicionado\" = Table.AddColumn(#\"Colunas Removidas1\", \"USERCULTURE\", each \"en-US\")",
          "in",
          "    #\"Personalizado Adicionado\""
        ],
        "kind": "m",
        "lineageTag": "496e609e-a18c-41d9-9b7f-0cd89e3b3036",
        "queryGroup": "Origens"
      },
      {
        "name": "GBL_Dim_Site_Types_GSC_FR",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Origem = Sql.Database(\"SCSQLSRV3.sc.pt\\PRD\", \"BI_GSC\"),",
          "    dbo_GBL_Dim_Site_Types_GSC = Origem{[Schema=\"dbo\",Item=\"GBL_Dim_Site_Types_GSC\"]}[Data],",
          "    #\"Colunas Removidas\" = Table.RemoveColumns(dbo_GBL_Dim_Site_Types_GSC,{\"Site_Type_Level_1_Code\", \"Site_Type_Level_2_Code\", \"PT_Site_Type_Level_1_Desc\", \"PT_Site_Type_Level_2_Desc\", \"ES_Site_Type_Level_1_Desc\", \"ES_Site_Type_Level_2_Desc\", \"EN_Site_Type_Level_1_Desc\", \"EN_Site_Type_Level_2_Desc\", \"FR_Site_Type_Level_1_Desc\", \"FR_Site_Type_Level_2_Desc\"}),",
          "    #\"Colunas com Nome Mudado\" = Table.RenameColumns(#\"Colunas Removidas\",{{\"FR_Site_Type_Desc\", \"Site_Type\"}}),",
          "    #\"Colunas Removidas1\" = Table.RemoveColumns(#\"Colunas com Nome Mudado\",{\"PT_Site_Type_Desc\", \"ES_Site_Type_Desc\", \"EN_Site_Type_Desc\", \"Site_Type_Display_Order\"}),",
          "    #\"Personalizado Adicionado\" = Table.AddColumn(#\"Colunas Removidas1\", \"USERCULTURE\", each \"fr-FR\")",
          "in",
          "    #\"Personalizado Adicionado\""
        ],
        "kind": "m",
        "lineageTag": "451d0a35-251e-4a61-aa8c-a574e171a746",
        "queryGroup": "Origens"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Calendário"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Origens"
      }
    ],
    "relationships": [
      {
        "name": "e568f3b0-2d3f-49d9-b521-d9583821fb16",
        "fromColumn": "USERCULTURE",
        "fromTable": "Origens",
        "toColumn": "USERCULTURE",
        "toTable": "Línguas"
      },
      {
        "name": "de623f06-2b66-493f-b7ac-f821d3bfa6aa",
        "fromColumn": "Data",
        "fromTable": "Vendas",
        "toColumn": "Data",
        "toTable": "Calendário"
      },
      {
        "name": "aef5e89a-b95e-4268-89b1-3431e83ed575",
        "fromColumn": "USERCULTURE",
        "fromTable": "Medida",
        "toColumn": "USERCULTURE",
        "toTable": "Línguas"
      },
      {
        "name": "AutoDetected_d702431f-b70f-448d-8048-e13813208686",
        "fromColumn": "USERCULTURE",
        "fromTable": "GBL_Dim_Site_Types_GSC",
        "toColumn": "USERCULTURE",
        "toTable": "Línguas"
      },
      {
        "name": "596dfff3-ca2e-486e-fdb3-2718c21bb0ff",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "ID_ORIGEM",
        "fromTable": "Origens",
        "toColumn": "ID_ORIGEM",
        "toTable": "Bridge Origens"
      },
      {
        "name": "4b9a7e46-ef0c-784c-e843-642a2aa7579c",
        "fromColumn": "ID_ORIGEM",
        "fromTable": "Vendas",
        "toColumn": "ID_ORIGEM",
        "toTable": "Bridge Origens"
      }
    ],
    "roles": [
      {
        "name": "USERCULTURE",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "a4b7cd8f2ad947c0b329c7b9445a2a3b"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Línguas",
            "filterExpression": "[USERCULTURE] = USERCULTURE()"
          }
        ]
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Vendas",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "changedProperties": [
          {
            "property": "Name"
          }
        ],
        "columns": [
          {
            "name": "ID_ORIGEM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2e9a6a10-9c94-46ea-9f81-1d7111a6a3dd",
            "sourceColumn": "ID_ORIGEM",
            "summarizeBy": "none"
          },
          {
            "name": "Unidades",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6e695aa4-180d-43ba-9fc7-89d798f891ca",
            "sourceColumn": "Unidades",
            "summarizeBy": "sum"
          },
          {
            "name": "Valor Venda",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a5036b6c-8337-44b3-8036-1f2d9a811150",
            "sourceColumn": "Valor Venda",
            "summarizeBy": "sum"
          },
          {
            "name": "Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "b2e61fb2-3b57-4377-99f1-a2c7dd9c6859",
            "sourceColumn": "Data",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "90d48ae9-21c6-45f1-978a-3afb85bda6cd",
        "partitions": [
          {
            "name": "Vendas-071c08a3-89d7-4b29-81a0-017a3413a87c",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"scsbisrv1.sc.pt\", \"TCAP_DMV\"),",
                "    dbo_PBI_SV_VENDAS = Source{[Schema=\"dbo\",Item=\"PBI_SV_VENDAS\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_PBI_SV_VENDAS,{\"ID_ORIGEM\", \"Unidades\", \"Valor Venda\", \"Data\"})",
                "in",
                "    #\"Removed Other Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Medidas",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "28c0d240-86c1-422b-a3b6-02b5a6084d79",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "626444d9-d0a6-4777-9f1d-8bbd61693e60",
        "measures": [
          {
            "name": "Valor Vendas",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Vendas_teste",
            "expression": [
              "",
              "CALCULATE( ",
              "    SUM(Vendas[Valor Venda])",
              ")"
            ],
            "formatString": "#,0\\ \"€\";-#,0\\ \"€\";#,0\\ \"€\"",
            "lineageTag": "0d9659dd-7852-4a25-8b54-8491e87e6670"
          },
          {
            "name": "Valor Vendas LY",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Vendas_teste",
            "expression": [
              "",
              "CALCULATE(",
              "    [Valor Vendas], ",
              "    SAMEPERIODLASTYEAR('Calendário'[Data])",
              ")"
            ],
            "formatString": "#,0\\ \"€\";-#,0\\ \"€\";#,0\\ \"€\"",
            "lineageTag": "77dde0d0-debd-4179-9a51-66945ef58eab"
          },
          {
            "name": "UserCulture",
            "expression": "USERCULTURE()",
            "lineageTag": "08a2e24b-4ec0-4004-b35b-99860b24eb65"
          },
          {
            "name": "MainTitle",
            "displayFolder": "Títulos",
            "expression": [
              "",
              "SWITCH(",
              "    userculture(),",
              "    \"pt-PT\", \"Relatório de Vendas\",",
              "    \"en-US\", \"Sales Report\",",
              "    \"es-ES\", \"Reporte de Ventas\",",
              "    \"fr-FR\", \"Rapport des ventes\"",
              ")"
            ],
            "lineageTag": "5586afb4-1ec2-4667-8895-0f6c424b3b79"
          },
          {
            "name": "Unidades",
            "displayFolder": "Vendas_teste\\Unidades",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(Vendas[Unidades])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "37561c9b-896b-49a0-8f70-b4675d5ea7f2"
          },
          {
            "name": "Unidades LY",
            "displayFolder": "Vendas_teste\\Unidades",
            "expression": [
              "",
              "CALCULATE(",
              "    [Unidades],",
              "   SAMEPERIODLASTYEAR('Calendário'[Data])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "3931b6a5-c569-42dd-bfdc-d57b6f659653"
          },
          {
            "name": "VisualTitle",
            "displayFolder": "Títulos\\Visuais",
            "expression": [
              "",
              "SWITCH(",
              "    userculture(),",
              "    \"pt-PT\", \"Unidades vs Vendas\",",
              "    \"en-US\", \"Units vs Sales\",",
              "    \"es-ES\", \"Unidades vs Ventas\",",
              "    \"fr-FR\", \"Unités vs Ventes\"",
              ")"
            ],
            "lineageTag": "fc22e769-ac82-44d9-9b5c-e645d0a79c51"
          },
          {
            "name": "Dynamic_Label",
            "displayFolder": "Títulos",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    USERCULTURE() = \"pt-PT\" && [Unidades], \"Unidades\",",
              "    USERCULTURE() = 1033 && [Unidades], \"Units\",",
              "    USERCULTURE() = 1046 && [Unidades LY], \"Unidades LY\",",
              "    USERCULTURE() = 1033 && [Unidades LY], \"Units LY\",",
              "    USERCULTURE() = 1046 && [Valor Vendas], \"Vendas\",",
              "    USERCULTURE() = 1033 && [Valor Vendas], \"Sales\",",
              "    USERCULTURE() = 1046 && [Valor Vendas LY], \"Vendas LY\",",
              "    USERCULTURE() = 1033 && [Valor Vendas LY], \"Sales LY\",",
              "    BLANK()",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "6cce4b4b-3bc7-4e76-852e-debc6db957ab"
          }
        ],
        "partitions": [
          {
            "name": "Medidas-c5c30478-565f-4041-8440-c5f204d2ea7e",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Línguas",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Língua",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "1093ac4f-ea68-40bd-b3be-63ef66c91787",
            "sortByColumn": "Order",
            "sourceColumn": "Língua",
            "summarizeBy": "none"
          },
          {
            "name": "Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1f3168af-abee-4046-9e28-467886c4c300",
            "sourceColumn": "Order",
            "summarizeBy": "sum"
          },
          {
            "name": "USERCULTURE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "bb94d177-d060-450d-8cd4-68c53e824d57",
            "sourceColumn": "USERCULTURE",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "4a5cd5c8-2f6e-4d1c-922b-7dc57f731c78",
        "partitions": [
          {
            "name": "Línguas-35c37ed7-c066-4e91-9d1e-ddc1f84a58af",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"SCSQLSRV3.sc.pt\\PRD\", \"BI_SCG\"),",
                "    Lang_GBL_Setup_Language = Source{[Schema=\"Lang\",Item=\"GBL_Setup_Language\"]}[Data],",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Lang_GBL_Setup_Language,{{\"Língua\", type text}, {\"Order\", Int64.Type}, {\"USERCULTURE\", type text}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Origens",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "ID_ORIGEM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3ba942ea-6716-492a-8fbe-ea29201590e1",
            "sourceColumn": "ID_ORIGEM",
            "summarizeBy": "none"
          },
          {
            "name": "Origem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "c2701b11-c9c2-4eda-b1f2-1748634bc93a",
            "sourceColumn": "Origem",
            "summarizeBy": "none"
          },
          {
            "name": "USERCULTURE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "067e3889-0793-49e6-aee7-b8dbdf9f1dc9",
            "sourceColumn": "USERCULTURE",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7b026f34-4a3d-4ac7-9b43-2696d094300a",
        "partitions": [
          {
            "name": "Origens-5c893771-1134-4a4d-bf3e-0fb5ea3ca7a9",
            "mode": "import",
            "queryGroup": "Origens",
            "source": {
              "expression": [
                "let",
                "    Origem = Table.Combine({#\"Origens EN\", #\"Origens PT\"})",
                "in",
                "    Origem"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Medida",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "4fac4c8873ea4d9abd6624cc0b768678"
          }
        ],
        "columns": [
          {
            "name": "Medida",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "bfc8b3df-d9c8-4a14-9286-c23a1cd37d0c",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Medida Fields"
                }
              ]
            },
            "sortByColumn": "Medida Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Medida Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "62000fb8-cc64-4850-b4d2-2780a8839c21",
            "sortByColumn": "Medida Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Medida Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "787fe9d0-5d60-4992-b9f6-69dbd0268fa7",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Grupo Medida",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "858ffb0d-3b3d-4fa6-b0d7-7a337ff7d8a1",
            "sourceColumn": "[Value4]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "USERCULTURE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "b2867207-2f95-438c-9bd3-07fd78b92fea",
            "sourceColumn": "[Value5]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "33c159cc-5932-4b35-817b-4c06dfdc8e35",
        "partitions": [
          {
            "name": "Medida-e66c6855-f934-4489-a6ca-fb112b524158",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "{",
                "    (\"Unidades\", NAMEOF('Medidas'[Unidades]), 0,\"Unidades\", \"pt-PT\"),",
                "    (\"Unidades LY\", NAMEOF('Medidas'[Unidades LY]), 1, \"Unidades\",\"pt-PT\"),",
                "    (\"Valor Vendas\", NAMEOF('Medidas'[Valor Vendas]), 2, \"Valor Vendas\",\"pt-PT\"),",
                "    (\"Valor Vendas LY\", NAMEOF('Medidas'[Valor Vendas LY]), 3, \"Valor Vendas\",\"pt-PT\"),",
                "    (\"Units\", NAMEOF('Medidas'[Unidades]), 4,\"Units\",\"en-US\"),",
                "    (\"Units LY\", NAMEOF('Medidas'[Unidades LY]), 5, \"Units\",\"en-US\"),",
                "    (\"Sales\", NAMEOF('Medidas'[Valor Vendas]), 6, \"Sales\",\"en-US\"),",
                "    (\"Sales LY\", NAMEOF('Medidas'[Valor Vendas LY]), 7, \"Sales\",\"en-US\")",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Calendário",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isKey": true,
            "lineageTag": "7624d952-adc5-4869-946f-9adbd40c4fe7",
            "sourceColumn": "Data",
            "summarizeBy": "none"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ada18ecc-6bd1-4202-8be9-a47617cf5c9c",
            "sourceColumn": "Ano",
            "summarizeBy": "none"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8a93ab72-387d-4d47-a650-f7d3a61e3f59",
            "sourceColumn": "Mês",
            "summarizeBy": "none"
          }
        ],
        "dataCategory": "Time",
        "hierarchies": [
          {
            "name": "Data Hierarquia",
            "levels": [
              {
                "name": "Data",
                "column": "Data",
                "lineageTag": "f654028d-faf6-48e8-839a-248e0bae5731",
                "ordinal": 0
              },
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "4fedfd49-4807-4ad0-8065-f48274449235",
                "ordinal": 1
              }
            ],
            "lineageTag": "223db4a7-e575-4e7b-b8a3-7965dcc38cca"
          }
        ],
        "lineageTag": "99797356-8356-4449-9712-4add681f83cd",
        "partitions": [
          {
            "name": "Calendário-07e97999-52ea-4c4f-aa94-6a60511fcbe6",
            "mode": "import",
            "queryGroup": "Calendário",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMjDUByIjAwMDpdhYAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [StartDate = _t]),",
                "    #\"Added Custom\" = Table.AddColumn(Source, \"EndDate\", each Date.From(DateTime.LocalNow())),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"EndDate\", type date}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Changed Type2\",{{\"StartDate\", type date}}),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Changed Type\", \"Dates\", each {Number.From([StartDate])..Number.From([EndDate])}),",
                "    #\"Expanded Dates\" = Table.ExpandListColumn(#\"Added Custom1\", \"Dates\"),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Expanded Dates\",{{\"Dates\", type date}}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Changed Type1\",{\"StartDate\", \"EndDate\"}),",
                "    #\"Added Custom2\" = Table.AddColumn(#\"Removed Columns1\", \"Year\", each Date.Year([Dates])),",
                "    #\"Added Custom3\" = Table.AddColumn(#\"Added Custom2\", \"Month\", each Date.Month([Dates])),",
                "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Added Custom3\",{{\"Month\", Int64.Type}, {\"Year\", Int64.Type}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type3\",{{\"Dates\", \"Data\"}, {\"Month\", \"Mês\"}, {\"Year\", \"Ano\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "GBL_Dim_Site_Types_GSC",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Site_Type_Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e5568c53-c869-4ea6-8f47-9770b8604420",
            "sourceColumn": "Site_Type_Code",
            "summarizeBy": "count"
          },
          {
            "name": "Site_Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "945caa32-6034-4c7e-b1f0-5c8a33c689aa",
            "sourceColumn": "Site_Type",
            "summarizeBy": "none"
          },
          {
            "name": "USERCULTURE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4812d088-1cdb-4666-aea5-d65f462751eb",
            "sourceColumn": "USERCULTURE",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "712d26d2-59c1-4bf0-a0c6-d5e785233e5f",
        "partitions": [
          {
            "name": "GBL_Dim_Site_Types_GSC",
            "mode": "import",
            "queryGroup": "Origens",
            "source": {
              "expression": [
                "let",
                "    Origem = Table.Combine({GBL_Dim_Site_Types_GSC_PT, GBL_Dim_Site_Types_GSC_ES, GBL_Dim_Site_Types_GSC_EN, GBL_Dim_Site_Types_GSC_FR}),",
                "    #\"Linhas Ordenadas\" = Table.Sort(Origem,{{\"Site_Type_Code\", Order.Ascending}})",
                "in",
                "    #\"Linhas Ordenadas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Bridge Origens",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "8415dcb198eb4d8f9de8ece7bbd02d4d"
          }
        ],
        "columns": [
          {
            "name": "ID_ORIGEM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e3c1e9b8-44b4-4933-9065-422128920c66",
            "sourceColumn": "Origens[ID_ORIGEM]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "isHidden": true,
        "lineageTag": "95a68749-38a1-4620-a0db-62c22cd80db5",
        "partitions": [
          {
            "name": "Bridge Origens",
            "mode": "import",
            "source": {
              "expression": "VALUES(Origens[ID_ORIGEM])",
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}