{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.114.864.0 (23.02)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Orders\",\"Person\",\"Returns\",\"Metrics\"]"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Returns",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\racac\\Rigor\\6825_DGAA - DGAA\\03 - Documentação\\39 - Interno\\02 - Power BI\\Formação\\Formação\\Sample - Superstore.xlsx\"), null, true),",
          "    Orders_Sheet = Source{[Item=\"Returns\",Kind=\"Sheet\"]}[Data],",
          "    #\"Promoted Headers1\" = Table.PromoteHeaders(Orders_Sheet, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers1\",{{\"Returned\", type text}, {\"Order ID\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "1f0b7d4a-ab48-4bc7-964a-1070e7111528"
      },
      {
        "name": "Person",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\racac\\Rigor\\6825_DGAA - DGAA\\03 - Documentação\\39 - Interno\\02 - Power BI\\Formação\\Formação\\Sample - Superstore.xlsx\"), null, true),",
          "    People_Sheet = Source{[Item=\"People\",Kind=\"Sheet\"]}[Data],",
          "    #\"Changed Type\" = Table.TransformColumnTypes(People_Sheet,{{\"Column1\", type text}, {\"Column2\", type text}}),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Person\", type text}, {\"Region\", type text}})",
          "in",
          "    #\"Changed Type1\""
        ],
        "kind": "m",
        "lineageTag": "a0fbc085-777f-4374-899c-3b8dc28a0cff"
      }
    ],
    "perspectives": [
      {
        "name": "Sales",
        "tables": [
          {
            "name": "Orders",
            "columns": [
              {
                "name": "Customer Name"
              },
              {
                "name": "City"
              },
              {
                "name": "State"
              },
              {
                "name": "Postal Code"
              },
              {
                "name": "Region"
              },
              {
                "name": "Order ID"
              },
              {
                "name": "Ship Mode"
              },
              {
                "name": "Person"
              },
              {
                "name": "Segment"
              },
              {
                "name": "Category"
              },
              {
                "name": "Sub-Category"
              },
              {
                "name": "Product Name"
              },
              {
                "name": "Returned"
              }
            ]
          },
          {
            "name": "Metrics",
            "measures": [
              {
                "name": "Sales"
              },
              {
                "name": "Sales TD"
              },
              {
                "name": "Sales PM"
              },
              {
                "name": "Sales vs PM"
              },
              {
                "name": "Sales YTD"
              },
              {
                "name": "Sales SPLY"
              }
            ]
          }
        ]
      },
      {
        "name": "Orders",
        "tables": [
          {
            "name": "Orders",
            "columns": [
              {
                "name": "Order ID"
              },
              {
                "name": "Ship Mode"
              },
              {
                "name": "Person"
              },
              {
                "name": "Customer Name"
              },
              {
                "name": "City"
              },
              {
                "name": "State"
              },
              {
                "name": "Postal Code"
              },
              {
                "name": "Region"
              },
              {
                "name": "Segment"
              },
              {
                "name": "Category"
              },
              {
                "name": "Sub-Category"
              },
              {
                "name": "Product Name"
              },
              {
                "name": "Returned"
              }
            ]
          },
          {
            "name": "Metrics",
            "measures": [
              {
                "name": "Orders"
              },
              {
                "name": "Orders TD"
              },
              {
                "name": "Orders PM"
              },
              {
                "name": "Orders vs PM"
              },
              {
                "name": "Orders YTD"
              }
            ]
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "6b5e8cef-e8b3-4d13-a4a9-e31e9946d3a2",
        "fromColumn": "Ship Date",
        "fromTable": "Orders",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_627eac13-7b3b-40f8-9f1d-87bc0cf399e7"
      },
      {
        "name": "9f541fa5-9ff4-469a-995b-6aceaa9e08e3",
        "fromColumn": "Date",
        "fromTable": "Calendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_0fc16a12-a964-4f8e-bdb1-c5fafab0fc14"
      },
      {
        "name": "04e231f9-b2b0-49a2-9326-9e715d132de3",
        "fromColumn": "Order Date",
        "fromTable": "Orders",
        "toColumn": "Date",
        "toTable": "Calendar"
      }
    ],
    "sourceQueryCulture": "pt-PT",
    "tables": [
      {
        "name": "Orders",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Row ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Order",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "cdd05944-6cb3-46b9-adda-8452299ee4e0",
            "sourceColumn": "Row ID",
            "summarizeBy": "count"
          },
          {
            "name": "Order ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "displayFolder": "Order",
            "lineageTag": "4f05ed5e-7136-464c-88b2-928f1e8290b9",
            "sourceColumn": "Order ID",
            "summarizeBy": "none"
          },
          {
            "name": "Order Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataType": "dateTime",
            "displayFolder": "Order",
            "formatString": "yyyy-mm-dd",
            "isHidden": true,
            "lineageTag": "dba8057e-b3ac-414d-a156-756e058811b9",
            "sourceColumn": "Order Date",
            "summarizeBy": "none"
          },
          {
            "name": "Ship Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataType": "dateTime",
            "displayFolder": "Order",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "b0c64211-3ffe-4f2e-8641-dce70d7a6036",
            "sourceColumn": "Ship Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_627eac13-7b3b-40f8-9f1d-87bc0cf399e7"
                },
                "isDefault": true,
                "relationship": "6b5e8cef-e8b3-4d13-a4a9-e31e9946d3a2"
              }
            ]
          },
          {
            "name": "Ship Mode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "displayFolder": "Order",
            "lineageTag": "5d296973-cc9d-4cdf-9c6d-d9b79d746e3e",
            "sourceColumn": "Ship Mode",
            "summarizeBy": "none"
          },
          {
            "name": "Customer ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataType": "string",
            "displayFolder": "Customer",
            "isHidden": true,
            "lineageTag": "d95d310c-f94f-43c4-8e44-72c16ed90d5a",
            "sourceColumn": "Customer ID",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "displayFolder": "Customer",
            "lineageTag": "49c1bb09-ed1e-491a-be46-c1a8afabfc73",
            "sourceColumn": "Customer Name",
            "summarizeBy": "none"
          },
          {
            "name": "Segment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "displayFolder": "Product",
            "lineageTag": "ef8ac509-0f7c-40dd-9a15-e8dec0cd4d5f",
            "sourceColumn": "Segment",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "displayFolder": "Customer",
            "lineageTag": "a8c3b19e-83fc-4ba2-87d9-24888cf9dba3",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "displayFolder": "Customer",
            "lineageTag": "cf05c194-7a2e-4297-a804-0c02adefbb33",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "displayFolder": "Customer",
            "lineageTag": "876cd37a-7170-428c-b112-0e16465cdb95",
            "sourceColumn": "State",
            "summarizeBy": "none"
          },
          {
            "name": "Postal Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "displayFolder": "Customer",
            "formatString": "0",
            "lineageTag": "df2756a0-7efe-4388-ac2e-27ed50bfbd64",
            "sourceColumn": "Postal Code",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "displayFolder": "Customer",
            "lineageTag": "ff3600e7-0128-4b0a-93c7-24ac95495b74",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Product ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "displayFolder": "Product",
            "lineageTag": "679ead56-3a78-4e7a-984c-de34b8e6cc9c",
            "sourceColumn": "Product ID",
            "summarizeBy": "none"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "displayFolder": "Product",
            "lineageTag": "e00c9321-fd7e-49d4-b28c-03e73438a02d",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "Sub-Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "displayFolder": "Product",
            "lineageTag": "e0a51a40-0a6d-45ad-8e89-9e2d83c055f8",
            "sourceColumn": "Sub-Category",
            "summarizeBy": "none"
          },
          {
            "name": "Product Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "displayFolder": "Product",
            "lineageTag": "a0c1b499-8318-4aca-b4d3-c8eb3c46a372",
            "sourceColumn": "Product Name",
            "summarizeBy": "none"
          },
          {
            "name": "Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataType": "double",
            "displayFolder": "Order",
            "isHidden": true,
            "lineageTag": "47dd3968-2c1d-4ca3-bcbe-af98dcc39319",
            "sourceColumn": "Sales",
            "summarizeBy": "sum"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Order",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3b657142-70c6-4239-8245-87ddab93650a",
            "sourceColumn": "Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Discount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataType": "double",
            "displayFolder": "Order",
            "isHidden": true,
            "lineageTag": "87c838a6-a0c5-462c-a706-54382af19e65",
            "sourceColumn": "Discount",
            "summarizeBy": "sum"
          },
          {
            "name": "Profit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataType": "double",
            "displayFolder": "Order",
            "isHidden": true,
            "lineageTag": "740c8c4d-530d-4cd1-b4d7-61d587c0d70b",
            "sourceColumn": "Profit",
            "summarizeBy": "sum"
          },
          {
            "name": "Returned",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "displayFolder": "Product",
            "lineageTag": "5c8591ab-643f-4ac7-aeac-a511f984fff7",
            "sourceColumn": "Returned",
            "summarizeBy": "none"
          },
          {
            "name": "Days to Ship",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Order",
            "expression": "DATEDIFF(Orders[Order Date],Orders[Ship Date],DAY)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "b4f60de8-cc2a-47ed-87f9-ed47a06ddb11",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Person",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "displayFolder": "Order",
            "lineageTag": "eda260c5-0c69-48a5-8099-a6546d0c092d",
            "sourceColumn": "Person",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6cb45e92-0f02-4704-a030-3ea6fc807e92",
        "partitions": [
          {
            "name": "Orders-e67443c4-266f-4762-8382-52d166caaf92",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\racac\\Rigor\\6825_DGAA - DGAA\\03 - Documentação\\39 - Interno\\02 - Power BI\\Formação\\Formação\\Sample - Superstore.xlsx\"), null, true),",
                "    Orders_Sheet = Source{[Item=\"Orders\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Orders_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Row ID\", Int64.Type}, {\"Order ID\", type text}, {\"Order Date\", type date}, {\"Ship Date\", type date}, {\"Ship Mode\", type text}, {\"Customer ID\", type text}, {\"Customer Name\", type text}, {\"Segment\", type text}, {\"Country\", type text}, {\"City\", type text}, {\"State\", type text}, {\"Postal Code\", Int64.Type}, {\"Region\", type text}, {\"Product ID\", type text}, {\"Category\", type text}, {\"Sub-Category\", type text}, {\"Product Name\", type text}, {\"Sales\", type number}, {\"Quantity\", Int64.Type}, {\"Discount\", type number}, {\"Profit\", type number}}),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Changed Type\", {\"Order ID\"}, Returns, {\"Order ID\"}, \"Returns\", JoinKind.LeftOuter),",
                "    #\"Expanded Returns\" = Table.ExpandTableColumn(#\"Merged Queries\", \"Returns\", {\"Returned\"}, {\"Returned\"}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Expanded Returns\",null,\"No\",Replacer.ReplaceValue,{\"Returned\"}),",
                "    #\"Merged Queries1\" = Table.NestedJoin(#\"Replaced Value\", {\"Region\"}, Person, {\"Region\"}, \"Person\", JoinKind.LeftOuter),",
                "    #\"Expanded Person\" = Table.ExpandTableColumn(#\"Merged Queries1\", \"Person\", {\"Person\"}, {\"Person.1\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Expanded Person\",{{\"Person.1\", \"Person\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Metrics",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "d871a28d-3b52-4b7d-8473-55a76218506b",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "eb4fff25-6aec-4a02-b336-aed3f9774850",
        "measures": [
          {
            "name": "Orders",
            "expression": "DISTINCTCOUNT(Orders[Order ID])",
            "formatString": "0",
            "lineageTag": "654bc72c-4969-4c7f-80ff-929098a20e02"
          },
          {
            "name": "Quantity",
            "expression": "SUM(Orders[Quantity])",
            "formatString": "0",
            "lineageTag": "77e176f7-7518-41b1-8508-a6f527c561a5"
          },
          {
            "name": "Profit",
            "expression": "SUM(Orders[Profit])",
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "97b134b5-5bbd-488b-a2d6-02032162178e"
          },
          {
            "name": "Avg Days to Ship",
            "expression": "AVERAGE(Orders[Days to Ship])",
            "formatString": "0.0",
            "lineageTag": "ab2e8cd3-d92d-4f2e-b6cd-b8865299a94e"
          },
          {
            "name": "Sales",
            "description": "Somatório do valor de Vendas de cada Encomenda",
            "expression": "SUM(Orders[Sales])",
            "formatString": "#,0\\ \"€\";-#,0\\ \"€\";#,0\\ \"€\"",
            "lineageTag": "caea2fc3-45d4-4ddc-9833-dba12e7d109e"
          },
          {
            "name": "Discount",
            "expression": "AVERAGE(Orders[Discount])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "a97d5992-802f-44eb-b1b9-6687fea675b9"
          },
          {
            "name": "Customers",
            "expression": "DISTINCTCOUNT(Orders[Customer ID])",
            "formatString": "0",
            "lineageTag": "1ca5f201-e299-4570-a1fc-ebd5dacfafc4"
          },
          {
            "name": "Orders TD",
            "expression": [
              "",
              "VAR MaxDate = MAX('Calendar'[Date])",
              "",
              "RETURN",
              "CALCULATE(",
              "    [Orders],",
              "    ALL('Calendar'[Date]),",
              "    'Calendar'[Date] <= MaxDate",
              ")",
              "    "
            ],
            "formatString": "0",
            "lineageTag": "bdf86f17-09e6-4dfb-89bf-bc4d4c017606"
          },
          {
            "name": "Quantity TD",
            "expression": [
              "",
              "VAR MaxDate = MAX('Calendar'[Date])",
              "",
              "RETURN",
              "CALCULATE(",
              "    [Quantity],",
              "    ALL('Calendar'[Date]),",
              "    'Calendar'[Date] <= MaxDate",
              ")    "
            ],
            "formatString": "0",
            "lineageTag": "5076d458-42f8-4aaf-8b26-11140d49ad71"
          },
          {
            "name": "Profit TD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR MaxDate = MAX('Calendar'[Date])",
              "",
              "RETURN",
              "CALCULATE(",
              "    [Profit],",
              "    ALL('Calendar'[Date]),",
              "    'Calendar'[Date] <= MaxDate",
              ")   "
            ],
            "lineageTag": "3136decc-3b49-4cc1-9e0a-16efe8a9e539"
          },
          {
            "name": "Sales TD",
            "expression": [
              "",
              "VAR MaxDate = MAX('Calendar'[Date])",
              "",
              "RETURN",
              "CALCULATE(",
              "    [Sales],",
              "    ALL('Calendar'[Date]),",
              "    'Calendar'[Date] <= MaxDate",
              ")   "
            ],
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "dda0c72b-2172-4398-8aa0-c864fa149162"
          },
          {
            "name": "Orders PM",
            "expression": [
              "",
              "CALCULATE(",
              "    [Orders],",
              "    PREVIOUSMONTH('Calendar'[Date])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "2382e1c8-60c3-4b9c-920c-3da2704ed842"
          },
          {
            "name": "Orders vs PM",
            "expression": "[Orders] - [Orders PM]",
            "formatString": "0",
            "lineageTag": "b95d0039-e866-44ab-8339-354d704f1405"
          },
          {
            "name": "Profit PM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    [Profit],",
              "    PREVIOUSMONTH('Calendar'[Date])",
              ")",
              ""
            ],
            "lineageTag": "2a7e4501-9f00-4d9c-92e3-6b1dcd12cdad"
          },
          {
            "name": "Profit vs PM",
            "expression": "[Profit] - [Profit PM]",
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "0d366014-6b35-4b32-b4e4-859b79572ffe"
          },
          {
            "name": "Sales PM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    [Sales],",
              "    PREVIOUSMONTH('Calendar'[Date])",
              ")"
            ],
            "lineageTag": "15eea266-1cad-4297-aeeb-52ecd40c185e"
          },
          {
            "name": "Sales vs PM",
            "expression": [
              "",
              "CALCULATE(",
              "    [Sales],",
              "    PREVIOUSMONTH('Calendar'[Date])",
              ")"
            ],
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "c81b4d02-5c5d-40f0-8d27-6202394e2df8"
          },
          {
            "name": "Quantity PM",
            "expression": [
              "",
              "CALCULATE(",
              "    [Quantity],",
              "    PREVIOUSMONTH('Calendar'[Date])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "59485f0f-5f35-4f0d-8bfc-245d9721546b"
          },
          {
            "name": "Quantity vs PM",
            "expression": "[Quantity] - [Quantity PM]",
            "formatString": "0",
            "lineageTag": "8887135d-e0d1-40ee-b717-16e410c5ab9b"
          },
          {
            "name": "New Customers",
            "expression": [
              "",
              "COUNTROWS (",
              "    FILTER (",
              "        ADDCOLUMNS (",
              "            VALUES ( Orders[Customer ID] ),",
              "            \"New Customers\", CALCULATE (",
              "                [Customers],",
              "                FILTER (",
              "                    ALL ( 'Calendar'[Date] ),",
              "                    'Calendar'[Date] < MIN ( 'Calendar'[Date] )",
              "                )",
              "            )",
              "        ),",
              "        [New Customers] = 0",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "4b7fd527-f2b9-4ee0-8358-6403b322a1de"
          },
          {
            "name": "Avg Days to Ship TD",
            "expression": [
              "",
              "VAR MaxDate = MAX('Calendar'[Date])",
              "",
              "RETURN",
              "CALCULATE(",
              "    [Avg Days to Ship],",
              "    ALL('Calendar'[Date]),",
              "    'Calendar'[Date] <= MaxDate",
              ")  "
            ],
            "formatString": "0.0",
            "lineageTag": "4bb3a50e-7237-4847-8f78-2add7c3f5d82"
          },
          {
            "name": "Discount TD",
            "expression": [
              "",
              "VAR MaxDate = MAX('Calendar'[Date])",
              "",
              "RETURN",
              "CALCULATE(",
              "    [Discount],",
              "    ALL('Calendar'[Date]),",
              "    'Calendar'[Date] <= MaxDate",
              ")  "
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "3c40bf23-0da1-487a-abbd-be4988cda0cf"
          },
          {
            "name": "Sales YTD",
            "expression": [
              "",
              "    TOTALYTD(",
              "        [Sales],",
              "        'Calendar'[Date]",
              "    )"
            ],
            "formatString": "#,0\\ \"€\";-#,0\\ \"€\";#,0\\ \"€\"",
            "lineageTag": "c48ef475-b7ec-4545-9d29-96a253570e29"
          },
          {
            "name": "Profit YTD",
            "expression": [
              "",
              "TOTALYTD(",
              "    [Profit],",
              "    'Calendar'[Date]",
              ")"
            ],
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "9efcf0d2-68c9-48d5-a51b-42af0ef5cd3d"
          },
          {
            "name": "Orders YTD",
            "expression": [
              "",
              "TOTALYTD(",
              "    [Orders],",
              "    'Calendar'[Date]",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "fd63b268-0027-4072-8068-b07976a75299"
          },
          {
            "name": "Quantity YTD",
            "expression": [
              "",
              "TOTALYTD(",
              "    [Quantity],",
              "    'Calendar'[Date]",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "b6f7fe8f-ad57-4cf0-8ff2-353ac9b885ee"
          },
          {
            "name": "Profit by Unit",
            "expression": "DIVIDE([Profit] , [Quantity])",
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "9bbeaaba-207a-49da-86b6-9642a9c1d126"
          },
          {
            "name": "Sales SPLY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    [Sales],",
              "    SAMEPERIODLASTYEAR('Calendar'[Date])",
              ")"
            ],
            "lineageTag": "e649b023-dce1-4e06-987b-a51fe68f6372"
          },
          {
            "name": "Returning Customers",
            "expression": [
              "",
              "COUNTROWS (",
              "    CALCULATETABLE (",
              "        VALUES ( Orders[Customer ID] ),",
              "        VALUES ( Orders[Customer ID] ),",
              "        FILTER (",
              "            ALL ( 'Calendar' ),",
              "            'Calendar'[Date] < MIN ( 'Calendar'[Date] )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "a3700e0a-340e-4a2d-b429-33d60215d5d9"
          },
          {
            "name": "Days since last Order",
            "expression": [
              "",
              "VAR LastOrderDate = ",
              "CALCULATE( ",
              "    MAX( Orders[Order Date] ),",
              "    FILTER( ",
              "        ALL( Orders[Order Date] ), ",
              "        Orders[Order Date] < MAX(Orders[Order Date]) ",
              "    )   ",
              ")",
              "VAR CurrentOrderDate = MAX( Orders[Order Date] )",
              "",
              "RETURN DATEDIFF(LastOrderDate, CurrentOrderDate,DAY)",
              ""
            ],
            "formatString": "0",
            "lineageTag": "facf53db-d0da-44ec-8e52-76376374771c"
          }
        ],
        "partitions": [
          {
            "name": "Metrics-c403cccf-a5d1-4456-90fb-ae35fa114cfe",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_b510d20c-48b9-4708-a509-4813ef1bdd32",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "3812735c-66af-47d6-a85f-90ec1a85d638",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a44619f6-7d95-4b51-8bc5-da46bb62d27d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5ae1ff01-31c3-4cc8-ab48-cb3cd46c1def",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a922dbd9-d07e-468f-bdc9-9345f46ab9af",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5324c63d-5ab1-46cf-9f03-59349bf9cb24",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3c070428-66e6-4616-95b9-f40bf93e76fc",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ef5fbbb2-3bff-4b94-9365-1bf36c881497",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "6ba11d51-4861-45ca-9ded-f5b83289eec5",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "d31a3b97-343b-454c-bf4e-7d3418fddb46",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "fbe41a6e-9cec-4c17-8403-41fbc196ea3e",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "5efdf611-a405-46c9-95db-963a5d47ce64",
                "ordinal": 3
              }
            ],
            "lineageTag": "3c62cf86-7015-4d11-8e24-f7480b2f81c8"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "3a418f03-4ebb-4228-abc5-688588932ea7",
        "partitions": [
          {
            "name": "DateTableTemplate_b510d20c-48b9-4708-a509-4813ef1bdd32-fcd95203-eca3-4a42-91ca-c7724b6448d6",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_627eac13-7b3b-40f8-9f1d-87bc0cf399e7",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "a8f0ab3f-815e-447e-8708-e5e84c5592d3",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e0524885-1f09-4cc7-b9f8-1ed31e6a7aa2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ead658e2-1f34-4679-8db0-2d8690d1e5c8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "73765fd5-b890-4808-b5a9-20c1e7eb45fa",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "38ae8345-15d8-4f96-8eb8-7c40a3456d66",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0a5b783a-9944-4e26-99cb-5d4227e6e33a",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b0db0dea-a265-4d9a-a994-fd8900e0d000",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "97c38e68-e276-4820-aadf-7d4ff9e6093b",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "b82caf97-7698-4239-a926-a47b4f3bd4a1",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "a36cad7e-b934-4533-8a53-80083f150a76",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "0423e4d2-98dc-450f-bc2e-cba3dc144658",
                "ordinal": 3
              }
            ],
            "lineageTag": "2ef62fa7-fff2-4b4e-9846-d48472d47685"
          }
        ],
        "isHidden": true,
        "lineageTag": "d732b221-ad94-48b1-bdf1-754093e03714",
        "partitions": [
          {
            "name": "LocalDateTable_627eac13-7b3b-40f8-9f1d-87bc0cf399e7-1a52215d-0ed5-4e1f-bda6-6712d97dc5ca",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Orders'[Ship Date])), 1, 1), Date(Year(MAX('Orders'[Ship Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Calendar",
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"DataType\"]"
              }
            ],
            "dataType": "dateTime",
            "formatString": "yyyy-mm-dd",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "9f4d36a2-bc92-4b97-9a52-1f72adf1b96c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_0fc16a12-a964-4f8e-bdb1-c5fafab0fc14"
                },
                "isDefault": true,
                "relationship": "9f541fa5-9ff4-469a-995b-6aceaa9e08e3"
              }
            ]
          },
          {
            "name": "Week Day Nº",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "expression": "WEEKDAY('Calendar'[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "f94520c4-79d2-4676-a3fc-35669fdb3df4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Week Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('Calendar'[Date],\"ddd\")",
            "isDataTypeInferred": true,
            "lineageTag": "c31712c1-3ec0-4df5-8821-b804925d672f",
            "sortByColumn": "Week Day Nº",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "bdbfde54-8452-42d1-ad6e-35b7a61853d3",
        "partitions": [
          {
            "name": "Calendar-0c884134-c8ec-4c17-95e5-615bd2b51c3b",
            "mode": "import",
            "source": {
              "expression": "CALENDAR(DATE(YEAR(MIN(Orders[Order Date])),1,1),MAX(Orders[Order Date]))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_0fc16a12-a964-4f8e-bdb1-c5fafab0fc14",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "2c6f18d1-272f-48a4-a804-5904e22033e4",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "4e387a09-f535-44f7-be56-220b31f78a71",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b7b215fd-39da-4a0e-a730-116a2d1953a3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5384cd5c-54c3-4faf-943a-5121659d682a",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8a368c7e-f3dc-47c7-9998-b73b023f6e91",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "31326e8d-3c2d-4522-a8bf-df24d71450df",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "549dc2af-b7fb-4c46-aadc-406dbf988977",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "b4cf95d3-e887-47d9-8a22-a55e4c8f50d2",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "df1de21a-b886-4dca-b41a-11716884f054",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "6406accd-40c3-4dce-a84b-595566a3d9fc",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "acf8e2da-d966-424a-82d8-c884aa3c0acf",
                "ordinal": 3
              }
            ],
            "lineageTag": "8c81b859-1052-40d0-8260-b1a5603afd76"
          }
        ],
        "isHidden": true,
        "lineageTag": "e94949a2-b3a4-49fb-9765-2e6592a6a8e5",
        "partitions": [
          {
            "name": "LocalDateTable_0fc16a12-a964-4f8e-bdb1-c5fafab0fc14-3e60bf28-db33-457a-8f19-218af1b09f7b",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calendar'[Date])), 1, 1), Date(Year(MAX('Calendar'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}