{
  "compatibilityLevel": 1561,
  "model": {
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.102.845.0 (22.02)"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"PBIE\",\"DirectQuery to AS - Power Bi Service\",\"Medidas\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultMode": "directQuery",
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "DirectQuery to AS - Power Bi Service",
        "annotations": [
          {
            "name": "PBI_IncludeFutureArtifacts",
            "value": "False"
          },
          {
            "name": "PBI_RemovedChildren",
            "value": "[{\"remoteItemId\":{\"analysisServicesObject\":{\"sourceName\":null,\"sourceLineageTag\":\"b698f986-6657-429a-9a2a-7f4960fe8c9b\"}},\"objectType\":\"Table\"},{\"remoteItemId\":{\"analysisServicesObject\":{\"sourceName\":null,\"sourceLineageTag\":\"70ca7291-a1b0-4a8d-b30d-243688949858\"}},\"objectType\":\"Table\"},{\"remoteItemId\":{\"analysisServicesObject\":{\"sourceName\":null,\"sourceLineageTag\":\"f9802ff7-2584-4ddb-8e6b-5f399086f484\"}},\"objectType\":\"Table\"},{\"remoteItemId\":{\"analysisServicesObject\":{\"sourceName\":null,\"sourceLineageTag\":\"1b446727-9665-4ad5-94d5-6a6c837e840d\"}},\"objectType\":\"Table\"},{\"remoteItemId\":{\"analysisServicesObject\":{\"sourceName\":null,\"sourceLineageTag\":\"29680ec8-73ad-4a55-80cb-0af66d91b8e7\"}},\"objectType\":\"Table\"},{\"remoteItemId\":{\"analysisServicesObject\":{\"sourceName\":null,\"sourceLineageTag\":\"8a82a0a8-e676-4151-9185-c34fd1dfcd0a\"}},\"objectType\":\"Table\"},{\"remoteItemId\":{\"analysisServicesObject\":{\"sourceName\":null,\"sourceLineageTag\":\"08e0f96b-1045-48f6-997d-a4830eff5f1b\"}},\"objectType\":\"Table\"},{\"remoteItemId\":{\"analysisServicesObject\":{\"sourceName\":null,\"sourceLineageTag\":\"f99236b9-01ad-47ee-be73-fa14f0831a49\"}},\"objectType\":\"Table\"},{\"remoteItemId\":{\"analysisServicesObject\":{\"sourceName\":null,\"sourceLineageTag\":\"31586b82-9b3d-4adc-bf36-dfd87601ec45\"}},\"objectType\":\"Table\"},{\"remoteItemId\":{\"analysisServicesObject\":{\"sourceName\":null,\"sourceLineageTag\":\"ab831b9c-c61d-432f-8833-514e7b58af7b\"}},\"objectType\":\"Table\"},{\"remoteItemId\":{\"analysisServicesObject\":{\"sourceName\":null,\"sourceLineageTag\":\"15964ee9-5402-4e07-9c5a-225e400b7426\"}},\"objectType\":\"Table\"},{\"remoteItemId\":{\"analysisServicesObject\":{\"sourceName\":null,\"sourceLineageTag\":\"59717516-2d59-4527-8032-3c94ec42c56c\"}},\"objectType\":\"Table\"},{\"remoteItemId\":{\"analysisServicesObject\":{\"sourceName\":null,\"sourceLineageTag\":\"24a57171-e203-457f-b8b4-98247a725ee1\"}},\"objectType\":\"Table\"},{\"remoteItemId\":{\"analysisServicesObject\":{\"sourceName\":null,\"sourceLineageTag\":\"8c15925e-3510-4ff8-9174-30fb8208a006\"}},\"objectType\":\"Table\"}]"
          }
        ],
        "expression": [
          "let",
          "    Source = AnalysisServices.Database(\"powerbi://api.powerbi.com/v1.0/myorg/Rigor%20PBI%20Team\", \"Power Bi Service\"),",
          "    Cubes = Table.Combine(Source[Data]),",
          "    Cube = Cubes{[Id=\"\", Kind=\"Cube\"]}[Data]",
          "in",
          "    Cube"
        ],
        "kind": "m",
        "lineageTag": "9d886662-1f28-4711-b854-87c44545a26d"
      }
    ],
    "relationships": [
      {
        "name": "bc0e2e1a-8505-46f6-ab3a-1d5e7877c53a",
        "fromColumn": "Date",
        "fromTable": "ServiceActivity",
        "securityFilteringBehavior": "none",
        "toColumn": "Date",
        "toTable": "Calendar"
      }
    ],
    "sourceQueryCulture": "pt-PT",
    "tables": [
      {
        "name": "PBIE",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_ChangedProperties",
            "value": "[\"IsHidden\"]"
          }
        ],
        "columns": [
          {
            "name": "Cliente",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "f0f6cd4c-1663-4f55-8492-964226811036",
            "sourceColumn": "Cliente",
            "summarizeBy": "none"
          },
          {
            "name": "Report",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "f1b1dc3b-6e98-44aa-8289-886680bac7b1",
            "sourceColumn": "Report",
            "summarizeBy": "none"
          },
          {
            "name": "Nº Refreshes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"DataType\",\"IsHidden\"]"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1d9a9189-1b2f-41c5-9925-959de4527658",
            "sourceColumn": "Nº Refreshes",
            "summarizeBy": "sum"
          },
          {
            "name": "Dataset ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "a83224d2-3e61-47c7-8cef-9fc00b04e283",
            "sourceColumn": "Dataset ID",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "5e03f37c-ab62-4831-a878-a454ad5f635c",
        "partitions": [
          {
            "name": "PBIE-a0974877-897a-49a1-ba98-01d74e92476c",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(Web.Contents(\"https://gruposalvadorcaetano.sharepoint.com/sites/rigor/6825_DGAA/DGAA/03%20-%20Documenta%C3%A7%C3%A3o/39%20-%20Interno/02%20-%20Power%20BI/Power%20BI%20Portal/Portal%20Power%20BI%20Roles.xlsx\"), null, true),",
                "    #\"Portal Power BI_Sheet\" = Source{[Item=\"Portal Power BI\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Portal Power BI_Sheet\", [PromoteAllScalars=true]),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Promoted Headers\",{\"Cliente\", \"Report\", \"Nº Refreshes\", \"Dataset ID\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Other Columns\", each [Dataset ID] <> \" \")",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "ServiceActivity",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          },
          {
            "name": "PBI_ChangedProperties",
            "value": "[\"IsHidden\"]"
          }
        ],
        "columns": [
          {
            "name": "Source.Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "4b06c7ed-1f71-4c9e-9268-e529b50de2dc",
            "sourceColumn": "Source.Name",
            "sourceLineageTag": "3c2e356e-c86f-4c76-bc57-d93b20634393",
            "summarizeBy": "none"
          },
          {
            "name": "Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "f33a557d-f22d-4830-a3a0-4c9b14e363ed",
            "sourceColumn": "Id",
            "sourceLineageTag": "54d54024-d96a-4723-8fbd-dccc6c320e4a",
            "summarizeBy": "none"
          },
          {
            "name": "RecordType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "642a32de-a8ac-47ca-8589-9814ebb6966c",
            "sourceColumn": "RecordType",
            "sourceLineageTag": "0152c9df-276c-4367-bbc2-23268211ede8",
            "summarizeBy": "none"
          },
          {
            "name": "CreationTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "dateTime",
            "formatString": "General Number",
            "isHidden": true,
            "lineageTag": "0ffa84df-4552-4d56-994b-a3b907986ed1",
            "sourceColumn": "CreationTime",
            "sourceLineageTag": "28f22de9-3c06-4186-84b8-b9e287a117b7",
            "summarizeBy": "none"
          },
          {
            "name": "Operation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "56effd06-49aa-4e89-a445-333d27d2d606",
            "sourceColumn": "Operation",
            "sourceLineageTag": "39eac933-66a7-42f1-8e5b-33b14aa71e38",
            "summarizeBy": "none"
          },
          {
            "name": "OrganizationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "5fd5231b-4d06-41f9-96b3-d2f5a4e54f40",
            "sourceColumn": "OrganizationId",
            "sourceLineageTag": "1d2c9321-5b7c-429f-9fd3-42d27661e652",
            "summarizeBy": "none"
          },
          {
            "name": "UserType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "90b06bdc-26e8-4a58-9773-2a4a69178af1",
            "sourceColumn": "UserType",
            "sourceLineageTag": "5195d4e8-f5f9-46e5-b783-f49500095231",
            "summarizeBy": "none"
          },
          {
            "name": "UserKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "821cb74a-876c-4f7d-a35a-ba13f2b10534",
            "sourceColumn": "UserKey",
            "sourceLineageTag": "ee35acf1-9d11-4795-8991-791a24241002",
            "summarizeBy": "none"
          },
          {
            "name": "Workload",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "415cc75f-547f-4cce-8e51-a3b3c1f258ff",
            "sourceColumn": "Workload",
            "sourceLineageTag": "1dc11dc3-c86d-42db-8cfb-10699e08f63b",
            "summarizeBy": "none"
          },
          {
            "name": "UserId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "6f4b6fba-a762-4a31-8218-c8c31eb644c2",
            "sourceColumn": "UserId",
            "sourceLineageTag": "a2a62b74-28d5-47ba-af82-9a6f093ea663",
            "summarizeBy": "none"
          },
          {
            "name": "ClientIP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "8bd314b1-140b-4f86-ad21-41046ba964f6",
            "sourceColumn": "ClientIP",
            "sourceLineageTag": "e49da874-9570-4568-8b0b-e16877a0e0f8",
            "summarizeBy": "none"
          },
          {
            "name": "UserAgent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "0c86c9d5-8522-40b6-97b5-7bd2e1972e82",
            "sourceColumn": "UserAgent",
            "sourceLineageTag": "64ef353c-902e-4392-96af-4e0c91de9f26",
            "summarizeBy": "none"
          },
          {
            "name": "Activity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "856a2f8f-9ced-4a04-9cfc-02f893fab087",
            "sourceColumn": "Activity",
            "sourceLineageTag": "5bf331ec-329d-46ff-9669-2873764fa343",
            "summarizeBy": "none"
          },
          {
            "name": "ItemName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "04c983de-2edb-45e4-a55e-4c9bcec97637",
            "sourceColumn": "ItemName",
            "sourceLineageTag": "bd920b6f-1950-42d4-ac07-2dff44e6b027",
            "summarizeBy": "none"
          },
          {
            "name": "WorkSpaceName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "7e034dc2-36bb-4935-b8d9-20fc83579203",
            "sourceColumn": "WorkSpaceName",
            "sourceLineageTag": "44c8ea30-3509-4377-9422-0f12fca1d51f",
            "summarizeBy": "none"
          },
          {
            "name": "DatasetName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "b5f18c9b-b109-403c-9689-b5c484b34157",
            "sourceColumn": "DatasetName",
            "sourceLineageTag": "b7c14911-c0e2-48d2-9066-fe8db65b84b0",
            "summarizeBy": "none"
          },
          {
            "name": "ReportName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "48c43e85-febb-4cbc-8d4c-e62d69404d91",
            "sourceColumn": "ReportName",
            "sourceLineageTag": "dfb7a9a7-286d-484b-8dda-bb426af0cc1c",
            "summarizeBy": "none"
          },
          {
            "name": "WorkspaceId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "2ba90780-faed-436f-b72a-4b31c7a01f11",
            "sourceColumn": "WorkspaceId",
            "sourceLineageTag": "53ac8da3-d416-410f-b43b-82f6b87e371d",
            "summarizeBy": "none"
          },
          {
            "name": "ObjectId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "fac06daf-7c63-4cbd-a29e-a6a0041ca2f7",
            "sourceColumn": "ObjectId",
            "sourceLineageTag": "1a591ae6-f121-4426-9999-c8409767a968",
            "summarizeBy": "none"
          },
          {
            "name": "DatasetId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "b62e11d2-2125-4841-90c7-8ffc5cdc204b",
            "sourceColumn": "DatasetId",
            "sourceLineageTag": "9393b1db-71e8-48e2-9bae-5d95ede707d2",
            "summarizeBy": "none"
          },
          {
            "name": "ReportId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "b09df369-12d6-4f7b-9643-6986aed90d2e",
            "sourceColumn": "ReportId",
            "sourceLineageTag": "deb775ad-fedf-422e-bcb1-378dbd59b3ec",
            "summarizeBy": "none"
          },
          {
            "name": "IsSuccess",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "90307a64-23af-4c60-a8cc-e07a4c228c1f",
            "sourceColumn": "IsSuccess",
            "sourceLineageTag": "ceeba1f9-0250-42a5-8a56-44c4b482efdc",
            "summarizeBy": "none"
          },
          {
            "name": "ReportType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "d3c2dc99-24dd-48c9-8bfe-a9ecf9272301",
            "sourceColumn": "ReportType",
            "sourceLineageTag": "c62ce7ab-a4ca-43f3-b914-6d954833193c",
            "summarizeBy": "none"
          },
          {
            "name": "RequestId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9a652747-4595-4b68-9af9-0635f4af6ad6",
            "sourceColumn": "RequestId",
            "sourceLineageTag": "ece9c51b-cf26-4ed1-a7be-cc5a6d69e42e",
            "summarizeBy": "none"
          },
          {
            "name": "ActivityId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "ea374a32-8711-480e-a8b3-8d5c2eba657d",
            "sourceColumn": "ActivityId",
            "sourceLineageTag": "b0a9a158-d89a-43aa-b1b0-1b3a31d0ef04",
            "summarizeBy": "none"
          },
          {
            "name": "DistributionMethod",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "4bde38b0-ddfe-46e0-b51a-5e921f621559",
            "sourceColumn": "DistributionMethod",
            "sourceLineageTag": "a1183362-600d-4401-85cf-a3f26c605c34",
            "summarizeBy": "none"
          },
          {
            "name": "ConsumptionMethod",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "70dacc81-ebfc-4410-8afa-66f20556c67b",
            "sourceColumn": "ConsumptionMethod",
            "sourceLineageTag": "05946c60-7531-48ff-9151-7da93583e7b8",
            "summarizeBy": "none"
          },
          {
            "name": "DataConnectivityMode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "7db08cc4-f920-44dd-ac4f-cbfe00c6b026",
            "sourceColumn": "DataConnectivityMode",
            "sourceLineageTag": "59f429df-8d85-4b71-bdbf-f56e83889b5f",
            "summarizeBy": "none"
          },
          {
            "name": "LastRefreshTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9a45ce34-177b-4759-95a5-30c289e3416f",
            "sourceColumn": "LastRefreshTime",
            "sourceLineageTag": "c7636f09-bcfe-4d26-9dea-6a2c8a00bf2b",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "d098236e-ead0-43d1-8d78-a2adeeb87984",
            "sourceColumn": "Date",
            "sourceLineageTag": "d8cc713d-a92e-43a5-9137-79a2f8df63b9",
            "summarizeBy": "none"
          },
          {
            "name": "Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "dateTime",
            "formatString": "Long Time",
            "isHidden": true,
            "lineageTag": "98d4ca02-734e-406e-8f7c-eba87f56f679",
            "sourceColumn": "Time",
            "sourceLineageTag": "d8e84476-554e-41b8-829e-fb7601dd8261",
            "summarizeBy": "none"
          },
          {
            "name": "Hour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "942e6fe5-7851-4683-a92f-aaa8cd2032c9",
            "sourceColumn": "Hour",
            "sourceLineageTag": "0afe43a8-9adf-4de3-bda3-cde391bced54",
            "summarizeBy": "sum"
          },
          {
            "name": "Divice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "48d5160c-7e6b-4c79-90d7-233d648ca98a",
            "sourceColumn": "Divice",
            "sourceLineageTag": "b8b48aa1-f585-46f0-8ce3-59f5a5a0f16e",
            "summarizeBy": "none"
          },
          {
            "name": "ReportDeleted",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true,
            "lineageTag": "63959a9a-0f64-48b5-ad16-ed882b439c3c",
            "sourceColumn": "ReportDeleted",
            "sourceLineageTag": "886bc851-399c-4a2b-8819-347e64d6f177",
            "summarizeBy": "none"
          },
          {
            "name": "Person",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "6806dc2d-3940-4ccf-ad2f-9b18abd0fdfa",
            "sourceColumn": "Person",
            "sourceLineageTag": "10276d9b-5356-4e4b-b59a-8822d78190a0",
            "summarizeBy": "none"
          },
          {
            "name": "WorkspaceNameByDatasetID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "f31bfe4d-662d-4ecc-815d-30064ad2f16f",
            "sourceColumn": "WorkspaceNameByDatasetID",
            "sourceLineageTag": "22935f81-98d6-45aa-bb71-f0f5022bd0c9",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "21a4ff07-8664-436b-b84c-be1a31d0dabd",
        "partitions": [
          {
            "name": "ServiceActivity-bdc9d805-fd27-4143-80d4-7cefc5fa6ff5",
            "mode": "directQuery",
            "source": {
              "entityName": "ServiceActivity",
              "expressionSource": "DirectQuery to AS - Power Bi Service",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "e456259a-d1ea-4e83-8dc3-80a1ef6b60e3"
      },
      {
        "name": "Medidas",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "09cc4e3f-80ef-4b84-b556-404722ad18ed",
        "measures": [
          {
            "name": "Reports",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "expression": "CALCULATE(DISTINCTCOUNT(PBIE[Report]))",
            "formatString": "0",
            "lineageTag": "5559b2bd-4949-4499-af5b-9cb58d0542e2"
          },
          {
            "name": "Refreshes",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "expression": [
              "",
              "VAR Datasets = SUMMARIZE(PBIE, PBIE[Dataset ID], \"Refreshes\", MAX(PBIE[Nº Refreshes]))",
              "",
              "RETURN",
              "CALCULATE(",
              "    SUMX(",
              "        Datasets,",
              "        [Refreshes]",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "bcb8eb70-da08-4d79-8743-3541aab4662d"
          },
          {
            "name": "Datasets",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "expression": "DISTINCTCOUNT(PBIE[Dataset ID])",
            "formatString": "0",
            "lineageTag": "ee191974-0809-4e72-8c41-e7fcb50e94cd"
          },
          {
            "name": "Tokens",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "expression": [
              "",
              "VAR Datasets = VALUES(PBIE[Dataset ID])",
              "",
              "RETURN",
              "CALCULATE(",
              "    SUMX(",
              "        FILTER(",
              "            ServiceActivity,",
              "            ServiceActivity[Activity] = \"GenerateEmbedToken\" &&",
              "            ServiceActivity[DatasetId] IN (Datasets)",
              "            ),",
              "        1",
              "    )",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "f4c62b1e-a61f-46d5-87bd-a897f1a9a324"
          }
        ],
        "partitions": [
          {
            "name": "Medidas-f17f04ba-9738-4057-8495-1136115cccce",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Calendar",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "cc4ccb9cd6394dacb9b9fe17fdb74c75"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"2070\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "3bba9970-174b-4fa1-b0dc-6f1aaf4f234b",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "expression": "YEAR('Calendar'[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "6488682b-ad24-44f9-b891-f8fef3be81ba",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ],
            "dataType": "int64",
            "expression": "Month('Calendar'[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "ac0e6367-5c12-489f-9616-9e5a43dc703f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"SortByColumn\"]"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('Calendar'[Date], \"MMM\")",
            "isDataTypeInferred": true,
            "lineageTag": "8cfef7c7-47d0-4111-8831-70c1522aaffe",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "c56f0e36-8349-4f6c-b16a-6fd53ce16811",
        "partitions": [
          {
            "name": "Calendar-544fa41e-2bb7-43ed-82f2-bd3aef396328",
            "mode": "import",
            "source": {
              "expression": "CALENDAR(MIN(ServiceActivity[Date]), max(ServiceActivity[Date]))",
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}