{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"VIATURAS\",\"TOYOTA\",\"LEXUS\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.131.1203.0 (24.07)"
      },
      {
        "name": "BestPracticeAnalyzer_IgnoreRules",
        "value": "{\"RuleIDs\":[\"OBJECTS_WITH_NO_DESCRIPTION\"]}"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      }
    ],
    "culture": "pt-PT",
    "cultures": [
      {
        "name": "pt-PT",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "TOYOTA",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"TOYOTA\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "c9542b69-d809-47f7-ab3b-82848c455bf5"
      },
      {
        "name": "LEXUS",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"LEXUS\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "b8e998fc-fd37-42ea-850d-9d325e4a14b2"
      }
    ],
    "relationships": [
      {
        "name": "9e2b1cdb-0d35-ad79-d6c2-2d76d39042a2",
        "fromColumn": "DATA_ENCOMENDA_CONC",
        "fromTable": "VIATURAS",
        "toColumn": "Date",
        "toTable": "Calendar"
      }
    ],
    "sourceQueryCulture": "pt-PT",
    "tables": [
      {
        "name": "VIATURAS",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "VIA_MAR_DES",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "84305cfb-0224-41ad-b5b3-a8d57af74016",
            "sourceColumn": "VIA_MAR_DES",
            "summarizeBy": "none"
          },
          {
            "name": "VIA_GAM_DES",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2b822bfa-4e61-48dc-9884-a7a98b837e90",
            "sourceColumn": "VIA_GAM_DES",
            "summarizeBy": "none"
          },
          {
            "name": "VIA_MOD_DES",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3ff81f37-6885-484f-bba3-13e886ec35dc",
            "sourceColumn": "VIA_MOD_DES",
            "summarizeBy": "none"
          },
          {
            "name": "VIA_CAT_DES",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ec859c5c-f4c5-4a0a-bac4-ffc2145c0969",
            "sourceColumn": "VIA_CAT_DES",
            "summarizeBy": "none"
          },
          {
            "name": "VIN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fea1718b-2dc4-4c78-b22e-3caf2409c4ff",
            "sourceColumn": "VIN",
            "summarizeBy": "none"
          },
          {
            "name": "DATA_ENCOMENDA_CONC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "2a8d50e6-54e4-4e77-9a4b-9f0423e6731c",
            "sourceColumn": "DATA_ENCOMENDA_CONC",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9a733476-50e3-48dd-af7c-594bcbddf1fd",
        "partitions": [
          {
            "name": "VIATURAS",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origem = Sql.Database(\"scsbisrv1.sc.pt\", \"SCKPI_DM\"),",
                "    dbo_FACT_VENDA_VIATURAS = Origem{[Schema=\"dbo\",Item=\"FACT_VENDA_VIATURAS\"]}[Data],",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(dbo_FACT_VENDA_VIATURAS,{\"VIA_MAR_DES\", \"VIA_GAM_DES\", \"VIA_MOD_DES\", \"VIA_CAT_DES\", \"VIN\", \"DATA_ENCOMENDA_CONC\"}),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Outras Colunas Removidas\",{{\"DATA_ENCOMENDA_CONC\", type date}}),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Tipo Alterado\", each [VIA_MAR_DES] = TOYOTA)",
                "in",
                "    #\"Linhas Filtradas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Calendar",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "6aa77e8760bd4e74bdd3145e0a89b131"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mm/dd/yyyy",
            "isDataTypeInferred": true,
            "isKey": true,
            "isNameInferred": true,
            "lineageTag": "6190848a-ec41-4de6-9ab7-92927eae2609",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "dataCategory": "Time",
        "lineageTag": "aa561f33-cc31-4c53-a72b-5977f8d85188",
        "partitions": [
          {
            "name": "Calendar",
            "mode": "import",
            "source": {
              "expression": "CALENDAR(MIN(VIATURAS[DATA_ENCOMENDA_CONC]), MAX(VIATURAS[DATA_ENCOMENDA_CONC]))",
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}