/// DW: PBI.MEASURE_TABLE
table MEASURE_TABLE
	excludeFromModelRefresh
	lineageTag: 29f54252-5cb0-4e2e-9a0c-e4efcb059658

	measure 'DR PL CY (EUR)' = ```
			
			
			  VAR __Valor =
			 SUMX(
			     SUMMARIZECOLUMNS(
			         VIEW_NLR_FACT_BI_TRANS_PL[CURRENCY_RATE_KEY],
			         "BALANCE", SUM(VIEW_NLR_FACT_BI_TRANS_PL[VALUE])
			     ),
			     DIVIDE([BALANCE],
			     COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_BI_TRANS_PL[CURRENCY_RATE_KEY]), 1)
			     )
			 )
			
			 VAR __Unidades =
			 SUMX(
			     FILTER(
			         SUMMARIZECOLUMNS(
			             VIEW_NLR_FACT_BI_TRANS_PL[CURRENCY_RATE_KEY],
			             VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE],
			             "BALANCE", SUM(VIEW_NLR_FACT_BI_TRANS_PL[VALUE])
			         ),
			         VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE] = 15
			     ),
			     DIVIDE(
			         [BALANCE],
			         COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_BI_TRANS_PL[CURRENCY_RATE_KEY]), 1)
			     )
			 )
			
			 RETURN
			
			 IF(
			     SELECTEDVALUE(VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE]) = 15,
			     __Unidades,
			     __Valor - __Unidades
			 )
			```
		formatString: #,0
		isHidden
		displayFolder: FIN\DR PL\EUR\Real
		lineageTag: 7be8a209-54e5-48f8-84dd-848727fceaec

		changedProperty = IsHidden

	/// Calcula a diferença entre o DR Valor e o DR Valor Budget.
	measure 'DR PL Delta Bgt' =
			
			
			VAR __bgt = [DR PL Bgt]
			
			RETURN
			IF(
			    __bgt <> 0,
			    [DR PL CY] - __bgt
			)
		formatString: #,0
		displayFolder: FIN\DR PL\LC\Budget
		lineageTag: 3d84b9c8-47c4-45ed-82af-13b483e66975

		changedProperty = IsHidden

	/// Calcula o desvio percentual do N/N Budget em relação ao DR Valor Budget total para o código de nível 1 16.
	measure 'DR PL Delta Bgt %' = ```
			
			DIVIDE(
			    TRUNC([DR PL Delta Bgt]),
			    TRUNC(ABS([DR PL Bgt])),
				0
			)
			    
			
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: FIN\DR PL\LC\Budget
		lineageTag: b5c10e5c-dd3b-4ed0-be2e-7dcc2423fc3f

		changedProperty = IsHidden

	/// Calula o DR Valor para o mesmo período do ano anterior.
	measure 'DR PL LY' = ```
			
			
			-- Retorna os períodos fechados por plataforma
			VAR __ClosedPeriods = 
			    SUMMARIZECOLUMNS(
			        VIEW_GBL_DIM_CLIENTS[CLIENT_ID],
			        "CLOSED_PERIOD", MAX(VIEW_NLR_SETUP_CLOSED_PERIODS_USERS[NLR_CLOSEDDATE])
			    )
			-- Retorna os meses do calendário
			VAR __Calendar = 
			    SUMMARIZECOLUMNS(
			        VIEW_GBL_DIM_CALENDAR[SOMONTH]
			    )
			-- Cria uma tabela unindo as plataformas e os meses e em seguida retorna histórico dos meses fechados por plataforma
			VAR __FinalTable =
			    FILTER(
			        CROSSJOIN(
			            __ClosedPeriods,
			            __Calendar
			        ),
			        VIEW_GBL_DIM_CALENDAR[SOMONTH] <= [CLOSED_PERIOD]
			    )
			-- Armazena o valor dos períodos fechados
			VAR __ClosedPeriodValue =
			    SUMX(
			        __FinalTable,
			        CALCULATE(
			            [DR PL CY],
			            SAMEPERIODLASTYEAR(VIEW_GBL_DIM_CALENDAR[DATE])
			        )
			    )
			-- Armazena o valor total
			VAR __TotalPeriodValue =
			    CALCULATE(
			        [DR PL CY],
			        SAMEPERIODLASTYEAR(VIEW_GBL_DIM_CALENDAR[DATE])
			    )
			RETURN
			    
			IF(
			    SELECTEDVALUE(VIEW_NLR_DIM_CLOSED_PERIODS[CLOSED_PERIOD]) = 1,
			    __ClosedPeriodValue,
			    __TotalPeriodValue
			)
			```
		formatString: #,0
		displayFolder: FIN\DR PL\LC\Real
		lineageTag: f4573314-96e1-4f7d-bf6a-588ecdd4754e

		changedProperty = IsHidden

	/// Calcula a diferença entre o DR Valor atual e o DR Valor do ano anterior.
	measure 'DR PL Delta LY' =
			
			
			VAR __ly = [DR PL LY]
			
			RETURN
			IF(
			    __ly <> 0,
			    [DR PL CY] - __ly
			)
		formatString: #,0
		displayFolder: FIN\DR PL\LC\Real
		lineageTag: de4a2278-eabe-4f7b-9189-6c6ae477c457

		changedProperty = IsHidden

	/// Calcula o desvio percentual do N/N-1 em relação ao DR Valor Budget total para o código de nível 1 16.
	measure 'DR PL Delta LY %' =
			
			
			DIVIDE(
			    TRUNC([DR PL Delta LY]),
			    TRUNC(ABS([DR PL LY])),
				0
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: FIN\DR PL\LC\Real
		lineageTag: 5a18adce-c9bb-4981-882d-0e862db00c25

		changedProperty = IsHidden

	measure 'DR PL LY (EUR)' = ```
			
			
			-- Retorna os períodos fechados por plataforma
			VAR __ClosedPeriods = 
			    SUMMARIZECOLUMNS(
			        VIEW_GBL_DIM_CLIENTS[CLIENT_ID],
			        "CLOSED_PERIOD", MAX(VIEW_NLR_SETUP_CLOSED_PERIODS_USERS[NLR_CLOSEDDATE])
			    )
			-- Retorna os meses do calendário
			VAR __Calendar = 
			    SUMMARIZECOLUMNS(
			        VIEW_GBL_DIM_CALENDAR[SOMONTH]
			    )
			-- Cria uma tabela unindo as plataformas e os meses e em seguida retorna histórico dos meses fechados por plataforma
			VAR __FinalTable =
			    FILTER(
			        CROSSJOIN(
			            __ClosedPeriods,
			            __Calendar
			        ),
			        VIEW_GBL_DIM_CALENDAR[SOMONTH] <= [CLOSED_PERIOD]
			    )
			-- Armazena o valor dos períodos fechados
			VAR __ClosedPeriodValue =
			    SUMX(
			        __FinalTable,
			        CALCULATE(
			            [DR PL CY (EUR)],
			            SAMEPERIODLASTYEAR(VIEW_GBL_DIM_CALENDAR[DATE])
			        )
			    )
			-- Armazena o valor total
			VAR __TotalPeriodValue =
			    CALCULATE(
			        [DR PL CY (EUR)],
			        SAMEPERIODLASTYEAR(VIEW_GBL_DIM_CALENDAR[DATE])
			    )
			RETURN
			    
			IF(
			    SELECTEDVALUE(VIEW_NLR_DIM_CLOSED_PERIODS[CLOSED_PERIOD]) = 1,
			    __ClosedPeriodValue,
			    __TotalPeriodValue
			)        
			```
		formatString: #,0
		isHidden
		displayFolder: FIN\DR PL\EUR\Real
		lineageTag: 22666449-cc7e-415f-99fc-409bd561aa97

		changedProperty = IsHidden

	measure 'DR PL Bgt (EUR)' = ```
			
			
			  VAR __Valor =
			 SUMX(
			     FILTER(
			         SUMMARIZECOLUMNS(
			             VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[CURRENCY_RATE_KEY],
			             VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE_TYPE_CODE],
			             "BALANCE", SUM(VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE])
			         ),
			         VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE_TYPE_CODE] = 3
			     ),
			     DIVIDE([BALANCE],
			     COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[CURRENCY_RATE_KEY]), 1)
			     )
			 )
			
			 VAR __Unidades =
			 SUMX(
			     FILTER(FILTER(
			         SUMMARIZECOLUMNS(
			             VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[CURRENCY_RATE_KEY],
			             VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE_TYPE_CODE],
			             VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE],
			             "BALANCE", SUM(VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE])
			         ),
			         VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE_TYPE_CODE] = 3),
			         VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE] = 15
			     ),
			     DIVIDE([BALANCE],
			     COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[CURRENCY_RATE_KEY]), 1)
			     )
			 )
			 RETURN
			
			 IF(
			     SELECTEDVALUE(VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE]) = 15,
			     __Unidades,
			     __Valor - __Unidades
			 )
			```
		formatString: #,0
		isHidden
		displayFolder: FIN\DR PL\EUR\Budget
		lineageTag: 30e1c740-a4bb-47fe-8143-60afc3d0d4c8

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DR PL Delta Bgt (EUR)' =
			
			
			VAR __bgt = [DR PL Bgt (EUR)]
			
			RETURN
			IF(
			    __bgt <> 0,
			    [DR PL CY (EUR)] - __bgt
			)
		formatString: #,0
		isHidden
		displayFolder: FIN\DR PL\EUR\Budget
		lineageTag: 1d2756b4-9a3c-4fe1-8a91-b0f3cbdbf83c

		changedProperty = IsHidden

	measure 'DR PL Delta LY (EUR)' =
			
			
			VAR __ly = [DR PL LY (EUR)]
			
			RETURN
			IF(
			    __ly <> 0,
			    [DR PL CY (EUR)] - __ly
			)
		formatString: #,0
		isHidden
		displayFolder: FIN\DR PL\EUR\Real
		lineageTag: 8a3b45de-50ad-4ada-924b-f1589600f8a0

		changedProperty = IsHidden

	measure 'DR PL Delta Bgt (EUR) %' =
			
			
			DIVIDE(
			    TRUNC([DR PL Delta Bgt (EUR)]),
			    TRUNC(ABS([DR PL Bgt (EUR)])),
			    0
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: FIN\DR PL\EUR\Budget
		lineageTag: cbc6a9e1-6460-41b1-8890-dc0ec4a09f80

		changedProperty = IsHidden

	measure 'DR PL Delta LY (EUR) %' =
			
			
			DIVIDE(
			    TRUNC([DR PL Delta LY (EUR)]),
			    TRUNC(ABS([DR PL LY (EUR)])),
				0
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: FIN\DR PL\EUR\Real
		lineageTag: bb3704e9-688e-4b2f-bd8f-d411eada60a5

		changedProperty = IsHidden

	measure 'Visual Title' =
			
			
			SWITCH(
			    SELECTEDVALUE(VIEW_GBL_DIM_USER_CULTURE[USER_CULTURE]),
			    "pt-PT", SELECTEDVALUE(PBI_TABLE_TITLES[pt-PT]),
			    "en-US", SELECTEDVALUE(PBI_TABLE_TITLES[en-US]),
			    "es-ES", SELECTEDVALUE(PBI_TABLE_TITLES[es-ES]),
			    "fr-FR", SELECTEDVALUE(PBI_TABLE_TITLES[fr-FR]),
			    SELECTEDVALUE(PBI_TABLE_TITLES[en-US])
			)
		formatString: #,0
		isHidden
		displayFolder: _UI\Titles
		lineageTag: f0309be0-a988-45de-bcd9-ff4df1570ed9

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DR PL Bgt' = ```
			
			VAR __Unidades =
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE]),
			        VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE] = 15,
			        VIEW_GBL_DIM_VALUE_TYPES_ALL[VALUE_TYPE_CODE] = 3
			    )
			RETURN
			 
			IF(
			    SELECTEDVALUE(VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE]) = 15,
			    __Unidades,
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE]),
			        VIEW_GBL_DIM_VALUE_TYPES_ALL[VALUE_TYPE_CODE] = 3
			    )
			    -
			    __Unidades
			)
			```
		formatString: #,0
		displayFolder: FIN\DR PL\LC\Budget
		lineageTag: 40181499-2913-4954-9d76-5aa959a9999c

		changedProperty = IsHidden

	measure 'DR PL CY' = ```
			
			VAR __Unidades =
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[VALUE]),
			        VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE] = 15
			    )
			RETURN
			 
			IF(
			    SELECTEDVALUE(VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE]) = 15,
			    __Unidades,
			    SUM(VIEW_NLR_FACT_BI_TRANS_PL[VALUE]) - __Unidades
			)
			
			```
		formatString: #,0
		displayFolder: FIN\DR PL\LC\Real
		lineageTag: bc133c3e-fdf5-47ec-be26-591de25a7227

		changedProperty = IsHidden

	measure 'DR PL CY %' = ```
			
			
			VAR __Valor = [DR PL CY]
			 
			VAR __ValorVendas =
			CALCULATE(
			    [DR PL CY],
			    VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE] = 16,
			    ALL(VIEW_NLR_DIM_PL),
			    ALL(VIEW_NLR_DIM_ACTIVITIES)
			)
			VAR __ValorVendasWActivity =
			CALCULATE(
			    [DR PL CY],
			    ALL(VIEW_NLR_DIM_PL),
			    VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE] = 16
			)
			 
			RETURN
			
			SWITCH(
			        TRUE(),
			        SELECTEDVALUE(VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE]) = 16, DIVIDE(__Valor, __ValorVendas),
			        SELECTEDVALUE(VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE]) <> 15, DIVIDE(__Valor, __ValorVendasWActivity)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: FIN\DR PL\LC\Real
		lineageTag: 968eab2e-a288-4f88-8c51-8119b7100bd9

		changedProperty = IsHidden

	measure 'DR PL CY (EUR) %' = ```
			
			
			VAR __Valor = [DR PL CY (EUR)]
			 
			VAR __ValorVendas =
			CALCULATE(
			    [DR PL CY (EUR)],
			    VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE] = 16,
			    ALL(VIEW_NLR_DIM_PL),
			    ALL(VIEW_NLR_DIM_ACTIVITIES)
			)
			VAR __ValorVendasWActivity =
			CALCULATE(
			    [DR PL CY (EUR)],
			    ALL(VIEW_NLR_DIM_PL),
			    VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE] = 16
			)
			 
			RETURN
			
			SWITCH(
			        TRUE(),
			        SELECTEDVALUE(VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE]) = 16, DIVIDE(__Valor, __ValorVendas),
			        SELECTEDVALUE(VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE]) <> 15, DIVIDE(__Valor, __ValorVendasWActivity)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: FIN\DR PL\EUR\Real
		lineageTag: cad90b07-22d4-4d49-bf83-08663c3add38

		changedProperty = IsHidden

	measure 'DR PL Bgt %' = ```
			
			VAR __Valor = [DR PL Bgt]
			 
			VAR __ValorVendas =
			CALCULATE(
			    [DR PL Bgt],
			    VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE] = 16,
			    ALL(VIEW_NLR_DIM_PL),
			    ALL(VIEW_NLR_DIM_ACTIVITIES)
			)
			VAR __ValorVendasWActivity =
			CALCULATE(
			    [DR PL Bgt],
			    ALL(VIEW_NLR_DIM_PL),
			    VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE] = 16
			)
			 
			RETURN
			
			SWITCH(
			        TRUE(),
			        SELECTEDVALUE(VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE]) = 16, DIVIDE(__Valor, __ValorVendas),
			        SELECTEDVALUE(VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE]) <> 15, DIVIDE(__Valor, __ValorVendasWActivity)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: FIN\DR PL\LC\Budget
		lineageTag: af43fd58-29cb-43f9-bd5e-733803f554c5

		changedProperty = IsHidden

	measure 'DR PL LY %' = ```
			
			
			VAR __Valor = [DR PL LY]
			 
			VAR __ValorVendas =
			CALCULATE(
			    [DR PL LY],
			    VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE] = 16,
			    ALL(VIEW_NLR_DIM_PL),
			    ALL(VIEW_NLR_DIM_ACTIVITIES)
			)
			VAR __ValorVendasWActivity =
			CALCULATE(
			    [DR PL LY],
			    ALL(VIEW_NLR_DIM_PL),
			    VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE] = 16
			)
			 
			RETURN
			
			SWITCH(
			        TRUE(),
			        SELECTEDVALUE(VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE]) = 16, DIVIDE(__Valor, __ValorVendas),
			        SELECTEDVALUE(VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE]) <> 15, DIVIDE(__Valor, __ValorVendasWActivity)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: FIN\DR PL\LC\Real
		lineageTag: f4d9586a-8765-434d-b7b7-ace3b7db38f5

		changedProperty = IsHidden

	measure 'DR PL Bgt (EUR) %' = ```
			
			
			VAR __Valor = [DR PL Bgt (EUR)]
			 
			VAR __ValorVendas =
			CALCULATE(
			    [DR PL Bgt (EUR)],
			    VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE] = 16,
			    ALL(VIEW_NLR_DIM_PL),
			    ALL(VIEW_NLR_DIM_ACTIVITIES)
			)
			VAR __ValorVendasWActivity =
			CALCULATE(
			    [DR PL Bgt (EUR)],
			    ALL(VIEW_NLR_DIM_PL),
			    VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE] = 16
			)
			 
			RETURN
			
			SWITCH(
			        TRUE(),
			        SELECTEDVALUE(VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE]) = 16, DIVIDE(__Valor, __ValorVendas),
			        SELECTEDVALUE(VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE]) <> 15, DIVIDE(__Valor, __ValorVendasWActivity)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: FIN\DR PL\EUR\Budget
		lineageTag: 66adab5d-bd7a-4868-89c6-9e7c9175cb40

		changedProperty = IsHidden

	measure 'DR PL LY (EUR) %' = ```
			
			
			VAR __Valor = [DR PL LY (EUR)]
			 
			VAR __ValorVendas =
			CALCULATE(
			    [DR PL LY (EUR)],
			    VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE] = 16,
			    ALL(VIEW_NLR_DIM_PL),
			    ALL(VIEW_NLR_DIM_ACTIVITIES)
			)
			VAR __ValorVendasWActivity =
			CALCULATE(
			    [DR PL LY (EUR)],
			    ALL(VIEW_NLR_DIM_PL),
			    VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE] = 16
			)
			 
			RETURN
			
			SWITCH(
			        TRUE(),
			        SELECTEDVALUE(VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE]) = 16, DIVIDE(__Valor, __ValorVendas),
			        SELECTEDVALUE(VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE]) <> 15, DIVIDE(__Valor, __ValorVendasWActivity)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: FIN\DR PL\EUR\Real
		lineageTag: 77062155-1570-48c3-a7b3-f2809bbd3b8e

		changedProperty = IsHidden

	measure 'DR PL Bgt Adm' = ```
			
			VAR __Unidades =
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE]),
			        VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE] = 15,
			        VIEW_GBL_DIM_VALUE_TYPES_ALL[VALUE_TYPE_CODE] = 4
			    )
			RETURN
			 
			IF(
			    SELECTEDVALUE(VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE]) = 15,
			    __Unidades,
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE]),
			        VIEW_GBL_DIM_VALUE_TYPES_ALL[VALUE_TYPE_CODE] = 4
			    )
			    -
			    __Unidades
			)
			```
		formatString: #,0
		displayFolder: FIN\DR PL\LC\Budget
		lineageTag: 066faf00-a2f0-44da-8a26-4cad719052d8

		changedProperty = IsHidden

	measure 'DR PL Bgt Adm %' = ```
			
			VAR __Valor = [DR PL Bgt Adm]
			 
			VAR __ValorVendas =
			CALCULATE(
			    [DR PL Bgt Adm],
			    VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE] = 16,
			    ALL(VIEW_NLR_DIM_PL),
			    ALL(VIEW_NLR_DIM_ACTIVITIES)
			)
			VAR __ValorVendasWActivity =
			CALCULATE(
			    [DR PL Bgt Adm],
			    ALL(VIEW_NLR_DIM_PL),
			    VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE] = 16
			)
			 
			RETURN
			
			SWITCH(
			        TRUE(),
			        SELECTEDVALUE(VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE]) = 16, DIVIDE(__Valor, __ValorVendas),
			        SELECTEDVALUE(VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE]) <> 15, DIVIDE(__Valor, __ValorVendasWActivity)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: FIN\DR PL\LC\Budget
		lineageTag: 60c1584e-227d-4cc0-abf4-a33362d888b1

		changedProperty = IsHidden

	measure 'DR PL Delta Bgt Adm' =
			
			
			VAR __bgt = [DR PL Bgt Adm]
			
			RETURN
			IF(
			    __bgt <> 0,
			    [DR PL CY] - __bgt
			)
		formatString: #,0
		displayFolder: FIN\DR PL\LC\Budget
		lineageTag: 045322b5-2dba-4668-861f-117fe225ad3d

		changedProperty = IsHidden

	measure 'DR PL Delta Bgt Adm %' =
			
			
			DIVIDE(
			    TRUNC([DR PL Delta Bgt Adm]),
			    TRUNC(ABS([DR PL Bgt Adm])),
				0
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: FIN\DR PL\LC\Budget
		lineageTag: 2e14cab4-736d-4ea1-afd1-d3a25c2d36c9

		changedProperty = IsHidden

	measure 'DR PL Bgt Adm (EUR)' =
			
			
			VAR __Valor =
			SUMX(
			    FILTER(
			        SUMMARIZECOLUMNS(
			            VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[CURRENCY_RATE_KEY],
			            VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE_TYPE_CODE],
			            "BALANCE", SUM(VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE])
			        ),
			        VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE_TYPE_CODE] = 4
			    ),
			    DIVIDE([BALANCE],
			    COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[CURRENCY_RATE_KEY]), 1)
			    )
			)
			
			VAR __Unidades =
			SUMX(
			    FILTER(FILTER(
			        SUMMARIZECOLUMNS(
			            VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[CURRENCY_RATE_KEY],
			            VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE_TYPE_CODE],
			            VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE],
			            "BALANCE", SUM(VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE])
			        ),
			        VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE_TYPE_CODE] = 4),
			        VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE] = 15
			    ),
			    DIVIDE([BALANCE],
			    COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[CURRENCY_RATE_KEY]), 1)
			    )
			)
			RETURN
			
			IF(
			    SELECTEDVALUE(VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE]) = 15,
			    __Unidades,
			    __Valor - __Unidades
			)
		formatString: #,0
		isHidden
		displayFolder: FIN\DR PL\EUR\Budget
		lineageTag: 06e0ea71-b0b3-4d9e-8d2e-366ced3e8465

		changedProperty = IsHidden

	measure 'DR PL Delta Bgt Adm (EUR)' =
			
			
			VAR __bgt = [DR PL Bgt Adm (EUR)]
			
			RETURN
			IF(
			    __bgt <> 0,
			    [DR PL CY (EUR)] - __bgt
			)
		formatString: #,0
		isHidden
		displayFolder: FIN\DR PL\EUR\Budget
		lineageTag: 99ae6c93-1a0f-443e-b619-ec2b75d9e5ec

		changedProperty = IsHidden

	measure 'DR PL Delta Bgt Adm (EUR) %' =
			
			
			DIVIDE(
			    TRUNC([DR PL Delta Bgt Adm (EUR)]),
			    TRUNC(ABS([DR PL Bgt Adm (EUR)])),
				0
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: FIN\DR PL\EUR\Budget
		lineageTag: 32ba9113-ced9-41a9-bb53-e072ebe54e96

		changedProperty = IsHidden

	measure 'DR PL Bgt Adm (EUR) %' = ```
			
			
			VAR __Valor = [DR PL Bgt Adm (EUR)]
			 
			VAR __ValorVendas =
			CALCULATE(
			    [DR PL Bgt Adm (EUR)],
			    VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE] = 16,
			    ALL(VIEW_NLR_DIM_PL),
			    ALL(VIEW_NLR_DIM_ACTIVITIES)
			)
			VAR __ValorVendasWActivity =
			CALCULATE(
			    [DR PL Bgt Adm (EUR)],
			    ALL(VIEW_NLR_DIM_PL),
			    VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE] = 16
			)
			 
			RETURN
			
			SWITCH(
			        TRUE(),
			        SELECTEDVALUE(VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE]) = 16, DIVIDE(__Valor, __ValorVendas),
			        SELECTEDVALUE(VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE]) <> 15, DIVIDE(__Valor, __ValorVendasWActivity)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: FIN\DR PL\EUR\Budget
		lineageTag: c3eb4924-72b9-4bd4-85cb-fb18ba86b1e3

		changedProperty = IsHidden

	measure Cabeçalhos =
			
			CALCULATE(
			    SUM(VIEW_NLR_FACT_BI_TRANS_PL[VALUE]) + SUM(VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE]),
			    ALL(CALCGROUP_CURRENCY),
			    ALL(CALCGROUP_ACCUMULATED_PERIOD),
			    REMOVEFILTERS(CALCGROUP_CURRENCY)
			)
		isHidden
		displayFolder: _UI\Cabeçalhos
		lineageTag: c4aaed7e-dea1-4fae-8a3f-b05cbde862d6

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Indicators DR PL' = ```
			
			
			SWITCH(
			    SELECTEDVALUE('PARAMETER_DRPL_INDICADORES'[Id]),
			    1, [DR PL CY],
			    2, [DR PL CY %],
			    3, [DR PL Bgt],
			    4, [DR PL Bgt %],
			    5, [DR PL Delta Bgt],
			    6, [DR PL Delta Bgt %],    
			    7, [DR PL Bgt Adm],
			    8, [DR PL Bgt Adm %],
			    9, [DR PL Delta Bgt Adm],
			    10, [DR PL Delta Bgt Adm %],
			    11, [DR PL LY],
			    12, [DR PL LY %],
			    13, [DR PL Delta LY],
			    14, [DR PL Delta LY %]
			)
			
			```
		displayFolder: FIN\DR PL\LC\Support Measures
		lineageTag: d200a109-4a26-45c3-ae14-1728172b98d6

		formatStringDefinition =
				SWITCH(
				    SELECTEDVALUE('PARAMETER_DRPL_INDICADORES'[Id]),
				    1, "#,###,###,###,###",
				    2, "#,##0..0%",
				    3, "#,###,###,###,###",
				    4, "#,##0..0%",
				    5, "#,###,###,###,###",
				    6, "#,##0..0%",
				    7, "#,###,###,###,###",
				    8, "#,##0..0%",
				    9, "#,###,###,###,###",
				    10, "#,##0..0%",
				    11, "#,###,###,###,###",
				    12, "#,##0..0%",
				    13, "#,###,###,###,###",
				    14, "#,##0..0%"
				)

		changedProperty = IsHidden

	measure 'Indicators DR PL (EUR)' = ```
			
			
			SWITCH(
			    SELECTEDVALUE('PARAMETER_DRPL_INDICADORES'[Id]),
			    1, [DR PL CY (EUR)],
			    2, [DR PL CY (EUR) %],
			    3, [DR PL Bgt (EUR)],
			    4, [DR PL Bgt (EUR) %],
			    5, [DR PL Delta Bgt (EUR)],
			    6, [DR PL Delta Bgt (EUR) %],    
			    7, [DR PL Bgt Adm (EUR)],
			    8, [DR PL Bgt Adm (EUR) %],
			    9, [DR PL Delta Bgt Adm (EUR)],
			    10, [DR PL Delta Bgt Adm (EUR) %],
			    11, [DR PL LY (EUR)],
			    12, [DR PL LY (EUR) %],
			    13, [DR PL Delta LY (EUR)],
			    14, [DR PL Delta LY (EUR) %]
			)
			```
		isHidden
		displayFolder: FIN\DR PL\EUR\Support Measures
		lineageTag: 129be14c-6467-4ad0-ae57-badccb93ad08

		formatStringDefinition =
				SWITCH(
				    SELECTEDVALUE('PARAMETER_DRPL_INDICADORES'[Id]),
				    1, "#,###,###,###,###",
				    2, "#,##0..0%",
				    3, "#,###,###,###,###",
				    4, "#,##0..0%",
				    5, "#,###,###,###,###",
				    6, "#,##0..0%",
				    7, "#,###,###,###,###",
				    8, "#,##0..0%",
				    9, "#,###,###,###,###",
				    10, "#,##0..0%",
				    11, "#,###,###,###,###",
				    12, "#,##0..0%",
				    13, "#,###,###,###,###",
				    14, "#,##0..0%"
				)

		changedProperty = IsHidden

	measure simbol_daily_update =
			
			VAR _update = MIN(VIEW_GBL_DTBI_LAST_UPDATE[DAILY_UPDATED])
			
			RETURN
			IF(
			    _update,
			    "✔️",
			    "❗"
			)
		isHidden
		displayFolder: _UI\Format
		lineageTag: 753b7fde-d78b-4956-a5fb-1ea1a27f18de

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Title - Clear Filters' =
			
			
			SWITCH(
			    LEFT(SELECTEDVALUE(VIEW_GBL_DIM_USER_CULTURE[USER_CULTURE]), 2),
			    "pt", "Limpar Filtros",
			    "en", "Clear Filters",
			    "es", "Borrar Filtros",
			    "fr", "Effacer les Filtres",
			    "Clear Filters"
			)
		isHidden
		displayFolder: _UI\Titles
		lineageTag: c2ba323f-7f38-4496-9009-82138bbbfc43

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Title - Close Filters' =
			
			
			SWITCH(
			    LEFT(SELECTEDVALUE(VIEW_GBL_DIM_USER_CULTURE[USER_CULTURE]), 2),
			    "pt", "Fechar Filtros",
			    "en", "Close Filters",
			    "es", "Cerrar Filtros",
			    "fr", "Fermer les Filtres",
			    "Close Filters"
			)
		isHidden
		displayFolder: _UI\Titles
		lineageTag: fcc30af3-012c-411c-9554-31a00cc9e4c2

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Title - Filter' =
			
			
			SWITCH(
			    LEFT(SELECTEDVALUE(VIEW_GBL_DIM_USER_CULTURE[USER_CULTURE]), 2),
			    "pt", "Mais Filtros",
			    "en", "More Filters",
			    "es", "Más Filtros",
			    "fr", "Plus de Filtres",
			    "More Filters"
			)
		isHidden
		displayFolder: _UI\Titles
		lineageTag: 59550c9e-b237-4ca1-b840-51ddbeaccde3

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure simbol_daily_update_tt =
			
			
			VAR _update = SELECTEDVALUE(VIEW_GBL_DTBI_LAST_UPDATE[DAILY_UPDATED])
			
			RETURN
			
			IF(
			    _update,
			    "🟢",
			    "🟠"
			)
		isHidden
		displayFolder: _UI\Format
		lineageTag: 30f549ad-2264-48d6-bd9b-6a40f4661aaa

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Title - Page' =
			
			
			SWITCH(
			    LEFT(SELECTEDVALUE(VIEW_GBL_DIM_USER_CULTURE[USER_CULTURE]), 2),
			    "pt", "Página",
			    "en", "Page",
			    "es", "Página",
			    "fr", "Page",
			    "Page"
			)
		isHidden
		displayFolder: _UI\Titles
		lineageTag: fd44387f-31d5-4db6-9cda-b398798aff70

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DR IFRS CY' =
			
			SUM(VIEW_NLR_FACT_BI_TRANS_PL[IFRS_VALUE])
		formatString: #,0
		displayFolder: FIN\DR IFRS\LC\Real
		lineageTag: 21d85cec-f057-4f75-b597-6331c5d5ac8b

		changedProperty = IsHidden

	measure 'DR IFRS Bgt' = ```
			
			CALCULATE(
			    SUM(VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[IFRS_VALUE]),
			    VIEW_GBL_DIM_VALUE_TYPES_ALL[VALUE_TYPE_CODE] = 3
			)
			
			```
		formatString: #,0
		displayFolder: FIN\DR IFRS\LC\Budget
		lineageTag: a4cde384-1290-48b0-a29a-5cce2817d849

		changedProperty = IsHidden

	measure 'DR IFRS Bgt Adm' =
			
			CALCULATE(
			    SUM(VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[IFRS_VALUE]),
			    VIEW_GBL_DIM_VALUE_TYPES_ALL[VALUE_TYPE_CODE] = 4
			)
		formatString: #,0
		displayFolder: FIN\DR IFRS\LC\Budget
		lineageTag: d3fd8689-621e-4165-a352-ce90e5fbe38e

		changedProperty = IsHidden

	measure 'DR IFRS Delta Bgt Adm' =
			
			
			VAR __bgt = [DR IFRS Bgt Adm]
			
			RETURN
			IF(
			    __bgt <> 0,
			    [DR IFRS CY] - __bgt
			)
		formatString: #,0
		displayFolder: FIN\DR IFRS\LC\Budget
		lineageTag: edfa50da-23f8-41a6-9512-7df5e868f5ee

		changedProperty = IsHidden

	measure 'DR IFRS Delta Bgt' =
			
			VAR __bgt = [DR IFRS Bgt]
			RETURN
			IF(
			    __bgt <> 0,
			    [DR IFRS CY] - __bgt
			)
		formatString: #,0
		displayFolder: FIN\DR IFRS\LC\Budget
		lineageTag: df2ce7a2-b321-432b-9e11-b5676fccdf55

		changedProperty = IsHidden

	measure 'DR IFRS Delta LY' =
			
			
			VAR __ly = [DR IFRS LY]
			
			RETURN
			IF(
			    __ly <> 0,
			    [DR IFRS CY] - __ly
			)
		formatString: #,0
		displayFolder: FIN\DR IFRS\LC\Real
		lineageTag: e7f803c7-c45e-4870-bf86-367778c105e1

		changedProperty = IsHidden

	measure 'DR IFRS LY' =
			
			CALCULATE(
			    [DR IFRS CY],
			    SAMEPERIODLASTYEAR(VIEW_GBL_DIM_CALENDAR[DATE])
			)
		formatString: #,0
		displayFolder: FIN\DR IFRS\LC\Real
		lineageTag: 2d157f3c-04c7-4d32-94ab-b1a698a0ff46

		changedProperty = IsHidden

	measure 'Title - Reset Table' =
			
			
			SWITCH(
			    LEFT(SELECTEDVALUE(VIEW_GBL_DIM_USER_CULTURE[USER_CULTURE]), 2),
			    "pt", "Repor Tabela",
			    "en", "Reset Table",
			    "es", "Restablecer Tabla",
			    "fr", "Réinitialiser le Tableau",
			    "Reset Table"
			)
		isHidden
		displayFolder: _UI\Titles
		lineageTag: 6f942aed-ac5d-49cf-b236-a18e44f53567

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Indicators IFRS' = ```
			
			
			SWITCH(
			    SELECTEDVALUE(PARAMETER_DRIFRS_INDICADORES[Id]),
			    1, [DR IFRS CY],
			    2, [DR IFRS CY %],
			    3, [DR IFRS Bgt],
			    4, [DR IFRS Bgt %],
			    5, [DR IFRS Delta Bgt],
			    6, [DR IFRS Delta Bgt %],    
			    7, [DR IFRS Bgt Adm],
			    8, [DR IFRS Bgt Adm %],
			    9, [DR IFRS Delta Bgt Adm],
			    10, [DR IFRS Delta Bgt Adm %],
			    11, [DR IFRS LY],
			    12, [DR IFRS LY %],
			    13, [DR IFRS Delta LY],
			    14, [DR IFRS Delta LY %]
			)
			```
		displayFolder: FIN\DR IFRS\LC\Support Measures
		lineageTag: 56ac688d-f195-4f87-9aaf-7907ad726ed5

		formatStringDefinition =
				SWITCH(
				    SELECTEDVALUE(PARAMETER_DRIFRS_INDICADORES[Id]),
				    1, "#,###,###,###,###",
				    2, "#,##0.0%",
				    3, "#,###,###,###,###",
				    4, "#,##0.0%",
				    5, "#,###,###,###,###",
				    6, "#,##0.0%",
				    7, "#,###,###,###,###",
				    8, "#,##0.0%",
				    9, "#,###,###,###,###",
				    10, "#,##0.0%",
				    11, "#,###,###,###,###",
				    12, "#,##0.0%",
				    13, "#,###,###,###,###",
				    14, "#,##0.0%"
				)

		changedProperty = IsHidden

	measure 'DR IFRS CY (EUR)' =
			
			
			SUMX(
			    SUMMARIZECOLUMNS(
			        VIEW_NLR_FACT_BI_TRANS_PL[CURRENCY_RATE_KEY],
			        "TOTAL", SUM(VIEW_NLR_FACT_BI_TRANS_PL[IFRS_VALUE])
			    ),
			    DIVIDE([TOTAL],
			    COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_BI_TRANS_PL[CURRENCY_RATE_KEY]), 1)
			    )
			)
		formatString: #,0
		isHidden
		displayFolder: FIN\DR IFRS\EUR\Real
		lineageTag: f4b397fb-a5b1-4962-97c1-bfe687e8a7b6

		changedProperty = IsHidden

	measure 'DR IFRS Bgt Adm (EUR)' =
			
			
			SUMX(
			    FILTER(
			        SUMMARIZECOLUMNS(
			            VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[CURRENCY_RATE_KEY],
			            VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE_TYPE_CODE],
			            "TOTAL", SUM(VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[IFRS_VALUE])
			        ),
			        VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE_TYPE_CODE] = 4
			    ),
			    DIVIDE(
			        [TOTAL],
			        COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[CURRENCY_RATE_KEY]), 1)
			    )
			)
		formatString: #,0
		isHidden
		displayFolder: FIN\DR IFRS\EUR\Budget
		lineageTag: f73e7f23-9938-4769-bdec-712db3108ed9

		changedProperty = IsHidden

	measure 'DR IFRS Bgt (EUR)' =
			
			
			SUMX(
			    FILTER(
			        SUMMARIZECOLUMNS(
			            VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[CURRENCY_RATE_KEY],
			            VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE_TYPE_CODE],
			            "TOTAL", SUM(VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[IFRS_VALUE])
			        ),
			        VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE_TYPE_CODE] = 3
			    ),
			    DIVIDE(
			        [TOTAL],
			        COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[CURRENCY_RATE_KEY]), 1)
			    )
			)
		formatString: #,0
		isHidden
		displayFolder: FIN\DR IFRS\EUR\Budget
		lineageTag: 76dbb42a-fd3a-4efe-b86a-132c06c3f37e

		changedProperty = IsHidden

	measure 'DR IFRS Delta Bgt (EUR) %' =
			
			
			DIVIDE(
			    TRUNC([DR IFRS Delta Bgt (EUR)]),
			    TRUNC(ABS([DR IFRS Bgt (EUR)])),
			    0
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: FIN\DR IFRS\EUR\Budget
		lineageTag: c68ebfd1-7ce1-452b-9eec-0d3919f49dc4

		changedProperty = IsHidden

	measure 'DR IFRS Delta Bgt (EUR)' =
			
			
			VAR __bgt = [DR IFRS Bgt (EUR)]
			RETURN
			IF(
			    __bgt <> 0,
			    [DR IFRS CY (EUR)] - __bgt
			)
		formatString: #,0
		isHidden
		displayFolder: FIN\DR IFRS\EUR\Budget
		lineageTag: e38e9d92-a0e8-49bf-96e6-3418add7945a

		changedProperty = IsHidden

	measure 'DR IFRS Delta Bgt Adm (EUR)' =
			
			
			VAR __bgt = [DR IFRS Bgt Adm (EUR)]
			RETURN
			IF(
			    __bgt <> 0,
			    [DR IFRS CY (EUR)] - __bgt
			)
		formatString: #,0
		isHidden
		displayFolder: FIN\DR IFRS\EUR\Budget
		lineageTag: 825c75a8-6c12-4421-b3db-4df7245aa1fa

		changedProperty = IsHidden

	measure 'DR IFRS Delta Bgt Adm (EUR) %' =
			
			
			DIVIDE(
			    TRUNC([DR IFRS Delta Bgt Adm (EUR)]),
			    TRUNC(ABS([DR IFRS Bgt Adm (EUR)])),
			    0
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: FIN\DR IFRS\EUR\Budget
		lineageTag: 9646d4cd-8eaf-469b-866b-dfc9d2bfad46

		changedProperty = IsHidden

	measure 'DR IFRS LY (EUR)' =
			
			CALCULATE(
			    [DR IFRS CY (EUR)],
			    SAMEPERIODLASTYEAR(VIEW_GBL_DIM_CALENDAR[DATE])
			)
		formatString: #,0
		isHidden
		displayFolder: FIN\DR IFRS\EUR\Real
		lineageTag: 10994af2-3e65-4770-a549-f84ca303e15f

		changedProperty = IsHidden

	measure 'DR IFRS Delta LY (EUR)' =
			
			
			VAR __ly = [DR IFRS LY (EUR)]
			RETURN
			IF(
			    __ly <> 0,
			    [DR IFRS CY (EUR)] - __ly
			)
		formatString: #,0
		isHidden
		displayFolder: FIN\DR IFRS\EUR\Real
		lineageTag: 47ff5cbc-7adf-4e68-8726-be1cb187c330

		changedProperty = IsHidden

	measure 'DR IFRS Delta LY (EUR) %' =
			
			
			DIVIDE(
			    TRUNC([DR IFRS Delta LY (EUR)]),
			    TRUNC(ABS([DR IFRS LY (EUR)]))
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: FIN\DR IFRS\EUR\Real
		lineageTag: ff373102-892e-4389-977b-081c073a5c4f

		changedProperty = IsHidden

	measure 'Indicators IFRS (EUR)' = ```
			
			
			SWITCH(
			    SELECTEDVALUE(PARAMETER_DRIFRS_INDICADORES[Id]),
			    1, [DR IFRS CY (EUR)],
			    2, [DR IFRS CY (EUR) %],
			    3, [DR IFRS Bgt (EUR)],
			    4, [DR IFRS Bgt (EUR) %],
			    5, [DR IFRS Delta Bgt (EUR)],
			    6, [DR IFRS Delta Bgt (EUR) %],    
			    7, [DR IFRS Bgt Adm (EUR)],
			    8, [DR IFRS Bgt Adm (EUR) %],
			    9, [DR IFRS Delta Bgt Adm (EUR)],
			    10, [DR IFRS Delta Bgt Adm (EUR) %],
			    11, [DR IFRS LY (EUR)],
			    12, [DR IFRS LY (EUR) %],
			    13, [DR IFRS Delta LY (EUR)],
			    14, [DR IFRS Delta LY (EUR) %]
			)
			```
		isHidden
		displayFolder: FIN\DR IFRS\EUR\Support Measures
		lineageTag: 92328390-d2a1-4ac7-ac34-a11f89634c8c

		formatStringDefinition =
				SWITCH(
				    SELECTEDVALUE(PARAMETER_DRIFRS_INDICADORES[Id]),
				    1, "#,###,###,###,###",
				    2, "#,##0.0%",
				    3, "#,###,###,###,###",
				    4, "#,##0.0%",
				    5, "#,###,###,###,###",
				    6, "#,##0.0%",
				    7, "#,###,###,###,###",
				    8, "#,##0.0%",
				    9, "#,###,###,###,###",
				    10, "#,##0.0%",
				    11, "#,###,###,###,###",
				    12, "#,##0.0%",
				    13, "#,###,###,###,###",
				    14, "#,##0.0%"
				)

		changedProperty = IsHidden

	measure 'DR IFRS Delta Bgt %' =
			
			
			DIVIDE(
			    [DR IFRS Delta Bgt],
			    ABS([DR IFRS Bgt])
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: FIN\DR IFRS\LC\Budget
		lineageTag: f5dc45a0-0c2e-4b2f-9b61-514913692115

		changedProperty = IsHidden

	measure 'DR IFRS Delta Bgt Adm %' =
			
			
			DIVIDE(
			    [DR IFRS Delta Bgt Adm],
			    ABS([DR IFRS Bgt Adm])
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: FIN\DR IFRS\LC\Budget
		lineageTag: 7e069e6c-ce9f-404e-a27c-139a45d93e2c

		changedProperty = IsHidden

	measure 'DR IFRS Delta LY %' =
			
			
			DIVIDE(
			    [DR IFRS Delta LY],
			    ABS([DR IFRS LY])
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: FIN\DR IFRS\LC\Real
		lineageTag: 2eb0958f-a4eb-47eb-b3eb-aefd1148f320

		changedProperty = IsHidden

	measure 'DR IFRS CY %' = ```
			
			VAR __vendas =
			CALCULATE(
			    [DR IFRS CY],
			    VIEW_NLR_DIM_PL_IFRS[PL_IFRS_LEVEL_2_CODE] = 11,
			    ALL(VIEW_NLR_DIM_PL_IFRS)
			)
			
			RETURN
			IF(
			    SELECTEDVALUE(VIEW_NLR_DIM_PL_IFRS[PL_IFRS_LEVEL_2_CODE]) <> 11, 
			    DIVIDE([DR IFRS CY], __vendas)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: FIN\DR IFRS\LC\Real
		lineageTag: 9c97d277-a14f-40fe-b901-f11d0fc0a68d

		changedProperty = IsHidden

	measure 'DR IFRS Bgt %' = ```
			
			VAR __vendas =
			CALCULATE(
			    [DR IFRS Bgt],
			    VIEW_NLR_DIM_PL_IFRS[PL_IFRS_LEVEL_2_CODE] = 11,
			    ALL(VIEW_NLR_DIM_PL_IFRS)
			)
			
			RETURN
			IF(
			    SELECTEDVALUE(VIEW_NLR_DIM_PL_IFRS[PL_IFRS_LEVEL_2_CODE]) <> 11, 
			    DIVIDE([DR IFRS Bgt], __vendas)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: FIN\DR IFRS\LC\Budget
		lineageTag: 5c091233-511e-4551-9220-23ecf17f3b52

		changedProperty = IsHidden

	measure 'DR IFRS Bgt Adm %' = ```
			
			VAR __vendas =
			CALCULATE(
			    [DR IFRS Bgt Adm],
			    VIEW_NLR_DIM_PL_IFRS[PL_IFRS_LEVEL_2_CODE] = 11,
			    ALL(VIEW_NLR_DIM_PL_IFRS)
			)
			
			RETURN
			IF(
			    SELECTEDVALUE(VIEW_NLR_DIM_PL_IFRS[PL_IFRS_LEVEL_2_CODE]) <> 11, 
			    DIVIDE([DR IFRS Bgt Adm], __vendas)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: FIN\DR IFRS\LC\Budget
		lineageTag: d0b5d464-fb32-435f-9469-43eabd5ddb8e

		changedProperty = IsHidden

	measure 'DR IFRS LY %' = ```
			
			VAR __vendas =
			CALCULATE(
			    [DR IFRS LY],
			    VIEW_NLR_DIM_PL_IFRS[PL_IFRS_LEVEL_2_CODE] = 11,
			    ALL(VIEW_NLR_DIM_PL_IFRS)
			)
			
			RETURN
			IF(
			    SELECTEDVALUE(VIEW_NLR_DIM_PL_IFRS[PL_IFRS_LEVEL_2_CODE]) <> 11, 
			    DIVIDE([DR IFRS LY], __vendas)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: FIN\DR IFRS\LC\Real
		lineageTag: b2837e06-a634-42be-b7d9-8eee167a230c

		changedProperty = IsHidden

	measure 'DR IFRS CY (EUR) %' = ```
			
			VAR __vendas =
			CALCULATE(
			    [DR IFRS CY (EUR)],
			    VIEW_NLR_DIM_PL_IFRS[PL_IFRS_LEVEL_2_CODE] = 11,
			    ALL(VIEW_NLR_DIM_PL_IFRS)
			)
			
			RETURN
			IF(
			    SELECTEDVALUE(VIEW_NLR_DIM_PL_IFRS[PL_IFRS_LEVEL_2_CODE]) <> 11, 
			    DIVIDE([DR IFRS CY (EUR)], __vendas)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: FIN\DR IFRS\EUR\Real
		lineageTag: 5842e70f-12dd-48a3-a7d3-8f1c6fdebeaa

		changedProperty = IsHidden

	measure 'DR IFRS Bgt (EUR) %' = ```
			
			VAR __vendas =
			CALCULATE(
			    [DR IFRS Bgt (EUR)],
			    VIEW_NLR_DIM_PL_IFRS[PL_IFRS_LEVEL_2_CODE] = 11,
			    ALL(VIEW_NLR_DIM_PL_IFRS)
			)
			
			RETURN
			IF(
			    SELECTEDVALUE(VIEW_NLR_DIM_PL_IFRS[PL_IFRS_LEVEL_2_CODE]) <> 11, 
			    DIVIDE([DR IFRS Bgt (EUR)], __vendas)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: FIN\DR IFRS\EUR\Budget
		lineageTag: bfbea27a-9f85-4cbf-9b9e-9e0dba0387af

		changedProperty = IsHidden

	measure 'DR IFRS Bgt Adm (EUR) %' = ```
			
			VAR __vendas =
			CALCULATE(
			    [DR IFRS Bgt Adm (EUR)],
			    VIEW_NLR_DIM_PL_IFRS[PL_IFRS_LEVEL_2_CODE] = 11,
			    ALL(VIEW_NLR_DIM_PL_IFRS)
			)
			
			RETURN
			IF(
			    SELECTEDVALUE(VIEW_NLR_DIM_PL_IFRS[PL_IFRS_LEVEL_2_CODE]) <> 11, 
			    DIVIDE([DR IFRS Bgt Adm (EUR)], __vendas)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: FIN\DR IFRS\EUR\Budget
		lineageTag: 3faaa3d2-a71b-49b5-be7b-b96b86f66855

		changedProperty = IsHidden

	measure 'DR IFRS LY (EUR) %' = ```
			
			VAR __vendas =
			CALCULATE(
			    [DR IFRS LY (EUR)],
			    VIEW_NLR_DIM_PL_IFRS[PL_IFRS_LEVEL_2_CODE] = 11,
			    ALL(VIEW_NLR_DIM_PL_IFRS)
			)
			
			RETURN
			IF(
			    SELECTEDVALUE(VIEW_NLR_DIM_PL_IFRS[PL_IFRS_LEVEL_2_CODE]) <> 11, 
			    DIVIDE([DR IFRS LY (EUR)], __vendas)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: FIN\DR IFRS\EUR\Real
		lineageTag: 476a087a-e46a-428d-aa4f-7084f6ec4259

		changedProperty = IsHidden

	measure 'BL IFRS CY' = ```
			
			
			 VAR __Scope =
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[PT_BL_IFRS_LEVEL_1_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[EN_BL_IFRS_LEVEL_1_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[ES_BL_IFRS_LEVEL_1_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[FR_BL_IFRS_LEVEL_1_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[PT_BL_IFRS_LEVEL_2_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[EN_BL_IFRS_LEVEL_2_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[ES_BL_IFRS_LEVEL_2_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[FR_BL_IFRS_LEVEL_2_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[PT_BL_IFRS_LEVEL_3_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[EN_BL_IFRS_LEVEL_3_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[ES_BL_IFRS_LEVEL_3_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[FR_BL_IFRS_LEVEL_3_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[PT_BL_IFRS_LEVEL_4_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[EN_BL_IFRS_LEVEL_4_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[ES_BL_IFRS_LEVEL_4_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[FR_BL_IFRS_LEVEL_4_DESC])
			  
			 RETURN
			
			 SWITCH(
			     TRUE(),
			     -- Retorna o valor do mês/ano contextualizado para a linha de total (Diferença dos Ativos - (CP + Passivo))
			     NOT(__Scope),
			
			     CALCULATE(
			         [BL IFRS Origin],
			         ALL(VIEW_NLR_DIM_BL_IFRS),
			         VIEW_NLR_DIM_BL_IFRS[BL_IFRS_LEVEL_1_CODE] = 1
			     )
			     -
			     CALCULATE(
			         [BL IFRS Origin],
			         ALL(VIEW_NLR_DIM_BL_IFRS),
			         VIEW_NLR_DIM_BL_IFRS[BL_IFRS_LEVEL_1_CODE] = 4
			     ),
			     [BL IFRS Origin]
			  )
			```
		formatString: #,0
		displayFolder: FIN\BL IFRS\LC\Real
		lineageTag: d64892ea-d6e0-4440-9568-c6caa588acc4

		changedProperty = IsHidden

	measure 'BL IFRS CY (EUR)' =
			
			
			VAR __Scope =
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[PT_BL_IFRS_LEVEL_1_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[EN_BL_IFRS_LEVEL_1_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[ES_BL_IFRS_LEVEL_1_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[FR_BL_IFRS_LEVEL_1_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[PT_BL_IFRS_LEVEL_2_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[EN_BL_IFRS_LEVEL_2_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[ES_BL_IFRS_LEVEL_2_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[FR_BL_IFRS_LEVEL_2_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[PT_BL_IFRS_LEVEL_3_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[EN_BL_IFRS_LEVEL_3_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[ES_BL_IFRS_LEVEL_3_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[FR_BL_IFRS_LEVEL_3_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[PT_BL_IFRS_LEVEL_4_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[EN_BL_IFRS_LEVEL_4_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[ES_BL_IFRS_LEVEL_4_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[FR_BL_IFRS_LEVEL_4_DESC])
			
			RETURN
			
			SWITCH(
			    TRUE(),
			    -- Retorna o valor do mês/ano contextualizado para a linha de total (Diferença dos Ativos - (CP + Passivo))
			    NOT(__Scope),
			        CALCULATE(
			            [BL IFRS Origin (EUR)],
			            ALL(VIEW_NLR_DIM_BL_IFRS),
			            VIEW_NLR_DIM_BL_IFRS[BL_IFRS_LEVEL_1_CODE] =1
			        )
			        -
			        CALCULATE(
			            [BL IFRS Origin (EUR)],
			            ALL(VIEW_NLR_DIM_BL_IFRS),
			            VIEW_NLR_DIM_BL_IFRS[BL_IFRS_LEVEL_1_CODE] = 4
			        ),
			    [BL IFRS Origin (EUR)]
			)
		formatString: #,0
		isHidden
		displayFolder: FIN\BL IFRS\EUR\Real
		lineageTag: 2342fe52-253d-4ce7-9f0e-8013dc855630

		changedProperty = IsHidden

	measure 'BL IFRS CY %' =
			
			
			VAR __Ativos =
			CALCULATE(
			    [BL IFRS Origin],
			    VIEW_NLR_DIM_BL_IFRS[BL_IFRS_LEVEL_1_CODE] = 1,
			    ALL(VIEW_NLR_DIM_BL_IFRS)
			)
			RETURN
			
			DIVIDE(
			    TRUNC([BL IFRS CY]),
			    TRUNC(__Ativos)
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: FIN\BL IFRS\LC\Real
		lineageTag: 01106e0f-a2dd-44f4-bea1-8bccb66f6cf7

		changedProperty = IsHidden

	measure 'BL IFRS CY (EUR) %' = ```
			
			  
			VAR __Ativos =
			CALCULATE(
			    [BL IFRS Origin (EUR)],
			    VIEW_NLR_DIM_BL_IFRS[BL_IFRS_LEVEL_1_CODE] = 1,
			    ALL(VIEW_NLR_DIM_BL_IFRS)
			)
			RETURN
			
			DIVIDE(
			    TRUNC([BL IFRS CY (EUR)]),
			    TRUNC(__Ativos)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: FIN\BL IFRS\EUR\Real
		lineageTag: 1d6a9baa-cbe4-47b8-8366-c98f629c7b59

		changedProperty = IsHidden

	measure 'BL IFRS LY' = ```
			
			 
			VAR __ClosedDate =
			    CALCULATE(
			        MAX(VIEW_NLR_FACT_BI_TRANS_PL[ANALYSIS_DATE]),
			        VIEW_NLR_FACT_BI_TRANS_PL[CLOSED_PERIOD] = 1
			        )
			VAR __ClosedMonth = MONTH(__ClosedDate)
			 
			VAR __ClosedPeriodValue =
			    CALCULATE(
			        [BL IFRS CY],
			        SAMEPERIODLASTYEAR(VIEW_GBL_DIM_CALENDAR[DATE]),
			        VIEW_GBL_DIM_CALENDAR[MONTH] <= __ClosedMonth
			    )
			VAR __TotalPeriodValue =
			    CALCULATE(
			        [BL IFRS CY],
			        SAMEPERIODLASTYEAR(VIEW_GBL_DIM_CALENDAR[DATE])
			    )
			RETURN
			 
			IF(
			    SELECTEDVALUE(VIEW_NLR_DIM_CLOSED_PERIODS[CLOSED_PERIOD]) = 1,
			    __ClosedPeriodValue,
			    __TotalPeriodValue
			)
			
			```
		formatString: #,0
		displayFolder: FIN\BL IFRS\LC\Real
		lineageTag: 27773065-8acc-4819-9af8-872ec9f318ed

		changedProperty = IsHidden

	measure 'BL IFRS LY (EUR)' = ```
			
			 
			VAR __ClosedDate =
			    CALCULATE(
			        MAX(VIEW_NLR_FACT_BI_TRANS_PL[ANALYSIS_DATE]),
			        VIEW_NLR_FACT_BI_TRANS_PL[CLOSED_PERIOD] = 1
			        )
			VAR __ClosedMonth = MONTH(__ClosedDate)
			 
			VAR __ClosedPeriodValue =
			    CALCULATE(
			        [BL IFRS CY (EUR)],
			        SAMEPERIODLASTYEAR(VIEW_GBL_DIM_CALENDAR[DATE]),
			        VIEW_GBL_DIM_CALENDAR[MONTH] <= __ClosedMonth
			    )
			VAR __TotalPeriodValue =
			    CALCULATE(
			        [BL IFRS CY (EUR)],
			        SAMEPERIODLASTYEAR(VIEW_GBL_DIM_CALENDAR[DATE])
			    )
			RETURN
			 
			IF(
			    SELECTEDVALUE(VIEW_NLR_DIM_CLOSED_PERIODS[CLOSED_PERIOD]) = 1,
			    __ClosedPeriodValue,
			    __TotalPeriodValue
			)
			```
		formatString: #,0
		isHidden
		displayFolder: FIN\BL IFRS\EUR\Real
		lineageTag: 39f60b38-f13a-49dc-9ae6-f6ab7ee05d1b

		changedProperty = IsHidden

	measure 'BL IFRS LY %' =
			
			CALCULATE(
			    [BL IFRS CY %],
			    SAMEPERIODLASTYEAR(VIEW_GBL_DIM_CALENDAR[DATE])
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: FIN\BL IFRS\LC\Real
		lineageTag: 8e7ff8d6-4fe3-40e9-bb5b-a9587ce773c2

		changedProperty = IsHidden

	measure 'BL IFRS LY (EUR) %' = ```
			
			 
			CALCULATE(
			    [BL IFRS CY (EUR) %],
			    SAMEPERIODLASTYEAR(VIEW_GBL_DIM_CALENDAR[DATE])
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: FIN\BL IFRS\EUR\Real
		lineageTag: f1d93da0-792b-479f-acf0-136470dc3b69

		changedProperty = IsHidden

	measure 'BL IFRS Delta LY' =
			
			
			VAR __ly = [BL IFRS LY]
			
			RETURN
			IF(
			    __ly <> 0,
			    [BL IFRS CY] - __ly
			)
		formatString: #,0
		displayFolder: FIN\BL IFRS\LC\Real
		lineageTag: 8aa3c376-0292-45ba-ad59-3cc8445b67e3

		changedProperty = IsHidden

	measure 'BL IFRS Delta LY (EUR)' =
			
			
			VAR __ly = [BL IFRS LY (EUR)]
			
			RETURN
			IF(
			    __ly <> 0,
			    [BL IFRS CY (EUR)] - __ly
			)
		formatString: #,0
		isHidden
		displayFolder: FIN\BL IFRS\EUR\Real
		lineageTag: 583abfb3-9f0b-4b0f-9c26-9255cc73fad4

		changedProperty = IsHidden

	measure 'BL IFRS Delta LY %' =
			
			
			DIVIDE(
			    TRUNC([BL IFRS Delta LY]),
			    TRUNC(ABS([BL IFRS LY])),
			    0
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: FIN\BL IFRS\LC\Real
		lineageTag: fd3df46a-a098-41f7-8624-5ab24a4392cc

		changedProperty = IsHidden

	measure 'BL IFRS Delta LY (EUR) %' =
			
			
			DIVIDE(
			    TRUNC([BL IFRS Delta LY (EUR)]),
			    TRUNC(ABS([BL IFRS LY (EUR)]))
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: FIN\BL IFRS\EUR\Real
		lineageTag: 9499a507-36aa-4b01-ad56-6858dab29c89

		changedProperty = IsHidden

	measure 'Indicators BL IFRS' = ```
			
			
			SWITCH(
			    SELECTEDVALUE(PARAMETER_BL_IFRS_INDICADORES[Id]),
			    1, [BL IFRS CY],
			    2, [BL IFRS CY %],
			    3, [BL IFRS Bgt],
			    4, [BL IFRS Bgt %],
			    5, [BL IFRS Delta Bgt],
			    6, [BL IFRS Delta Bgt %],    
			    7, [BL IFRS Bgt Adm],
			    8, [BL IFRS Bgt Adm %],
			    9, [BL IFRS Delta Bgt Adm],
			    10, [BL IFRS Delta Bgt Adm %],
			    11, [BL IFRS LY],
			    12, [BL IFRS LY %],
			    13, [BL IFRS Delta LY],
			    14, [BL IFRS Delta LY %]
			)
			```
		displayFolder: FIN\BL IFRS\LC\Support Measures
		lineageTag: a9d414fa-c7f7-4ecb-8622-9933eea08ccd

		formatStringDefinition =
				SWITCH(
				    SELECTEDVALUE(PARAMETER_BL_IFRS_INDICADORES[Id]),
				    1, "#,###,###,###,###",
				    2, "#,##0.0%",
				    3, "#,###,###,###,###",
				    4, "#,##0.0%",
				    5, "#,###,###,###,###",
				    6, "#,##0.0%",
				    7, "#,###,###,###,###",
				    8, "#,##0.0%",
				    9, "#,###,###,###,###",
				    10, "#,##0.0%",
				    11, "#,###,###,###,###",
				    12, "#,##0.0%",
				    13, "#,###,###,###,###",
				    14, "#,##0.0%"
				)

		changedProperty = IsHidden

	measure 'BL IFRS Bgt' =
			
			
			VAR __ValueType = 3 -- Tipo de orçamento
			
			VAR __Scope =
			ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[PT_BL_IFRS_LEVEL_1_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[EN_BL_IFRS_LEVEL_1_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[ES_BL_IFRS_LEVEL_1_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[FR_BL_IFRS_LEVEL_1_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[PT_BL_IFRS_LEVEL_2_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[EN_BL_IFRS_LEVEL_2_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[ES_BL_IFRS_LEVEL_2_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[FR_BL_IFRS_LEVEL_2_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[PT_BL_IFRS_LEVEL_3_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[EN_BL_IFRS_LEVEL_3_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[ES_BL_IFRS_LEVEL_3_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[FR_BL_IFRS_LEVEL_3_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[PT_BL_IFRS_LEVEL_4_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[EN_BL_IFRS_LEVEL_4_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[ES_BL_IFRS_LEVEL_4_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[FR_BL_IFRS_LEVEL_4_DESC])
			
			RETURN
			
			SWITCH(
			    TRUE(),
			
			    -- Retorna o valor do orçamento do mês/ano contextualizado para a linha de total (Diferença dos Ativos - (CP + Passivo))
			    NOT(__Scope),
			        CALCULATE(
			            [BL IFRS Bgt Origin],
			            VIEW_GBL_DIM_VALUE_TYPES_ALL[VALUE_TYPE_CODE] = __ValueType,
			            ALL(VIEW_NLR_DIM_BL_IFRS),
			            VIEW_NLR_DIM_BL_IFRS[BL_IFRS_LEVEL_1_CODE] = 1
			        ) -
			        CALCULATE(
			            [BL IFRS Bgt Origin],
			            VIEW_GBL_DIM_VALUE_TYPES_ALL[VALUE_TYPE_CODE] = __ValueType,
			            ALL(VIEW_NLR_DIM_BL_IFRS),
			            VIEW_NLR_DIM_BL_IFRS[BL_IFRS_LEVEL_1_CODE] = 4
			        ),
			
			    CALCULATE(
			        [BL IFRS Bgt Origin],
			        VIEW_GBL_DIM_VALUE_TYPES_ALL[VALUE_TYPE_CODE] = __ValueType
			    )
			)
		formatString: #,0
		displayFolder: FIN\BL IFRS\LC\Budget
		lineageTag: ca0adfcf-a385-492f-900c-9e8f5ea7d379

		changedProperty = IsHidden

	measure 'BL IFRS Bgt (EUR)' = ```
			
			
			 VAR __ValueType = 3 -- Tipo de orçamento
			
			 VAR __Scope =
			  ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[PT_BL_IFRS_LEVEL_1_DESC]) ||
			  ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[EN_BL_IFRS_LEVEL_1_DESC]) ||
			  ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[ES_BL_IFRS_LEVEL_1_DESC]) ||
			  ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[FR_BL_IFRS_LEVEL_1_DESC]) ||
			  ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[PT_BL_IFRS_LEVEL_2_DESC]) ||
			  ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[EN_BL_IFRS_LEVEL_2_DESC]) ||
			  ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[ES_BL_IFRS_LEVEL_2_DESC]) ||
			  ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[FR_BL_IFRS_LEVEL_2_DESC]) ||
			  ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[PT_BL_IFRS_LEVEL_3_DESC]) ||
			  ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[EN_BL_IFRS_LEVEL_3_DESC]) ||
			  ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[ES_BL_IFRS_LEVEL_3_DESC]) ||
			  ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[FR_BL_IFRS_LEVEL_3_DESC]) ||
			  ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[PT_BL_IFRS_LEVEL_4_DESC]) ||
			  ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[EN_BL_IFRS_LEVEL_4_DESC]) ||
			  ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[ES_BL_IFRS_LEVEL_4_DESC]) ||
			  ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[FR_BL_IFRS_LEVEL_4_DESC])
			
			 RETURN
			
			SWITCH(
			    TRUE(),
			    -- Retorna o valor do mês/ano contextualizado para a linha de total (Diferença dos Ativos - (CP + Passivo))
			    NOT(__Scope),
			        CALCULATE(
			            [BL IFRS Bgt Origin (EUR)],
			            VIEW_GBL_DIM_VALUE_TYPES_ALL[VALUE_TYPE_CODE] = __ValueType,
			            ALL(VIEW_NLR_DIM_BL_IFRS),
			            VIEW_NLR_DIM_BL_IFRS[BL_IFRS_LEVEL_1_CODE] = 1
			        )
			        -
			        CALCULATE(
			            [BL IFRS Bgt Origin (EUR)],
			            VIEW_GBL_DIM_VALUE_TYPES_ALL[VALUE_TYPE_CODE] = __ValueType,
			            ALL(VIEW_NLR_DIM_BL_IFRS),
			            VIEW_NLR_DIM_BL_IFRS[BL_IFRS_LEVEL_1_CODE] = 4
			        ),
			    CALCULATE(    
			        [BL IFRS Bgt Origin (EUR)],
			        VIEW_GBL_DIM_VALUE_TYPES_ALL[VALUE_TYPE_CODE] = __ValueType
			    )
			)
			```
		formatString: #,0
		isHidden
		displayFolder: FIN\BL IFRS\EUR\Budget
		lineageTag: f6d5528d-6ba4-414d-b090-57d41025ca4b

		changedProperty = IsHidden

	measure 'BL IFRS Bgt %' =
			
			
			VAR __Ativos =
			CALCULATE(
			    [BL IFRS Bgt Origin],
			    VIEW_NLR_DIM_BL_IFRS[BL_IFRS_LEVEL_1_CODE] = 1,
			    VIEW_GBL_DIM_VALUE_TYPES_ALL[VALUE_TYPE_CODE] = 3,
			    ALL(VIEW_NLR_DIM_BL_IFRS)
			)
			RETURN
			
			DIVIDE(
			    TRUNC([BL IFRS Bgt]),
			    TRUNC(__Ativos)
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: FIN\BL IFRS\LC\Budget
		lineageTag: 588ceeb6-fbe2-4e09-a2e9-c5594442561f

		changedProperty = IsHidden

	measure 'BL IFRS Bgt (EUR) %' =
			
			VAR __Ativos =
			CALCULATE(
			    [BL IFRS Bgt Origin (EUR)],
			    VIEW_NLR_DIM_BL_IFRS[BL_IFRS_LEVEL_1_CODE] = 1,
			    VIEW_GBL_DIM_VALUE_TYPES_ALL[VALUE_TYPE_CODE] = 3,
			    ALL(VIEW_NLR_DIM_BL_IFRS)
			)
			RETURN
			
			DIVIDE(
			    TRUNC([BL IFRS Bgt (EUR)]),
			    TRUNC(__Ativos)
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: FIN\BL IFRS\EUR\Budget
		lineageTag: 2c02b202-9a74-4420-8fdf-919143811375

		changedProperty = IsHidden

	measure 'BL IFRS Bgt Adm' =
			
			
			VAR __ValueType = 4 -- Tipo de orçamento
			
			VAR __Scope =
			ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[PT_BL_IFRS_LEVEL_1_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[EN_BL_IFRS_LEVEL_1_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[ES_BL_IFRS_LEVEL_1_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[FR_BL_IFRS_LEVEL_1_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[PT_BL_IFRS_LEVEL_2_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[EN_BL_IFRS_LEVEL_2_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[ES_BL_IFRS_LEVEL_2_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[FR_BL_IFRS_LEVEL_2_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[PT_BL_IFRS_LEVEL_3_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[EN_BL_IFRS_LEVEL_3_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[ES_BL_IFRS_LEVEL_3_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[FR_BL_IFRS_LEVEL_3_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[PT_BL_IFRS_LEVEL_4_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[EN_BL_IFRS_LEVEL_4_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[ES_BL_IFRS_LEVEL_4_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[FR_BL_IFRS_LEVEL_4_DESC])
			
			RETURN
			
			SWITCH(
			    TRUE(),
			
			    -- Retorna o valor do orçamento do mês/ano contextualizado para a linha de total (Diferença dos Ativos - (CP + Passivo))
			    NOT(__Scope),
			        CALCULATE(
			            [BL IFRS Bgt Origin],
			            ALL(VIEW_NLR_DIM_BL_IFRS),
			            VIEW_GBL_DIM_VALUE_TYPES_ALL[VALUE_TYPE_CODE] = __ValueType,
			            VIEW_NLR_DIM_BL_IFRS[BL_IFRS_LEVEL_1_CODE] = 1
			        )
			        -
			        CALCULATE(
			            [BL IFRS Bgt Origin],
			            ALL(VIEW_NLR_DIM_BL_IFRS),
			            VIEW_GBL_DIM_VALUE_TYPES_ALL[VALUE_TYPE_CODE] = __ValueType,
			            VIEW_NLR_DIM_BL_IFRS[BL_IFRS_LEVEL_1_CODE] = 4
			        ),
			
			    CALCULATE(
			        [BL IFRS Bgt Origin],
			        VIEW_GBL_DIM_VALUE_TYPES_ALL[VALUE_TYPE_CODE] = __ValueType
			    )
			)
		formatString: #,0
		displayFolder: FIN\BL IFRS\LC\Budget
		lineageTag: 0a5fc04e-0bd7-4375-b4cf-43ea775e2271

		changedProperty = IsHidden

	measure 'BL IFRS Bgt Adm (EUR)' =
			
			
			VAR __ValueType = 4 -- Tipo de orçamento
			
			VAR __Scope =
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[PT_BL_IFRS_LEVEL_1_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[EN_BL_IFRS_LEVEL_1_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[ES_BL_IFRS_LEVEL_1_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[FR_BL_IFRS_LEVEL_1_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[PT_BL_IFRS_LEVEL_2_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[EN_BL_IFRS_LEVEL_2_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[ES_BL_IFRS_LEVEL_2_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[FR_BL_IFRS_LEVEL_2_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[PT_BL_IFRS_LEVEL_3_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[EN_BL_IFRS_LEVEL_3_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[ES_BL_IFRS_LEVEL_3_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[FR_BL_IFRS_LEVEL_3_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[PT_BL_IFRS_LEVEL_4_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[EN_BL_IFRS_LEVEL_4_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[ES_BL_IFRS_LEVEL_4_DESC]) ||
			 ISINSCOPE(VIEW_NLR_DIM_BL_IFRS[FR_BL_IFRS_LEVEL_4_DESC])
			
			RETURN
			
			SWITCH(
			    TRUE(),
			    -- Retorna o valor do mês/ano contextualizado para a linha de total (Diferença dos Ativos - (CP + Passivo))
			    NOT(__Scope),
			        CALCULATE(
			            [BL IFRS Bgt Adm Origin (EUR)],
			            VIEW_GBL_DIM_VALUE_TYPES_ALL[VALUE_TYPE_CODE] = __ValueType,
			            ALL(VIEW_NLR_DIM_BL_IFRS),
			            VIEW_NLR_DIM_BL_IFRS[BL_IFRS_LEVEL_1_CODE] =1
			        )
			        -
			        CALCULATE(
			            [BL IFRS Bgt Adm Origin (EUR)],
			            VIEW_GBL_DIM_VALUE_TYPES_ALL[VALUE_TYPE_CODE] = __ValueType,
			            ALL(VIEW_NLR_DIM_BL_IFRS),
			            VIEW_NLR_DIM_BL_IFRS[BL_IFRS_LEVEL_1_CODE] = 4
			        ),
			    CALCULATE(
			        [BL IFRS Bgt Adm Origin (EUR)],
			        VIEW_GBL_DIM_VALUE_TYPES_ALL[VALUE_TYPE_CODE] = __ValueType
			    )
			)
		formatString: #,0
		isHidden
		displayFolder: FIN\BL IFRS\EUR\Budget
		lineageTag: 84eaf277-b5c0-443f-844a-76a46fff3d30

		changedProperty = IsHidden

	measure 'BL IFRS Bgt Adm %' =
			
			
			VAR __Ativos =
			CALCULATE(
			    [BL IFRS Bgt Origin],
			    VIEW_NLR_DIM_BL_IFRS[BL_IFRS_LEVEL_1_CODE] = 1,
			    VIEW_GBL_DIM_VALUE_TYPES_ALL[VALUE_TYPE_CODE] = 4,
			    ALL(VIEW_NLR_DIM_BL_IFRS)
			)
			RETURN
			
			DIVIDE(
			    TRUNC([BL IFRS Bgt Adm]),
			    TRUNC(__Ativos)
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: FIN\BL IFRS\LC\Budget
		lineageTag: 94764766-df86-408c-9f94-2f4813869feb

		changedProperty = IsHidden

	measure 'BL IFRS Bgt Adm (EUR) %' =
			
			VAR __Ativos =
			CALCULATE(
			    [BL IFRS Bgt Adm Origin (EUR)],
			    VIEW_NLR_DIM_BL_IFRS[BL_IFRS_LEVEL_1_CODE] = 1,
			    VIEW_GBL_DIM_VALUE_TYPES_ALL[VALUE_TYPE_CODE] = 4,
			    ALL(VIEW_NLR_DIM_BL_IFRS)
			)
			RETURN
			
			DIVIDE(
			    TRUNC([BL IFRS Bgt Adm (EUR)]),
			    TRUNC(__Ativos)
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: FIN\BL IFRS\EUR\Budget
		lineageTag: 8a46a3bd-5518-47d2-809d-7d9fc85d4f3a

		changedProperty = IsHidden

	measure 'BL IFRS Delta Bgt' =
			
			
			VAR __bgt = [BL IFRS Bgt]
			
			RETURN
			IF(
			    __bgt <> 0,
			    [BL IFRS CY] - __bgt
			)
		formatString: #,0
		displayFolder: FIN\BL IFRS\LC\Budget
		lineageTag: e47b47af-5a0c-4601-b5ef-858aa0f5605a

		changedProperty = IsHidden

	measure 'BL IFRS Delta Bgt (EUR)' =
			
			
			VAR __bgt = [BL IFRS Bgt (EUR)]
			
			RETURN
			IF(
			    __bgt <> 0,
			    [BL IFRS CY (EUR)] - __bgt
			)
		formatString: #,0
		isHidden
		displayFolder: FIN\BL IFRS\EUR\Budget
		lineageTag: 5f691a88-326c-4ec2-9c72-e199f2d92437

		changedProperty = IsHidden

	measure 'BL IFRS Delta Bgt Adm' =
			
			
			VAR __bgt = [BL IFRS Bgt Adm]
			
			RETURN
			IF(
			    __bgt <> 0,
			    [BL IFRS CY] - __bgt
			)
		formatString: #,0
		displayFolder: FIN\BL IFRS\LC\Budget
		lineageTag: 859541f4-255e-4389-998b-8ea016e35082

		changedProperty = IsHidden

	measure 'BL IFRS Delta Bgt Adm (EUR)' =
			
			
			VAR __bgt = [BL IFRS Bgt Adm (EUR)]
			
			RETURN
			IF(
			    __bgt <> 0,
			    [BL IFRS CY (EUR)] - __bgt
			)
		formatString: #,0
		isHidden
		displayFolder: FIN\BL IFRS\EUR\Budget
		lineageTag: 6941d51a-22ce-4218-9358-72a6958d668f

		changedProperty = IsHidden

	measure 'BL IFRS Delta Bgt %' =
			
			
			DIVIDE(
			    TRUNC([BL IFRS Delta Bgt]),
			    TRUNC(ABS([BL IFRS Bgt])),
			    0
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: FIN\BL IFRS\LC\Budget
		lineageTag: 216610d2-e8c1-4c0a-a720-97415d21b694

		changedProperty = IsHidden

	measure 'BL IFRS Delta Bgt (EUR) %' =
			
			
			DIVIDE(
			    TRUNC([BL IFRS Delta Bgt (EUR)]),
			    TRUNC(ABS([BL IFRS Bgt (EUR)])),
			    0
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: FIN\BL IFRS\EUR\Budget
		lineageTag: 9dd70e59-fd64-4fad-bc20-51be651415d1

		changedProperty = IsHidden

	measure 'BL IFRS Delta Bgt Adm %' =
			
			
			DIVIDE(
			    TRUNC([BL IFRS Delta Bgt Adm]),
			    TRUNC(ABS([BL IFRS Bgt Adm])),
			    0
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: FIN\BL IFRS\LC\Budget
		lineageTag: 7247520f-761f-4864-90d9-a1e022f7327a

		changedProperty = IsHidden

	measure 'BL IFRS Delta Bgt Adm (EUR) %' =
			
			
			DIVIDE(
			    TRUNC([BL IFRS Delta Bgt Adm (EUR)]),
			    TRUNC(ABS([BL IFRS Bgt Adm (EUR)])),
			    0
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: FIN\BL IFRS\EUR\Budget
		lineageTag: 7edd9145-00e7-4724-bbb2-9cbe119ca49d

		changedProperty = IsHidden

	measure 'Indicators BL IFRS (EUR)' = ```
			
			
			SWITCH(
			    SELECTEDVALUE(PARAMETER_BL_IFRS_INDICADORES[Id]),
			    1, [BL IFRS CY (EUR)],
			    2, [BL IFRS CY (EUR) %],
			    3, [BL IFRS Bgt (EUR)],
			    4, [BL IFRS Bgt (EUR) %],
			    5, [BL IFRS Delta Bgt (EUR)],
			    6, [BL IFRS Delta Bgt (EUR) %],    
			    7, [BL IFRS Bgt Adm (EUR)],
			    8, [BL IFRS Bgt Adm (EUR) %],
			    9, [BL IFRS Delta Bgt Adm (EUR)],
			    10, [BL IFRS Delta Bgt Adm (EUR) %],
			    11, [BL IFRS LY (EUR)],
			    12, [BL IFRS LY (EUR) %],
			    13, [BL IFRS Delta LY (EUR)],
			    14, [BL IFRS Delta LY (EUR) %]
			)
			```
		isHidden
		displayFolder: FIN\BL IFRS\EUR\Support Measures
		lineageTag: 5b0b5a3f-8cc9-42ac-90de-99786ca2e71c

		formatStringDefinition =
				SWITCH(
				    SELECTEDVALUE(PARAMETER_BL_IFRS_INDICADORES[Id]),
				    1, "#,###,###,###,###",
				    2, "#,##0.0%",
				    3, "#,###,###,###,###",
				    4, "#,##0.0%",
				    5, "#,###,###,###,###",
				    6, "#,##0.0%",
				    7, "#,###,###,###,###",
				    8, "#,##0.0%",
				    9, "#,###,###,###,###",
				    10, "#,##0.0%",
				    11, "#,###,###,###,###",
				    12, "#,##0.0%",
				    13, "#,###,###,###,###",
				    14, "#,##0.0%"
				)

		changedProperty = IsHidden

	measure 'Cabeçalhos BL IFRS' =
			
			CALCULATE(
			    SUM(VIEW_NLR_FACT_BI_BL[BALANCE]) + SUM(VIEW_NLR_FACT_BI_BL_BUDGET[BALANCE]),
			    ALL(CALCGROUP_CURRENCY),
			    REMOVEFILTERS(CALCGROUP_CURRENCY)
			)
		isHidden
		displayFolder: _UI\Cabeçalhos
		lineageTag: bb106919-28fe-4e13-b324-2935e29adcc1

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'BL IFRS Origin' = ```
			
			VAR __SelectedMonth = HASONEVALUE(VIEW_GBL_DIM_CALENDAR[MONTH]) -- Avalia se existe somente um mês contextualizado
			VAR __SelectedYear = HASONEVALUE(VIEW_GBL_DIM_CALENDAR[YEAR]) -- Avalia se existe somente um ano contextualizado
			 
			VAR __Year = YEAR(MAX(VIEW_NLR_FACT_BI_BL[ANALYSIS_DATE])) -- Retorna o último ano contextualizado (Para contornar os casos onde o usuário selecionar mais de um ano)
			VAR __Month = MONTH(MAX(VIEW_NLR_FACT_BI_BL[ANALYSIS_DATE])) -- Retorna o último mês contextualizado (Para contornar os casos onde o usuário selecionar mais de um mês)
			
			RETURN
			 
			SWITCH(
			    TRUE(),
			    -- Retorna o valor do mês/ano contextualizado, se estiver contextualizado/filtrado apenas um ano e mês.
			    __SelectedYear && __SelectedMonth,
			        SUM(VIEW_NLR_FACT_BI_BL[BALANCE]),
			 
			    -- Retorna o valor do último mês com dados do ano contextualizado, se estiver contextualizado/filtrado apenas um ano.
			    __SelectedYear && NOT(__SelectedMonth),
			        CALCULATE(
			            SUM(VIEW_NLR_FACT_BI_BL[BALANCE]),
			            MONTH(VIEW_NLR_FACT_BI_BL[ANALYSIS_DATE]) = __Month
			        ),
			 
			    -- Retorna o valor do mês contextualizado do ano atual, se estiver contextualizado/filtrado apenas um mês.
			    __SelectedMonth && NOT(__SelectedYear),
			        CALCULATE(
			            SUM(VIEW_NLR_FACT_BI_BL[BALANCE]),
			            YEAR(VIEW_NLR_FACT_BI_BL[ANALYSIS_DATE]) = __Year
			        ),
			       
			    -- Retorna o valor do último mês com dados do ano atual, se não estiver contextualizado/filtrado apenas ano e mês.
			        CALCULATE(
			            SUM(VIEW_NLR_FACT_BI_BL[BALANCE]),
			            YEAR(VIEW_NLR_FACT_BI_BL[ANALYSIS_DATE]) = __Year,
			            MONTH(VIEW_NLR_FACT_BI_BL[ANALYSIS_DATE]) = __Month
			        )
			)
			```
		formatString: #,0
		displayFolder: FIN\BL IFRS\LC\Real
		lineageTag: 4ab8678e-1dac-437c-be83-09d7c7a89584

		changedProperty = IsHidden

	measure 'BL IFRS Bgt Origin' = ```
			
			VAR __SelectedMonth = HASONEVALUE(VIEW_GBL_DIM_CALENDAR[MONTH]) -- Avalia se existe somente um mês contextualizado
			VAR __SelectedYear = HASONEVALUE(VIEW_GBL_DIM_CALENDAR[YEAR]) -- Avalia se existe somente um ano contextualizado
			 
			VAR __Year = YEAR(MAX(VIEW_NLR_FACT_BI_BL_BUDGET[ANALYSIS_DATE])) -- Retorna o último ano contextualizado (Para contornar os casos onde o usuário selecionar mais de um ano)
			VAR __Month = MONTH(MAX(VIEW_NLR_FACT_BI_BL_BUDGET[ANALYSIS_DATE]))
			--12 -- Retorna o último mês com orçamento (Por norma, sempre tem orçamento até dezembro, por isso o valor é fixo)
			
			RETURN
			 
			SWITCH(
			    TRUE(),
			 
			    -- Retorna o valor do orçamento do mês/ano contextualizado, se estiver contextualizado/filtrado apenas um ano e mês.
			    __SelectedYear && __SelectedMonth,
			        SUM(VIEW_NLR_FACT_BI_BL_BUDGET[BALANCE]),
			 
			    -- Retorna o valor do orçamento de dezembro do ano contextualizado, se estiver contextualizado/filtrado apenas um ano.
			    __SelectedYear && NOT(__SelectedMonth),
			        CALCULATE(
			            SUM(VIEW_NLR_FACT_BI_BL_BUDGET[BALANCE]),
			            MONTH(VIEW_NLR_FACT_BI_BL_BUDGET[ANALYSIS_DATE]) = __Month
			        ),
			 
			    -- Retorna o valor do orçamento do mês contextualizado do ano atual, se estiver contextualizado/filtrado apenas um mês.
			    __SelectedMonth && NOT(__SelectedYear),
			        CALCULATE(
			            SUM(VIEW_NLR_FACT_BI_BL_BUDGET[BALANCE]),
			            YEAR(VIEW_NLR_FACT_BI_BL_BUDGET[ANALYSIS_DATE]) = __Year
			        ),
			       
			    -- Retorna o valor do orçamento de dezembro do ano atual, se não estiver contextualizado/filtrado apenas ano e mês.
			        CALCULATE(
			            SUM(VIEW_NLR_FACT_BI_BL_BUDGET[BALANCE]),
			            YEAR(VIEW_NLR_FACT_BI_BL_BUDGET[ANALYSIS_DATE]) = __Year,
			            MONTH(VIEW_NLR_FACT_BI_BL_BUDGET[ANALYSIS_DATE]) = __Month
			        )
			)
			```
		formatString: #,0
		displayFolder: FIN\BL IFRS\LC\Budget
		lineageTag: d410d0ed-281f-4f76-8ba4-8e17df416b2d

		changedProperty = IsHidden

	measure 'BL IFRS Origin (EUR)' = ```
			
			 VAR __SelectedMonth = HASONEVALUE(VIEW_GBL_DIM_CALENDAR[MONTH]) -- Avalia se existe somente um mês contextualizado
			 VAR __SelectedYear = HASONEVALUE(VIEW_GBL_DIM_CALENDAR[YEAR]) -- Avalia se existe somente um ano contextualizado
			  
			 VAR __Year = YEAR(MAX(VIEW_NLR_FACT_BI_BL[ANALYSIS_DATE])) -- Retorna o último ano contextualizado (Para contornar os casos onde o usuário selecionar mais de um ano)
			 VAR __Month = MONTH(MAX(VIEW_NLR_FACT_BI_BL[ANALYSIS_DATE])) -- Retorna o último mês contextualizado (Para contornar os casos onde o usuário selecionar mais de um mês)
			
			 RETURN
			  
			 SWITCH(
			     TRUE(),
			     -- Retorna o valor do mês/ano contextualizado, se estiver contextualizado/filtrado apenas um ano e mês.
			     __SelectedYear && __SelectedMonth,
			         SUMX(
			             SUMMARIZECOLUMNS(
			                 VIEW_NLR_FACT_BI_BL[CURRENCY_RATE_KEY],
			                 "BALANCE", SUM(VIEW_NLR_FACT_BI_BL[BALANCE])
			             ),
			             DIVIDE(
			                 [BALANCE],
			                 COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_EOM], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_BI_BL[CURRENCY_RATE_KEY]), 1)
			             )
			         ),
			  
			     -- Retorna o valor do último mês com dados do ano contextualizado, se estiver contextualizado/filtrado apenas um ano.
			     __SelectedYear && NOT(__SelectedMonth),
			         SUMX(
			             FILTER(
			                 SUMMARIZECOLUMNS(
			                     VIEW_NLR_FACT_BI_BL[CURRENCY_RATE_KEY],
			                     VIEW_NLR_FACT_BI_BL[ANALYSIS_DATE],
			                     "BALANCE", SUM(VIEW_NLR_FACT_BI_BL[BALANCE])
			                 ),
			                 MONTH(VIEW_NLR_FACT_BI_BL[ANALYSIS_DATE]) = __Month
			             ),
			             DIVIDE([BALANCE],
			             COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_EOM], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_BI_BL[CURRENCY_RATE_KEY]), 1)
			             )
			         ),
			  
			     -- Retorna o valor do mês contextualizado do ano atual, se estiver contextualizado/filtrado apenas um mês.
			     __SelectedMonth && NOT(__SelectedYear),
			         SUMX(
			             FILTER(
			                 SUMMARIZECOLUMNS(
			                     VIEW_NLR_FACT_BI_BL[CURRENCY_RATE_KEY],
			                     VIEW_NLR_FACT_BI_BL[ANALYSIS_DATE],
			                     "BALANCE", SUM(VIEW_NLR_FACT_BI_BL[BALANCE])
			                 ),
			                 YEAR(VIEW_NLR_FACT_BI_BL[ANALYSIS_DATE]) = __Year
			             ),
			             DIVIDE([BALANCE],
			             COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_EOM], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_BI_BL[CURRENCY_RATE_KEY]), 1)
			             )
			         ),
			        
			     -- Retorna o valor do último mês com dados do ano atual, se não estiver contextualizado/filtrado apenas ano e mês.
			         SUMX(
			             FILTER(
			                 SUMMARIZECOLUMNS(
			                     VIEW_NLR_FACT_BI_BL[CURRENCY_RATE_KEY],
			                     VIEW_NLR_FACT_BI_BL[ANALYSIS_DATE],
			                     "BALANCE", SUM(VIEW_NLR_FACT_BI_BL[BALANCE])
			                 ),
			             YEAR(VIEW_NLR_FACT_BI_BL[ANALYSIS_DATE]) = __Year && MONTH(VIEW_NLR_FACT_BI_BL[ANALYSIS_DATE]) = __Month
			             ),
			             DIVIDE([BALANCE],
			             COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_EOM], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_BI_BL[CURRENCY_RATE_KEY]), 1)
			             )
			         )
			 )
			```
		formatString: #,0
		isHidden
		displayFolder: FIN\BL IFRS\EUR\Real
		lineageTag: 209ea604-3df6-4ece-865a-15c74e977ef1

		changedProperty = IsHidden

	measure 'BL IFRS Bgt Origin (EUR)' = ```
			
			 VAR __SelectedMonth = HASONEVALUE(VIEW_GBL_DIM_CALENDAR[MONTH]) -- Avalia se existe somente um mês contextualizado
			 VAR __SelectedYear = HASONEVALUE(VIEW_GBL_DIM_CALENDAR[YEAR]) -- Avalia se existe somente um ano contextualizado
			  
			 VAR __Year = YEAR(MAX(VIEW_NLR_FACT_BI_BL_BUDGET[ANALYSIS_DATE])) -- Retorna o último ano contextualizado (Para contornar os casos onde o usuário selecionar mais de um ano)
			 VAR __Month = MONTH(MAX(VIEW_NLR_FACT_BI_BL_BUDGET[ANALYSIS_DATE])) -- Retorna o último mês contextualizado (Para contornar os casos onde o usuário selecionar mais de um mês) Por norma, tem sempre dados até dezembro, se não for selecionado mês, apresentará o orçamento de dezembro do respectivo ano.
			
			 VAR __ValueType = 3 -- Tipo de orçamento
			
			 RETURN
			  
			 SWITCH(
			     TRUE(),
			     -- Retorna o valor do mês/ano contextualizado, se estiver contextualizado/filtrado apenas um ano e mês.
			     __SelectedYear && __SelectedMonth,
			         SUMX(
			             FILTER(
			                 SUMMARIZECOLUMNS(
			                     VIEW_NLR_FACT_BI_BL_BUDGET[CURRENCY_RATE_KEY],
			                     VIEW_NLR_FACT_BI_BL_BUDGET[VALUE_TYPE_CODE],
			                     "BALANCE", SUM(VIEW_NLR_FACT_BI_BL_BUDGET[BALANCE])
			                 ),
			                 VIEW_NLR_FACT_BI_BL_BUDGET[VALUE_TYPE_CODE] = __ValueType
			             ),
			             DIVIDE(
			                 [BALANCE],
			                 COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_EOM], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_BI_BL_BUDGET[CURRENCY_RATE_KEY]), 1)
			             )
			         ),
			  
			     -- Retorna o valor do último mês com dados do ano contextualizado, se estiver contextualizado/filtrado apenas um ano.
			     __SelectedYear && NOT(__SelectedMonth),
			         SUMX(
			             FILTER(FILTER(
			                 SUMMARIZECOLUMNS(
			                     VIEW_NLR_FACT_BI_BL_BUDGET[CURRENCY_RATE_KEY],
			                     VIEW_NLR_FACT_BI_BL_BUDGET[ANALYSIS_DATE],
			                     VIEW_NLR_FACT_BI_BL_BUDGET[VALUE_TYPE_CODE],
			                     "BALANCE", SUM(VIEW_NLR_FACT_BI_BL_BUDGET[BALANCE])
			                 ),
			                 MONTH(VIEW_NLR_FACT_BI_BL_BUDGET[ANALYSIS_DATE]) = __Month),
			                 VIEW_NLR_FACT_BI_BL_BUDGET[VALUE_TYPE_CODE] = __ValueType
			             ),
			             DIVIDE([BALANCE],
			             COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_EOM], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_BI_BL_BUDGET[CURRENCY_RATE_KEY]), 1)
			             )
			         ),
			  
			     -- Retorna o valor do mês contextualizado do ano atual, se estiver contextualizado/filtrado apenas um mês.
			     __SelectedMonth && NOT(__SelectedYear),
			         SUMX(
			             FILTER(FILTER(
			                 SUMMARIZECOLUMNS(
			                     VIEW_NLR_FACT_BI_BL_BUDGET[CURRENCY_RATE_KEY],
			                     VIEW_NLR_FACT_BI_BL_BUDGET[ANALYSIS_DATE],
			                     VIEW_NLR_FACT_BI_BL_BUDGET[VALUE_TYPE_CODE],
			                     "BALANCE", SUM(VIEW_NLR_FACT_BI_BL_BUDGET[BALANCE])
			                 ),
			                 YEAR(VIEW_NLR_FACT_BI_BL_BUDGET[ANALYSIS_DATE]) = __Year),
			                 VIEW_NLR_FACT_BI_BL_BUDGET[VALUE_TYPE_CODE] = __ValueType
			             ),
			             DIVIDE([BALANCE],
			             COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_EOM], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_BI_BL_BUDGET[CURRENCY_RATE_KEY]), 1)
			             )
			         ),
			        
			     -- Retorna o valor do último mês com dados do ano atual, se não estiver contextualizado/filtrado apenas ano e mês.
			         SUMX(
			             FILTER(FILTER(
			                 SUMMARIZECOLUMNS(
			                     VIEW_NLR_FACT_BI_BL_BUDGET[CURRENCY_RATE_KEY],
			                     VIEW_NLR_FACT_BI_BL_BUDGET[ANALYSIS_DATE],
			                     VIEW_NLR_FACT_BI_BL_BUDGET[VALUE_TYPE_CODE],
			                     "BALANCE", SUM(VIEW_NLR_FACT_BI_BL_BUDGET[BALANCE])
			                 ),
			                 YEAR(VIEW_NLR_FACT_BI_BL_BUDGET[ANALYSIS_DATE]) = __Year && MONTH(VIEW_NLR_FACT_BI_BL_BUDGET[ANALYSIS_DATE]) = __Month),
			                 VIEW_NLR_FACT_BI_BL_BUDGET[VALUE_TYPE_CODE] = __ValueType
			             ),
			             DIVIDE([BALANCE],
			             COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_EOM], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_BI_BL_BUDGET[CURRENCY_RATE_KEY]), 1)
			             )
			         )
			 )
			```
		formatString: #,0
		isHidden
		displayFolder: FIN\BL IFRS\EUR\Budget
		lineageTag: e39c858d-d746-44c9-aca9-2555e80d50b7

		changedProperty = IsHidden

	measure 'BL IFRS Bgt Adm Origin (EUR)' = ```
			
			 VAR __SelectedMonth = HASONEVALUE(VIEW_GBL_DIM_CALENDAR[MONTH]) -- Avalia se existe somente um mês contextualizado
			 VAR __SelectedYear = HASONEVALUE(VIEW_GBL_DIM_CALENDAR[YEAR]) -- Avalia se existe somente um ano contextualizado
			  
			 VAR __Year = YEAR(MAX(VIEW_NLR_FACT_BI_BL_BUDGET[ANALYSIS_DATE])) -- Retorna o último ano contextualizado (Para contornar os casos onde o usuário selecionar mais de um ano)
			 VAR __Month = MONTH(MAX(VIEW_NLR_FACT_BI_BL_BUDGET[ANALYSIS_DATE])) -- Retorna o último mês contextualizado (Para contornar os casos onde o usuário selecionar mais de um mês) Por norma, tem sempre dados até dezembro, se não for selecionado mês, apresentará o orçamento de dezembro do respectivo ano.
			
			 VAR __ValueType = 4 -- Tipo de orçamento
			
			 RETURN
			  
			 SWITCH(
			     TRUE(),
			     -- Retorna o valor do mês/ano contextualizado, se estiver contextualizado/filtrado apenas um ano e mês.
			     __SelectedYear && __SelectedMonth,
			         SUMX(
			             FILTER(
			                 SUMMARIZECOLUMNS(
			                     VIEW_NLR_FACT_BI_BL_BUDGET[CURRENCY_RATE_KEY],
			                     VIEW_NLR_FACT_BI_BL_BUDGET[VALUE_TYPE_CODE],
			                     "BALANCE", SUM(VIEW_NLR_FACT_BI_BL_BUDGET[BALANCE])
			                 ),
			                 VIEW_NLR_FACT_BI_BL_BUDGET[VALUE_TYPE_CODE] = __ValueType
			             ),
			             DIVIDE(
			                 [BALANCE],
			                 COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_EOM], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_BI_BL_BUDGET[CURRENCY_RATE_KEY]), 1)
			             )
			         ),
			  
			     -- Retorna o valor do último mês com dados do ano contextualizado, se estiver contextualizado/filtrado apenas um ano.
			     __SelectedYear && NOT(__SelectedMonth),
			         SUMX(
			             FILTER(FILTER(
			                 SUMMARIZECOLUMNS(
			                     VIEW_NLR_FACT_BI_BL_BUDGET[CURRENCY_RATE_KEY],
			                     VIEW_NLR_FACT_BI_BL_BUDGET[ANALYSIS_DATE],
			                     VIEW_NLR_FACT_BI_BL_BUDGET[VALUE_TYPE_CODE],
			                     "BALANCE", SUM(VIEW_NLR_FACT_BI_BL_BUDGET[BALANCE])
			                 ),
			                 MONTH(VIEW_NLR_FACT_BI_BL_BUDGET[ANALYSIS_DATE]) = __Month),
			                 VIEW_NLR_FACT_BI_BL_BUDGET[VALUE_TYPE_CODE] = __ValueType
			             ),
			             DIVIDE([BALANCE],
			             COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_EOM], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_BI_BL_BUDGET[CURRENCY_RATE_KEY]), 1)
			             )
			         ),
			  
			     -- Retorna o valor do mês contextualizado do ano atual, se estiver contextualizado/filtrado apenas um mês.
			     __SelectedMonth && NOT(__SelectedYear),
			         SUMX(
			             FILTER(FILTER(
			                 SUMMARIZECOLUMNS(
			                     VIEW_NLR_FACT_BI_BL_BUDGET[CURRENCY_RATE_KEY],
			                     VIEW_NLR_FACT_BI_BL_BUDGET[ANALYSIS_DATE],
			                     VIEW_NLR_FACT_BI_BL_BUDGET[VALUE_TYPE_CODE],
			                     "BALANCE", SUM(VIEW_NLR_FACT_BI_BL_BUDGET[BALANCE])
			                 ),
			                 YEAR(VIEW_NLR_FACT_BI_BL_BUDGET[ANALYSIS_DATE]) = __Year),
			                 VIEW_NLR_FACT_BI_BL_BUDGET[VALUE_TYPE_CODE] = __ValueType
			             ),
			             DIVIDE([BALANCE],
			             COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_EOM], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_BI_BL_BUDGET[CURRENCY_RATE_KEY]), 1)
			             )
			         ),
			        
			     -- Retorna o valor do último mês com dados do ano atual, se não estiver contextualizado/filtrado apenas ano e mês.
			         SUMX(
			             FILTER(FILTER(
			                 SUMMARIZECOLUMNS(
			                     VIEW_NLR_FACT_BI_BL_BUDGET[CURRENCY_RATE_KEY],
			                     VIEW_NLR_FACT_BI_BL_BUDGET[ANALYSIS_DATE],
			                     VIEW_NLR_FACT_BI_BL_BUDGET[VALUE_TYPE_CODE],
			                     "BALANCE", SUM(VIEW_NLR_FACT_BI_BL_BUDGET[BALANCE])
			                 ),
			                 YEAR(VIEW_NLR_FACT_BI_BL_BUDGET[ANALYSIS_DATE]) = __Year && MONTH(VIEW_NLR_FACT_BI_BL_BUDGET[ANALYSIS_DATE]) = __Month),
			                 VIEW_NLR_FACT_BI_BL_BUDGET[VALUE_TYPE_CODE] = __ValueType
			             ),
			             DIVIDE([BALANCE],
			             COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_EOM], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_BI_BL_BUDGET[CURRENCY_RATE_KEY]), 1)
			             )
			         )
			 )
			```
		formatString: #,0
		isHidden
		displayFolder: FIN\BL IFRS\EUR\Budget
		lineageTag: ef4bdb61-54c5-4fe6-8417-1fc7ecb12592

		changedProperty = IsHidden

	measure 'CF CY' = ```
			
			VAR __SelectedMonth = HASONEVALUE(VIEW_GBL_DIM_CALENDAR[MONTH]) -- Avalia se existe somente um mês contextualizado
			VAR __SelectedYear = HASONEVALUE(VIEW_GBL_DIM_CALENDAR[YEAR]) -- Avalia se existe somente um ano contextualizado
			 
			VAR __Year = YEAR(MAX(VIEW_NLR_FACT_CASH_FLOW[ANALYSIS_DATE])) -- Retorna o último ano contextualizado (Para contornar os casos onde o usuário selecionar mais de um ano)
			VAR __Month = MONTH(MAX(VIEW_NLR_FACT_CASH_FLOW[ANALYSIS_DATE])) -- Retorna o último mês contextualizado (Para contornar os casos onde o usuário selecionar mais de um mês)
			
			VAR __CFCode = HASONEVALUE(VIEW_NLR_DIM_CASH_FLOW[CF_CODE])
			
			RETURN
			
			IF(
			    __CFCode,
			    SWITCH(
			        TRUE(),
			        -- Retorna o valor do mês/ano contextualizado, se estiver contextualizado/filtrado apenas um ano e mês.
			        __SelectedYear && __SelectedMonth,
			            SUM(VIEW_NLR_FACT_CASH_FLOW[BALANCE_DISPLAY]),
			    
			        -- Retorna o valor do último mês com dados do ano contextualizado, se estiver contextualizado/filtrado apenas um ano.
			        __SelectedYear && NOT(__SelectedMonth),
			            CALCULATE(
			                SUM(VIEW_NLR_FACT_CASH_FLOW[BALANCE_DISPLAY]),
			                MONTH(VIEW_NLR_FACT_CASH_FLOW[ANALYSIS_DATE]) = __Month
			            ),
			    
			        -- Retorna o valor do mês contextualizado do ano atual, se estiver contextualizado/filtrado apenas um mês.
			        __SelectedMonth && NOT(__SelectedYear),
			            CALCULATE(
			                SUM(VIEW_NLR_FACT_CASH_FLOW[BALANCE_DISPLAY]),
			                YEAR(VIEW_NLR_FACT_CASH_FLOW[ANALYSIS_DATE]) = __Year
			            ),
			        
			        -- Retorna o valor do último mês com dados do ano atual, se não estiver contextualizado/filtrado apenas ano e mês.
			            CALCULATE(
			                SUM(VIEW_NLR_FACT_CASH_FLOW[BALANCE_DISPLAY]),
			                YEAR(VIEW_NLR_FACT_CASH_FLOW[ANALYSIS_DATE]) = __Year,
			                MONTH(VIEW_NLR_FACT_CASH_FLOW[ANALYSIS_DATE]) = __Month
			            )
			    )
			)
			```
		formatString: #,0
		displayFolder: FIN\CF\LC\Real
		lineageTag: c678c572-3294-4c8e-aaf9-e3780e5eca41

		changedProperty = IsHidden

	measure 'CF LY' =
			
			CALCULATE(
			    [CF CY],
			    SAMEPERIODLASTYEAR(VIEW_GBL_DIM_CALENDAR[DATE])
			)
		formatString: #,0
		displayFolder: FIN\CF\LC\Real
		lineageTag: a632a7ac-03ab-4d0b-b5b5-b33bf2e7effe

		changedProperty = IsHidden

	measure 'CF Delta LY' =
			
			
			VAR __ly = [CF LY]
			
			RETURN
			IF(
			    __ly <> 0,
			    [CF CY] - __ly
			)
		formatString: #,0
		displayFolder: FIN\CF\LC\Real
		lineageTag: 98b41ce5-70b0-4928-8f60-69adc4b80ab4

		changedProperty = IsHidden

	measure 'Indicators CF' =
			
			
			SWITCH(
			    SELECTEDVALUE(PARAMETER_CF_INDICADORES[Id]),
			    1, [CF CY],
			    2, [CF LY],
			    3, [CF Delta LY]
			)
		displayFolder: FIN\CF\LC\Support Measures
		lineageTag: 27c7f85a-307e-4480-8984-9d11c975c194

		formatStringDefinition =
				SWITCH(
				    SELECTEDVALUE(PARAMETER_CF_INDICADORES[Id]),
				    1, "#,###,###,###,###",
				    2, "#,###,###,###,###",
				    3, "#,###,###,###,###"
				)

		changedProperty = IsHidden

	measure 'GM CY' =
			
			
			CALCULATE(
			    [GM Origin],
			    VIEW_NLR_FACT_GM[VALUE_TYPE_CODE] = 2
			)
		displayFolder: FIN\GM\LC\Real
		lineageTag: 6f4cca9f-5905-444a-bf1c-cf50eee8d1a0

		formatStringDefinition =
				IF(
				    SELECTEDVALUE(VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE]) IN {51, 52, 55, 56},
				    "###,###,###,###",
				    "###,###,###,##0.00"
				)

		changedProperty = IsHidden

	measure 'GM Bgt' =
			
			
			CALCULATE(
			    [GM Origin],
			    VIEW_NLR_FACT_GM[VALUE_TYPE_CODE] = 3
			)
		displayFolder: FIN\GM\LC\Budget
		lineageTag: 08521c52-b16e-4885-b3e2-67c7ccddcef7

		formatStringDefinition =
				IF(
				    SELECTEDVALUE(VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE]) IN {51, 52, 55, 56},
				    "###,###,###,###",
				    "###,###,###,##0.00"
				)

		changedProperty = IsHidden

	measure 'GM Bgt Adm' =
			
			
			CALCULATE(
			    [GM Origin],
			    VIEW_NLR_FACT_GM[VALUE_TYPE_CODE] = 4
			)
		displayFolder: FIN\GM\LC\Budget
		lineageTag: 63baf983-e81f-49cb-adc6-9b7f45749160

		formatStringDefinition =
				IF(
				    SELECTEDVALUE(VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE]) IN {51, 52, 55, 56},
				    "###,###,###,###",
				    "###,###,###,##0.00"
				)

		changedProperty = IsHidden

	measure 'GM LY' =
			
			
			CALCULATE(
			    [GM CY],
			    SAMEPERIODLASTYEAR(VIEW_GBL_DIM_CALENDAR[DATE])
			)
		displayFolder: FIN\GM\LC\Real
		lineageTag: bd6e7398-b7e3-4528-9dde-17862377250a

		formatStringDefinition =
				IF(
				    SELECTEDVALUE(VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE]) IN {51, 52, 55, 56},
				    "###,###,###,###",
				    "###,###,###,##0.00"
				)

		changedProperty = IsHidden

	measure 'GM Delta Bgt' = ```
			
			
			VAR __Bdg = [GM Bgt]
			VAR __Delta = [GM CY]-__Bdg
			RETURN
			
			DIVIDE(
			    __Delta, 
			    __Bdg
			    )
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: FIN\GM\LC\Budget
		lineageTag: d04d882a-842d-4b1c-b1e8-55f5121317ef

		changedProperty = IsHidden

	measure 'GM Delta Bgt Adm' = ```
			
			
			VAR __Bdg = [GM Bgt Adm]
			VAR __Delta = [GM CY] - __Bdg
			RETURN
			
			DIVIDE(
			    __Delta, 
			    __Bdg
			    )
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: FIN\GM\LC\Budget
		lineageTag: 3b4669a0-84c5-4a80-8e86-f1bf2a248d99

		changedProperty = IsHidden

	measure 'GM Delta LY' =
			
			
			VAR __LY = [GM LY]
			VAR __Delta = [GM CY] - __LY
			RETURN
			
			DIVIDE(
			    __Delta,
			    __LY
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: FIN\GM\LC\Real
		lineageTag: e8e07315-ebd6-451b-adf6-b73c3b674ccc

		changedProperty = IsHidden

	measure 'Indicators GM' = ```
			
			
			SWITCH(
			    SELECTEDVALUE(PARAMETER_GM_INDICADORES[Id]),
			    1, [GM CY],
			    2, [GM Bgt],
			    3, [GM Delta Bgt],   
			    4, [GM Bgt Adm],
			    5, [GM Delta Bgt Adm],
			    6, [GM LY],
			    7, [GM Delta LY]
			)
			```
		displayFolder: FIN\GM\LC\Support Measures
		lineageTag: e325662a-d494-41e3-bc01-72e93b98be02

		formatStringDefinition =
				SWITCH(
				    SELECTEDVALUE(PARAMETER_GM_INDICADORES[Id]),
				    1, "#,###,###,###,##0.00",
				    2, "#,###,###,###,##0.00",
				    3, "#,##0.0%",
				    4, "#,###,###,###,##0.00",
				    5, "#,##0.0%",
				    6, "#,###,###,###,##0.00",
				    7, "#,##0.0%"
				)

		changedProperty = IsHidden

	measure 'HRE CY' =
			
			
			CALCULATE(
			    [HRE Origin],
			    VIEW_HRE_FACT_HR[VALUE_TYPE_CODE] = 2
			)
		formatString: #,0
		displayFolder: FIN\HRE\Real
		lineageTag: 75cfef8b-2ccb-4039-9d50-b4f2b51f9a61

		changedProperty = IsHidden

	measure 'HRE CY M' =
			
			
			CALCULATE(
			    [HRE Origin M],
			    VIEW_HRE_FACT_HR[VALUE_TYPE_CODE] = 2
			)
		formatString: #,0
		displayFolder: FIN\HRE\Real
		lineageTag: 39d7ade3-ac18-4326-8d5e-46ec02177e07

		changedProperty = IsHidden

	measure 'HRE LY M' =
			
			CALCULATE(
			    [HRE CY M],
			    SAMEPERIODLASTYEAR(VIEW_GBL_DIM_CALENDAR[DATE])
			)
		formatString: #,0
		displayFolder: FIN\HRE\Real
		lineageTag: 85fd4058-0649-4f5c-be58-d4bd226ab2c6

		changedProperty = IsHidden

	measure 'HRE LY' =
			
			CALCULATE(
			    [HRE CY],
			    SAMEPERIODLASTYEAR(VIEW_GBL_DIM_CALENDAR[DATE])
			)
		formatString: #,0
		displayFolder: FIN\HRE\Real
		lineageTag: f0f39976-8f7e-478f-a21a-7c7cf14ab6be

		changedProperty = IsHidden

	measure 'HRE Bgt' =
			
			
			CALCULATE(
			    [HRE Origin],
			    VIEW_HRE_FACT_HR[VALUE_TYPE_CODE] = 3
			)
		displayFolder: FIN\HRE\Budget
		lineageTag: 10f322d2-3164-4f62-8f8c-4b349ca5e4b7

		formatStringDefinition = "#,0"

		changedProperty = IsHidden

	measure 'HRE Bgt M' =
			
			
			CALCULATE(
			    [HRE Origin M],
			    VIEW_HRE_FACT_HR[VALUE_TYPE_CODE] = 3
			)
		formatString: #,0
		displayFolder: FIN\HRE\Budget
		lineageTag: f2dabc81-7314-4a39-8e57-17c6de63ea59

		changedProperty = IsHidden

	measure 'HRE Delta Bgt' =
			
			
			VAR __Bdg = [HRE Bgt]
			VAR __delta = [HRE CY] - __Bdg
			
			RETURN
			DIVIDE(
			    __delta,
			    __Bdg
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: FIN\HRE\Budget
		lineageTag: 3993f6e3-c4f8-4ca9-bf25-32c28f07b98d

		changedProperty = IsHidden

	measure 'HRE Delta LY' =
			
			
			VAR __LY = [HRE LY]
			VAR __delta = [HRE CY] - __LY
			
			RETURN
			DIVIDE(
			    __delta,
			    __LY
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: FIN\HRE\Real
		lineageTag: 17c0106f-a5e6-4e69-a0aa-edc43e0b0413

		changedProperty = IsHidden

	measure 'Indicators HRE' =
			
			
			SWITCH(
			    SELECTEDVALUE(PARAMETER_HRE_INDICADORES[Id]),
			    1, [HRE CY],
			    2, [HRE CY M],
			    3, [HRE Bgt],
			    4, [HRE Bgt M],
			    5, [HRE Delta Bgt],
			    6, [HRE LY],
			    7, [HRE LY M],
			    8, [HRE Delta LY]
			)
		displayFolder: FIN\HRE\Support Measures
		lineageTag: aed97ab8-6934-488e-9bde-54ca1be41cd8

		formatStringDefinition =
				SWITCH(
				    SELECTEDVALUE(PARAMETER_HRE_INDICADORES[Id]),
				    1, "#,###,###,###,###",
				    2, "#,###,###,###,###",
				    3, "#,###,###,###,###",
				    4, "#,###,###,###,###",
				    5, "#,##0.0%",
				    6, "#,###,###,###,###",
				    7, "#,###,###,###,###",
				    8, "#,##0.0%"
				)

		changedProperty = IsHidden

	measure 'Cabeçalhos HRE' =
			
			CALCULATE(
			    SUM(VIEW_HRE_FACT_HR[HR_NUMBER]),
			    ALL(CALCGROUP_CURRENCY),
			    REMOVEFILTERS(CALCGROUP_CURRENCY)
			)
		isHidden
		displayFolder: _UI\Cabeçalhos
		lineageTag: 399638a1-0c4e-4bbd-b96d-bcb51d78f919

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cabeçalhos CF' =
			
			CALCULATE(
			    SUM(VIEW_NLR_FACT_CASH_FLOW[BALANCE_DISPLAY]),
			    ALL(CALCGROUP_CURRENCY),
			    REMOVEFILTERS(CALCGROUP_CURRENCY)
			)
		isHidden
		displayFolder: _UI\Cabeçalhos
		lineageTag: 9e92b381-0944-4208-a6ef-c13145c32ef1

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cabeçalhos GM' =
			
			
			IF(
			    ISINSCOPE(VIEW_NLR_DIM_GM_MEASURES[EN_GM_MEASURE_DESC]) || ISINSCOPE(VIEW_NLR_DIM_GM_MEASURES[ES_GM_MEASURE_DESC]) || ISINSCOPE(VIEW_NLR_DIM_GM_MEASURES[PT_GM_MEASURE_DESC]) || ISINSCOPE(VIEW_NLR_DIM_GM_MEASURES[FR_GM_MEASURE_DESC]),
			    [GM Origin],
			    SUM(VIEW_NLR_FACT_GM[GM_VALUE])
			)
		isHidden
		displayFolder: _UI\Cabeçalhos
		lineageTag: 70a40769-5eb6-4da0-b7d9-e7b4361f80ce

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'HRE_C CY' =
			
			
			SUM(VIEW_NLR_FACT_HRE_COSTS[HRE_COST_VALUE])
			+
			CALCULATE(
			    [DR PL CY],
			    VIEW_NLR_FACT_BI_TRANS_PL[HRE_COST_INCLUDED] = 1
			)
		formatString: #,0
		displayFolder: FIN\HRE COST\CR\Real
		lineageTag: b64ef6f8-e124-4c09-8840-fef1a9660e13

		changedProperty = IsHidden

	measure 'HRE_C Bgt' =
			
			CALCULATE(
			    SUM(VIEW_NLR_FACT_HRE_COSTS_BUDGET[HRE_COST_VALUE]),
			    VIEW_NLR_FACT_HRE_COSTS_BUDGET[VALUE_TYPE_CODE] = 3
			)
		formatString: #,0
		displayFolder: FIN\HRE COST\CR\Budget
		lineageTag: adf3bb35-5d7a-4470-9973-c2922579849e

		changedProperty = IsHidden

	measure 'HRE_C Bgt Adm' =
			
			CALCULATE(
			    SUM(VIEW_NLR_FACT_HRE_COSTS_BUDGET[HRE_COST_VALUE]),
			    VIEW_NLR_FACT_HRE_COSTS_BUDGET[VALUE_TYPE_CODE] = 4
			)
		formatString: #,0
		displayFolder: FIN\HRE COST\CR\Budget
		lineageTag: ead6d70f-5131-496e-93b0-081dbe6d6995

		changedProperty = IsHidden

	measure 'HRE_C LY' =
			
			CALCULATE(
			    [HRE_C CY],
			    SAMEPERIODLASTYEAR(VIEW_GBL_DIM_CALENDAR[DATE])
			)
		formatString: #,0
		displayFolder: FIN\HRE COST\CR\Real
		lineageTag: 87de7ff6-fda6-48be-bf91-6e4a444b0372

		changedProperty = IsHidden

	measure 'HRE_C Delta LY %' = ```
			
			
			VAR __LY = [HRE_C LY]
			VAR __delta = [HRE_C CY] - __LY
			
			RETURN
			DIVIDE(
			    TRUNC(__delta), 
			    TRUNC(__LY)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: FIN\HRE COST\CR\Real
		lineageTag: 1f07880c-e3bb-4216-b286-1e6ac496755e

		changedProperty = IsHidden

	measure 'HRE_C Delta Bgt %' = ```
			
			
			VAR __Bgt = [HRE_C Bgt]
			VAR __delta = [HRE_C CY] - __Bgt
			
			RETURN
			DIVIDE(
			    TRUNC(__delta), 
			    TRUNC(__Bgt)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: FIN\HRE COST\CR\Budget
		lineageTag: ca7b4332-ed5e-4cab-9015-9dda759a8c89

		changedProperty = IsHidden

	measure 'HRE_C Delta Bgt Adm %' = ```
			
			
			VAR __Bgt = [HRE_C Bgt Adm]
			VAR __delta = [HRE_C CY] - __Bgt
			
			RETURN
			DIVIDE(
			    TRUNC(__delta), 
			    TRUNC(__Bgt)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: FIN\HRE COST\CR\Budget
		lineageTag: 9dc84450-1154-4699-95be-dc1236ed8bb8

		changedProperty = IsHidden

	measure 'HRE_C Bgt (EUR)' =
			
			
			SUMX(
			    FILTER(
			        SUMMARIZECOLUMNS(
			            VIEW_NLR_FACT_HRE_COSTS_BUDGET[CURRENCY_RATE_KEY],
			            VIEW_NLR_FACT_HRE_COSTS_BUDGET[VALUE_TYPE_CODE],
			            "BALANCE", SUM(VIEW_NLR_FACT_HRE_COSTS_BUDGET[HRE_COST_VALUE])
			        ),
			        VIEW_NLR_FACT_HRE_COSTS_BUDGET[VALUE_TYPE_CODE] = 3
			    ),
			    DIVIDE(
			        [BALANCE],
			        COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_HRE_COSTS_BUDGET[CURRENCY_RATE_KEY]), 1)
			    )
			)
		formatString: #,0
		isHidden
		displayFolder: FIN\HRE COST\EUR\Budget
		lineageTag: 7ed8e4e1-b058-4494-9c63-b8cbdeec9e92

		changedProperty = IsHidden

	measure 'HRE_C Bgt Adm (EUR)' =
			
			
			SUMX(
			    FILTER(
			        SUMMARIZECOLUMNS(
			            VIEW_NLR_FACT_HRE_COSTS_BUDGET[CURRENCY_RATE_KEY],
			            VIEW_NLR_FACT_HRE_COSTS_BUDGET[VALUE_TYPE_CODE],
			            "BALANCE", SUM(VIEW_NLR_FACT_HRE_COSTS_BUDGET[HRE_COST_VALUE])
			        ),
			        VIEW_NLR_FACT_HRE_COSTS_BUDGET[VALUE_TYPE_CODE] = 4
			    ),
			    DIVIDE(
			        [BALANCE],
			        COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_HRE_COSTS_BUDGET[CURRENCY_RATE_KEY]), 1)
			    )
			)
		formatString: #,0
		isHidden
		displayFolder: FIN\HRE COST\EUR\Budget
		lineageTag: b13871ce-8eab-4192-91d9-c3ef87c20706

		changedProperty = IsHidden

	measure 'HRE_C CY (EUR)' = ```
			
			
			SUMX(
			    SUMMARIZECOLUMNS(
			        VIEW_NLR_FACT_HRE_COSTS[CURRENCY_RATE_KEY],
			        "BALANCE", SUM(VIEW_NLR_FACT_HRE_COSTS[HRE_COST_VALUE])
			    ),
			    DIVIDE([BALANCE],
			    COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_HRE_COSTS[CURRENCY_RATE_KEY]), 1)
			    )
			)
			+ 
			CALCULATE(
			    [DR PL CY (EUR)],
			    VIEW_NLR_FACT_BI_TRANS_PL[HRE_COST_INCLUDED] = 1
			)
			```
		formatString: #,0
		isHidden
		displayFolder: FIN\HRE COST\EUR\Real
		lineageTag: 0ee7a05c-c7a5-4079-a37f-942635d68d83

		changedProperty = IsHidden

	measure 'HRE_C LY (EUR)' =
			
			CALCULATE(
			    [HRE_C CY (EUR)],
			    SAMEPERIODLASTYEAR(VIEW_GBL_DIM_CALENDAR[DATE])
			)
		formatString: #,0
		isHidden
		displayFolder: FIN\HRE COST\EUR\Real
		lineageTag: dfb90c56-8cb1-41a1-9f42-cf11a3d6ec5a

		changedProperty = IsHidden

	measure 'HRE_C Delta LY % (EUR)' = ```
			
			
			VAR __LY = [HRE_C LY (EUR)]
			VAR __delta = [HRE_C CY (EUR)] - __LY
			
			RETURN
			DIVIDE(
			    TRUNC(__delta), 
			    TRUNC(__LY)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: FIN\HRE COST\EUR\Real
		lineageTag: 9b988fe6-34cb-4d8c-af78-3a9868dfd74c

		changedProperty = IsHidden

	measure 'HRE_C Delta Bgt % (EUR)' = ```
			
			
			VAR __Bgt = [HRE_C Bgt (EUR)]
			VAR __delta = [HRE_C CY (EUR)] - __Bgt
			
			RETURN
			DIVIDE(
			    TRUNC(__delta), 
			    TRUNC(__Bgt)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: FIN\HRE COST\EUR\Budget
		lineageTag: d077ad17-3889-4dcb-8b22-50c7405837d1

		changedProperty = IsHidden

	measure 'HRE_C Delta Bgt Adm % (EUR)' = ```
			
			
			VAR __Bgt = [HRE_C Bgt Adm (EUR)]
			VAR __delta = [HRE_C CY (EUR)] - __Bgt
			
			RETURN
			DIVIDE(
			    TRUNC(__delta), 
			    TRUNC(__Bgt)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: FIN\HRE COST\EUR\Budget
		lineageTag: dc91432e-b411-4708-9add-4f0b35fe4bea

		changedProperty = IsHidden

	measure 'Indicators HRE_C' =
			
			
			SWITCH(
			    SELECTEDVALUE(PARAMETER_HRE_C_INDICADORES[Id]),
			    1, [HRE_C CY],
			    2, [HRE_C Bgt],
			    3, [HRE_C Delta Bgt],
			    4, [HRE_C Delta Bgt %],
			    5, [HRE_C Bgt Adm],
			    6, [HRE_C Delta Bgt Adm],
			    7, [HRE_C Delta Bgt Adm %],
			    8, [HRE_C LY],
			    9, [HRE_C Delta LY],
			    10, [HRE_C Delta LY %]
			)
		displayFolder: FIN\HRE COST\CR\Support Measures
		lineageTag: 2d5ffdef-0f1f-4648-9e97-e1629622e160

		formatStringDefinition =
				SWITCH(
				    SELECTEDVALUE(PARAMETER_HRE_C_INDICADORES[Id]),
				    1, "#,###,###,###,###",
				    2, "#,###,###,###,###",
				    3, "#,###,###,###,###",
				    4, "#,##0.0%",
				    5, "#,###,###,###,###",
				    6, "#,###,###,###,###",
				    7, "#,##0.0%",
				    8, "#,###,###,###,###",
				    9, "#,###,###,###,###",
				    10, "#,##0.0%"
				)
				
				--1, [HRE_C CY],
				--2, [HRE_C Bgt],
				--3, [HRE_C Delta Bgt],
				--4, [HRE_C Delta Bgt %],
				--5, [HRE_C Bgt Adm],
				--6, [HRE_C Delta Bgt Adm],
				--7, [HRE_C Delta Bgt Adm %],
				--8, [HRE_C LY],
				--9, [HRE_C Delta LY],
				--10, [HRE_C Delta LY %]

		changedProperty = IsHidden

	measure 'Indicators HRE_C (EUR)' =
			
			
			SWITCH(
			    SELECTEDVALUE(PARAMETER_HRE_C_INDICADORES[Id]),
			    1, [HRE_C CY (EUR)],
			    2, [HRE_C Bgt (EUR)],
			    3, [HRE_C Delta Bgt (EUR)],
			    4, [HRE_C Delta Bgt % (EUR)],
			    5, [HRE_C Bgt Adm (EUR)],
			    6, [HRE_C Delta Bgt Adm (EUR)],
			    7, [HRE_C Delta Bgt Adm % (EUR)],
			    8, [HRE_C LY (EUR)],
			    9, [HRE_C Delta LY (EUR)],
			    10, [HRE_C Delta LY % (EUR)]
			)
			
			--1, [HRE_C CY],
			--2, [HRE_C Bgt],
			--3, [HRE_C Delta Bgt],
			--4, [HRE_C Delta Bgt %],
			--5, [HRE_C Bgt Adm],
			--6, [HRE_C Delta Bgt Adm],
			--7, [HRE_C Delta Bgt Adm %],
			--8, [HRE_C LY],
			--9, [HRE_C Delta LY],
			--10, [HRE_C Delta LY %]
		isHidden
		displayFolder: FIN\HRE COST\EUR\Support Measures
		lineageTag: 20b5f6ef-054e-4320-884c-746415b8ed6c

		formatStringDefinition =
				SWITCH(
				    SELECTEDVALUE(PARAMETER_HRE_C_INDICADORES[Id]),
				    1, "#,###,###,###,###",
				    2, "#,###,###,###,###",
				    3, "#,###,###,###,###",
				    4, "#,##0.0%",
				    5, "#,###,###,###,###",
				    6, "#,###,###,###,###",
				    7, "#,##0.0%",
				    8, "#,###,###,###,###",
				    9, "#,###,###,###,###",
				    10, "#,##0.0%"
				)

		changedProperty = IsHidden

	measure 'Cabeçalhos HRE_C' =
			
			CALCULATE(
			    SUM(VIEW_NLR_FACT_HRE_COSTS[HRE_COST_VALUE]),
			    ALL(CALCGROUP_CURRENCY),
			    REMOVEFILTERS(CALCGROUP_CURRENCY)
			)
		isHidden
		displayFolder: _UI\Cabeçalhos
		lineageTag: 467b978d-547f-4225-a95b-9653af707c14

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_GM 101 Financial Autonomy Ratio' = ```
			
			
			VAR __Measure10 = 
			CALCULATE(
			    SUM(VIEW_NLR_FACT_GM[GM_VALUE]),
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 10
			)
			
			VAR __Measure8 = 
			CALCULATE(
			    SUM(VIEW_NLR_FACT_GM[GM_VALUE]),
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 8
			)
			RETURN
			
			DIVIDE(
			    __Measure10,
			    __Measure8
			) * 100
			```
		formatString: #,0.00
		displayFolder: FIN\GM\LC\Support Measures
		lineageTag: 5171040d-3c9d-47bc-92b5-051ba98aeda7

		changedProperty = IsHidden

	measure '_GM 102 - Asset Turnover' = ```
			
			
			VAR __Months = 
			CALCULATE(
			    MONTH(MAX(VIEW_NLR_FACT_GM[ANALYSIS_DATE])), 
			    ALL(VIEW_NLR_DIM_GM_MEASURES)
			    )
			
			VAR __Measure1 = 
			CALCULATE(
			    SUM(VIEW_NLR_FACT_GM[GM_VALUE]),
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 1
			)
			
			VAR __Measure8 = 
			CALCULATE(
			    SUM(VIEW_NLR_FACT_GM[GM_VALUE]),
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 8
			)
			RETURN
			
			DIVIDE(
			    DIVIDE(
			        __Measure1,
			        __Months
			    ) * 12,
			    __Measure8
			)
			```
		formatString: #,0.00
		displayFolder: FIN\GM\LC\Support Measures
		lineageTag: 14ecf1aa-588e-4379-a90f-17d85cea0e73

		changedProperty = IsHidden

	measure '_GM 103 - Sales Profitability' = ```
			
			
			VAR __Measure2 = 
			CALCULATE(
			    SUM(VIEW_NLR_FACT_GM[GM_VALUE]),
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 2
			)
			
			VAR __Measure7 = 
			CALCULATE(
			    SUM(VIEW_NLR_FACT_GM[GM_VALUE]),
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 7
			)
			RETURN
			
			DIVIDE(
			    __Measure2,
			    __Measure7
			) * 100
			```
		formatString: #,0
		displayFolder: FIN\GM\LC\Support Measures
		lineageTag: 5ec1dbc0-726a-4fd2-8c64-30e584ad6cd3

		changedProperty = IsHidden

	measure '_GM 104 - Average Collection Period' = ```
			
			
			VAR __Months = 
			CALCULATE(
			    MONTH(MAX(VIEW_NLR_FACT_GM[ANALYSIS_DATE])), 
			    ALL(VIEW_NLR_DIM_GM_MEASURES)
			    )
			
			VAR __Measure4 = 
			CALCULATE(
			    SUM(VIEW_NLR_FACT_GM[GM_VALUE]),
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 4
			)
			
			VAR __Measure7 = 
			CALCULATE(
			    SUMX(
			        FILTER(
			            SUMMARIZECOLUMNS(
			                VIEW_GBL_DTBI_VAT_RATES[VAT_RATE],
			                VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE],
			                "GM_VALUE", SUM(VIEW_NLR_FACT_GM[GM_VALUE])
			            ),
			            VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 7
			        ),
			        VIEW_GBL_DTBI_VAT_RATES[VAT_RATE] * [GM_VALUE]
			         ),
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES)
			)
			RETURN
			
			DIVIDE(
			    __Measure4,
			    __Measure7
			) * __Months
			```
		formatString: #,0
		displayFolder: FIN\GM\LC\Support Measures
		lineageTag: d279998f-0781-4a74-ace4-f6553639a72b

	measure '_GM 105 - Average Collection Period 3M' = ```
			
			
			VAR __Measure4 = 
			CALCULATE(
			    SUM(VIEW_NLR_FACT_GM[GM_VALUE]),
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 4
			)
			
			VAR __Measure16 = 
			CALCULATE(
			    SUMX(
			        FILTER(
			            SUMMARIZECOLUMNS(
			                VIEW_GBL_DTBI_VAT_RATES[VAT_RATE],
			                VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE],
			                "GM_VALUE", SUM(VIEW_NLR_FACT_GM[GM_VALUE])
			            ),
			            VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 16
			        ),
			        VIEW_GBL_DTBI_VAT_RATES[VAT_RATE] * [GM_VALUE]
			    ),
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES)
			)
			RETURN
			
			DIVIDE(
			    __Measure4,
			    __Measure16
			) * 3
			```
		formatString: #,0
		displayFolder: FIN\GM\LC\Support Measures
		lineageTag: 2ee57b66-5bd4-4942-a76f-6066a91154da

		changedProperty = IsHidden

	measure '_GM 106 - Average Collection Period 12M' = ```
			
			
			VAR __Measure4 = 
			CALCULATE(
			    SUM(VIEW_NLR_FACT_GM[GM_VALUE]),
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 4
			)
			
			VAR __Measure17 = 
			CALCULATE(
			    SUMX(
			        FILTER(
			            SUMMARIZECOLUMNS(
			                VIEW_GBL_DTBI_VAT_RATES[VAT_RATE],
			                VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE],
			                "GM_VALUE", SUM(VIEW_NLR_FACT_GM[GM_VALUE])
			            ),
			            VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 17
			        ),
			        VIEW_GBL_DTBI_VAT_RATES[VAT_RATE] * [GM_VALUE]
			        ),
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES)
			)
			RETURN
			
			DIVIDE(
			    __Measure4,
			    __Measure17
			) * 12
			```
		formatString: #,0
		displayFolder: FIN\GM\LC\Support Measures
		lineageTag: 8e69b974-f74f-4828-b0bb-9c89440cfab5

		changedProperty = IsHidden

	measure '_GM 107 - Average Days in Inventory' = ```
			
			
			VAR __Months = 
			CALCULATE(
			    MONTH(MAX(VIEW_NLR_FACT_GM[ANALYSIS_DATE])), 
			    ALL(VIEW_NLR_DIM_GM_MEASURES)
			    )
			
			VAR __Measure11 = 
			CALCULATE(
			    SUM(VIEW_NLR_FACT_GM[GM_VALUE]),
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 11
			)
			
			VAR __Measure6 = 
			CALCULATE(
			    SUM(VIEW_NLR_FACT_GM[GM_VALUE]),
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 6
			)
			RETURN
			
			DIVIDE(
			    __Measure11,
			    __Measure6
			) * __Months
			```
		formatString: #,0
		displayFolder: FIN\GM\LC\Support Measures
		lineageTag: 55f60bd7-8c03-436b-99d0-bb63bf8da0b6

	measure '_GM 108 - Average Days in Inventory 3M' = ```
			
			
			VAR __Measure11 = 
			CALCULATE(
			    SUM(VIEW_NLR_FACT_GM[GM_VALUE]),
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 11
			)
			
			VAR __Measure14 = 
			CALCULATE(
			    SUM(VIEW_NLR_FACT_GM[GM_VALUE]),
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 14
			)
			RETURN
			
			DIVIDE(
			    __Measure11,
			    __Measure14
			) * 3
			```
		formatString: #,0
		displayFolder: FIN\GM\LC\Support Measures
		lineageTag: 49ad6801-0132-4280-9cac-61091c116780

		changedProperty = IsHidden

	measure '_GM 109 - Average Days in Inventory 12M' = ```
			
			
			VAR __Measure11 = 
			CALCULATE(
			    SUM(VIEW_NLR_FACT_GM[GM_VALUE]),
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 11
			)
			
			VAR __Measure15 = 
			CALCULATE(
			    SUM(VIEW_NLR_FACT_GM[GM_VALUE]),
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 15
			)
			RETURN
			
			DIVIDE(
			    __Measure11,
			    __Measure15
			) * 12
			```
		formatString: #,0
		displayFolder: FIN\GM\LC\Support Measures
		lineageTag: d542a659-f51f-4ef3-9679-1fb25a35e6e1

		changedProperty = IsHidden

	measure '_GM 110 - Average Days Payable' = ```
			
			
			VAR __Months = 
			CALCULATE(
			    MONTH(MAX(VIEW_NLR_FACT_GM[ANALYSIS_DATE])), 
			    ALL(VIEW_NLR_DIM_GM_MEASURES)
			    )
			
			VAR __Measure9 = 
			CALCULATE(
			    SUM(VIEW_NLR_FACT_GM[GM_VALUE]),
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 9
			)
			
			VAR __Measure44 = 
			CALCULATE(
			    SUM(VIEW_NLR_FACT_GM[GM_VALUE]),
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 44
			)
			RETURN
			
			DIVIDE(
			    __Measure9,
			    __Measure44
			) * __Months
			```
		formatString: 0
		displayFolder: FIN\GM\LC\Support Measures
		lineageTag: ff774bc9-4401-49dd-8e91-74089c77af2f

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_GM 111 - Average Days Payable 3M' = ```
			
			
			VAR __Measure9 = 
			CALCULATE(
			    SUM(VIEW_NLR_FACT_GM[GM_VALUE]),
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 9
			)
			
			VAR __Measure45 = 
			CALCULATE(
			    SUM(VIEW_NLR_FACT_GM[GM_VALUE]),
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 45
			)
			RETURN
			
			DIVIDE(
			    __Measure9,
			    __Measure45
			) * 3
			```
		formatString: #,0
		displayFolder: FIN\GM\LC\Support Measures
		lineageTag: 4a01af75-4138-45a8-a469-9819359e0871

		changedProperty = IsHidden

	measure '_GM 112 - Average Days Payable 12M' = ```
			
			
			VAR __Measure9 = 
			CALCULATE(
			    SUM(VIEW_NLR_FACT_GM[GM_VALUE]),
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 9
			)
			
			VAR __Measure46 = 
			CALCULATE(
			    SUM(VIEW_NLR_FACT_GM[GM_VALUE]),
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 46
			)
			RETURN
			
			DIVIDE(
			    __Measure9,
			    __Measure46
			) * 12
			```
		formatString: #,0
		displayFolder: FIN\GM\LC\Support Measures
		lineageTag: d91b616a-890f-412f-99e2-e73c611cda02

		changedProperty = IsHidden

	measure '_GM 113 - Cash Conversion Cycle' =
			
			
			[_GM 104 - Average Collection Period] + [_GM 107 - Average Days in Inventory] - [_GM 110 - Average Days Payable]
		formatString: #,0
		displayFolder: FIN\GM\LC\Support Measures
		lineageTag: 44ccb700-47e9-4309-a74a-4efa5dbd63b2

		changedProperty = IsHidden

	measure '_GM 114 - Net Debt / EBITDA' = ```
			
			
			VAR __Months = 
			CALCULATE(
			    MONTH(MAX(VIEW_NLR_FACT_GM[ANALYSIS_DATE])), 
			    ALL(VIEW_NLR_DIM_GM_MEASURES)
			    )
			
			VAR __Measure53 = 
			CALCULATE(
			    SUM(VIEW_NLR_FACT_GM[GM_VALUE]),
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 53
			)
			
			VAR __Measure3 = 
			CALCULATE(
			    SUM(VIEW_NLR_FACT_GM[GM_VALUE]),
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 3
			)
			RETURN
			
			DIVIDE(
			    __Measure53,
			    DIVIDE(
			        __Measure3,
			        __Months
			    ) * 12
			)
			```
		formatString: #,0.00
		displayFolder: FIN\GM\LC\Support Measures
		lineageTag: e636ba77-5453-4759-8be1-ca4d25a388f4

		changedProperty = IsHidden

	measure '_GM 115 - Net Debt / EBITDA 12M' = ```
			
			
			VAR __Measure53 = 
			CALCULATE(
			    SUM(VIEW_NLR_FACT_GM[GM_VALUE]),
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 53
			)
			
			VAR __Measure54 = 
			CALCULATE(
			    SUM(VIEW_NLR_FACT_GM[GM_VALUE]),
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 54
			)
			RETURN
			
			DIVIDE(
			    __Measure53,
			    __Measure54
			)
			```
		formatString: #,0.00
		displayFolder: FIN\GM\LC\Support Measures
		lineageTag: d1842066-af93-4e01-8d1b-6d1883bd246b

		changedProperty = IsHidden

	measure '_GM 116 - Return on Equity' = ```
			
			
			VAR __Months = 
			CALCULATE(
			    MONTH(MAX(VIEW_NLR_FACT_GM[ANALYSIS_DATE])), 
			    ALL(VIEW_NLR_DIM_GM_MEASURES)
			    )
			
			VAR __Measure2 = 
			CALCULATE(
			    SUM(VIEW_NLR_FACT_GM[GM_VALUE]),
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 2
			)
			
			VAR __Measure10 = 
			CALCULATE(
			    SUM(VIEW_NLR_FACT_GM[GM_VALUE]),
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 10
			)
			RETURN
			
			DIVIDE(
			    DIVIDE(
			        __Measure2,
			        __Months
			    ) * 12,
			    __Measure10
			)
			```
		displayFolder: FIN\GM\LC\Support Measures
		lineageTag: 101643a4-fee6-442c-80d8-a3a842312a88

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_GM 117 - Leverage Ratio' = ```
			
			
			VAR __Measure53 = 
			CALCULATE(
			    SUM(VIEW_NLR_FACT_GM[GM_VALUE]),
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 53
			)
			
			VAR __Measure10_53 = 
			CALCULATE(
			    SUM(VIEW_NLR_FACT_GM[GM_VALUE]),
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] IN {10, 53}
			)
			RETURN
			
			DIVIDE(
			    __Measure53,
			    __Measure10_53
			)
			```
		displayFolder: FIN\GM\LC\Support Measures
		lineageTag: f3cb37bb-5c30-4cf3-9b33-475e150546a0

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OR CY' = SUM(VIEW_NLR_FACT_BI_TRANS_PL[FISCAL_ES_VALUE])
		formatString: #,0
		displayFolder: FIN\OR\LC\Real
		lineageTag: 9ceac5dd-ff37-4ecc-aaa6-a95af3a6ad80

		changedProperty = IsHidden

	measure 'OR CY (EUR)' =
			
			SUMX(
			     SUMMARIZECOLUMNS(
			         VIEW_NLR_FACT_BI_TRANS_PL[CURRENCY_RATE_KEY],
			         "BALANCE", SUM(VIEW_NLR_FACT_BI_TRANS_PL[FISCAL_ES_VALUE])
			     ),
			     DIVIDE([BALANCE],
			     COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_BI_TRANS_PL[CURRENCY_RATE_KEY]), 1)
			     )
			 )
		formatString: #,0
		isHidden
		displayFolder: FIN\OR\EUR\Real
		lineageTag: 4d465f7b-71e5-4f75-8c83-e713c67c6e90

		changedProperty = IsHidden

	measure 'OR LY' =
			
			CALCULATE(
			    [OR CY],
			    SAMEPERIODLASTYEAR(VIEW_GBL_DIM_CALENDAR[DATE])
			)
		formatString: #,0
		displayFolder: FIN\OR\LC\Real
		lineageTag: 9853af95-f928-4544-a399-fc5a78a91419

		changedProperty = IsHidden

	measure 'OR LY (EUR)' =
			
			CALCULATE(
			    [OR CY (EUR)],
			    SAMEPERIODLASTYEAR(VIEW_GBL_DIM_CALENDAR[DATE])
			)
		formatString: #,0
		isHidden
		displayFolder: FIN\OR\EUR\Real
		lineageTag: 5dda2b8c-6331-4e30-9079-dd5a7f7dd901

		changedProperty = IsHidden

	measure 'OR Delta LY %' = ```
			
			
			VAR __LY = [OR LY]
			VAR __delta = [OR CY] - __LY
			
			RETURN
			DIVIDE(
			    TRUNC(__delta), 
			    TRUNC(__LY)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: FIN\OR\LC\Real
		lineageTag: fc5b1e8f-160d-4457-bd62-36b80509b8c4

		changedProperty = IsHidden

	measure 'OR Delta LY (EUR) %' = ```
			
			VAR __LY = [OR LY (EUR)]
			VAR __delta = [OR CY (EUR)] - __LY
			 
			RETURN
			DIVIDE(
			    TRUNC(__delta),
			    TRUNC(__LY)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: FIN\OR\EUR\Real
		lineageTag: c9aba1b3-1cc2-42d4-8f06-9fbb62881d2b

		changedProperty = IsHidden

	measure 'Indicators OR' =
			
			
			SWITCH(
			    SELECTEDVALUE(PARAMETER_OR_INDICADORES[Id]),
			    1, [OR CY],
			    2, [OR LY],
			    3, [OR Delta LY %]
			)
		displayFolder: FIN\OR\LC\Support Measures
		lineageTag: a5915d94-65b7-4af0-9176-49031f587d2d

		formatStringDefinition =
				SWITCH(
				    SELECTEDVALUE(PARAMETER_OR_INDICADORES[Id]),
				    1, "#,###,###,###,###",
				    2, "#,###,###,###,###",
				    3, "#,##0.0%"
				)

		changedProperty = IsHidden

	measure 'Indicators OR (EUR)' =
			
			
			SWITCH(
			    SELECTEDVALUE(PARAMETER_OR_INDICADORES[Id]),
			    1, [OR CY (EUR)],
			    2, [OR LY (EUR)],
			    3, [OR Delta LY (EUR) %]
			)
		isHidden
		displayFolder: FIN\OR\EUR\Support Measures
		lineageTag: bbb6c5a0-2f4e-4ea3-b9ec-a24822edde0d

		formatStringDefinition =
				SWITCH(
				    SELECTEDVALUE(PARAMETER_OR_INDICADORES[Id]),
				    1, "#,###,###,###,###",
				    2, "#,###,###,###,###",
				    3, "#,##0.0%"
				)

		changedProperty = IsHidden

	measure 'Cabeçalhos OR' =
			
			CALCULATE(
			    SUM(VIEW_NLR_FACT_BI_TRANS_PL[FISCAL_ES_VALUE]),
			    ALL(CALCGROUP_CURRENCY),
			    REMOVEFILTERS(CALCGROUP_CURRENCY)
			)
		isHidden
		displayFolder: _UI\Cabeçalhos
		lineageTag: 1335cb7e-110a-47bb-ab96-dfb52aafdcb9

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Title - Matrix OR' =
			
			
			SWITCH(
			    LEFT(SELECTEDVALUE(VIEW_GBL_DIM_USER_CULTURE[USER_CULTURE]), 2),
			    "pt", "Resultados Oficiais (ES)",
			    "en", "Official Results (ES)",
			    "es", "Resultados Oficiales (ES)",
			    "fr", "Résultats Officiels (ES)",
			    "Official Results (ES)"
			)
		isHidden
		displayFolder: _UI\Titles
		lineageTag: 1c416f9e-8a20-4274-98b0-cad3c4a6fb68

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'BL ES CY' =
			
			
			VAR __Scope =
			ISINSCOPE(VIEW_NLR_DIM_BL_FISCAL_ES[PT_BL_FISCAL_ES_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_FISCAL_ES[PT_BL_FISCAL_ES_LEVEL_1_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_FISCAL_ES[PT_BL_FISCAL_ES_LEVEL_2_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_FISCAL_ES[PT_BL_FISCAL_ES_LEVEL_3_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_FISCAL_ES[PT_BL_FISCAL_ES_LEVEL_4_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_FISCAL_ES[EN_BL_FISCAL_ES_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_FISCAL_ES[EN_BL_FISCAL_ES_LEVEL_1_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_FISCAL_ES[EN_BL_FISCAL_ES_LEVEL_2_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_FISCAL_ES[EN_BL_FISCAL_ES_LEVEL_3_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_FISCAL_ES[EN_BL_FISCAL_ES_LEVEL_4_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_FISCAL_ES[ES_BL_FISCAL_ES_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_FISCAL_ES[ES_BL_FISCAL_ES_LEVEL_1_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_FISCAL_ES[ES_BL_FISCAL_ES_LEVEL_2_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_FISCAL_ES[ES_BL_FISCAL_ES_LEVEL_3_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_FISCAL_ES[ES_BL_FISCAL_ES_LEVEL_4_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_FISCAL_ES[FR_BL_FISCAL_ES_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_FISCAL_ES[FR_BL_FISCAL_ES_LEVEL_1_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_FISCAL_ES[FR_BL_FISCAL_ES_LEVEL_2_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_FISCAL_ES[FR_BL_FISCAL_ES_LEVEL_3_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_FISCAL_ES[FR_BL_FISCAL_ES_LEVEL_4_DESC])
			
			RETURN
			
			SWITCH(
			    TRUE(),
			    -- Retorna o valor do mês/ano contextualizado para a linha de total (Diferença de Activo - Patrimonio Neto y Pasivo)
			    NOT(__Scope),
			
			    CALCULATE(
			        [BL ES Origin],
			        ALL(VIEW_NLR_DIM_BL_FISCAL_ES),
			        VIEW_NLR_DIM_BL_FISCAL_ES[BL_FISCAL_ES_LEVEL_1_CODE] = 194
			    )
			    -
			    CALCULATE(
			        [BL ES Origin],
			        ALL(VIEW_NLR_DIM_BL_FISCAL_ES),
			        VIEW_NLR_DIM_BL_FISCAL_ES[BL_FISCAL_ES_LEVEL_1_CODE] = 195
			    ),
			    [BL ES Origin]
			)
		formatString: #,0
		displayFolder: FIN\BL ES\LC\Real
		lineageTag: 00ab1f33-432c-4045-a998-b2340f53d238

		changedProperty = IsHidden

	measure 'BL ES LY' =
			
			CALCULATE(
			    [BL ES CY],
			    SAMEPERIODLASTYEAR(VIEW_GBL_DIM_CALENDAR[DATE])
			)
		formatString: #,0
		displayFolder: FIN\BL ES\LC\Real
		lineageTag: d3b8a9fc-2363-4095-bc83-adfcef21db4f

		changedProperty = IsHidden

	measure 'BL ES Delta LY %' =
			
			
			VAR __LY = [BL ES LY]
			VAR __delta = [BL ES CY]-__LY
			
			RETURN
			DIVIDE(
			    TRUNC(__delta),
			    TRUNC(__LY),
			    0
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: FIN\BL ES\LC\Real
		lineageTag: e4283fd3-4acc-4a38-a91c-5de62bfd3b4c

		changedProperty = IsHidden

	measure 'BL ES CY (EUR)' =
			
			
			VAR __Scope =
			ISINSCOPE(VIEW_NLR_DIM_BL_FISCAL_ES[PT_BL_FISCAL_ES_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_FISCAL_ES[PT_BL_FISCAL_ES_LEVEL_1_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_FISCAL_ES[PT_BL_FISCAL_ES_LEVEL_2_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_FISCAL_ES[PT_BL_FISCAL_ES_LEVEL_3_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_FISCAL_ES[PT_BL_FISCAL_ES_LEVEL_4_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_FISCAL_ES[EN_BL_FISCAL_ES_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_FISCAL_ES[EN_BL_FISCAL_ES_LEVEL_1_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_FISCAL_ES[EN_BL_FISCAL_ES_LEVEL_2_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_FISCAL_ES[EN_BL_FISCAL_ES_LEVEL_3_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_FISCAL_ES[EN_BL_FISCAL_ES_LEVEL_4_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_FISCAL_ES[ES_BL_FISCAL_ES_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_FISCAL_ES[ES_BL_FISCAL_ES_LEVEL_1_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_FISCAL_ES[ES_BL_FISCAL_ES_LEVEL_2_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_FISCAL_ES[ES_BL_FISCAL_ES_LEVEL_3_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_FISCAL_ES[ES_BL_FISCAL_ES_LEVEL_4_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_FISCAL_ES[FR_BL_FISCAL_ES_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_FISCAL_ES[FR_BL_FISCAL_ES_LEVEL_1_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_FISCAL_ES[FR_BL_FISCAL_ES_LEVEL_2_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_FISCAL_ES[FR_BL_FISCAL_ES_LEVEL_3_DESC]) ||
			ISINSCOPE(VIEW_NLR_DIM_BL_FISCAL_ES[FR_BL_FISCAL_ES_LEVEL_4_DESC])
			
			RETURN
			
			SWITCH(
			    TRUE(),
			    -- Retorna o valor do mês/ano contextualizado para a linha de total (Diferença de Activo - Patrimonio Neto y Pasivo)
			    NOT(__Scope),
			
			    CALCULATE(
			        [BL ES Origin (EUR)],
			        ALL(VIEW_NLR_DIM_BL_FISCAL_ES),
			        VIEW_NLR_DIM_BL_FISCAL_ES[BL_FISCAL_ES_LEVEL_1_CODE] = 194
			    )
			    -
			    CALCULATE(
			        [BL ES Origin (EUR)],
			        ALL(VIEW_NLR_DIM_BL_FISCAL_ES),
			        VIEW_NLR_DIM_BL_FISCAL_ES[BL_FISCAL_ES_LEVEL_1_CODE] = 195
			    ),
			    [BL ES Origin (EUR)]
			)
		formatString: #,0
		isHidden
		displayFolder: FIN\BL ES\EUR\Real
		lineageTag: 451ffd24-abba-4d81-a780-8d95a114c1a6

		changedProperty = IsHidden

	measure 'BL ES LY (EUR)' =
			
			CALCULATE(
			    [BL ES CY (EUR)],
			    SAMEPERIODLASTYEAR(VIEW_GBL_DIM_CALENDAR[DATE])
			)
		formatString: #,0
		isHidden
		displayFolder: FIN\BL ES\EUR\Real
		lineageTag: 1e60f2a8-af77-414f-ad5b-1669b596fe51

		changedProperty = IsHidden

	measure 'BL ES Delta LY (EUR) %' =
			
			
			VAR __LY = [BL ES LY (EUR)]
			VAR __delta = [BL ES CY (EUR)] - __LY
			
			RETURN
			DIVIDE(
			    TRUNC(__delta),
			    TRUNC(__LY),
			    0
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: FIN\BL ES\EUR\Real
		lineageTag: 9e3d350f-e4c0-4b23-91c0-57a06c9e9fb8

		changedProperty = IsHidden

	measure 'Indicators BL ES' =
			
			
			SWITCH(
			    SELECTEDVALUE(PARAMETER_BL_ES_INDICADORES[Id]),
			    1, [BL ES CY],
			    2, [BL ES LY],
			    3, [BL ES Delta LY %]
			)
		displayFolder: FIN\BL ES\LC\Support Measures
		lineageTag: f7d4513e-af28-4ec5-b6d4-65acb0b82b6f

		formatStringDefinition =
				SWITCH(
				    SELECTEDVALUE(PARAMETER_BL_ES_INDICADORES[Id]),
				    1, "#,###,###,###,###",
				    2, "#,###,###,###,###",
				    3, "#,##0.0%"
				)

		changedProperty = IsHidden

	measure 'Indicators BL ES (EUR)' =
			
			
			SWITCH(
			    SELECTEDVALUE(PARAMETER_BL_ES_INDICADORES[Id]),
			    1, [BL ES CY (EUR)],
			    2, [BL ES LY (EUR)],
			    3, [BL ES Delta LY (EUR) %]
			)
		isHidden
		displayFolder: FIN\BL ES\EUR\Support Measures
		lineageTag: dab8c6ec-e276-4d53-b136-eecc5e1ed460

		formatStringDefinition =
				SWITCH(
				    SELECTEDVALUE(PARAMETER_BL_ES_INDICADORES[Id]),
				    1, "#,###,###,###,###",
				    2, "#,###,###,###,###",
				    3, "#,##0.0%"
				)

		changedProperty = IsHidden

	measure 'Cabeçalhos BL ES' =
			
			CALCULATE(
			    SUM(VIEW_NLR_FACT_BI_BL[BALANCE_FISCAL_ES]),
			    ALL(CALCGROUP_CURRENCY),
			    REMOVEFILTERS(CALCGROUP_CURRENCY)
			)
		isHidden
		displayFolder: _UI\Cabeçalhos
		lineageTag: 0f55cf7e-d28c-4cc4-9619-a127fe385733

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Title - Matrix BL ES' =
			
			
			SWITCH(
			    LEFT(SELECTEDVALUE(VIEW_GBL_DIM_USER_CULTURE[USER_CULTURE]), 2),
			    "pt", "Balanço Oficial (ES)",
			    "en", "Official Balance (ES)",
			    "es", "Balance Oficial (ES)",
			    "fr", "Bilan Officiel (ES)",
			    "Official Balance (ES)"
			)
		isHidden
		displayFolder: _UI\Titles
		lineageTag: a4f29ae1-87d8-4a7f-b05e-8852fd307f4b

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CF CY (EUR)' = ```
			
			 
			VAR __SelectedMonth = HASONEVALUE(VIEW_GBL_DIM_CALENDAR[MONTH]) -- Avalia se existe somente um mês contextualizado
			VAR __SelectedYear = HASONEVALUE(VIEW_GBL_DIM_CALENDAR[YEAR]) -- Avalia se existe somente um ano contextualizado
			 
			VAR __Year = YEAR(MAX(VIEW_NLR_FACT_CASH_FLOW[ANALYSIS_DATE])) -- Retorna o último ano contextualizado (Para contornar os casos onde o usuário selecionar mais de um ano)
			VAR __Month = MONTH(MAX(VIEW_NLR_FACT_CASH_FLOW[ANALYSIS_DATE])) -- Retorna o último mês contextualizado (Para contornar os casos onde o usuário selecionar mais de um mês) (Para contornar os casos onde o usuário selecionar mais de um mês)
			
			VAR __CFCode = HASONEVALUE(VIEW_NLR_DIM_CASH_FLOW[CF_CODE])
			
			RETURN
			
			IF(
			    __CFCode,
			    SWITCH(
			        TRUE(),
			        -- Retorna o valor do mês/ano contextualizado, se estiver contextualizado/filtrado apenas um ano e mês.
			        __SelectedYear && __SelectedMonth,
			            SUMX(
			                SUMMARIZECOLUMNS(
			                    VIEW_NLR_FACT_CASH_FLOW[CURRENCY_RATE_KEY],
			                    "BALANCE", SUM(VIEW_NLR_FACT_CASH_FLOW[BALANCE_DISPLAY])
			                ),
			                DIVIDE(
			                    [BALANCE],
			                    COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_CASH_FLOW[CURRENCY_RATE_KEY]), 1)
			                )
			            ),
			    
			        -- Retorna o valor do último mês com dados do ano contextualizado, se estiver contextualizado/filtrado apenas um ano.
			        __SelectedYear && NOT(__SelectedMonth),
			            SUMX(
			                FILTER(
			                    SUMMARIZECOLUMNS(
			                        VIEW_NLR_FACT_CASH_FLOW[CURRENCY_RATE_KEY],
			                        VIEW_NLR_FACT_CASH_FLOW[ANALYSIS_DATE],
			                        "BALANCE", SUM(VIEW_NLR_FACT_CASH_FLOW[BALANCE_DISPLAY])
			                    ),
			                    MONTH(VIEW_NLR_FACT_CASH_FLOW[ANALYSIS_DATE]) = __Month
			                ),
			                DIVIDE([BALANCE],
			                COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_CASH_FLOW[CURRENCY_RATE_KEY]), 1)
			                )
			            ),
			    
			        -- Retorna o valor do mês contextualizado do ano atual, se estiver contextualizado/filtrado apenas um mês.
			        __SelectedMonth && NOT(__SelectedYear),
			            SUMX(
			                FILTER(
			                    SUMMARIZECOLUMNS(
			                        VIEW_NLR_FACT_CASH_FLOW[CURRENCY_RATE_KEY],
			                        VIEW_NLR_FACT_CASH_FLOW[ANALYSIS_DATE],
			                        "BALANCE", SUM(VIEW_NLR_FACT_CASH_FLOW[BALANCE_DISPLAY])
			                    ),
			                    YEAR(VIEW_NLR_FACT_CASH_FLOW[ANALYSIS_DATE]) = __Year
			                ),
			                DIVIDE([BALANCE],
			                COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_CASH_FLOW[CURRENCY_RATE_KEY]), 1)
			                )
			            ),
			        
			        -- Retorna o valor do último mês com dados do ano atual, se não estiver contextualizado/filtrado apenas ano e mês.
			            SUMX(
			                FILTER(
			                    SUMMARIZECOLUMNS(
			                        VIEW_NLR_FACT_CASH_FLOW[CURRENCY_RATE_KEY],
			                        VIEW_NLR_FACT_CASH_FLOW[ANALYSIS_DATE],
			                        "BALANCE", SUM(VIEW_NLR_FACT_CASH_FLOW[BALANCE_DISPLAY])
			                    ),
			                YEAR(VIEW_NLR_FACT_CASH_FLOW[ANALYSIS_DATE]) = __Year && MONTH(VIEW_NLR_FACT_CASH_FLOW[ANALYSIS_DATE]) = __Month
			                ),
			                DIVIDE([BALANCE],
			                COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_CASH_FLOW[CURRENCY_RATE_KEY]), 1)
			                )
			            )
			    )
			)
			```
		formatString: #,0
		isHidden
		displayFolder: FIN\CF\EUR\Real
		lineageTag: 5149f266-ce24-4104-982c-ef62aec46991

		changedProperty = IsHidden

	measure 'CF LY (EUR)' =
			
			CALCULATE(
			    [CF CY (EUR)],
			    SAMEPERIODLASTYEAR(VIEW_GBL_DIM_CALENDAR[DATE])
			)
		formatString: #,0
		isHidden
		displayFolder: FIN\CF\EUR\Real
		lineageTag: 3db5b945-bf7b-4bbb-8ae7-e4285170fc67

		changedProperty = IsHidden

	measure 'CF Delta LY (EUR)' =
			
			
			VAR __ly = [CF LY (EUR)]
			
			RETURN
			IF(
			    __ly <> 0,
			    [CF CY (EUR)] - __ly
			)
		formatString: #,0
		isHidden
		displayFolder: FIN\CF\EUR\Real
		lineageTag: 8c135952-5c67-4dcc-8eaa-5d8d7229849d

		changedProperty = IsHidden

	measure 'Indicators CF (EUR)' =
			
			
			SWITCH(
			    SELECTEDVALUE(PARAMETER_CF_INDICADORES[Id]),
			    1, [CF CY (EUR)],
			    2, [CF LY (EUR)],
			    3, [CF Delta LY (EUR)]
			)
		isHidden
		displayFolder: FIN\CF\EUR\Support Measures
		lineageTag: 3eab90a2-c3a9-42cd-904a-f0c27d967f88

		formatStringDefinition =
				SWITCH(
				    SELECTEDVALUE(PARAMETER_CF_INDICADORES[Id]),
				    1, "#,###,###,###,###",
				    2, "#,###,###,###,###",
				    3, "#,###,###,###,###"
				)

		changedProperty = IsHidden

	measure 'HRE Origin' = ```
			
			 VAR __SelectedMonth = HASONEVALUE(VIEW_GBL_DIM_CALENDAR[MONTH]) -- Avalia se existe somente um mês contextualizado
			 VAR __SelectedYear = HASONEVALUE(VIEW_GBL_DIM_CALENDAR[YEAR]) -- Avalia se existe somente um ano contextualizado
			  
			 VAR __Year = YEAR(MAX(VIEW_HRE_FACT_HR[ANALYSIS_DATE])) -- Retorna o último ano contextualizado (Para contornar os casos onde o usuário selecionar mais de um ano)
			 VAR __Month = MONTH(MAX(VIEW_HRE_FACT_HR[ANALYSIS_DATE])) -- Retorna o último mês contextualizado (Para contornar os casos onde o usuário selecionar mais de um mês)
			
			 RETURN
			
			 SWITCH(
			     TRUE(),
			     -- Retorna o valor do mês/ano contextualizado, se estiver contextualizado/filtrado apenas um ano e mês.
			     __SelectedYear && __SelectedMonth,
			         SUM(VIEW_HRE_FACT_HR[HR_NUMBER]),
			  
			     -- Retorna o valor do último mês com dados do ano contextualizado, se estiver contextualizado/filtrado apenas um ano.
			     __SelectedYear && NOT(__SelectedMonth),
			         CALCULATE(
			             SUM(VIEW_HRE_FACT_HR[HR_NUMBER]),
			             MONTH(VIEW_HRE_FACT_HR[ANALYSIS_DATE]) = __Month
			         ),
			  
			     -- Retorna o valor do mês contextualizado do ano atual, se estiver contextualizado/filtrado apenas um mês.
			     __SelectedMonth && NOT(__SelectedYear),
			         CALCULATE(
			             SUM(VIEW_HRE_FACT_HR[HR_NUMBER]),
			             YEAR(VIEW_HRE_FACT_HR[ANALYSIS_DATE]) = __Year
			         ),
			        
			     -- Retorna o valor do último mês com dados do ano atual, se não estiver contextualizado/filtrado apenas ano e mês.
			         CALCULATE(
			             SUM(VIEW_HRE_FACT_HR[HR_NUMBER]),
			             YEAR(VIEW_HRE_FACT_HR[ANALYSIS_DATE]) = __Year,
			             MONTH(VIEW_HRE_FACT_HR[ANALYSIS_DATE]) = __Month
			         )
			 )
			```
		displayFolder: FIN\HRE\Support Measures
		lineageTag: 0200beaf-963d-4fba-891b-0727dfd0e996

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'HRE Origin M' =
			
			
			VAR __Year = YEAR(MAX(VIEW_HRE_FACT_HR[ANALYSIS_DATE])) -- Retorna o último ano contextualizado
			RETURN
			
			DIVIDE(
			    -- Retorna o acumulado do respectivo ano.
			    TOTALYTD(
			        SUM(VIEW_HRE_FACT_HR[HR_NUMBER]),
			        VIEW_GBL_DIM_CALENDAR[DATE]
			    ),
			    -- Retorna a quantidade de meses do respectivo ano, limitado ao mês corrente.
			    CALCULATE(
			        MONTH(MAX(VIEW_HRE_FACT_HR[ANALYSIS_DATE])),
			        VIEW_GBL_DIM_CALENDAR[YEAR] = __Year
			    )
			)
		displayFolder: FIN\HRE\Support Measures
		lineageTag: 0d1ce758-f7ba-4cdf-9233-c6db505498a3

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Title - Sytner' =
			
			
			SWITCH(
			    LEFT(SELECTEDVALUE(VIEW_GBL_DIM_USER_CULTURE[USER_CULTURE]), 2),
			    "pt", "Análise Sytner",
			    "en", "Sytner Analysis",
			    "es", "Análisis Sytner",
			    "fr", "Analyse Sytner",
			    "Sytner Analysis"
			)
		isHidden
		displayFolder: _UI\Titles
		lineageTag: 34fad7fe-b6ea-4ff2-b7e0-07b63db7073d

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sytner CY' = ```
			
			VAR __Unidades =
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_SYTNER_PL_DETAIL_WITH_LANG[PL_SYTNER_DETAIL_LEVEL_1_CODE] = 1000
			    )
			RETURN
			 
			IF(
			    SELECTEDVALUE(VIEW_NLR_DIM_SYTNER_PL_DETAIL_WITH_LANG[PL_SYTNER_DETAIL_LEVEL_1_CODE]) = 1000,
			    __Unidades,
			    SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]) - __Unidades
			)
			```
		formatString: #,0
		displayFolder: Archive\Sytner\CY
		lineageTag: f0dae8d4-99f1-48be-b614-8d2099388c54

		changedProperty = IsHidden

	measure 'Sytner CY %' = ```
			
			
			VAR __Valor = [Sytner CY]
			 
			VAR __ValorVendas =
			CALCULATE(
			    [Sytner CY],
			    VIEW_NLR_DIM_SYTNER_PL_DETAIL_WITH_LANG[PL_SYTNER_DETAIL_LEVEL_1_CODE] = 1010,
			    ALL(VIEW_NLR_DIM_SYTNER_PL),
			    ALL(VIEW_NLR_DIM_ACTIVITIES)
			)
			VAR __ValorVendasWActivity =
			CALCULATE(
			    [Sytner CY],
			    ALL(VIEW_NLR_DIM_SYTNER_PL),
			    VIEW_NLR_DIM_SYTNER_PL_DETAIL_WITH_LANG[PL_SYTNER_DETAIL_LEVEL_1_CODE] = 1010
			)
			 
			RETURN
			
			SWITCH(
			        TRUE(),
			        SELECTEDVALUE(VIEW_NLR_DIM_SYTNER_PL_DETAIL_WITH_LANG[PL_SYTNER_DETAIL_LEVEL_1_CODE]) = 1010, DIVIDE(__Valor, __ValorVendas),
			        SELECTEDVALUE(VIEW_NLR_DIM_SYTNER_PL_DETAIL_WITH_LANG[PL_SYTNER_DETAIL_LEVEL_1_CODE]) <> 1000, DIVIDE(__Valor, __ValorVendasWActivity)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: Archive\Sytner\CY
		lineageTag: bb46866e-5be7-4dea-8f8c-85ce34bdf4fe

		changedProperty = IsHidden

	measure 'Sytner LY' =
			
			CALCULATE(
			    [Sytner CY],
			    SAMEPERIODLASTYEAR(VIEW_GBL_DIM_SHORT_CALENDAR[DATE])
			)
		formatString: #,0
		displayFolder: Archive\Sytner\LY
		lineageTag: 59e6da1b-4a77-454d-9ff0-5f9f92002a44

		changedProperty = IsHidden

	measure 'Sytner LY %' = ```
			
			
			VAR __Valor = [Sytner LY]
			 
			VAR __ValorVendas =
			CALCULATE(
			    [Sytner LY],
			    VIEW_NLR_DIM_SYTNER_PL_DETAIL_WITH_LANG[PL_SYTNER_DETAIL_LEVEL_1_CODE] = 1010,
			    ALL(VIEW_NLR_DIM_SYTNER_PL),
			    ALL(VIEW_NLR_DIM_ACTIVITIES_WITH_LANG)
			)
			VAR __ValorVendasWActivity =
			CALCULATE(
			    [Sytner LY],
			    ALL(VIEW_NLR_DIM_SYTNER_PL),
			    VIEW_NLR_DIM_SYTNER_PL_DETAIL_WITH_LANG[PL_SYTNER_DETAIL_LEVEL_1_CODE] = 1010
			)
			 
			RETURN
			
			SWITCH(
			        TRUE(),
			        SELECTEDVALUE(VIEW_NLR_DIM_SYTNER_PL_DETAIL_WITH_LANG[PL_SYTNER_DETAIL_LEVEL_1_CODE]) = 1010, DIVIDE(__Valor, __ValorVendas),
			        SELECTEDVALUE(VIEW_NLR_DIM_SYTNER_PL_DETAIL_WITH_LANG[PL_SYTNER_DETAIL_LEVEL_1_CODE]) <> 1000, DIVIDE(__Valor, __ValorVendasWActivity)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: Archive\Sytner\LY
		lineageTag: b2fd613b-5f39-4cd2-995f-ba865fe5985c

		changedProperty = IsHidden

	measure 'Sytner Bgt' = ```
			
			VAR __Unidades =
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[SYTNER_VALUE]),
			        VIEW_NLR_DIM_SYTNER_PL_DETAIL_WITH_LANG[PL_SYTNER_DETAIL_LEVEL_1_CODE] = 1000,
			        VIEW_GBL_DIM_VALUE_TYPES_ALL_WITH_LANG[VALUE_TYPE_CODE] = 3
			    )
			RETURN
			 
			IF(
			    SELECTEDVALUE(VIEW_NLR_DIM_SYTNER_PL_DETAIL_WITH_LANG[PL_SYTNER_DETAIL_LEVEL_1_CODE]) = 1000,
			    __Unidades,
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[SYTNER_VALUE]),
			        VIEW_GBL_DIM_VALUE_TYPES_ALL_WITH_LANG[VALUE_TYPE_CODE] = 3
			    )
			    -
			    __Unidades
			)
			```
		formatString: #,0
		displayFolder: Archive\Sytner\Budget
		lineageTag: 7e87a255-e2fd-4558-9808-088cc55f5862

		changedProperty = IsHidden

	measure 'Sytner Bgt %' = ```
			
			
			VAR __Valor = [Sytner Bgt]
			 
			VAR __ValorVendas =
			CALCULATE(
			    [Sytner Bgt],
			    VIEW_NLR_DIM_SYTNER_PL_DETAIL_WITH_LANG[PL_SYTNER_DETAIL_LEVEL_1_CODE] = 1010,
			    ALL(VIEW_NLR_DIM_SYTNER_PL),
			    ALL(VIEW_NLR_DIM_ACTIVITIES_WITH_LANG)
			)
			VAR __ValorVendasWActivity =
			CALCULATE(
			    [Sytner Bgt],
			    ALL(VIEW_NLR_DIM_SYTNER_PL),
			    VIEW_NLR_DIM_SYTNER_PL_DETAIL_WITH_LANG[PL_SYTNER_DETAIL_LEVEL_1_CODE] = 1010
			)
			 
			RETURN
			
			SWITCH(
			        TRUE(),
			        SELECTEDVALUE(VIEW_NLR_DIM_SYTNER_PL_DETAIL_WITH_LANG[PL_SYTNER_DETAIL_LEVEL_1_CODE]) = 1010, DIVIDE(__Valor, __ValorVendas),
			        SELECTEDVALUE(VIEW_NLR_DIM_SYTNER_PL_DETAIL_WITH_LANG[PL_SYTNER_DETAIL_LEVEL_1_CODE]) <> 1000, DIVIDE(__Valor, __ValorVendasWActivity)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: Archive\Sytner\Budget
		lineageTag: 95d38542-94d8-4073-be58-4d56cbddc68b

		changedProperty = IsHidden

	measure 'Sytner Delta Bgt' =
			
			
			VAR __bgt = [Sytner Bgt]
			
			RETURN
			IF(
			    __bgt <> 0,
			    [Sytner CY] - __bgt
			)
		formatString: #,0
		displayFolder: Archive\Sytner\Delta
		lineageTag: 6e1ab34d-50fd-4fda-b0e2-68fc4e62855d

		changedProperty = IsHidden

	measure 'Sytner Delta LY' =
			
			
			VAR __ly = [Sytner LY]
			
			RETURN
			IF(
			    __ly <> 0,
			    [Sytner CY] - __ly
			)
		formatString: #,0
		displayFolder: Archive\Sytner\Delta
		lineageTag: ad3e6b86-ff15-4485-8b40-e6390199ff33

		changedProperty = IsHidden

	measure 'Sytner Delta Bgt %' = ```
			
			DIVIDE(
			    [Sytner Delta Bgt], 
			    ABS([Sytner Bgt])
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: Archive\Sytner\Delta
		lineageTag: 0d8e409d-f015-45f4-b934-4464cc007cbd

		changedProperty = IsHidden

	measure 'Sytner Delta LY %' =
			
			
			DIVIDE(
			    [Sytner Delta LY],
			    ABS([Sytner LY])
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: Archive\Sytner\Delta
		lineageTag: 8490ada0-385f-47e6-a5a7-4bf137eed3c4

		changedProperty = IsHidden

	measure 'Sytner Bgt (EUR)' = ```
			
			
			  VAR __Valor =
			 SUMX(
			     FILTER(
			         SUMMARIZECOLUMNS(
			             VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[CURRENCY_RATE_KEY],
			             VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE_TYPE_CODE],
			             "BALANCE", SUM(VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[SYTNER_VALUE])
			         ),
			         VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE_TYPE_CODE] = 3
			     ),
			     DIVIDE([BALANCE],
			     COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[CURRENCY_RATE_KEY]), 1)
			     )
			 )
			
			 VAR __Unidades =
			 SUMX(
			     FILTER(FILTER(
			         SUMMARIZECOLUMNS(
			             VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[CURRENCY_RATE_KEY],
			             VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE_TYPE_CODE],
			             VIEW_NLR_DIM_SYTNER_PL_DETAIL_WITH_LANG[PL_SYTNER_DETAIL_LEVEL_1_CODE],
			             "BALANCE", SUM(VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[SYTNER_VALUE])
			         ),
			         VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE_TYPE_CODE] = 3),
			         VIEW_NLR_DIM_SYTNER_PL_DETAIL_WITH_LANG[PL_SYTNER_DETAIL_LEVEL_1_CODE] = 1000
			     ),
			     DIVIDE([BALANCE],
			     COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[CURRENCY_RATE_KEY]), 1)
			     )
			 )
			 RETURN
			
			 IF(
			     SELECTEDVALUE(VIEW_NLR_DIM_SYTNER_PL_DETAIL_WITH_LANG[PL_SYTNER_DETAIL_LEVEL_1_CODE]) = 1000,
			     __Unidades,
			     __Valor - __Unidades
			 )
			```
		formatString: #,0
		isHidden
		displayFolder: Archive\Sytner\EUR
		lineageTag: a49dad7c-3622-4da6-ad47-069752ca0096

		changedProperty = IsHidden

	measure 'Sytner Bgt (EUR) %' = ```
			
			
			VAR __Valor = [Sytner Bgt (EUR)]
			 
			VAR __ValorVendas =
			CALCULATE(
			    [Sytner Bgt (EUR)],
			    VIEW_NLR_DIM_SYTNER_PL_DETAIL_WITH_LANG[PL_SYTNER_DETAIL_LEVEL_1_CODE] = 1010,
			    ALL(VIEW_NLR_DIM_SYTNER_PL),
			    ALL(VIEW_NLR_DIM_ACTIVITIES_WITH_LANG)
			)
			VAR __ValorVendasWActivity =
			CALCULATE(
			    [Sytner Bgt (EUR)],
			    ALL(VIEW_NLR_DIM_SYTNER_PL),
			    VIEW_NLR_DIM_SYTNER_PL_DETAIL_WITH_LANG[PL_SYTNER_DETAIL_LEVEL_1_CODE] = 1010
			)
			 
			RETURN
			
			SWITCH(
			        TRUE(),
			        SELECTEDVALUE(VIEW_NLR_DIM_SYTNER_PL_DETAIL_WITH_LANG[PL_SYTNER_DETAIL_LEVEL_1_CODE]) = 1010, DIVIDE(__Valor, __ValorVendas),
			        SELECTEDVALUE(VIEW_NLR_DIM_SYTNER_PL_DETAIL_WITH_LANG[PL_SYTNER_DETAIL_LEVEL_1_CODE]) <> 1000, DIVIDE(__Valor, __ValorVendasWActivity)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: Archive\Sytner\EUR
		lineageTag: 4838bfcc-36a4-437b-a421-58d31561e1ef

		changedProperty = IsHidden

	measure 'Sytner CY (EUR)' = ```
			
			
			  VAR __Valor =
			 SUMX(
			     SUMMARIZECOLUMNS(
			         VIEW_NLR_FACT_BI_TRANS_PL[CURRENCY_RATE_KEY],
			         "BALANCE", SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE])
			     ),
			     DIVIDE([BALANCE],
			     COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_BI_TRANS_PL[CURRENCY_RATE_KEY]), 1)
			     )
			 )
			
			 VAR __Unidades =
			 SUMX(
			     FILTER(
			         SUMMARIZECOLUMNS(
			             VIEW_NLR_FACT_BI_TRANS_PL[CURRENCY_RATE_KEY],
			             VIEW_NLR_DIM_SYTNER_PL_DETAIL_WITH_LANG[PL_SYTNER_DETAIL_LEVEL_1_CODE],
			             "BALANCE", SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE])
			         ),
			         VIEW_NLR_DIM_SYTNER_PL_DETAIL_WITH_LANG[PL_SYTNER_DETAIL_LEVEL_1_CODE] = 1000
			     ),
			     DIVIDE(
			         [BALANCE],
			         COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_BI_TRANS_PL[CURRENCY_RATE_KEY]), 1)
			     )
			 )
			
			 RETURN
			
			 IF(
			     SELECTEDVALUE(VIEW_NLR_DIM_SYTNER_PL_DETAIL_WITH_LANG[PL_SYTNER_DETAIL_LEVEL_1_CODE]) = 1000,
			     __Unidades,
			     __Valor - __Unidades
			 )
			```
		formatString: #,0
		isHidden
		displayFolder: Archive\Sytner\EUR
		lineageTag: c9f94731-fda1-4f9e-a8bc-bde8768accf8

		changedProperty = IsHidden

	measure 'Sytner CY (EUR) %' = ```
			
			
			VAR __Valor = [Sytner CY (EUR)]
			 
			VAR __ValorVendas =
			CALCULATE(
			    [Sytner CY (EUR)],
			    VIEW_NLR_DIM_SYTNER_PL_DETAIL_WITH_LANG[PL_SYTNER_DETAIL_LEVEL_1_CODE] = 1010,
			    ALL(VIEW_NLR_DIM_SYTNER_PL),
			    ALL(VIEW_NLR_DIM_ACTIVITIES_WITH_LANG)
			)
			VAR __ValorVendasWActivity =
			CALCULATE(
			    [Sytner CY (EUR)],
			    ALL(VIEW_NLR_DIM_SYTNER_PL),
			    VIEW_NLR_DIM_SYTNER_PL_DETAIL_WITH_LANG[PL_SYTNER_DETAIL_LEVEL_1_CODE] = 1010
			)
			 
			RETURN
			
			SWITCH(
			        TRUE(),
			        SELECTEDVALUE(VIEW_NLR_DIM_SYTNER_PL_DETAIL_WITH_LANG[PL_SYTNER_DETAIL_LEVEL_1_CODE]) = 1010, DIVIDE(__Valor, __ValorVendas),
			        SELECTEDVALUE(VIEW_NLR_DIM_SYTNER_PL_DETAIL_WITH_LANG[PL_SYTNER_DETAIL_LEVEL_1_CODE]) <> 1000, DIVIDE(__Valor, __ValorVendasWActivity)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: Archive\Sytner\EUR
		lineageTag: 25781070-c400-43b7-a2f3-018d564b596b

		changedProperty = IsHidden

	measure 'Sytner LY (EUR)' =
			
			CALCULATE(
			    [Sytner CY (EUR)],
			    SAMEPERIODLASTYEAR(VIEW_GBL_DIM_SHORT_CALENDAR[DATE])
			)
		formatString: #,0
		isHidden
		displayFolder: Archive\Sytner\EUR
		lineageTag: e4ab538a-4804-49c0-aeac-6da0eee3e505

		changedProperty = IsHidden

	measure 'Sytner LY (EUR) %' = ```
			
			
			VAR __Valor = [Sytner LY (EUR)]
			 
			VAR __ValorVendas =
			CALCULATE(
			    [Sytner LY (EUR)],
			    VIEW_NLR_DIM_SYTNER_PL_DETAIL_WITH_LANG[PL_SYTNER_DETAIL_LEVEL_1_CODE] = 1010,
			    ALL(VIEW_NLR_DIM_SYTNER_PL),
			    ALL(VIEW_NLR_DIM_ACTIVITIES_WITH_LANG)
			)
			VAR __ValorVendasWActivity =
			CALCULATE(
			    [Sytner LY (EUR)],
			    ALL(VIEW_NLR_DIM_SYTNER_PL),
			    VIEW_NLR_DIM_SYTNER_PL_DETAIL_WITH_LANG[PL_SYTNER_DETAIL_LEVEL_1_CODE] = 1010
			)
			 
			RETURN
			
			SWITCH(
			        TRUE(),
			        SELECTEDVALUE(VIEW_NLR_DIM_SYTNER_PL_DETAIL_WITH_LANG[PL_SYTNER_DETAIL_LEVEL_1_CODE]) = 1010, DIVIDE(__Valor, __ValorVendas),
			        SELECTEDVALUE(VIEW_NLR_DIM_SYTNER_PL_DETAIL_WITH_LANG[PL_SYTNER_DETAIL_LEVEL_1_CODE]) <> 1000, DIVIDE(__Valor, __ValorVendasWActivity)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: Archive\Sytner\EUR
		lineageTag: 4fef990c-6d1a-4334-a303-a998f0c7c175

		changedProperty = IsHidden

	measure 'Sytner Delta Bgt (EUR)' =
			
			
			VAR __bgt = [Sytner Bgt (EUR)]
			
			RETURN
			IF(
			    __bgt <> 0,
			    [Sytner CY (EUR)] - __bgt
			)
		formatString: #,0
		isHidden
		displayFolder: Archive\Sytner\EUR
		lineageTag: ff292318-d4aa-41af-8be2-0047c8dfb87a

		changedProperty = IsHidden

	measure 'Sytner Delta Bgt (EUR) %' =
			
			
			DIVIDE(
			    [Sytner Delta Bgt (EUR)],
			    ABS([Sytner Bgt (EUR)])
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: Archive\Sytner\EUR
		lineageTag: fb6163db-a780-42df-b0a0-8789b29c45eb

		changedProperty = IsHidden

	measure 'Sytner Delta LY (EUR)' =
			
			
			VAR __ly = [Sytner LY (EUR)]
			
			RETURN
			IF(
			    __ly <> 0,
			    [Sytner CY (EUR)] - __ly
			)
		formatString: #,0
		isHidden
		displayFolder: Archive\Sytner\EUR
		lineageTag: ff8de6fa-bd26-42f6-af6a-8966f012799e

		changedProperty = IsHidden

	measure 'Sytner Delta LY (EUR) %' =
			
			
			DIVIDE(
			    [Sytner Delta LY (EUR)],
			    ABS([Sytner LY (EUR)])
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: Archive\Sytner\EUR
		lineageTag: daff4095-a205-49d5-b06f-20f15e58a669

		changedProperty = IsHidden

	measure Debt = SUM(VIEW_SLR_FACT_OPEN_DOCUMENTS[OPEN_VALUE])
		formatString: #,0
		displayFolder: FIN\DEBT\LC\Real
		lineageTag: cbd1d59f-13ad-4872-87f5-287b2934fe73

		changedProperty = IsHidden

	measure 'Debt (EUR)' = ```
			
			 SUMX(
			     SUMMARIZECOLUMNS(
			         VIEW_SLR_FACT_OPEN_DOCUMENTS[CURRENCY_RATE_KEY],
			         "BALANCE", SUM(VIEW_SLR_FACT_OPEN_DOCUMENTS[OPEN_VALUE])
			     ),
			     DIVIDE([BALANCE],
			     COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_SLR_FACT_OPEN_DOCUMENTS[CURRENCY_RATE_KEY]), 1)
			     )
			 )
			```
		formatString: #,0
		isHidden
		displayFolder: FIN\DEBT\EUR\Real
		lineageTag: 85513635-6548-46c8-8999-a35210b768ff

		changedProperty = IsHidden

	measure 'Title - Ant. Saldos Clientes' =
			
			
			SWITCH(
			    LEFT(SELECTEDVALUE(VIEW_GBL_DIM_USER_CULTURE[USER_CULTURE]), 2),
			    "pt", "Antiguidade de Saldos Clientes",
			    "en", "Customer Balance Aging",
			    "es", "Antigüedad de Saldos de Clientes",
			    "fr", "Ancienneté du Soldes des Clients",
			    "Customer Balance Aging"
			)
		isHidden
		displayFolder: _UI\Titles
		lineageTag: f6ef575b-53ee-400f-a550-1baecab8bf59

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'GM Origin' = ```
			
			
			VAR __Year = CALCULATE(YEAR(MAX(VIEW_GBL_DIM_CALENDAR[DATE])), VIEW_NLR_FACT_GM[VALUE_TYPE_CODE] = 2, VIEW_NLR_DIM_GM_MEASURES[VISIBLE_TO_CUSTOMER] = 1) -- Retorna o último ano contextualizado (Para contornar os casos onde o usuário selecionar mais de um ano)
			VAR __Month = CALCULATE(MONTH(MAX(VIEW_GBL_DIM_CALENDAR[DATE])), VIEW_NLR_FACT_GM[VALUE_TYPE_CODE] = 2, VIEW_NLR_DIM_GM_MEASURES[VISIBLE_TO_CUSTOMER] = 1) -- Retorna o último mês contextualizado (Para contornar os casos onde o usuário selecionar mais de um mês)
			VAR __Measures = HASONEVALUE(VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE])
			RETURN
			
			IF(
			    __Measures,
			    CALCULATE(
			        SWITCH(
			            SELECTEDVALUE(VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE]),
			            
			            -- Rúbricas calculadas
			            101, [_GM 101 Financial Autonomy Ratio],
			            102, [_GM 102 - Asset Turnover],
			            103, [_GM 103 - Sales Profitability],
			            104, [_GM 104 - Average Collection Period],
			            105, [_GM 105 - Average Collection Period 3M],
			            106, [_GM 106 - Average Collection Period 12M],
			            107, [_GM 107 - Average Days in Inventory],
			            108, [_GM 108 - Average Days in Inventory 3M],
			            109, [_GM 109 - Average Days in Inventory 12M],
			            110, [_GM 110 - Average Days Payable],
			            111, [_GM 111 - Average Days Payable 3M],
			            112, [_GM 112 - Average Days Payable 12M],
			            113, [_GM 113 - Cash Conversion Cycle],
			            114, [_GM 114 - Net Debt / EBITDA],
			            115, [_GM 115 - Net Debt / EBITDA 12M],
			            116, [_GM 116 - Return on Equity],
			            117, [_GM 117 - Leverage Ratio],
			
			            -- Rúbricas de valor
			            SUM(VIEW_NLR_FACT_GM[GM_VALUE])
			        ),
			        YEAR(VIEW_NLR_FACT_GM[ANALYSIS_DATE]) = __Year,
			        MONTH(VIEW_NLR_FACT_GM[ANALYSIS_DATE]) = __Month
			)
			/*
			VAR __Year = YEAR(MAX(VIEW_GBL_DIM_CALENDAR[DATE])) -- Retorna o último ano contextualizado (Para contornar os casos onde o usuário selecionar mais de um ano)
			VAR __Month = MONTH(MAX(VIEW_GBL_DIM_CALENDAR[DATE])) -- Retorna o último mês contextualizado (Para contornar os casos onde o usuário selecionar mais de um mês)
			VAR __Measures = HASONEVALUE(VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE])
			IF(
			    __Measures,
			    CALCULATE(
			        [_GM Origin],
			        YEAR(VIEW_NLR_FACT_GM[ANALYSIS_DATE]) = __Year,
			        MONTH(VIEW_NLR_FACT_GM[ANALYSIS_DATE]) = __Month
			    )
			)
			*/)
			```
		displayFolder: FIN\GM\LC\Support Measures
		lineageTag: 7b117d72-056e-498f-a210-3d8a0e9c26a7

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Payment CY' = SUM(VIEW_SLR_FACT_PAYMENT_METHOD[PAID_VALUE])
		formatString: #,0
		displayFolder: FIN\PAYMENT\LC\Real
		lineageTag: 7db65473-b5f1-4e40-afb5-869ecd2e181b

		changedProperty = IsHidden

	measure 'Payment CY %' = ```
			
			VAR __total = 
			CALCULATE(
			    [Payment CY],
			    ALL(VIEW_SLR_DIM_PAYMENT_METHODS[PT_PAYMENT_METHOD_DESC]),
			    ALL(VIEW_SLR_DIM_PAYMENT_METHODS[EN_PAYMENT_METHOD_DESC]),
			    ALL(VIEW_SLR_DIM_PAYMENT_METHODS[ES_PAYMENT_METHOD_DESC]),
			    ALL(VIEW_SLR_DIM_PAYMENT_METHODS[FR_PAYMENT_METHOD_DESC]),
			    ALL(VIEW_SLR_DIM_PAYMENT_METHODS[PT_PAYMENT_METHOD_SOURCE]),
			    ALL(VIEW_SLR_DIM_PAYMENT_METHODS[EN_PAYMENT_METHOD_SOURCE]),
			    ALL(VIEW_SLR_DIM_PAYMENT_METHODS[ES_PAYMENT_METHOD_SOURCE]),
			    ALL(VIEW_SLR_DIM_PAYMENT_METHODS[FR_PAYMENT_METHOD_SOURCE])
			)
			
			RETURN
			DIVIDE(
			    [Payment CY],
			    __total
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: FIN\PAYMENT\LC\Real
		lineageTag: cde9d938-1677-40f5-ad26-af644d5ed883

		changedProperty = IsHidden

	measure 'Indicators Payment' =
			
			
			SWITCH(
			    SELECTEDVALUE(PARAMETER_PAYMENT_INDICADORES[Id]),
			    1, [Payment CY],
			    2, [Payment CY %]
			)
		displayFolder: FIN\PAYMENT\Support Measures
		lineageTag: 81527b45-5597-4ae2-9b1b-7eb866f15559

		formatStringDefinition =
				SWITCH(
				    SELECTEDVALUE(PARAMETER_PAYMENT_INDICADORES[Id]),
				    1, "#,###,###,###,###",
				    2, "#,##0.0%"
				)

		changedProperty = IsHidden

	measure 'Cabeçalhos Payment' =
			
			CALCULATE(
			    SUM(VIEW_SLR_FACT_PAYMENT_METHOD[PAID_VALUE]),
			    ALL(CALCGROUP_CURRENCY),
			    REMOVEFILTERS(CALCGROUP_CURRENCY)
			)
		isHidden
		displayFolder: _UI\Cabeçalhos
		lineageTag: 21fa80e9-1f9d-4318-bce4-7115aa6c23ff

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Title - Matrix Payment' =
			
			
			SWITCH(
			    LEFT(SELECTEDVALUE(VIEW_GBL_DIM_USER_CULTURE[USER_CULTURE]), 2),
			    "pt", "Formas de Pagamento",
			    "en", "Payment Methods",
			    "es", "Formas de Pago",
			    "fr", "Moyens de Paiement",
			    "Payment Methods"
			)
		isHidden
		displayFolder: _UI\Titles
		lineageTag: 4b1a5992-e1ab-462a-adf7-00f25b7edfba

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Title - Ant. Saldos Fornecedores' =
			
			
			SWITCH(
			    LEFT(SELECTEDVALUE(VIEW_GBL_DIM_USER_CULTURE[USER_CULTURE]), 2),
			    "pt", "Antiguidade de Saldos Fornecedores",
			    "en", "Suppliers Balance Aging",
			    "es", "Antigüedad de Saldos de Proveedores",
			    "fr", "Ancienneté du Soldes des Fournisseurs",
			    "Suppliers Balance Aging"
			)
		isHidden
		displayFolder: _UI\Titles
		lineageTag: 3baed6e1-d066-4486-b2df-6f79baa6e590

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_GM 101 Financial Autonomy Ratio (EUR)' = ```
			
			
			VAR __Measure10 = 
			CALCULATE(
			    [_GM Value],
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 10
			)
			
			VAR __Measure8 = 
			CALCULATE(
			    [_GM Value],
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 8
			)
			RETURN
			
			DIVIDE(
			    __Measure10,
			    __Measure8
			) * 100
			```
		isHidden
		displayFolder: FIN\GM\EUR\Support Measures
		lineageTag: 8c0cf2c6-cdaa-4e47-9924-b63a21952705

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_GM 102 - Asset Turnover (EUR)' = ```
			
			
			VAR __Months = 
			CALCULATE(
			    MONTH(MAX(VIEW_NLR_FACT_GM[ANALYSIS_DATE])), 
			    ALL(VIEW_NLR_DIM_GM_MEASURES)
			    )
			
			VAR __Measure1 = 
			CALCULATE(
			    [_GM Value],
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 1
			)
			
			VAR __Measure8 = 
			CALCULATE(
			    [_GM Value],
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 8
			)
			RETURN
			
			DIVIDE(
			    DIVIDE(
			        __Measure1,
			        __Months
			    ) * 12,
			    __Measure8
			)
			```
		isHidden
		displayFolder: FIN\GM\EUR\Support Measures
		lineageTag: 4ebdd19f-b00d-4336-992f-191357040cb1

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_GM 103 - Sales Profitability (EUR)' = ```
			
			
			VAR __Measure2 = 
			CALCULATE(
			    [_GM Value],
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 2
			)
			
			VAR __Measure7 = 
			CALCULATE(
			    [_GM Value],
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 7
			)
			RETURN
			
			DIVIDE(
			    __Measure2,
			    __Measure7
			) * 100
			```
		isHidden
		displayFolder: FIN\GM\EUR\Support Measures
		lineageTag: 962e5b42-6afa-409f-8540-e370a21c3b11

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_GM 104 - Average Collection Period (EUR)' = ```
			
			
			VAR __Months = 
			CALCULATE(
			    MONTH(MAX(VIEW_NLR_FACT_GM[ANALYSIS_DATE])), 
			    ALL(VIEW_NLR_DIM_GM_MEASURES)
			    )
			
			VAR __Measure4 = 
			CALCULATE(
			    [_GM Value],
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 4
			)
			
			VAR __Measure7 = 
			CALCULATE(
			    [_GM Value VAT],
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 7
			)
			RETURN
			
			DIVIDE(
			    __Measure4,
			    __Measure7
			) * __Months
			```
		isHidden
		displayFolder: FIN\GM\EUR\Support Measures
		lineageTag: a00b0d3d-b350-416c-b454-80a3e6235c23

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_GM 105 - Average Collection Period 3M (EUR)' = ```
			
			
			VAR __Measure4 = 
			CALCULATE(
			    [_GM Value],
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 4
			)
			
			VAR __Measure16 = 
			CALCULATE(
			    [_GM Value VAT],
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 16
			)
			RETURN
			
			DIVIDE(
			    __Measure4,
			    __Measure16
			) * 3
			```
		isHidden
		displayFolder: FIN\GM\EUR\Support Measures
		lineageTag: 05bd0831-e1a0-46ce-883f-f95375bfb26c

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_GM 106 - Average Collection Period 12M (EUR)' = ```
			
			
			VAR __Measure4 = 
			CALCULATE(
			    [_GM Value],
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 4
			)
			
			VAR __Measure17 = 
			CALCULATE(
			    [_GM Value VAT],
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 17
			)
			RETURN
			
			DIVIDE(
			    __Measure4,
			    __Measure17
			) * 12
			```
		isHidden
		displayFolder: FIN\GM\EUR\Support Measures
		lineageTag: 344e1aeb-4794-4c3c-997a-bbc8b27615ef

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_GM 107 - Average Days in Inventory (EUR)' = ```
			
			
			VAR __Months = 
			CALCULATE(
			    MONTH(MAX(VIEW_NLR_FACT_GM[ANALYSIS_DATE])), 
			    ALL(VIEW_NLR_DIM_GM_MEASURES)
			    )
			
			VAR __Measure11 = 
			CALCULATE(
			    [_GM Value],
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 11
			)
			
			VAR __Measure6 = 
			CALCULATE(
			    [_GM Value],
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 6
			)
			RETURN
			
			DIVIDE(
			    __Measure11,
			    __Measure6
			) * __Months
			```
		isHidden
		displayFolder: FIN\GM\EUR\Support Measures
		lineageTag: 2bb24ee4-86cc-44dc-9fdc-a82d9a68962c

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_GM 108 - Average Days in Inventory 3M (EUR)' = ```
			
			
			VAR __Measure11 = 
			CALCULATE(
			    [_GM Value],
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 11
			)
			
			VAR __Measure14 = 
			CALCULATE(
			    [_GM Value],
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 14
			)
			RETURN
			
			DIVIDE(
			    __Measure11,
			    __Measure14
			) * 3
			```
		isHidden
		displayFolder: FIN\GM\EUR\Support Measures
		lineageTag: 313822dc-756d-4c7b-b474-b7231ec3c415

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_GM 109 - Average Days in Inventory 12M (EUR)' = ```
			
			
			VAR __Measure11 = 
			CALCULATE(
			    [_GM Value],
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 11
			)
			
			VAR __Measure15 = 
			CALCULATE(
			    [_GM Value],
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 15
			)
			RETURN
			
			DIVIDE(
			    __Measure11,
			    __Measure15
			) * 12
			```
		isHidden
		displayFolder: FIN\GM\EUR\Support Measures
		lineageTag: 3325b830-6a63-4397-aa2f-d21ce6fae3cc

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_GM 110 - Average Days Payable (EUR)' = ```
			
			
			VAR __Months = 
			CALCULATE(
			    MONTH(MAX(VIEW_NLR_FACT_GM[ANALYSIS_DATE])), 
			    ALL(VIEW_NLR_DIM_GM_MEASURES)
			    )
			
			VAR __Measure9 = 
			CALCULATE(
			    [_GM Value],
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 9
			)
			
			VAR __Measure44 = 
			CALCULATE(
			    [_GM Value],
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 44
			)
			RETURN
			
			DIVIDE(
			    __Measure9,
			    __Measure44
			) * __Months
			```
		isHidden
		displayFolder: FIN\GM\EUR\Support Measures
		lineageTag: 26b59b32-f00a-493c-909d-c976c2ba774c

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_GM 111 - Average Days Payable 3M (EUR)' = ```
			
			
			VAR __Measure9 = 
			CALCULATE(
			    [_GM Value],
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 9
			)
			
			VAR __Measure45 = 
			CALCULATE(
			    [_GM Value],
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 45
			)
			RETURN
			
			DIVIDE(
			    __Measure9,
			    __Measure45
			) * 3
			```
		isHidden
		displayFolder: FIN\GM\EUR\Support Measures
		lineageTag: fd38eed8-a21a-498f-b148-7f81005be044

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_GM 112 - Average Days Payable 12M (EUR)' = ```
			
			
			VAR __Measure9 = 
			CALCULATE(
			    [_GM Value],
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 9
			)
			
			VAR __Measure46 = 
			CALCULATE(
			    [_GM Value],
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 46
			)
			RETURN
			
			DIVIDE(
			    __Measure9,
			    __Measure46
			) * 12
			```
		isHidden
		displayFolder: FIN\GM\EUR\Support Measures
		lineageTag: c9b5596e-f065-49d0-a7a4-d9a46c6961ce

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_GM 113 - Cash Conversion Cycle (EUR)' =
			
			
			[_GM 104 - Average Collection Period (EUR)] + [_GM 107 - Average Days in Inventory (EUR)] - [_GM 110 - Average Days Payable (EUR)]
		isHidden
		displayFolder: FIN\GM\EUR\Support Measures
		lineageTag: 8b38d257-db07-4f7e-b0ee-7b3cd51cffe7

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_GM 114 - Net Debt / EBITDA (EUR)' = ```
			
			
			VAR __Months = 
			CALCULATE(
			    MONTH(MAX(VIEW_NLR_FACT_GM[ANALYSIS_DATE])), 
			    ALL(VIEW_NLR_DIM_GM_MEASURES)
			    )
			
			VAR __Measure53 = 
			CALCULATE(
			    [_GM Value],
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 53
			)
			
			VAR __Measure3 = 
			CALCULATE(
			    [_GM Value],
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 3
			)
			RETURN
			
			DIVIDE(
			    __Measure53,
			    DIVIDE(
			        __Measure3,
			        __Months
			    ) * 12
			)
			```
		isHidden
		displayFolder: FIN\GM\EUR\Support Measures
		lineageTag: c2362b6b-996e-43a0-816f-97a12a72a301

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_GM 115 - Net Debt / EBITDA 12M (EUR)' = ```
			
			
			VAR __Measure53 = 
			CALCULATE(
			    [_GM Value],
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 53
			)
			
			VAR __Measure54 = 
			CALCULATE(
			    [_GM Value],
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 54
			)
			RETURN
			
			DIVIDE(
			    __Measure53,
			    __Measure54
			)
			```
		isHidden
		displayFolder: FIN\GM\EUR\Support Measures
		lineageTag: 7a4f9a7c-4eac-4acb-b84d-f6ffb3f69981

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_GM 116 - Return on Equity (EUR)' = ```
			
			
			VAR __Months = 
			CALCULATE(
			    MONTH(MAX(VIEW_NLR_FACT_GM[ANALYSIS_DATE])), 
			    ALL(VIEW_NLR_DIM_GM_MEASURES)
			    )
			
			VAR __Measure2 = 
			CALCULATE(
			    [_GM Value],
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 2
			)
			
			VAR __Measure10 = 
			CALCULATE(
			    [_GM Value],
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 10
			)
			RETURN
			
			DIVIDE(
			    DIVIDE(
			        __Measure2,
			        __Months
			    ) * 12,
			    __Measure10
			)
			```
		isHidden
		displayFolder: FIN\GM\EUR\Support Measures
		lineageTag: 22f99914-6895-4e46-ad9e-0a1199dd4f63

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_GM 117 - Leverage Ratio (EUR)' = ```
			
			
			VAR __Measure53 = 
			CALCULATE(
			    [_GM Value],
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] = 53
			)
			
			VAR __Measure10_53 = 
			CALCULATE(
			    [_GM Value],
			    REMOVEFILTERS(VIEW_NLR_DIM_GM_MEASURES),
			    VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE] IN {10, 53}
			)
			RETURN
			
			DIVIDE(
			    __Measure53,
			    __Measure10_53
			)
			```
		isHidden
		displayFolder: FIN\GM\EUR\Support Measures
		lineageTag: 607c9b2e-b6ab-4728-ae7a-eb231118fb6a

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_GM Origin (EUR)' = ```
			
			
			VAR __NoConversion = [GM Origin]
			RETURN
			
			SWITCH(
			    SELECTEDVALUE(VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE]),
			
			    -- Rúbricas calculadas com conversão
			    101, [_GM 101 Financial Autonomy Ratio (EUR)],
			    102, [_GM 102 - Asset Turnover (EUR)],
			    103, [_GM 103 - Sales Profitability (EUR)],
			    104, [_GM 104 - Average Collection Period (EUR)],
			    105, [_GM 105 - Average Collection Period 3M (EUR)],
			    106, [_GM 106 - Average Collection Period 12M (EUR)],
			    107, [_GM 107 - Average Days in Inventory (EUR)],
			    108, [_GM 108 - Average Days in Inventory 3M (EUR)],
			    109, [_GM 109 - Average Days in Inventory 12M (EUR)],
			    110, [_GM 110 - Average Days Payable (EUR)],
			    111, [_GM 111 - Average Days Payable 3M (EUR)],
			    112, [_GM 112 - Average Days Payable 12M (EUR)],
			    113, [_GM 113 - Cash Conversion Cycle (EUR)],
			    114, [_GM 114 - Net Debt / EBITDA (EUR)],
			    115, [_GM 115 - Net Debt / EBITDA 12M (EUR)],
			    116, [_GM 116 - Return on Equity (EUR)],
			    117, [_GM 117 - Leverage Ratio (EUR)],
			
			    -- Rúbricas de valor sem conversão
			    13, __NoConversion,
			    51, __NoConversion,
			    52, __NoConversion,
			    55, __NoConversion,
			    56, __NoConversion,
			    57, __NoConversion,
			    
			    -- Rúbricas de valor com conversão
			    [_GM Value]
			)
			```
		isHidden
		displayFolder: FIN\GM\EUR\Support Measures
		lineageTag: d5b6db2a-cf7c-4039-b257-8172a506610e

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_GM Value' =
			
			
			SUMX(
			    SUMMARIZECOLUMNS(
			        VIEW_NLR_FACT_GM[CURRENCY_RATE_KEY],
			        "GM_VALUE", SUM(VIEW_NLR_FACT_GM[GM_VALUE])
			    ),
			    DIVIDE(
			        [GM_VALUE],
			        COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_EOM], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_GM[CURRENCY_RATE_KEY]), 1)
			    )
			)
		isHidden
		displayFolder: FIN\GM\EUR\Support Measures
		lineageTag: a98600c0-bd42-4049-a41d-91a850fe4c91

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_GM Value VAT' =
			
			
			SUMX(
			    SUMMARIZECOLUMNS(
			        VIEW_GBL_DTBI_VAT_RATES[VAT_RATE],
			        VIEW_NLR_FACT_GM[CURRENCY_RATE_KEY],
			        "GM_VALUE", SUM(VIEW_NLR_FACT_GM[GM_VALUE])
			    ),
			    DIVIDE(
			        [GM_VALUE],
			        COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_EOM], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_GM[CURRENCY_RATE_KEY]), 1)
			    ) * VIEW_GBL_DTBI_VAT_RATES[VAT_RATE]
			)
		isHidden
		displayFolder: FIN\GM\EUR\Support Measures
		lineageTag: 980d677c-be1c-45fd-acec-737718e72637

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'GM Origin (EUR)' =
			
			
			VAR __Year = CALCULATE(YEAR(MAX(VIEW_GBL_DIM_CALENDAR[DATE])), VIEW_NLR_FACT_GM[VALUE_TYPE_CODE] = 2, VIEW_NLR_DIM_GM_MEASURES[VISIBLE_TO_CUSTOMER] = 1) -- Retorna o último ano contextualizado (Para contornar os casos onde o usuário selecionar mais de um ano)
			VAR __Month = CALCULATE(MONTH(MAX(VIEW_GBL_DIM_CALENDAR[DATE])), VIEW_NLR_FACT_GM[VALUE_TYPE_CODE] = 2, VIEW_NLR_DIM_GM_MEASURES[VISIBLE_TO_CUSTOMER] = 1) -- Retorna o último mês contextualizado (Para contornar os casos onde o usuário selecionar mais de um mês)
			VAR __Measures = HASONEVALUE(VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE])
			VAR __NoConversion = [GM Origin]
			RETURN
			
			IF(
			    __Measures,
			    CALCULATE(
			        [_GM Origin (EUR)],
			        YEAR(VIEW_NLR_FACT_GM[ANALYSIS_DATE]) = __Year,
			        MONTH(VIEW_NLR_FACT_GM[ANALYSIS_DATE]) = __Month
			    )
			)
		isHidden
		displayFolder: FIN\GM\EUR\Support Measures
		lineageTag: 69c3f953-e87f-499c-8cee-38d0a60832bb

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Indicators GM (EUR)' = ```
			
			
			SWITCH(
			    SELECTEDVALUE(PARAMETER_GM_INDICADORES[Id]),
			    1, [GM CY (EUR)],
			    2, [GM Bgt (EUR)],
			    3, [GM Delta Bgt (EUR)],   
			    4, [GM Bgt Adm (EUR)],
			    5, [GM Delta Bgt Adm (EUR)],
			    6, [GM LY (EUR)],
			    7, [GM Delta LY (EUR)]
			)
			```
		isHidden
		displayFolder: FIN\GM\EUR\Support Measures
		lineageTag: e6cf92e1-a681-45d5-9fd4-eac87d80489c

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'GM LY (EUR)' =
			
			
			CALCULATE(
			    [GM CY (EUR)],
			    SAMEPERIODLASTYEAR(VIEW_GBL_DIM_CALENDAR[DATE])
			)
		isHidden
		displayFolder: FIN\GM\EUR\Real
		lineageTag: a619c563-3259-43f3-98bc-725c7bf5e64a

		formatStringDefinition =
				IF(
				    SELECTEDVALUE(VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE]) IN {51, 52, 55, 56},
				    "###,###,###,###",
				    "###,###,###,##0.00"
				)

		changedProperty = IsHidden

	measure 'GM Delta LY (EUR)' =
			
			
			VAR __LY = [GM LY (EUR)]
			VAR __Delta = [GM CY (EUR)] - __LY
			RETURN
			
			DIVIDE(
			    __Delta,
			    __LY
			)
		formatString: 0.0%;-0.0%;0.0%
		isHidden
		displayFolder: FIN\GM\EUR\Real
		lineageTag: e145b424-3e40-4ed3-8ca4-edea9ef8f399

		changedProperty = IsHidden

	measure 'GM Delta Bgt Adm (EUR)' = ```
			
			
			VAR __Bdg = [GM Bgt Adm (EUR)]
			VAR __Delta = [GM CY (EUR)] - __Bdg
			
			RETURN
			DIVIDE(
			    __Delta, 
			    __Bdg
			    )
			```
		formatString: 0.0%;-0.0%;0.0%
		isHidden
		displayFolder: FIN\GM\EUR\Budget
		lineageTag: f096166e-cd45-43ab-855d-cf79bd392e93

		changedProperty = IsHidden

	measure 'GM Delta Bgt (EUR)' = ```
			
			
			VAR __Bdg = [GM Bgt (EUR)]
			VAR __Delta = [GM CY (EUR)]-__Bdg
			RETURN
			
			DIVIDE(
			    __Delta, 
			    __Bdg
			    )
			```
		formatString: 0.0%;-0.0%;0.0%
		isHidden
		displayFolder: FIN\GM\EUR\Budget
		lineageTag: 0e3e7ec6-5f5c-4539-ae22-66608da85955

		changedProperty = IsHidden

	measure 'GM CY (EUR)' =
			
			
			CALCULATE(
			    [GM Origin (EUR)],
			    VIEW_NLR_FACT_GM[VALUE_TYPE_CODE] = 2
			)
		isHidden
		displayFolder: FIN\GM\EUR\Real
		lineageTag: 6c7ea410-6b1e-413a-9162-7785a9bd3d86

		formatStringDefinition =
				IF(
				    SELECTEDVALUE(VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE]) IN {51, 52, 55, 56},
				    "###,###,###,###",
				    "###,###,###,##0.00"
				)

		changedProperty = IsHidden

	measure 'GM Bgt Adm (EUR)' =
			
			
			CALCULATE(
			    [GM Origin (EUR)],
			    VIEW_NLR_FACT_GM[VALUE_TYPE_CODE] = 4
			)
		isHidden
		displayFolder: FIN\GM\EUR\Budget
		lineageTag: a77d60cd-8521-4a1e-9912-c15c43be8e32

		formatStringDefinition =
				IF(
				    SELECTEDVALUE(VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE]) IN {51, 52, 55, 56},
				    "###,###,###,###",
				    "###,###,###,##0.00"
				)

		changedProperty = IsHidden

	measure 'GM Bgt (EUR)' =
			
			
			CALCULATE(
			    [GM Origin (EUR)],
			    VIEW_NLR_FACT_GM[VALUE_TYPE_CODE] = 3
			)
		isHidden
		displayFolder: FIN\GM\EUR\Budget
		lineageTag: f756b24c-fa56-4fe5-9f6d-a91dc65ede20

		formatStringDefinition =
				IF(
				    SELECTEDVALUE(VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE]) IN {51, 52, 55, 56},
				    "###,###,###,###",
				    "###,###,###,##0.00"
				)

	measure 'Title - Vehicle Purchase' =
			
			
			SWITCH(
			    LEFT(SELECTEDVALUE(VIEW_GBL_DIM_USER_CULTURE[USER_CULTURE]), 2),
			    "pt", "Compra de Viaturas",
			    "en", "Vehicle Purchase",
			    "es", "Compra de Vehículos",
			    "fr", "Achat de Véhicules",
			    "Vehicle Purchase"
			)
		isHidden
		displayFolder: _UI\Titles
		lineageTag: 7caaa78b-33e4-40d1-9790-0f3162374cc9

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_SPL 01 - New BMW GP Average' = ```
			
			
			VAR __GrossProfit = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_1_CODE] = 87, -- Viaturas Novas
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1035, -- Gross Profit II
			        NOT(VIEW_GBL_DIM_FRANCHISES[FRANCHISE_CODE] IN {10, 37}) -- 10 = Mini / 37 BMW Motos
			    )
			VAR __Units = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_1_CODE] = 87, -- Viaturas Novas
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1000, -- Units Sold
			        NOT(VIEW_GBL_DIM_FRANCHISES[FRANCHISE_CODE] IN {10, 37}) -- 10 = Mini / 37 BMW Motos
			    )
			RETURN
			
			DIVIDE(
			    __GrossProfit,
			    __Units
			)
			```
		formatString: #,0
		displayFolder: Archive\Sytner
		lineageTag: 27838db4-894d-4ca3-afea-768f86089956

	measure '_SPL 02 - New Mini GP Average' = ```
			
			
			VAR __GrossProfit = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_1_CODE] = 87, -- Viaturas Novas
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1035, -- Gross Profit II
			        VIEW_GBL_DIM_FRANCHISES[FRANCHISE_CODE] = 10 -- 10 = Mini
			    )
			VAR __Units = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_1_CODE] = 87, -- Viaturas Novas
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1000, -- Units Sold
			        VIEW_GBL_DIM_FRANCHISES[FRANCHISE_CODE] = 10 -- 10 = Mini
			    )
			RETURN
			
			DIVIDE(
			    __GrossProfit,
			    __Units
			)
			```
		formatString: #,0
		displayFolder: Archive\Sytner
		lineageTag: 3b221ae6-632f-43a5-a0dc-69463b89da9c

	measure '_SPL 03 - New Xpeng GP Average' = ```
			
			
			VAR __GrossProfit = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_1_CODE] = 87, -- Viaturas Novas
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1035, -- Gross Profit II
			        VIEW_GBL_DIM_FRANCHISES[FRANCHISE_CODE] = 208 -- Xpeng
			    )
			VAR __Units = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_1_CODE] = 87, -- Viaturas Novas
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1000, -- Units Sold
			        VIEW_GBL_DIM_FRANCHISES[FRANCHISE_CODE] = 208 -- Xpeng
			    )
			RETURN
			
			DIVIDE(
			    __GrossProfit,
			    __Units
			)
			```
		formatString: #,0
		displayFolder: Archive\Sytner
		lineageTag: 13acc5ca-970d-4aee-bef4-8eeb81a58eea

	measure '_SPL 04 - New Dongfeng GP Average' = ```
			
			
			VAR __GrossProfit = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_1_CODE] = 87, -- Viaturas Novas
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1035, -- Gross Profit II
			        VIEW_GBL_DIM_FRANCHISES[FRANCHISE_CODE] = 205 -- Dongfeng
			    )
			VAR __Units = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_1_CODE] = 87, -- Viaturas Novas
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1000, -- Units Sold
			        VIEW_GBL_DIM_FRANCHISES[FRANCHISE_CODE] = 205 -- Dongfeng
			    )
			RETURN
			
			DIVIDE(
			    __GrossProfit,
			    __Units
			)
			```
		formatString: #,0
		displayFolder: Archive\Sytner
		lineageTag: a799f5e0-65bd-44cc-a3d3-710aadab0f74

	measure '_SPL 05 - New Voyah GP Average' = ```
			
			
			VAR __GrossProfit = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_1_CODE] = 87, -- Viaturas Novas
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1035, -- Gross Profit II
			        VIEW_GBL_DIM_FRANCHISES[FRANCHISE_CODE] = 206 -- Voyah
			    )
			VAR __Units = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_1_CODE] = 87, -- Viaturas Novas
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1000, -- Units Sold
			        VIEW_GBL_DIM_FRANCHISES[FRANCHISE_CODE] = 206 -- Voyah
			    )
			RETURN
			
			DIVIDE(
			    __GrossProfit,
			    __Units
			)
			```
		formatString: #,0
		displayFolder: Archive\Sytner
		lineageTag: 53d44944-a6c9-42fe-a4f2-a8b09a7eedb6

	measure '_SPL 06 - Used Retail Cars GP Average' = ```
			
			
			VAR __GrossProfit = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_1_CODE] = 88, -- Viaturas Usadas
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1035, -- Gross Profit II
			        VIEW_NLR_DIM_SALES_TYPES[SALES_TYPE_CODE] = 6, -- Retail (Used Vehicles)
			        VIEW_GBL_DIM_FRANCHISES[FRANCHISE_CODE] <> 37 -- BMW Motos
			    )
			VAR __Units = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_1_CODE] = 88, -- Viaturas Usadas
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1000, -- Units Sold
			        VIEW_NLR_DIM_SALES_TYPES[SALES_TYPE_CODE] = 6, -- Retail (Used Vehicles)
			        VIEW_GBL_DIM_FRANCHISES[FRANCHISE_CODE] <> 37 -- BMW Motos
			    )
			RETURN
			
			DIVIDE(
			    __GrossProfit,
			    __Units
			)
			```
		formatString: #,0
		displayFolder: Archive\Sytner
		lineageTag: c7115f7f-918e-49ac-9403-42997aa420a1

	measure '_SPL 07 - Used Wholesale GP Average' = ```
			
			
			VAR __GrossProfit = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_1_CODE] = 88, -- Viaturas Usadas
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1035, -- Gross Profit II
			        VIEW_NLR_DIM_SALES_TYPES[SALES_TYPE_CODE] = 6, -- Retail (Used Vehicles)
			        VIEW_GBL_DIM_FRANCHISES[FRANCHISE_CODE] <> 37 -- BMW Motos
			    )
			VAR __Units = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_1_CODE] = 88, -- Viaturas Usadas
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1000, -- Units Sold
			        VIEW_NLR_DIM_SALES_TYPES[SALES_TYPE_CODE] = 6, -- Retail (Used Vehicles)
			        VIEW_GBL_DIM_FRANCHISES[FRANCHISE_CODE] <> 37 -- BMW Motos
			    )
			RETURN
			
			DIVIDE(
			    __GrossProfit,
			    __Units
			)
			```
		formatString: #,0
		displayFolder: Archive\Sytner
		lineageTag: 6495c922-1f08-4293-9501-1cb34b667f4b

	measure '_SPL 08 - New Motorcycle GP Average' = ```
			
			
			VAR __GrossProfit = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_1_CODE] = 87, -- Viaturas Novas
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1035, -- Gross Profit II
			        VIEW_GBL_DIM_FRANCHISES[FRANCHISE_CODE] = 37 -- BMW Motos
			    )
			VAR __Units = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_1_CODE] = 87, -- Viaturas Novas
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1000, -- Units Sold
			        VIEW_GBL_DIM_FRANCHISES[FRANCHISE_CODE] = 37 -- BMW Motos
			    )
			RETURN
			
			DIVIDE(
			    __GrossProfit,
			    __Units
			)
			```
		formatString: #,0
		displayFolder: Archive\Sytner
		lineageTag: 1459cd10-4298-4044-a059-533a56f1014c

	measure '_SPL 09 - Used Motorcyle GP Average' = ```
			
			
			VAR __GrossProfit = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_1_CODE] = 88, -- Viaturas Usadas
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1035, -- Gross Profit II
			        VIEW_GBL_DIM_FRANCHISES[FRANCHISE_CODE] = 37 -- BMW Motos
			    )
			VAR __Units = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_1_CODE] = 88, -- Viaturas Usadas
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1000, -- Units Sold
			        VIEW_GBL_DIM_FRANCHISES[FRANCHISE_CODE] = 37 -- BMW Motos
			    )
			RETURN
			
			DIVIDE(
			    __GrossProfit,
			    __Units
			)
			```
		formatString: #,0
		displayFolder: Archive\Sytner
		lineageTag: ce33a28a-c83d-454c-808a-6a445122a2fc

	measure '_SPL 10 - New BMW GP as % of Sales' = ```
			
			
			VAR __GrossProfit = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_1_CODE] = 87, -- Viaturas Novas
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1035, -- Gross Profit II
			        NOT(VIEW_GBL_DIM_FRANCHISES[FRANCHISE_CODE] IN {10, 37}) -- 10 = Mini / 37 BMW Motos
			    )
			VAR __Sales = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_1_CODE] = 87, -- Viaturas Novas
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1010, -- Sales
			        NOT(VIEW_GBL_DIM_FRANCHISES[FRANCHISE_CODE] IN {10, 37}) -- 10 = Mini / 37 BMW Motos
			    )
			RETURN
			
			DIVIDE(
			    __GrossProfit,
			    __Sales
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: Archive\Sytner
		lineageTag: 7e612146-be6b-4d03-a504-ec0ffd713318

	measure '_SPL 11 - New Mini GP as % of Sales' = ```
			
			
			VAR __GrossProfit = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_1_CODE] = 87, -- Viaturas Novas
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1035, -- Gross Profit II
			        VIEW_GBL_DIM_FRANCHISES[FRANCHISE_CODE] = 10 -- 10 = Mini
			    )
			VAR __Sales = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_1_CODE] = 87, -- Viaturas Novas
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1010, -- Sales
			        VIEW_GBL_DIM_FRANCHISES[FRANCHISE_CODE] = 10 -- 10 = Mini
			    )
			RETURN
			
			DIVIDE(
			    __GrossProfit,
			    __Sales
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: Archive\Sytner
		lineageTag: 431e60aa-7c3b-46f9-8b20-cb14ca3f15ef

	measure '_SPL 12 - New Xpeng GP as % of Sales' = ```
			
			
			VAR __GrossProfit = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_1_CODE] = 87, -- Viaturas Novas
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1035, -- Gross Profit II
			        VIEW_GBL_DIM_FRANCHISES[FRANCHISE_CODE] = 208 -- Xpeng
			    )
			VAR __Sales = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_1_CODE] = 87, -- Viaturas Novas
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1010, -- Sales
			        VIEW_GBL_DIM_FRANCHISES[FRANCHISE_CODE] = 208 -- Xpeng
			    )
			RETURN
			
			DIVIDE(
			    __GrossProfit,
			    __Sales
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: Archive\Sytner
		lineageTag: 93e49d4e-898f-4206-b281-3e6a5704b4e1

	measure '_SPL 14 - New VoyahGP as % of Sales' = ```
			
			
			VAR __GrossProfit = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_1_CODE] = 87, -- Viaturas Novas
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1035, -- Gross Profit II
			        VIEW_GBL_DIM_FRANCHISES[FRANCHISE_CODE] = 206 -- Voyah
			    )
			VAR __Sales = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_1_CODE] = 87, -- Viaturas Novas
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1010, -- Sales
			        VIEW_GBL_DIM_FRANCHISES[FRANCHISE_CODE] = 206 -- Voyah
			    )
			RETURN
			
			DIVIDE(
			    __GrossProfit,
			    __Sales
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: Archive\Sytner
		lineageTag: 4cf6ebf0-fa24-4e87-8c91-aba523dfced1

	measure '_SPL 13 - New Dongfeng GP as % of Sales' = ```
			
			
			VAR __GrossProfit = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_1_CODE] = 87, -- Viaturas Novas
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1035, -- Gross Profit II
			        VIEW_GBL_DIM_FRANCHISES[FRANCHISE_CODE] = 205 -- Dongfeng
			    )
			VAR __Sales = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_1_CODE] = 87, -- Viaturas Novas
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1010, -- Sales
			        VIEW_GBL_DIM_FRANCHISES[FRANCHISE_CODE] = 205 -- Dongfeng
			    )
			RETURN
			
			DIVIDE(
			    __GrossProfit,
			    __Sales
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: Archive\Sytner
		lineageTag: 3e9cec36-5fad-43da-b73e-f056736abcbc

	measure '_SPL 15 - Used Retail GP as % of Sales' = ```
			
			
			VAR __GrossProfit = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_1_CODE] = 88, -- Viaturas Usadas
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1035, -- Gross Profit II
			        VIEW_NLR_DIM_SALES_TYPES[SALES_TYPE_CODE] = 6, -- Retail (Used Vehicles)
			        VIEW_GBL_DIM_FRANCHISES[FRANCHISE_CODE] <> 37 -- BMW Motos
			    )
			VAR __Sales = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_1_CODE] = 88, -- Viaturas Usadas
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1010, -- Sales
			        VIEW_NLR_DIM_SALES_TYPES[SALES_TYPE_CODE] = 6, -- Retail (Used Vehicles)
			        VIEW_GBL_DIM_FRANCHISES[FRANCHISE_CODE] <> 37 -- BMW Motos
			    )
			RETURN
			
			DIVIDE(
			    __GrossProfit,
			    __Sales
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: Archive\Sytner
		lineageTag: 77ccdb1a-18c5-417d-85e0-975da2a6a220

	measure '_SPL 16 - Used Wholesale GP as % of Sales' = ```
			
			
			VAR __GrossProfit = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_1_CODE] = 88, -- Viaturas Usadas
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1035, -- Gross Profit II
			        VIEW_NLR_DIM_SALES_TYPES[SALES_TYPE_CODE] = 6, -- Retail (Used Vehicles)
			        VIEW_GBL_DIM_FRANCHISES[FRANCHISE_CODE] <> 37 -- BMW Motos
			    )
			VAR __Sales = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_1_CODE] = 88, -- Viaturas Usadas
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1010, -- Sales
			        VIEW_NLR_DIM_SALES_TYPES[SALES_TYPE_CODE] = 6, -- Retail (Used Vehicles)
			        VIEW_GBL_DIM_FRANCHISES[FRANCHISE_CODE] <> 37 -- BMW Motos
			    )
			RETURN
			
			DIVIDE(
			    __GrossProfit,
			    __Sales
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: Archive\Sytner
		lineageTag: 6517c6c6-1619-4c9f-b1c9-d2cb2105e308

	measure '_SPL 17 - New Motorcycles GP as % of Sales' = ```
			
			
			VAR __GrossProfit = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_1_CODE] = 87, -- Viaturas Novas
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1035, -- Gross Profit II
			        VIEW_GBL_DIM_FRANCHISES[FRANCHISE_CODE] = 37 -- BMW Motos
			    )
			VAR __Sales = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_1_CODE] = 87, -- Viaturas Novas
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1010, -- Sales
			        VIEW_GBL_DIM_FRANCHISES[FRANCHISE_CODE] = 37 -- BMW Motos
			    )
			RETURN
			
			DIVIDE(
			    __GrossProfit,
			    __Sales
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: Archive\Sytner
		lineageTag: ae2293ed-5157-4342-8383-73f6043bb324

	measure '_SPL 18 - Used Motorcycle GP as % of Sales' = ```
			
			
			VAR __GrossProfit = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_1_CODE] = 88, -- Viaturas Usadas
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1035, -- Gross Profit II
			        VIEW_GBL_DIM_FRANCHISES[FRANCHISE_CODE] = 37 -- BMW Motos
			    )
			VAR __Sales = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_1_CODE] = 88, -- Viaturas Usadas
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1010, -- Sales
			        VIEW_GBL_DIM_FRANCHISES[FRANCHISE_CODE] = 37 -- BMW Motos
			    )
			RETURN
			
			DIVIDE(
			    __GrossProfit,
			    __Sales
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: Archive\Sytner
		lineageTag: 8d2709c7-f650-4603-81fb-64ddeda70753

	measure '_SPL 19 - Service GP as % of Sales' = ```
			
			
			VAR __GrossProfit = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_CODE] IN {49, 48, 40}, -- 49 e 48 External Services / 40 Mechanic Labour
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1035, -- Gross Profit II
			        VIEW_GBL_DIM_FRANCHISES[FRANCHISE_CODE] <> 37 -- BMW Motos
			    )
			VAR __Sales = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_CODE] IN {49, 48, 40}, -- 49 e 48 External Services / 40 Mechanic Labour
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1010, -- Sales
			        VIEW_GBL_DIM_FRANCHISES[FRANCHISE_CODE] <> 37 -- BMW Motos
			    )
			RETURN
			
			DIVIDE(
			    __GrossProfit,
			    __Sales
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: Archive\Sytner
		lineageTag: 71a8b85d-0333-45ef-88a6-644d381be86d

	measure '_SPL 20 - Bodyshop GP as % of Sales' = ```
			
			
			VAR __GrossProfit = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_CODE] IN {45, 44, 49, 48}, -- 45 e 44 Bodyshop Labour / 49 e 48 External Services
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1035 -- Gross Profit II
			    )
			VAR __Sales = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_CODE] IN {45, 44, 49, 48}, -- 45 e 44 Bodyshop Labour / 49 e 48 External Services
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1010 -- Sales
			    )
			RETURN
			
			DIVIDE(
			    __GrossProfit,
			    __Sales
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: Archive\Sytner
		lineageTag: 136c570b-5e81-4e5b-a0c4-ce9af26b9710

	measure '_SPL 21 - Motorcycle Repair GP as % of Sales' = ```
			
			
			VAR __GrossProfit = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_CODE] IN {40, 49, 48}, -- 49 e 48 External Services / 40 Mechanic Labour
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1035, -- Gross Profit II
			        VIEW_GBL_DIM_FRANCHISES[FRANCHISE_CODE] = 37 -- 37 BMW Motos
			    )
			VAR __Sales = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_CODE] IN {40, 49, 48}, -- 49 e 48 External Services / 40 Mechanic Labour
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1010, -- Sales
			        VIEW_GBL_DIM_FRANCHISES[FRANCHISE_CODE] = 37 -- 37 BMW Motos
			    )
			RETURN
			
			DIVIDE(
			    __GrossProfit,
			    __Sales
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: Archive\Sytner
		lineageTag: 8f75f5e6-0167-475a-8336-cf8189e058e9

	measure 'Sytner KPIs CY' =
			
			
			SWITCH(
			    SELECTEDVALUE(VIEW_NLR_DIM_SYTNER_PL_KPIS[SYTNER_PL_KPI_CODE]),
			    1, [_SPL 01 - New BMW GP Average],
			    2, [_SPL 02 - New Mini GP Average],
			    3, [_SPL 03 - New Xpeng GP Average],
			    4, [_SPL 04 - New Dongfeng GP Average],
			    5, [_SPL 05 - New Voyah GP Average],
			    6, [_SPL 06 - Used Retail Cars GP Average],
			    7, [_SPL 07 - Used Wholesale GP Average],
			    8, [_SPL 08 - New Motorcycle GP Average],
			    9, [_SPL 09 - Used Motorcyle GP Average],
			    10, [_SPL 10 - New BMW GP as % of Sales],
			    11, [_SPL 11 - New Mini GP as % of Sales],
			    12, [_SPL 12 - New Xpeng GP as % of Sales],
			    13, [_SPL 13 - New Dongfeng GP as % of Sales],
			    14, [_SPL 14 - New VoyahGP as % of Sales],
			    15, [_SPL 15 - Used Retail GP as % of Sales],
			    16, [_SPL 16 - Used Wholesale GP as % of Sales],
			    17, [_SPL 17 - New Motorcycles GP as % of Sales],
			    18, [_SPL 18 - Used Motorcycle GP as % of Sales],
			    19, [_SPL 19 - Service GP as % of Sales],
			    20, [_SPL 20 - Bodyshop GP as % of Sales],
			    21, [_SPL 21 - Motorcycle Repair GP as % of Sales],
			    22, [_SPL 22 - Parts GP as % of Sales],
			    23, [_SPL 23 - Total Comp as % of Total GP],
			    24, [_SPL 24 - Variable Commissions as % of Vehicle GP],
			    25, [_SPL 25 - Rent as % of Sales],
			    26, [_SPL 26 - Advertising per Unit (Euro)],
			    27, [_SPL 27 - Pretax Income as % of GP],
			    28, [_SPL 28 - Pretax Income as % of Sales]
			)
		displayFolder: Archive\Sytner\CY
		lineageTag: 8ae8000b-9f48-4190-b307-76802cfc3847

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_SPL 22 - Parts GP as % of Sales' = ```
			
			
			VAR __GrossProfit = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        (VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_1_CODE] = 85 && VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_3_CODE] IN {137, 141, 255}) || VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_1_CODE] = 86, -- Workshop Parts / Parts
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1035 -- Gross Profit II
			    )
			VAR __Sales = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        (VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_1_CODE] = 85 && VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_3_CODE] IN {137, 141, 255}) || VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_1_CODE] = 86, -- Workshop Parts / Parts
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1010 -- Sales
			    )
			RETURN
			
			DIVIDE(
			    __GrossProfit,
			    __Sales
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: Archive\Sytner
		lineageTag: a02b5757-de92-4157-988f-0577eb64245c

	measure '_SPL 24 - Variable Commissions as % of Vehicle GP' = ```
			
			
			VAR __VariableComissions = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_CODE] = 15 -- Variable Commissions
			    )
			VAR __VehiclesGP = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_ACTIVITIES[ACTIVITY_LEVEL_3_CODE] = 234, -- Vehicles
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1035 -- Gross Profit II
			    )
			RETURN
			
			DIVIDE(
			    __VariableComissions,
			    __VehiclesGP
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: Archive\Sytner
		lineageTag: 6b0f803f-cf83-4e5b-a6ce-304fcc0248ed

	measure '_SPL 25 - Rent as % of Sales' = ```
			
			
			VAR __Rents = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_CODE] = 15 -- Variable Commissions
			    )
			VAR __Sales = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1010 -- Sales
			    )
			RETURN
			
			DIVIDE(
			    __Rents,
			    __Sales
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: Archive\Sytner
		lineageTag: c7c37b02-eac0-49f6-80f3-8bb62b619e06

	measure '_SPL 23 - Total Comp as % of Total GP' = ```
			
			
			VAR __CPS = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_CODE] = 1015 -- Costs of Sales
			    )
			VAR __GrossProfit = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1035 -- Gross Profit II
			    )
			RETURN
			
			DIVIDE(
			    __CPS,
			    __GrossProfit
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: Archive\Sytner
		lineageTag: ed5ca37d-0303-4da5-a7a1-f380d40a3165

	measure '_SPL 26 - Advertising per Unit (Euro)' = ```
			
			
			VAR __Marketing = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_CODE] = 22 -- Marketing
			    )
			VAR __Units = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_CODE] = 1 -- Units
			    )
			RETURN
			
			DIVIDE(
			    __Marketing,
			    __Units
			)
			```
		formatString: #,0
		displayFolder: Archive\Sytner
		lineageTag: 108c2cac-d1b9-4d2e-a6e2-de64dd97e76a

	measure '_SPL 27 - Pretax Income as % of GP' = ```
			
			
			VAR __IBT = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_CODE] = 1085 -- Income Before Taxes
			    )
			VAR __GrossProfit = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1035 -- Gross Profit II
			    )
			RETURN
			
			DIVIDE(
			    __IBT,
			    __GrossProfit
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: Archive\Sytner
		lineageTag: 7c7751cb-4a25-4402-a654-e7cd48ab22b4

	measure '_SPL 28 - Pretax Income as % of Sales' = ```
			
			
			VAR __IBT = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_CODE] = 1085 -- Income Before Taxes
			    )
			VAR __Sales = 
			    CALCULATE(
			        SUM(VIEW_NLR_FACT_BI_TRANS_PL[SYTNER_VALUE]),
			        VIEW_NLR_DIM_SYTNER_PL[SYTNER_PL_LEVEL_1_CODE] = 1010 -- Sales
			    )
			RETURN
			
			DIVIDE(
			    __IBT,
			    __Sales
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: Archive\Sytner
		lineageTag: 6aeb52dd-1a70-4b1e-985a-c992d41ab5bc

	measure '_GM Origin' = ```
			
			
			 SWITCH(
			     SELECTEDVALUE(VIEW_NLR_DIM_GM_MEASURES[GM_MEASURE_CODE]),
			    
			     -- Rúbricas calculadas
			     101, [_GM 101 Financial Autonomy Ratio],
			     102, [_GM 102 - Asset Turnover],
			     103, [_GM 103 - Sales Profitability],
			     104, [_GM 104 - Average Collection Period],
			     105, [_GM 105 - Average Collection Period 3M],
			     106, [_GM 106 - Average Collection Period 12M],
			     107, [_GM 107 - Average Days in Inventory],
			     108, [_GM 108 - Average Days in Inventory 3M],
			     109, [_GM 109 - Average Days in Inventory 12M],
			     110, [_GM 110 - Average Days Payable],
			     111, [_GM 111 - Average Days Payable 3M],
			     112, [_GM 112 - Average Days Payable 12M],
			     113, [_GM 113 - Cash Conversion Cycle],
			     114, [_GM 114 - Net Debt / EBITDA],
			     115, [_GM 115 - Net Debt / EBITDA 12M],
			     116, [_GM 116 - Return on Equity],
			     117, [_GM 117 - Leverage Ratio],
			
			     -- Rúbricas de valor
			     SUM(VIEW_NLR_FACT_GM[GM_VALUE])
			 )
			```
		formatString: #,0.00
		displayFolder: FIN\GM\LC\Support Measures
		lineageTag: 984b8d95-1b52-4f8e-b7b0-4b7433c726e4

		changedProperty = IsHidden

	measure 'Cabeçalhos Debt' =
			
			CALCULATE(
			    SUM(VIEW_SLR_FACT_OPEN_DOCUMENTS[OPEN_VALUE]),
			    ALL(CALCGROUP_CURRENCY),
			    REMOVEFILTERS(CALCGROUP_CURRENCY)
			)
		isHidden
		displayFolder: _UI\Cabeçalhos
		lineageTag: eb934790-aea8-4c19-9aea-3cef36ff15ae

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'VHE Sales CY' = ```
			
			
			VAR __Indicator =
			    CALCULATE(
			        ISFILTERED(VIEW_VHE_DIM_MEASURES),
			        REMOVEFILTERS(VIEW_VHE_DIM_MEASURES[MEASURE_HIDDEN])
			    )
			RETURN
			
			IF(
			    __Indicator,
			    SWITCH(
			            SELECTEDVALUE(VIEW_VHE_DIM_MEASURES[MEASURE_CODE]),
			                -- Rúbricas calculadas
			                9962, [Gross Margin After Commissions and Others %],
			                9963, [Gross Margin % (Turnover/Sales)],
			                9964, [Gross Margin %],
			                9965, [Variable Margin %],
			                9966, [Variable Margin - Importer %],
			                9967, [Fixed Margin %],
			                9968, [Campaigns/Incentives %],
			                9969, [Invoice Discount %],
			                9970, [Net Discount %],
			                    
			                -- Rúbricas de valor
			
			                SWITCH(
			                    TRUE(),
			
			                    -- Level 3
			                    ISINSCOPE(VIEW_VHE_DIM_MEASURES[PT_MEASURE_LEVEL_3_DESC]) ||
			                    ISINSCOPE(VIEW_VHE_DIM_MEASURES[EN_MEASURE_LEVEL_3_DESC]) ||
			                    ISINSCOPE(VIEW_VHE_DIM_MEASURES[ES_MEASURE_LEVEL_3_DESC]) ||
			                    ISINSCOPE(VIEW_VHE_DIM_MEASURES[FR_MEASURE_LEVEL_3_DESC]),
			                    CALCULATE(
			                        SUM(VIEW_VHE_FACT_SALES[VALUE]),
			                        VIEW_VHE_DIM_MEASURES[REPORT_LEVEL] = 3
			                    ),
			
			                    -- Level 2
			                    ISINSCOPE(VIEW_VHE_DIM_MEASURES[PT_MEASURE_LEVEL_2_DESC]) ||
			                    ISINSCOPE(VIEW_VHE_DIM_MEASURES[EN_MEASURE_LEVEL_2_DESC]) ||
			                    ISINSCOPE(VIEW_VHE_DIM_MEASURES[ES_MEASURE_LEVEL_2_DESC]) ||
			                    ISINSCOPE(VIEW_VHE_DIM_MEASURES[FR_MEASURE_LEVEL_2_DESC]),
			                    CALCULATE(
			                        SUM(VIEW_VHE_FACT_SALES[VALUE]),
			                        VIEW_VHE_DIM_MEASURES[REPORT_LEVEL] = 2 || ISBLANK(VIEW_VHE_DIM_MEASURES[PARENT_MEASURE_CODE])
			                    ),
			
			                    -- Level 1
			                    ISINSCOPE(VIEW_VHE_DIM_MEASURES[PT_MEASURE_LEVEL_1_DESC]) ||
			                    ISINSCOPE(VIEW_VHE_DIM_MEASURES[EN_MEASURE_LEVEL_1_DESC]) ||
			                    ISINSCOPE(VIEW_VHE_DIM_MEASURES[ES_MEASURE_LEVEL_1_DESC]) ||
			                    ISINSCOPE(VIEW_VHE_DIM_MEASURES[FR_MEASURE_LEVEL_1_DESC]),
			                    CALCULATE(
			                        SUM(VIEW_VHE_FACT_SALES[VALUE]),
			                        VIEW_VHE_DIM_MEASURES[REPORT_LEVEL] = 1 || ISBLANK(VIEW_VHE_DIM_MEASURES[PARENT_MEASURE_CODE])
			                    )
			                )
			        ),
			    -- Se não houver nenhum indicador selecionado, retornará as quantidades.    
			    CALCULATE(
			        SUM(VIEW_VHE_FACT_SALES[VALUE]),
			        VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9973
			    )
			)
			```
		displayFolder: VHE\SALES\LC\Real
		lineageTag: 825187b3-ebf0-45af-8af5-98e125f3d1a7

		formatStringDefinition =
				IF(
				    SELECTEDVALUE(VIEW_VHE_DIM_MEASURES[FORMAT_TYPE]) = "%" ,
				    "#,##0.0%",
				    "#,###,###,###,###"
				)

	measure 'VHE Sales Bgt' =
			
			
			CALCULATE(
			    [VHE Sales Bgt Origin],
			    VIEW_GBL_DIM_VALUE_TYPES_ALL[VALUE_TYPE_CODE] = 3
			)
		displayFolder: VHE\SALES\LC\Budget
		lineageTag: 58b7e302-eac3-422e-a4e0-d2ec9b62e465

		formatStringDefinition =
				IF(
				    SELECTEDVALUE(VIEW_VHE_DIM_MEASURES[FORMAT_TYPE]) = "%" ,
				    "#,##0.0%",
				    "#,###,###,###,###"
				)

	measure 'VHE Sales Bgt Adm' =
			
			
			CALCULATE(
			    [VHE Sales Bgt Origin],
			    VIEW_GBL_DIM_VALUE_TYPES_ALL[VALUE_TYPE_CODE] = 4
			)
		displayFolder: VHE\SALES\LC\Budget
		lineageTag: 13539415-c84c-4a0d-a52b-40342de455b7

		formatStringDefinition =
				IF(
				    SELECTEDVALUE(VIEW_VHE_DIM_MEASURES[FORMAT_TYPE]) = "%" ,
				    "#,##0.0%",
				    "#,###,###,###,###"
				)

	measure 'VHE Sales LY' =
			
			CALCULATE(
			    [VHE Sales CY],
			    SAMEPERIODLASTYEAR(VIEW_GBL_DIM_CALENDAR[DATE])
			)
		displayFolder: VHE\SALES\LC\Real
		lineageTag: bd7da8cc-da39-4e90-b79f-e9685ef6383c

		formatStringDefinition =
				IF(
				    SELECTEDVALUE(VIEW_VHE_DIM_MEASURES[FORMAT_TYPE]) = "%" ,
				    "#,##0.0%",
				    "#,###,###,###,###"
				)

	measure 'VHE Sales Delta LY %' =
			
			
			VAR __ly = [VHE Sales LY]
			VAR __delta = [VHE Sales CY] - __ly
			
			RETURN
			DIVIDE(
			    TRUNC(__delta),
			    TRUNC(__ly)
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: VHE\SALES\LC\Real
		lineageTag: 48d7d6f5-0c1a-4f31-b7fc-eecc01ebd1bd

	measure 'VHE Sales Delta Bgt %' =
			
			
			VAR __Bgt = [VHE Sales Bgt]
			VAR __delta = [VHE Sales CY] - __Bgt
			
			RETURN
			DIVIDE(
			    TRUNC(__delta),
			    TRUNC(__Bgt)
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: VHE\SALES\LC\Budget
		lineageTag: 45bec46e-0d2e-462c-ac0d-10659280af21

	measure 'VHE Sales Delta Bgt Adm %' = ```
			
			
			VAR __Bgt  = [VHE Sales Bgt Adm]
			VAR __delta = [VHE Sales CY] - __Bgt 
			
			RETURN
			DIVIDE(
			    TRUNC(__delta),
			    TRUNC(__Bgt)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: VHE\SALES\LC\Budget
		lineageTag: 8c6f3a40-3a62-48f5-85c2-c0a7b71150b1

	measure 'VHE Sales CY (EUR)' = ```
			
			
			VAR __Indicator =
			    CALCULATE(
			        ISFILTERED(VIEW_VHE_DIM_MEASURES),
			        REMOVEFILTERS(VIEW_VHE_DIM_MEASURES[MEASURE_HIDDEN])
			    )
			RETURN
			
			IF(
			    __Indicator, 
			    SWITCH(
			        SELECTEDVALUE(VIEW_VHE_DIM_MEASURES[MEASURE_CODE]),
			            -- Rúbricas calculadas
			            9962, [Gross Margin After Commissions and Others (EUR) %],
			            9963, [Gross Margin (EUR) % (Turnover/Sales)],
			            9964, [Gross Margin (EUR) %],
			            9965, [Variable Margin (EUR) %],
			            9966, [Variable Margin - Importer (EUR) %],
			            9967, [Fixed Margin (EUR) %],
			            9968, [Campaigns/Incentives (EUR) %],
			            9969, [Invoice Discount (EUR) %],
			            9970, [Net Discount (EUR) %],
			                
			            -- Rúbricas de valor
			            SWITCH(
			                TRUE(),
			                -- Level 3
			                ISINSCOPE(VIEW_VHE_DIM_MEASURES[PT_MEASURE_LEVEL_3_DESC]) ||
			                ISINSCOPE(VIEW_VHE_DIM_MEASURES[EN_MEASURE_LEVEL_3_DESC]) ||
			                ISINSCOPE(VIEW_VHE_DIM_MEASURES[ES_MEASURE_LEVEL_3_DESC]) ||
			                ISINSCOPE(VIEW_VHE_DIM_MEASURES[FR_MEASURE_LEVEL_3_DESC]),
			                SUMX(
			                    FILTER(
			                        SUMMARIZECOLUMNS(
			                            VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY],
			                            VIEW_VHE_DIM_MEASURES[REPORT_LEVEL],
			                            "TOTAL", SUM(VIEW_VHE_FACT_SALES[VALUE])
			                        ),
			                        VIEW_VHE_DIM_MEASURES[REPORT_LEVEL] = 3
			                    ),
			                    DIVIDE(
			                        [TOTAL],
			                        COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY]), 1)
			                    )
			                ),
			
			                -- Level 2
			                ISINSCOPE(VIEW_VHE_DIM_MEASURES[PT_MEASURE_LEVEL_2_DESC]) ||
			                ISINSCOPE(VIEW_VHE_DIM_MEASURES[EN_MEASURE_LEVEL_2_DESC]) ||
			                ISINSCOPE(VIEW_VHE_DIM_MEASURES[ES_MEASURE_LEVEL_2_DESC]) ||
			                ISINSCOPE(VIEW_VHE_DIM_MEASURES[FR_MEASURE_LEVEL_2_DESC]),
			                SUMX(
			                    FILTER(
			                        SUMMARIZECOLUMNS(
			                            VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY],
			                            VIEW_VHE_DIM_MEASURES[REPORT_LEVEL],
			                            VIEW_VHE_DIM_MEASURES[PARENT_MEASURE_CODE],
			                            "TOTAL", SUM(VIEW_VHE_FACT_SALES[VALUE])
			                        ),
			                        VIEW_VHE_DIM_MEASURES[REPORT_LEVEL] = 2 || ISBLANK(VIEW_VHE_DIM_MEASURES[PARENT_MEASURE_CODE])
			                    ),
			                    DIVIDE(
			                        [TOTAL],
			                        COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY]), 1)
			                    )
			                ),
			
			                -- Level 1
			                ISINSCOPE(VIEW_VHE_DIM_MEASURES[PT_MEASURE_LEVEL_1_DESC]) ||
			                ISINSCOPE(VIEW_VHE_DIM_MEASURES[EN_MEASURE_LEVEL_1_DESC]) ||
			                ISINSCOPE(VIEW_VHE_DIM_MEASURES[ES_MEASURE_LEVEL_1_DESC]) ||
			                ISINSCOPE(VIEW_VHE_DIM_MEASURES[FR_MEASURE_LEVEL_1_DESC]),
			                SUMX(
			                    FILTER(
			                        SUMMARIZECOLUMNS(
			                            VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY],
			                            VIEW_VHE_FACT_SALES[VALUE_TYPE_CODE],
			                            VIEW_VHE_DIM_MEASURES[REPORT_LEVEL],
			                            VIEW_VHE_DIM_MEASURES[PARENT_MEASURE_CODE],
			                            "TOTAL", SUM(VIEW_VHE_FACT_SALES[VALUE])
			                        ),
			                        VIEW_VHE_DIM_MEASURES[REPORT_LEVEL] = 1 || ISBLANK(VIEW_VHE_DIM_MEASURES[PARENT_MEASURE_CODE])
			                    ),
			                    DIVIDE(
			                        [TOTAL],
			                        COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY]), 1)
			                    )
			                )
			        )
			    ),
			    -- Se não houver nenhum indicador selecionado, retornará as quantidades.  
			    SUMX(
			        FILTER(
			            SUMMARIZECOLUMNS(
			                VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY],
			                VIEW_VHE_FACT_SALES[VALUE_TYPE_CODE],
			                VIEW_VHE_DIM_MEASURES[MEASURE_CODE],
			                "TOTAL", SUM(VIEW_VHE_FACT_SALES[VALUE])
			            ),
			            VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9973
			        ),
			        DIVIDE(
			            [TOTAL],
			            COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY]), 1)
			        )
			    )
			)
			```
		isHidden
		displayFolder: VHE\SALES\EUR\Real
		lineageTag: 65097946-40c2-449d-a9d3-4cbfaec2dfd8

		formatStringDefinition =
				IF(
				    SELECTEDVALUE(VIEW_VHE_DIM_MEASURES[FORMAT_TYPE]) = "%" ,
				    "#,##0.0%",
				    "#,###,###,###,###"
				)

		changedProperty = IsHidden

	measure 'VHE Sales LY (EUR)' =
			
			CALCULATE(
			    [VHE Sales CY (EUR)],
			    SAMEPERIODLASTYEAR(VIEW_GBL_DIM_CALENDAR[DATE])
			)
		isHidden
		displayFolder: VHE\SALES\EUR\Real
		lineageTag: a81617ee-d18c-463a-bc4c-25854329822c

		formatStringDefinition =
				IF(
				    SELECTEDVALUE(VIEW_VHE_DIM_MEASURES[FORMAT_TYPE]) = "%" ,
				    "#,##0.0%",
				    "#,###,###,###,###"
				)

		changedProperty = IsHidden

	measure 'VHE Sales Bgt (EUR)' =
			
			
			CALCULATE(
			    [VHE Sales Bgt Origin (EUR)],
			    VIEW_GBL_DIM_VALUE_TYPES_ALL[VALUE_TYPE_CODE] = 3
			)
		isHidden
		displayFolder: VHE\SALES\EUR\Budget
		lineageTag: 24df7d71-2a8d-4f70-b659-c29d3afbb2de

		formatStringDefinition =
				IF(
				    SELECTEDVALUE(VIEW_VHE_DIM_MEASURES[FORMAT_TYPE]) = "%" ,
				    "#,##0.0%",
				    "#,###,###,###,###"
				)

		changedProperty = IsHidden

	measure 'VHE Sales Bgt Adm (EUR)' =
			
			
			CALCULATE(
			    [VHE Sales Bgt Origin (EUR)],
			    VIEW_GBL_DIM_VALUE_TYPES_ALL[VALUE_TYPE_CODE] = 4
			)
		isHidden
		displayFolder: VHE\SALES\EUR\Budget
		lineageTag: abc8c7f6-3b35-4bd9-966f-45f687755c91

		formatStringDefinition =
				IF(
				    SELECTEDVALUE(VIEW_VHE_DIM_MEASURES[FORMAT_TYPE]) = "%" ,
				    "#,##0.0%",
				    "#,###,###,###,###"
				)

		changedProperty = IsHidden

	measure 'VHE Sales Delta Bgt (EUR) %' =
			
			
			VAR __Bgt = [VHE Sales Bgt (EUR)]
			VAR __delta = [VHE Sales CY (EUR)] - __Bgt
			
			RETURN
			DIVIDE(
			    TRUNC(__delta),
			    TRUNC(__Bgt)
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\SALES\EUR\Budget
		lineageTag: c2ca2320-9c3b-4a2d-8dfd-f667a6be1c04

		changedProperty = IsHidden

	measure 'VHE Sales Delta Bgt Adm (EUR) %' =
			
			
			VAR __Bgt = [VHE Sales Bgt Adm (EUR)]
			VAR __delta = [VHE Sales CY (EUR)] - __Bgt
			
			RETURN
			DIVIDE(
			    TRUNC(__delta),
			    TRUNC(__Bgt)
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\SALES\EUR\Budget
		lineageTag: 818daf5a-6c53-4f7c-a0c4-0b6b8cb157d3

		changedProperty = IsHidden

	measure 'VHE Sales Delta LY (EUR) %' =
			
			
			VAR __ly = [VHE Sales LY (EUR)]
			VAR __delta = [VHE Sales CY (EUR)] - __ly
			
			RETURN
			DIVIDE(
			    TRUNC(__delta),
			    TRUNC(__ly)
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\SALES\EUR\Real
		lineageTag: 658ceefa-a46d-4152-9d2e-c8f90796c79a

		changedProperty = IsHidden

	measure 'Indicators VHE Sales' = ```
			
			
			SWITCH(
			    SELECTEDVALUE(PARAMETER_VHE_SALES_INDICADORES[Id]),
			    1, [VHE Sales CY],
			    2, [VHE Sales Bgt],
			    3, [VHE Sales Delta Bgt %],    
			    4, [VHE Sales Bgt Adm],
			    5, [VHE Sales Delta Bgt Adm %],
			    6, [VHE Sales LY],
			    7, [VHE Sales Delta LY %]
			)
			```
		isHidden
		displayFolder: VHE\SALES\LC\Support Measures
		lineageTag: f5b416a6-cf92-4770-894a-3109f62e5972

		formatStringDefinition =
				SWITCH(
				    SELECTEDVALUE(PARAMETER_VHE_SALES_INDICADORES[Id]),
				    1, "#,###,###,###,###",
				    2, "#,###,###,###,###",
				    3, "#,##0.0%",
				    4, "#,###,###,###,###",
				    5, "#,##0.0%",
				    6, "#,###,###,###,###",
				    7, "#,##0.0%"
				)

		changedProperty = IsHidden

	measure 'Indicators VHE Sales (EUR)' = ```
			
			
			SWITCH(
			    SELECTEDVALUE(PARAMETER_VHE_SALES_INDICADORES[Id]),
			    1, [VHE Sales CY (EUR)],
			    2, [VHE Sales Bgt (EUR)],
			    3, [VHE Sales Delta Bgt (EUR) %],    
			    4, [VHE Sales Bgt Adm (EUR)],
			    5, [VHE Sales Delta Bgt Adm (EUR) %],
			    6, [VHE Sales LY (EUR)],
			    7, [VHE Sales Delta LY (EUR) %]
			)
			```
		isHidden
		displayFolder: VHE\SALES\EUR\Support Measures
		lineageTag: e3addfaf-f38d-4468-8373-31720c513ec7

		formatStringDefinition =
				SWITCH(
				    SELECTEDVALUE(PARAMETER_VHE_SALES_INDICADORES[Id]),
				    1, "#,###,###,###,###",
				    2, "#,###,###,###,###",
				    3, "#,##0.0%",
				    4, "#,###,###,###,###",
				    5, "#,##0.0%",
				    6, "#,###,###,###,###",
				    7, "#,##0.0%"
				)

		changedProperty = IsHidden

	measure 'Cabeçalhos VHE SALES' =
			
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES[VALUE]) + SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE]),
			    ALL(CALCGROUP_CURRENCY),
			    REMOVEFILTERS(CALCGROUP_CURRENCY)
			)
		isHidden
		displayFolder: _UI\Cabeçalhos
		lineageTag: 0868ad5c-b2f9-4c3f-afbd-892b8707090f

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Title - GM' =
			
			
			SWITCH(
			    LEFT(SELECTEDVALUE(VIEW_GBL_DIM_USER_CULTURE[USER_CULTURE]), 2),
			    "pt", "Indicadores Gerais",
			    "en", "KPIs/General Indicators",
			    "es", "Indicadores Generales",
			    "fr", "Indicateurs Généraux",
			    "KPIs/General Indicators"
			)
		isHidden
		displayFolder: _UI\Titles
		lineageTag: 451bf144-8408-48ac-8c17-c22f2a88c3fa

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Closed Period Label' =
			
			
			SWITCH(
			    SELECTEDVALUE(VIEW_GBL_DIM_USER_CULTURE[USER_CULTURE]),
			    "pt-PT", SELECTEDVALUE(VIEW_NLR_DIM_CLOSED_PERIODS[PT_CLOSED_PERIOD_DESC], "Todos os Períodos"),
			    "en-US", SELECTEDVALUE(VIEW_NLR_DIM_CLOSED_PERIODS[EN_CLOSED_PERIOD_DESC], "All Periods"),
			    "es-ES", SELECTEDVALUE(VIEW_NLR_DIM_CLOSED_PERIODS[ES_CLOSED_PERIOD_DESC], "Todos los Períodos"),
			    "fr-FR", SELECTEDVALUE(VIEW_NLR_DIM_CLOSED_PERIODS[FR_CLOSED_PERIOD_DESC], "Toutes les Périodes")
			)
		isHidden
		displayFolder: _UI\Titles
		lineageTag: 43c394eb-b7fa-4bf8-a210-ba8b1752d0d8

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Closed Period Title' =
			
			
			SWITCH(
			    SELECTEDVALUE(VIEW_GBL_DIM_USER_CULTURE[USER_CULTURE]),
			    "pt-PT", "Períodos",
			    "en-US", "Periods",
			    "es-ES", "Períodos",
			    "fr-FR", "Périodes"
			)
		isHidden
		displayFolder: _UI\Titles
		lineageTag: 6686fa34-2728-4537-9b10-ed6f00161d3d

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Debt Suppliers' = SUM(VIEW_PLR_FACT_OPEN_DOCUMENTS[OPEN_VALUE])
		formatString: #,0
		displayFolder: FIN\DEBT SUPPLIERS\LC\Real
		lineageTag: 3fb58a98-a38a-4256-b9fb-b2c9505f275e

	measure 'Debt Suppliers (EUR)' = ```
			
			 SUMX(
			     SUMMARIZECOLUMNS(
			         VIEW_PLR_FACT_OPEN_DOCUMENTS[CURRENCY_RATE_KEY],
			         "BALANCE", SUM(VIEW_PLR_FACT_OPEN_DOCUMENTS[OPEN_VALUE])
			     ),
			     DIVIDE([BALANCE],
			     COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_EOM], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_PLR_FACT_OPEN_DOCUMENTS[CURRENCY_RATE_KEY]), 1)
			     )
			 )
			```
		formatString: #,0
		isHidden
		displayFolder: FIN\DEBT SUPPLIERS\EUR\Real
		lineageTag: 05fb77f7-18b6-4fb2-9971-0f780e2b2a1d

		changedProperty = IsHidden

	measure 'Cabeçalhos Debt Suppliers' =
			
			CALCULATE(
			    SUM(VIEW_PLR_FACT_OPEN_DOCUMENTS[OPEN_VALUE]),
			    ALL(CALCGROUP_CURRENCY),
			    REMOVEFILTERS(CALCGROUP_CURRENCY)
			)
		isHidden
		displayFolder: _UI\Cabeçalhos
		lineageTag: 82731368-89ce-4424-aa23-c650c0fafbde

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Title - Matrix BL IFRS' =
			
			
			SWITCH(
			    LEFT(SELECTEDVALUE(VIEW_GBL_DIM_USER_CULTURE[USER_CULTURE]), 2),
			    "pt", "Balanço Oficial IFRS",
			    "en", "Official Balance IFRS",
			    "es", "Balance Oficial IFRS",
			    "fr", "Bilan Officiel IFRS",
			    "Official Balance IFRS"
			)
		isHidden
		displayFolder: _UI\Format
		lineageTag: d06a377c-e823-4d9c-82c8-8bee271bafd8

		changedProperty = IsHidden

	measure 'Conditional Format - DRPL Indicators' = ```
			
			
			IF(
			    SELECTEDVALUE('PARAMETER_DRPL_INDICADORES'[Id]) IN {5, 9, 13},
			    [Indicators DR PL]
			)
			
			
			--    1 = DR PL CY
			--    2 = DR PL CY %
			--    3 = DR PL Bgt
			--    4 = DR PL Bgt %
			--    5 = DR PL Delta Bgt
			--    6 = DR PL Delta Bgt % 
			--    7 = DR PL Bgt Adm
			--    8 = DR PL Bgt Adm %
			--    9 = DR PL Delta Bgt Adm
			--    10 = DR PL Delta Bgt Adm %
			--    11 = DR PL LY
			--    12 = DR PL LY %
			--    13 = DR PL Delta LY
			--    14 = DR PL Delta LY %]
			```
		isHidden
		displayFolder: _UI\Format
		lineageTag: 3f4ca99c-6d8c-4ba2-b15e-0f74fad67621

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Conditional Format - BL IFRS Indicators' =
			
			
			IF(
			    SELECTEDVALUE('PARAMETER_BL_IFRS_INDICADORES'[Id]) IN {5, 9, 13},
			    [Indicators BL IFRS]
			)
			
			
			--    1 = BL IFRS CY
			--    2 = BL IFRS CY %
			--    3 = BL IFRS Bgt
			--    4 = BL IFRS Bgt %
			--    5 = BL IFRS Delta Bgt
			--    6 = BL IFRS Delta Bgt %
			--    7 = BL IFRS Bgt Adm
			--    8 = BL IFRS Bgt Adm %
			--    9 = BL IFRS Delta Bgt Adm
			--    10 = BL IFRS Delta Bgt Adm %
			--    11 = BL IFRS LY
			--    12 = BL IFRS LY %
			--    13 = BL IFRS Delta LY
			--    14 = BL IFRS Delta LY %
		isHidden
		displayFolder: _UI\Format
		lineageTag: d5aa386k-e823-4d9c-82c8-8bee271bafd8

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Variable Margin - Importer %' = ```
			
			VAR __VariableMargin = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9993
			)
			
			VAR __VariableMarginDivisor =
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES[VALUE]),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9974
			)
			
			RETURN
			DIVIDE(
			    __VariableMargin,
			    ABS(__VariableMarginDivisor)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\SALES\LC\Support Measures\Real
		lineageTag: 0af1720f-fdf5-44bf-a094-df0e3902d47f

		changedProperty = IsHidden

	measure 'Net Discount %' = ```
			
			VAR __VendaISV = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 4
			)
			
			VAR __Net_Discount = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9983
			)
			
			VAR __TotalSales = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9982
			)
			
			RETURN
			DIVIDE(
			    __Net_Discount,
			    ABS(__TotalSales - __VendaISV)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\SALES\LC\Support Measures\Real
		lineageTag: 0a5a4e0a-cd14-49b5-9499-b2c34921e483

		changedProperty = IsHidden

	measure 'Invoice Discount %' = ```
			
			VAR __VendaISV = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 4
			)
			
			VAR __Invoice_Discount = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9
			)
			
			VAR __TotalSales = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9982
			)
			
			RETURN
			DIVIDE(
			    __Invoice_Discount,
			    ABS(__TotalSales - __VendaISV)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\SALES\LC\Support Measures\Real
		lineageTag: dc42e7df-239a-4485-9b2f-4a3419106dfe

		changedProperty = IsHidden

	measure 'Campaigns/Incentives %' = ```
			
			VAR __VendaISV = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 4
			)
			
			VAR __Campaigns = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9985
			)
			
			VAR __TotalSales = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9982
			)
			
			RETURN
			DIVIDE(
			    __Campaigns,
			    ABS(__TotalSales - __VendaISV)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\SALES\LC\Support Measures\Real
		lineageTag: 7b3b0bc6-ea93-4346-aa56-43f22d49c4f3

		changedProperty = IsHidden

	measure 'Fixed Margin %' = ```
			
			VAR __VendaISV = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 4
			)
			
			VAR __Fixed_Margin = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9992
			)
			
			VAR __TotalSales = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9982
			)
			
			RETURN
			DIVIDE(
			    __Fixed_Margin,
			    ABS(__TotalSales - __VendaISV)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\SALES\LC\Support Measures\Real
		lineageTag: ad33c762-88f7-47bb-ade8-926a1f85eb5d

		changedProperty = IsHidden

	measure 'Variable Margin %' = ```
			
			VAR __VendaISV = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 4
			)
			
			VAR __Variable_Margin = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9993
			)
			
			VAR __TotalSales = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9982
			)
			
			RETURN
			DIVIDE(
			    __Variable_Margin,
			    ABS(__TotalSales - __VendaISV)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\SALES\LC\Support Measures\Real
		lineageTag: 04587fd3-56a0-44b8-a4dc-a78d5d9be023

		changedProperty = IsHidden

	measure 'Gross Margin %' = ```
			
			VAR __VendaISV = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 4
			)
			
			VAR __GrossMargin = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9994
			)
			
			VAR __TotalSales = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9982
			)
			
			RETURN
			DIVIDE(
			    __GrossMargin,
			    ABS(__TotalSales - __VendaISV)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\SALES\LC\Support Measures\Real
		lineageTag: a8ef52c2-ebd0-41f2-92f8-1f95a52e8f9a

		changedProperty = IsHidden

	measure 'Gross Margin % (Turnover/Sales)' = ```
			
			VAR __GrossMargin = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9994
			)
			
			VAR __Turnover_Sales = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES[VALUE]),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9984
			)
			
			RETURN
			DIVIDE(
			    __GrossMargin,
			    ABS(__Turnover_Sales)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\SALES\LC\Support Measures\Real
		lineageTag: d996807a-eaea-489d-9612-2fffbb564045

		changedProperty = IsHidden

	measure 'Gross Margin After Commissions and Others %' = ```
			
			VAR __VendaISV = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 4
			)
			
			VAR __GrossMargin = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9995
			)
			
			VAR __TotalSales = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9982
			)
			
			RETURN
			DIVIDE(
			    __GrossMargin,
			    ABS(__TotalSales - __VendaISV)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\SALES\LC\Support Measures\Real
		lineageTag: 439d9846-ecb0-4d4a-afcd-83b1373918ff

		changedProperty = IsHidden

	measure 'Campaigns/Incentives Bgt %' = ```
			
			
			VAR __VendaISV = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 4
			)
			
			VAR __Campaigns = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9985
			)
			
			VAR __TotalSales = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9982
			)
			
			RETURN
			DIVIDE(
			    __Campaigns,
			    ABS(__TotalSales - __VendaISV)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\SALES\LC\Support Measures\Budget
		lineageTag: 3d84780e-5247-4f47-8253-40455891b453

		changedProperty = IsHidden

	measure 'Fixed Margin Bgt %' = ```
			
			VAR __VendaISV = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 4
			)
			
			VAR __Fixed_Margin = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9992
			)
			
			VAR __TotalSales = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9982
			)
			
			RETURN
			DIVIDE(
			    __Fixed_Margin,
			    ABS(__TotalSales - __VendaISV)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\SALES\LC\Support Measures\Budget
		lineageTag: 2098257d-eda3-4245-8f2c-c7a8013d1070

		changedProperty = IsHidden

	measure 'Gross Margin Bgt %' = ```
			
			VAR __VendaISV = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 4
			)
			
			VAR __GrossMargin = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9994
			)
			
			VAR __TotalSales = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9982
			)
			
			RETURN
			DIVIDE(
			    __GrossMargin,
			    ABS(__TotalSales - __VendaISV)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\SALES\LC\Support Measures\Budget
		lineageTag: 263772c6-273a-4a56-9916-c16d941e884c

		changedProperty = IsHidden

	measure 'Gross Margin Bgt % (Turnover/Sales)' = ```
			
			VAR __GrossMargin = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9994
			)
			
			VAR __Turnover_Sales = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE]),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9984
			)
			
			RETURN
			DIVIDE(
			    __GrossMargin,
			    ABS(__Turnover_Sales)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\SALES\LC\Support Measures\Budget
		lineageTag: 8369d0de-27be-4b4b-bfd2-6b4c8e1daff5

		changedProperty = IsHidden

	measure 'Gross Margin After Commissions and Others Bgt %' = ```
			
			VAR __VendaISV = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 4
			)
			
			VAR __GrossMargin = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9995
			)
			
			VAR __TotalSales = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9982
			)
			
			RETURN
			DIVIDE(
			    __GrossMargin,
			    ABS(__TotalSales - __VendaISV)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\SALES\LC\Support Measures\Budget
		lineageTag: 25d4d4d9-58b5-40fe-8b52-414f5ab12e6f

		changedProperty = IsHidden

	measure 'Invoice Discount Bgt %' = ```
			
			VAR __VendaISV = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 4
			)
			
			VAR __Invoice_Discount = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9
			)
			
			VAR __TotalSales = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9982
			)
			
			RETURN
			DIVIDE(
			    __Invoice_Discount,
			    ABS(__TotalSales - __VendaISV)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\SALES\LC\Support Measures\Budget
		lineageTag: 67bd7a80-69b6-4d70-872c-2db68f8e964b

		changedProperty = IsHidden

	measure 'Net Discount Bgt %' = ```
			
			VAR __VendaISV = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 4
			)
			
			VAR __Net_Discount = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9983
			)
			
			VAR __TotalSales = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9982
			)
			
			RETURN
			DIVIDE(
			    __Net_Discount,
			    ABS(__TotalSales - __VendaISV)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\SALES\LC\Support Measures\Budget
		lineageTag: f7a94f70-4572-4f06-9ecd-46c1fb42a4ca

		changedProperty = IsHidden

	measure 'Variable Margin - Importer Bgt %' = ```
			
			VAR __VariableMargin = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9993
			)
			
			VAR __VariableMarginDivisor =
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE]),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9974
			)
			
			RETURN
			DIVIDE(
			    __VariableMargin,
			    ABS(__VariableMarginDivisor)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\SALES\LC\Support Measures\Budget
		lineageTag: 9da107d8-debe-4a84-8d2d-5ad57055e0b6

		changedProperty = IsHidden

	measure 'Variable Margin Bgt %' = ```
			
			VAR __VendaISV = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 4
			)
			
			VAR __Variable_Margin = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9993
			)
			
			VAR __TotalSales = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9982
			)
			
			RETURN
			DIVIDE(
			    __Variable_Margin,
			    ABS(__TotalSales - __VendaISV)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\SALES\LC\Support Measures\Budget
		lineageTag: 9af20772-39fd-4a28-883b-4a26a630b25f

		changedProperty = IsHidden

	measure 'Campaigns/Incentives (EUR) %' = ```
							
							VAR __VendaISV = 
							CALCULATE(
								SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 4
							)
							
							VAR __Campaigns = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9985
							)
							
							VAR __TotalSales = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9982
							)
							
							RETURN
							DIVIDE(
							    __Campaigns,
							    ABS(__TotalSales - __VendaISV)
							)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\SALES\EUR\Support Measures\Real
		lineageTag: da1b41d9-8bf0-4b46-a7b4-0219419980fa

		changedProperty = IsHidden

	measure 'Fixed Margin (EUR) %' = ```
							
							VAR __VendaISV = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 4
							)
							
							VAR __Fixed_Margin = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9992
							)
							
							VAR __TotalSales = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9982
							)
							
							RETURN
							DIVIDE(
							    __Fixed_Margin,
							    ABS(__TotalSales - __VendaISV)
							)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\SALES\EUR\Support Measures\Real
		lineageTag: c9400e68-e6f4-4dd2-a148-fe5d6656de90

		changedProperty = IsHidden

	measure 'Gross Margin (EUR) %' = ```
							
							VAR __VendaISV = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 4
							)
							
							VAR __GrossMargin = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9994
							)
							
							VAR __TotalSales = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9982
							)
							
							RETURN
							DIVIDE(
							    __GrossMargin,
							    ABS(__TotalSales - __VendaISV)
							)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\SALES\EUR\Support Measures\Real
		lineageTag: 96f03e3d-a13e-441e-80f2-e80eee5224fc

		changedProperty = IsHidden

	measure 'Gross Margin (EUR) % (Turnover/Sales)' = ```
							
							VAR __GrossMargin = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9994
							)
							
							VAR __Turnover_Sales = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY]), 1))
			    				),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9984
							)
							
							RETURN
							DIVIDE(
							    __GrossMargin,
							    ABS(__Turnover_Sales)
							)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\SALES\EUR\Support Measures\Real
		lineageTag: 0480cd4e-bf82-422f-9cc9-e0b15de28a04

		changedProperty = IsHidden

	measure 'Gross Margin After Commissions and Others (EUR) %' = ```
							
							VAR __VendaISV = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 4
							)
							
							VAR __GrossMargin = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9995
							)
							
							VAR __TotalSales = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9982
							)
							
							RETURN
							DIVIDE(
							    __GrossMargin,
							    ABS(__TotalSales - __VendaISV)
							)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\SALES\EUR\Support Measures\Real
		lineageTag: 0b83f32e-bc12-4e6c-bd16-be2c16bd94c6

		changedProperty = IsHidden

	measure 'Invoice Discount (EUR) %' = ```
							
							VAR __VendaISV = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 4
							)
							
							VAR __Invoice_Discount = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9
							)
							
							VAR __TotalSales = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9982
							)
							
							RETURN
							DIVIDE(
							    __Invoice_Discount,
							    ABS(__TotalSales - __VendaISV)
							)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\SALES\EUR\Support Measures\Real
		lineageTag: ceec7d5b-a1a1-45f7-9a55-03a1c04329b9

		changedProperty = IsHidden

	measure 'Net Discount (EUR) %' = ```
							
							VAR __VendaISV = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 4
							)
							
							VAR __Net_Discount = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9983
							)
							
							VAR __TotalSales = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9982
							)
							
							RETURN
							DIVIDE(
							    __Net_Discount,
							    ABS(__TotalSales - __VendaISV)
							)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\SALES\EUR\Support Measures\Real
		lineageTag: 122877a7-763d-4922-8571-1bbb9bbb792e

		changedProperty = IsHidden

	measure 'Variable Margin - Importer (EUR) %' = ```
							
							VAR __VariableMargin = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9993
							)
							
							VAR __VariableMarginDivisor =
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY]), 1))
			    				),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9974
							)
							
							RETURN
							DIVIDE(
							    __VariableMargin,
							    ABS(__VariableMarginDivisor)
							)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\SALES\EUR\Support Measures\Real
		lineageTag: 1db581c7-4acb-46a0-96cf-4ea5d6cff014

		changedProperty = IsHidden

	measure 'Variable Margin (EUR) %' = ```
							
							VAR __VendaISV = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 4
							)
							
							VAR __Variable_Margin = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9993
							)
							
							VAR __TotalSales = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9982
							)
							
							RETURN
							DIVIDE(
							    __Variable_Margin,
							    ABS(__TotalSales - __VendaISV)
							)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\SALES\EUR\Support Measures\Real
		lineageTag: 2cbcd3cc-5840-44c6-98bc-3d732a33627c

		changedProperty = IsHidden

	measure 'Campaigns/Incentives Bgt (EUR) %' = ```
							
							
							VAR __VendaISV = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 4
							)
							
							VAR __Campaigns = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9985
							)
							
							VAR __TotalSales = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9982
							)
							
							RETURN
							DIVIDE(
							    __Campaigns,
							    ABS(__TotalSales - __VendaISV)
							)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\SALES\EUR\Support Measures\Budget
		lineageTag: 36ef3520-433c-4c70-9491-62da664f8836

		changedProperty = IsHidden

	measure 'Fixed Margin Bgt (EUR) %' = ```
							
							VAR __VendaISV = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 4
							)
							
							VAR __Fixed_Margin = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9992
							)
							
							VAR __TotalSales = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9982
							)
							
							RETURN
							DIVIDE(
							    __Fixed_Margin,
							    ABS(__TotalSales - __VendaISV)
							)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\SALES\EUR\Support Measures\Budget
		lineageTag: 965a0ea6-ca9d-4e98-a50b-e91079e33e9a

		changedProperty = IsHidden

	measure 'Gross Margin After Commissions and Others Bgt (EUR) %' = ```
							
							VAR __VendaISV = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 4
							)
							
							VAR __GrossMargin = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9995
							)
							
							VAR __TotalSales = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9982
							)
							
							RETURN
							DIVIDE(
							    __GrossMargin,
							    ABS(__TotalSales - __VendaISV)
							)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\SALES\EUR\Support Measures\Budget
		lineageTag: 01df1f57-ddbe-4e05-925c-ebf52fd8a2e6

		changedProperty = IsHidden

	measure 'Gross Margin Bgt (EUR) %' = ```
							
							VAR __VendaISV = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 4
							)
							
							VAR __GrossMargin = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9994
							)
							
							VAR __TotalSales = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9982
							)
							
							RETURN
							DIVIDE(
							    __GrossMargin,
							    ABS(__TotalSales - __VendaISV)
							)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\SALES\EUR\Support Measures\Budget
		lineageTag: 040ab2db-6a85-4fdb-b517-dabe112adf22

		changedProperty = IsHidden

	measure 'Gross Margin Bgt (EUR) % (Turnover/Sales)' = ```
							
							VAR __GrossMargin = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9994
							)
							
							VAR __Turnover_Sales = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY]), 1))
			    				),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9984
							)
							
							RETURN
							DIVIDE(
							    __GrossMargin,
							    ABS(__Turnover_Sales)
							)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\SALES\EUR\Support Measures\Budget
		lineageTag: 6c21e5a6-15c1-42fc-b1a7-904da58623ef

		changedProperty = IsHidden

	measure 'Invoice Discount Bgt (EUR) %' = ```
							
							VAR __VendaISV = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 4
							)
							
							VAR __Invoice_Discount = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9
							)
							
							VAR __TotalSales = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9982
							)
							
							RETURN
							DIVIDE(
							    __Invoice_Discount,
							    ABS(__TotalSales - __VendaISV)
							)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\SALES\EUR\Support Measures\Budget
		lineageTag: bfd5e1f1-8aa1-4532-a157-644767d3dd65

		changedProperty = IsHidden

	measure 'Net Discount Bgt (EUR) %' = ```
							
							VAR __VendaISV = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 4
							)
							
							VAR __Net_Discount = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9983
							)
							
							VAR __TotalSales = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9982
							)
							
							RETURN
							DIVIDE(
							    __Net_Discount,
							    ABS(__TotalSales - __VendaISV)
							)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\SALES\EUR\Support Measures\Budget
		lineageTag: a23d660b-b9c6-403e-b6ec-a960e0f1191d

		changedProperty = IsHidden

	measure 'Variable Margin - Importer Bgt (EUR) %' = ```
							
							VAR __VariableMargin = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9993
							)
							
							VAR __VariableMarginDivisor =
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY]), 1))
			    				),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9974
							)
							
							RETURN
							DIVIDE(
							    __VariableMargin,
							    ABS(__VariableMarginDivisor)
							)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\SALES\EUR\Support Measures\Budget
		lineageTag: dea66c30-bd05-4cb2-a7ab-117b39be465b

		changedProperty = IsHidden

	measure 'Variable Margin Bgt (EUR) %' = ```
							
							VAR __VendaISV = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 4
							)
							
							VAR __Variable_Margin = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9993
							)
							
							VAR __TotalSales = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9982
							)
							
							RETURN
							DIVIDE(
							    __Variable_Margin,
							    ABS(__TotalSales - __VendaISV)
							)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\SALES\EUR\Support Measures\Budget
		lineageTag: 4dca8495-6ba8-4307-9571-71eec88ab949

		changedProperty = IsHidden

	measure 'Conditional Format - VHE Sales' =
			
			IF(
			    SELECTEDVALUE(PARAMETER_VHE_SALES_INDICADORES[Id]) IN {3, 5, 7},
			    [Indicators VHE Sales]
			)
		isHidden
		displayFolder: _UI\Format
		lineageTag: 43620736-e3f6-4a9f-a3c1-56378a84b945

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'VHE Purchase CY' = ```
			
			    SUM(VIEW_VHE_FACT_STOCK_MONTH[VALUE])
			```
		formatString: #,0
		displayFolder: VHE\PURCHASE\LC\Real
		lineageTag: 8362770d-6ee0-46af-9131-a0ffb630442e

	measure 'VHE Purchase CY (EUR)' =
			
			SUMX(
			    SUMMARIZECOLUMNS(
			        VIEW_VHE_FACT_STOCK_MONTH[CURRENCY_RATE_KEY],
			        "TOTAL", SUM(VIEW_VHE_FACT_STOCK_MONTH[VALUE])
			    ),
			    DIVIDE([TOTAL],
			    COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_STOCK_MONTH[CURRENCY_RATE_KEY]), 1))
			)
		formatString: #,0
		isHidden
		displayFolder: VHE\PURCHASE\EUR\Real
		lineageTag: 666bf905-b609-4440-a7d2-4f1ee07a6933

		changedProperty = IsHidden

	measure 'Cabeçalhos VHE PURCHASE' =
			
			CALCULATE(
			    SUM(VIEW_VHE_FACT_STOCK_MONTH[VALUE]),
			    ALL(CALCGROUP_CURRENCY),
			    REMOVEFILTERS(CALCGROUP_CURRENCY)
			)
		isHidden
		displayFolder: _UI\Cabeçalhos
		lineageTag: 18abd4f9-8261-4fff-9b54-5d0d8dbaccbf

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Conditional Format - DRIFRS Indicators' = ```
			
			
			IF(
			    SELECTEDVALUE('PARAMETER_DRIFRS_INDICADORES'[Id]) IN {5, 9, 13},
			    [Indicators IFRS]
			)
			
			
			--    1 = DR PL CY
			--    2 = DR PL CY %
			--    3 = DR PL Bgt
			--    4 = DR PL Bgt %
			--    5 = DR PL Delta Bgt
			--    6 = DR PL Delta Bgt % 
			--    7 = DR PL Bgt Adm
			--    8 = DR PL Bgt Adm %
			--    9 = DR PL Delta Bgt Adm
			--    10 = DR PL Delta Bgt Adm %
			--    11 = DR PL LY
			--    12 = DR PL LY %
			--    13 = DR PL Delta LY
			--    14 = DR PL Delta LY %]
			```
		isHidden
		displayFolder: _UI\Format
		lineageTag: 4890fd2a-6071-4134-b50d-badb0443535d

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Conditional Format - CF Indicators' =
			
			
			IF(
			    SELECTEDVALUE('PARAMETER_CF_INDICADORES'[Id]) IN {3},
			    [Indicators CF]
			)
			
			
			--    1 = CY
			--    2 = LY
			--    3 = DELTA LY
		isHidden
		displayFolder: _UI\Format
		lineageTag: f3e44867-efd2-4d14-8dfc-45da0777466c

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Highlight DR PL' =
			
			
			IF(SELECTEDVALUE(VIEW_NLR_DIM_PL[HIGHLIGHT]), "#E0EBED")
		isHidden
		displayFolder: _UI
		lineageTag: 7e9b1eec-dedd-4d9b-bf55-cbe7be3c4f2e

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Conditional Format - Sytner Indicators' = ```
			
			
			IF(
			    SELECTEDVALUE('PARAMETER_DRPL_INDICADORES'[Id]) IN {5, 9, 13},
			    [Indicators DR PL]
			)
			
			
			--    1 = DR PL CY
			--    2 = DR PL CY %
			--    3 = DR PL Bgt
			--    4 = DR PL Bgt %
			--    5 = DR PL Delta Bgt
			--    6 = DR PL Delta Bgt % 
			--    7 = DR PL Bgt Adm
			--    8 = DR PL Bgt Adm %
			--    9 = DR PL Delta Bgt Adm
			--    10 = DR PL Delta Bgt Adm %
			--    11 = DR PL LY
			--    12 = DR PL LY %
			--    13 = DR PL Delta LY
			--    14 = DR PL Delta LY %]
			```
		isHidden
		displayFolder: _UI\Format
		lineageTag: c0ebf19e-a3f4-416f-9dad-7cec01190b52

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'VHE Stock Fixed Margin %' = ```
			
			VAR __VendaISV = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_STOCK_MONTH[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 4
			)
			
			VAR __Fixed_Margin = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_STOCK_MONTH[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9992
			)
			
			VAR __TotalSales = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_STOCK_MONTH[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9982
			)
			
			RETURN
			DIVIDE(
			    __Fixed_Margin,
			    ABS(__TotalSales - __VendaISV)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\STOCK\LC\Support Measures
		lineageTag: 19a58f68-922f-46b6-bf87-2e33a9a7feab

		changedProperty = IsHidden

	measure 'VHE Stock Variable Margin - Importer %' = ```
			
			VAR __VariableMargin = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_STOCK_MONTH[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9993
			)
			
			VAR __VariableMarginDivisor =
			CALCULATE(
			    SUM(VIEW_VHE_FACT_STOCK_MONTH[VALUE]),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9974
			)
			
			RETURN
			DIVIDE(
			    __VariableMargin,
			    ABS(__VariableMarginDivisor)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\STOCK\LC\Support Measures
		lineageTag: a6734786-c895-4c6a-8885-480d8bea3e59

		changedProperty = IsHidden

	measure 'VHE Stock Variable Margin %' = ```
			
			VAR __VendaISV = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_STOCK_MONTH[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 4
			)
			
			VAR __Variable_Margin = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_STOCK_MONTH[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9993
			)
			
			VAR __TotalSales = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_STOCK_MONTH[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9982
			)
			
			RETURN
			DIVIDE(
			    __Variable_Margin,
			    ABS(__TotalSales - __VendaISV)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\STOCK\LC\Support Measures
		lineageTag: d8ae0e0f-a8f0-4ec9-bb8c-b97b28c7fbc6

		changedProperty = IsHidden

	measure 'VHE Stock Gross Margin %' = ```
			
			VAR __VendaISV = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_STOCK_MONTH[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 4
			)
			
			VAR __GrossMargin = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_STOCK_MONTH[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9994
			)
			
			VAR __TotalSales = 
			CALCULATE(
			    SUM(VIEW_VHE_FACT_STOCK_MONTH[VALUE]),
			    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
			    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9982
			)
			
			RETURN
			DIVIDE(
			    __GrossMargin,
			    ABS(__TotalSales - __VendaISV)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\STOCK\LC\Support Measures
		lineageTag: 1bcee70b-d0f7-42b6-89bf-9de914860b69

		changedProperty = IsHidden

	measure 'VHE Stock CY' = ```
			
			
			VAR __Indicator = HASONEVALUE(VIEW_VHE_DIM_MEASURES[MEASURE_CODE])
			RETURN
			
			IF(
			    __Indicator,
			    SWITCH(
			        SELECTEDVALUE(VIEW_VHE_DIM_MEASURES[MEASURE_CODE]),
			            -- Rúbricas calculadas
			            9964, [VHE Stock Gross Margin %],
			            9965, [VHE Stock Variable Margin %],
			            9966, [VHE Stock Variable Margin - Importer %],
			            9967, [VHE Stock Fixed Margin %],
			                
			            -- Rúbricas de valor
			            SUM(VIEW_VHE_FACT_STOCK_MONTH[VALUE])
			    ),
			    CALCULATE(
			        SUM(VIEW_VHE_FACT_STOCK_MONTH[VALUE]),
			        VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9973
			    )
			)
			```
		displayFolder: VHE\STOCK\LC\Real
		lineageTag: 2797b6a7-0acd-44ad-8adc-881a45e5c708

		formatStringDefinition =
				IF(
				    SELECTEDVALUE(VIEW_VHE_DIM_MEASURES[FORMAT_TYPE]) = "%" ,
				    "#,##0.0%",
				    "#,###,###,###,###"
				)

	measure 'VHE Stock Fixed Margin (EUR) %' = ```
							
							VAR __VendaISV = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_STOCK_MONTH[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_STOCK_MONTH[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_STOCK_MONTH[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 4
							)
							
							VAR __Fixed_Margin = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_STOCK_MONTH[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_STOCK_MONTH[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_STOCK_MONTH[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9992
							)
							
							VAR __TotalSales = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_STOCK_MONTH[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_STOCK_MONTH[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_STOCK_MONTH[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9982
							)
							
							RETURN
							DIVIDE(
							    __Fixed_Margin,
							    ABS(__TotalSales - __VendaISV)
							)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\STOCK\EUR\Support Measures
		lineageTag: 7e8f478a-ab5d-4717-8767-1789efb0adf8

		changedProperty = IsHidden

	measure 'VHE Stock Gross Margin (EUR) %' = ```
							
							VAR __VendaISV = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_STOCK_MONTH[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_STOCK_MONTH[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_STOCK_MONTH[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 4
							)
							
							VAR __GrossMargin = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_STOCK_MONTH[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_STOCK_MONTH[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_STOCK_MONTH[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9994
							)
							
							VAR __TotalSales = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_STOCK_MONTH[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_STOCK_MONTH[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_STOCK_MONTH[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9982
							)
							
							RETURN
							DIVIDE(
							    __GrossMargin,
							    ABS(__TotalSales - __VendaISV)
							)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\STOCK\EUR\Support Measures
		lineageTag: 17c1faf1-d516-4a06-bcd0-a376ff5810f5

		changedProperty = IsHidden

	measure 'VHE Stock Variable Margin - Importer (EUR) %' = ```
							
							VAR __VariableMargin = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_STOCK_MONTH[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_STOCK_MONTH[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_STOCK_MONTH[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9993
							)
							
							VAR __VariableMarginDivisor =
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_STOCK_MONTH[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_STOCK_MONTH[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_STOCK_MONTH[CURRENCY_RATE_KEY]), 1))
			    				),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9974
							)
							
							RETURN
							DIVIDE(
							    __VariableMargin,
							    ABS(__VariableMarginDivisor)
							)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\STOCK\EUR\Support Measures
		lineageTag: 2844f788-71f8-4231-8d7f-7765dca9beb4

		changedProperty = IsHidden

	measure 'VHE Stock Variable Margin (EUR) %' = ```
							
							VAR __VendaISV = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_STOCK_MONTH[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_STOCK_MONTH[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_STOCK_MONTH[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 4
							)
							
							VAR __Variable_Margin = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_STOCK_MONTH[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_STOCK_MONTH[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_STOCK_MONTH[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9993
							)
							
							VAR __TotalSales = 
							CALCULATE(
							    SUMX(
			        				SUMMARIZECOLUMNS(
			            				VIEW_VHE_FACT_STOCK_MONTH[CURRENCY_RATE_KEY],
			            				"TOTAL", SUM(VIEW_VHE_FACT_STOCK_MONTH[VALUE])
			        				),
			        				DIVIDE([TOTAL],
			        				COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_STOCK_MONTH[CURRENCY_RATE_KEY]), 1))
			    				),
							    REMOVEFILTERS(VIEW_VHE_DIM_MEASURES),
							    VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9982
							)
							
							RETURN
							DIVIDE(
							    __Variable_Margin,
							    ABS(__TotalSales - __VendaISV)
							)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\STOCK\EUR\Support Measures
		lineageTag: 6072d821-3668-4572-9d11-305202f48ca8

		changedProperty = IsHidden

	measure 'VHE Stock CY (EUR)' = ```
			
			
			VAR __Indicator = HASONEVALUE(VIEW_VHE_DIM_MEASURES[MEASURE_CODE])
			RETURN
			
			IF(
			    __Indicator,
			    SWITCH(
			        SELECTEDVALUE(VIEW_VHE_DIM_MEASURES[MEASURE_CODE]),
			        -- Rúbricas calculadas
			        9964, [VHE Stock Gross Margin (EUR) %],
			        9965, [VHE Stock Variable Margin (EUR) %],
			        9966, [VHE Stock Variable Margin - Importer (EUR) %],
			        9967, [VHE Stock Fixed Margin (EUR) %],
			                
			        -- Rúbricas de valor
			        SUMX(
			            SUMMARIZECOLUMNS(
			                VIEW_VHE_FACT_STOCK_MONTH[CURRENCY_RATE_KEY],
			                "TOTAL", SUM(VIEW_VHE_FACT_STOCK_MONTH[VALUE])
			            ),
			            DIVIDE([TOTAL],
			            COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_STOCK_MONTH[CURRENCY_RATE_KEY]), 1))
			        )
			    ),
			    CALCULATE(
			        SUMX(
			            SUMMARIZECOLUMNS(
			                VIEW_VHE_FACT_STOCK_MONTH[CURRENCY_RATE_KEY],
			                "TOTAL", SUM(VIEW_VHE_FACT_STOCK_MONTH[VALUE])
			            ),
			            DIVIDE([TOTAL],
			            COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_STOCK_MONTH[CURRENCY_RATE_KEY]), 1))
			        ),
			        VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9973
			    )
			)
			```
		isHidden
		displayFolder: VHE\STOCK\EUR\Real
		lineageTag: e5a6a5ac-f215-4324-952f-2585d9091b7e

		formatStringDefinition =
				IF(
				    SELECTEDVALUE(VIEW_VHE_DIM_MEASURES[FORMAT_TYPE]) = "%" ,
				    "#,##0.0%",
				    "#,###,###,###,###"
				)

		changedProperty = IsHidden

	measure 'VHE Stock LY' =
			
			CALCULATE(
			    [VHE Stock CY],
			    SAMEPERIODLASTYEAR(VIEW_GBL_DIM_CALENDAR[DATE])
			)
		displayFolder: VHE\STOCK\LC\Real
		lineageTag: 48fce904-795b-434e-880c-62d739127607

		formatStringDefinition =
				IF(
				    SELECTEDVALUE(VIEW_VHE_DIM_MEASURES[FORMAT_TYPE]) = "%" ,
				    "#,##0.0%",
				    "#,###,###,###,###"
				)

	measure 'VHE Stock Delta LY' =
			
			[VHE Stock CY] - [VHE Stock LY]
		displayFolder: VHE\STOCK\LC\Real
		lineageTag: fe8c0082-df8a-42c7-baf2-16bb22581e8b

		formatStringDefinition =
				IF(
				    SELECTEDVALUE(VIEW_VHE_DIM_MEASURES[FORMAT_TYPE]) = "%" ,
				    "#,##0.0%",
				    "#,###,###,###,###"
				)

	measure 'VHE Stock Delta LY %' =
			
			DIVIDE(
			    [VHE Stock Delta LY],
			    [VHE Stock LY]
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: VHE\STOCK\LC\Real
		lineageTag: 8f2d6edd-6cb5-405e-a3b1-d5de179c2cb5

	measure 'VHE Stock Delta LY (EUR)' =
			
			[VHE Stock CY (EUR)] - [VHE Stock LY (EUR)]
		isHidden
		displayFolder: VHE\STOCK\EUR\Real
		lineageTag: 82e640be-bca9-4627-8eef-ac177e79cfc6

		formatStringDefinition =
				IF(
				    SELECTEDVALUE(VIEW_VHE_DIM_MEASURES[FORMAT_TYPE]) = "%" ,
				    "#,##0.0%",
				    "#,###,###,###,###"
				)

		changedProperty = IsHidden

	measure 'VHE Stock Delta LY (EUR) %' =
			
			DIVIDE(
			    [VHE Stock Delta LY (EUR)],
			    [VHE Stock LY (EUR)]
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: VHE\STOCK\EUR\Real
		lineageTag: 60470743-c496-4b7e-8cd0-08d5de7aa7fe

		changedProperty = IsHidden

	measure 'VHE Stock LY (EUR)' =
			
			CALCULATE(
			    [VHE Stock CY (EUR)],
			    SAMEPERIODLASTYEAR(VIEW_GBL_DIM_CALENDAR[DATE])
			)
		isHidden
		displayFolder: VHE\STOCK\EUR\Real
		lineageTag: 053df41c-373b-4cb5-9605-5329b5f258cd

		formatStringDefinition =
				IF(
				    SELECTEDVALUE(VIEW_VHE_DIM_MEASURES[FORMAT_TYPE]) = "%" ,
				    "#,##0.0%",
				    "#,###,###,###,###"
				)

		changedProperty = IsHidden

	measure 'Indicators VHE Stock' =
			
			
			SWITCH(
			    SELECTEDVALUE(PARAMETER_VHE_STOCK_INDICADORES[Id]),
			    1, [VHE Stock CY],
			    2, [VHE Stock LY],
			    3, [VHE Stock Delta LY],
			    4, [VHE Stock Delta LY %]
			)
		displayFolder: VHE\STOCK\LC\Support Measures
		lineageTag: 116d5425-f741-4bec-8d4e-e3ae58a2c048

		formatStringDefinition = ```
				VAR FormatType = SELECTEDVALUE(VIEW_VHE_DIM_MEASURES[FORMAT_TYPE])
				
				RETURN
				SWITCH(
				    SELECTEDVALUE(PARAMETER_VHE_SALES_INDICADORES[Id]),
				    
				    1, IF(FormatType = "%", "#,##0.0%", "#,###,###,###,###"),
				    2, IF(FormatType = "%", "#,##0.0%", "#,###,###,###,###"),
				    3, IF(FormatType = "%", "#,##0.0%", "#,###,###,###,###"),
				    4, "#,##0.0%"
				)
				```

	measure 'Indicators VHE Stock (EUR)' =
			
			
			SWITCH(
			    SELECTEDVALUE(PARAMETER_VHE_STOCK_INDICADORES[Id]),
			    1, [VHE Stock CY (EUR)],
			    2, [VHE Stock LY (EUR)],
			    3, [VHE Stock Delta LY (EUR)],
			    4, [VHE Stock Delta LY (EUR) %]
			)
		isHidden
		displayFolder: VHE\STOCK\EUR\Support Measures
		lineageTag: 19ab4ca0-d8bc-4648-836d-80533fb7f1be

		formatStringDefinition = ```
				VAR FormatType = SELECTEDVALUE(VIEW_VHE_DIM_MEASURES[FORMAT_TYPE])
				
				RETURN
				SWITCH(
				    SELECTEDVALUE(PARAMETER_VHE_SALES_INDICADORES[Id]),
				    
				    1, IF(FormatType = "%", "#,##0.0%", "#,###,###,###,###"),
				    2, IF(FormatType = "%", "#,##0.0%", "#,###,###,###,###"),
				    3, IF(FormatType = "%", "#,##0.0%", "#,###,###,###,###"),
				    4, "#,##0.0%"
				)
				```

		changedProperty = IsHidden

	measure 'Title - Vehicle Stock' =
			
			
			SWITCH(
			    LEFT(SELECTEDVALUE(VIEW_GBL_DIM_USER_CULTURE[USER_CULTURE]), 2),
			    "pt", "Stock Viaturas",
			    "en", "Vehicle Stock",
			    "es", "Stock Vehículos",
			    "fr", "Stock Véhicules",
			    "Vehicle Stock"
			)
		isHidden
		displayFolder: _UI\Titles
		lineageTag: 8eae22aa-4960-44e7-a11e-b78de69479b4

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Title - Tables' = ```
			
			
			-- Avalia se tem algum filtro de ano aplicado
			VAR __FiltredYear = 
			    ISFILTERED(VIEW_GBL_DIM_CALENDAR[PT_CURRENT_YEAR]) ||
			    ISFILTERED(VIEW_GBL_DIM_CALENDAR[EN_CURRENT_YEAR]) ||
			    ISFILTERED(VIEW_GBL_DIM_CALENDAR[ES_CURRENT_YEAR]) ||
			    ISFILTERED(VIEW_GBL_DIM_CALENDAR[FR_CURRENT_YEAR])
			
			-- Retorna os anos selecionados
			VAR __SelectedYears = 
			    CONCATENATEX(
			        FILTER(
			            VALUES(VIEW_GBL_DIM_CALENDAR[YEAR]),
			            NOT(ISBLANK(VIEW_GBL_DIM_CALENDAR[YEAR]))
			        ),
			        VIEW_GBL_DIM_CALENDAR[YEAR],
			        ", "
			    )
			-- Verifica se existe apenas um ano selecionado (Para o texto no singular/plural)
			VAR __YearValue = NOT(HASONEVALUE(VIEW_GBL_DIM_CALENDAR[YEAR]))
			
			-- Retorna o texto do ano por idioma
			VAR __YearText = 
			
			IF(
			    __FiltredYear,
			    SWITCH(
			        SELECTEDVALUE(VIEW_GBL_DIM_USER_CULTURE[USER_CULTURE]),
			        "pt-PT", "Ano",
			        "en-US", "Year",
			        "es-ES", "Año",
			        "fr-FR", "Année"
			    ) & 
			    IF( __YearValue, "s" ) & 
			    " " & __SelectedYears,
			    SWITCH(
			        SELECTEDVALUE(VIEW_GBL_DIM_USER_CULTURE[USER_CULTURE]),
			        "pt-PT", "Todos os anos",
			        "en-US", "All Years",
			        "es-ES", "Todos los Años",
			        "fr-FR", "Toutes les Années"
			    )
			)
			
			-- Retorna o último mês numérico contextualizado
			VAR __MaxMonth = MAX(VIEW_GBL_DIM_CALENDAR[MONTH])
			
			-- Retorna o último mês contextualizado por idioma
			VAR __MaxMonthText = 
			    " " &
			    SWITCH(
			        SELECTEDVALUE(VIEW_GBL_DIM_USER_CULTURE[USER_CULTURE]),
			        "pt-PT", 
			            CALCULATE(
			                MAX(VIEW_GBL_DIM_CALENDAR[PT_MONTH_SHORT_DESC]),
			                VIEW_GBL_DIM_CALENDAR[MONTH] = __MaxMonth
			            ),
			        "en-US", 
			            CALCULATE(
			                MAX(VIEW_GBL_DIM_CALENDAR[EN_MONTH_SHORT_DESC]),
			                VIEW_GBL_DIM_CALENDAR[MONTH] = __MaxMonth
			            ),
			        "es-ES", 
			            CALCULATE(
			                MAX(VIEW_GBL_DIM_CALENDAR[ES_MONTH_SHORT_DESC]),
			                VIEW_GBL_DIM_CALENDAR[MONTH] = __MaxMonth
			            ),
			        "fr-FR", 
			            CALCULATE(
			                MAX(VIEW_GBL_DIM_CALENDAR[FR_MONTH_SHORT_DESC]),
			                VIEW_GBL_DIM_CALENDAR[MONTH] = __MaxMonth
			            )
			    )
			
			-- Retorna os meses contextualizados por idioma
			VAR __SelectedMonths = 
			    " " &
			    SWITCH(
			        SELECTEDVALUE(VIEW_GBL_DIM_USER_CULTURE[USER_CULTURE]),
			        "pt-PT", 
			            CONCATENATEX(
			                FILTER(
			                    VALUES(VIEW_GBL_DIM_CALENDAR[PT_MONTH_SHORT_DESC]),
			                    NOT(ISBLANK(VIEW_GBL_DIM_CALENDAR[PT_MONTH_SHORT_DESC]))
			                ),
			                VIEW_GBL_DIM_CALENDAR[PT_MONTH_SHORT_DESC],
			                ", "
			            ),
			        "en-US", 
			            CONCATENATEX(
			                FILTER(
			                    VALUES(VIEW_GBL_DIM_CALENDAR[EN_MONTH_SHORT_DESC]),
			                    NOT(ISBLANK(VIEW_GBL_DIM_CALENDAR[EN_MONTH_SHORT_DESC]))
			                ),
			                VIEW_GBL_DIM_CALENDAR[EN_MONTH_SHORT_DESC],
			                ", "
			            ),
			        "es-ES", 
			            CONCATENATEX(
			                FILTER(
			                    VALUES(VIEW_GBL_DIM_CALENDAR[ES_MONTH_SHORT_DESC]),
			                    NOT(ISBLANK(VIEW_GBL_DIM_CALENDAR[ES_MONTH_SHORT_DESC]))
			                ),
			                VIEW_GBL_DIM_CALENDAR[ES_MONTH_SHORT_DESC],
			                ", "
			            ),
			        "fr-FR", 
			            CONCATENATEX(
			                FILTER(
			                    VALUES(VIEW_GBL_DIM_CALENDAR[FR_MONTH_SHORT_DESC]),
			                    NOT(ISBLANK(VIEW_GBL_DIM_CALENDAR[FR_MONTH_SHORT_DESC]))
			                ),
			                VIEW_GBL_DIM_CALENDAR[FR_MONTH_SHORT_DESC],
			                ", "
			            )
			    )
			-- Retorna o valor selecionado do grupo de cálculos do período
			VAR __Period = SELECTEDVALUE(CALCGROUP_ACCUMULATED_PERIOD[Period])
			
			-- Verifica se existe um filtro de mês
			VAR __MonthValue = ISFILTERED(VIEW_GBL_DIM_CALENDAR[MONTH])
			
			-- Retorna o texto do grupo de cálculos de período concatenado ao mês/meses contextualizados por idioma
			VAR __PeriodText =
			    SWITCH(
			        TRUE(),
			        __Period = "YTD", 
			            SWITCH(
			                SELECTEDVALUE(VIEW_GBL_DIM_USER_CULTURE[USER_CULTURE]),
			                "pt-PT", "Valores Acumulados" & IF( ISFILTERED(VIEW_GBL_DIM_CALENDAR[PT_MONTH_DESC]), " a" & __MaxMonthText ),
			                "en-US", "Accumulated Values" & IF( ISFILTERED(VIEW_GBL_DIM_CALENDAR[EN_MONTH_DESC]), " up to" & __MaxMonthText ),
			                "es-ES", "Valores Acumulados" & IF( ISFILTERED(VIEW_GBL_DIM_CALENDAR[ES_MONTH_DESC]), " hasta" & __MaxMonthText ),
			                "fr-FR", "Valeurs Cumulées" & IF( ISFILTERED(VIEW_GBL_DIM_CALENDAR[FR_MONTH_DESC]), " jusqu'en" & __MaxMonthText )
			                ) & 
			            IF( __MonthValue, __MaxMonthText ),
			        __Period = "Monthly", 
			            SWITCH(
			                SELECTEDVALUE(VIEW_GBL_DIM_USER_CULTURE[USER_CULTURE]),
			                "pt-PT", IF( ISFILTERED(VIEW_GBL_DIM_CALENDAR[PT_MONTH_DESC]) , "Valores de" & __SelectedMonths , "Valores Mensais" ),
			                "en-US", IF( ISFILTERED(VIEW_GBL_DIM_CALENDAR[EN_MONTH_DESC]), "Monthly of" & __SelectedMonths, "Monthly Values" ),
			                "es-ES", IF( ISFILTERED(VIEW_GBL_DIM_CALENDAR[ES_MONTH_DESC]), "Valores de" & __SelectedMonths, "Valores Mensuales" ),
			                "fr-FR", IF( ISFILTERED(VIEW_GBL_DIM_CALENDAR[FR_MONTH_DESC]), "Valeurs de" & __SelectedMonths, "Valeurs Mensuelles" )
			            )
			    )
			
			-- Retorna o período selecionado (Aberto/Fechado)
			VAR __ClosedPeriod = SELECTEDVALUE(VIEW_NLR_DIM_CLOSED_PERIODS[CLOSED_PERIOD])
			
			-- Retorna o texto do período selecionado (Aberto/Fechado) por idioma
			VAR __Periods = 
			    SWITCH(
			        __ClosedPeriod,
			        1, 
			            SWITCH(
			                SELECTEDVALUE(VIEW_GBL_DIM_USER_CULTURE[USER_CULTURE]),
			                "pt-PT", "APENAS Períodos Fechados",
			                "en-US", "ONLY Closed Periods",
			                "es-ES","SOLO Períodos Cerrados",
			                "fr-FR", "SEULEMENT Périodes Clôturées"
			            ),
			        0,
			            SWITCH(
			                SELECTEDVALUE(VIEW_GBL_DIM_USER_CULTURE[USER_CULTURE]),
			                "pt-PT", "APENAS Períodos Abertos",
			                "en-US", "ONLY Open Periods",
			                "es-ES","SOLO Períodos Abiertos",
			                "fr-FR", "SEULEMENT Périodes Ouvertes"
			            ),
			        SWITCH(
			            SELECTEDVALUE(VIEW_GBL_DIM_USER_CULTURE[USER_CULTURE]),
			            "pt-PT", "Períodos Fechados + Abertos",
			            "en-US", "Closed and Open Periods",
			            "es-ES","Períodos Cerrados y Abiertos",
			            "fr-FR", "Périodes Clôturées et Ouvertes"
			        )
			    )
			
			RETURN
			
			__YearText &
			
			-- Condicional porque nem todos os reports possuem períodos acumulados
			IF(
			    (SELECTEDVALUE(PBI_TABLE_REPORTS[GRUPO_CALCULO_PERIODOS]) || (__Period = "Monthly" || ISBLANK(__Period))) && NOT(ISBLANK(__PeriodText)),
			    " | " & __PeriodText
			) &
			
			-- Condicional porque esse valores só são utilizados em alguns reports da área financeira
			IF(
			    SELECTEDVALUE(PBI_TABLE_REPORTS[CLOSED_PERIODS]) && NOT(ISBLANK(__Periods)),
			    " | " & __Periods
			)
			
			```
		isHidden
		displayFolder: _UI\Titles
		lineageTag: 33d75690-2364-41f5-9569-c8b977fcf517

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isText":true}

	measure 'Subtitle - Month/Indicator' =
			
			
			SWITCH(
			    SELECTEDVALUE(VIEW_GBL_DIM_USER_CULTURE[USER_CULTURE]),
			    "pt-PT", "Mês/Indicador",
			    "en-US", "Month/Indicator",
			    "es-ES", "Mes/Indicador",
			    "fr-FR", "Mois/Indicateur",
			    "Month/Indicator"
			)
		isHidden
		displayFolder: _UI\Titles
		lineageTag: 1c77fd68-3814-4c4b-9f76-1e8831274791

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Subtitle - Indicator/Month' =
			
			
			SWITCH(
			    SELECTEDVALUE(VIEW_GBL_DIM_USER_CULTURE[USER_CULTURE]),
			    "pt-PT", "Indicador/Mês",
			    "en-US", "Indicator/Month",
			    "es-ES", "Indicador/Mes",
			    "fr-FR", "Indicateur/Mois",
			    "Indicator/Month"
			)
		isHidden
		displayFolder: _UI\Titles
		lineageTag: 6c1fe045-afb7-409a-a030-ecc7893fa315

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DR PL Bgt (BDT)' = ```
			
			
			  VAR __Valor =
			 SUMX(
			     FILTER(
			         SUMMARIZECOLUMNS(
			             VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[CURRENCY_RATE_KEY],
			             VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE_TYPE_CODE],
			             "BALANCE", SUM(VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE])
			         ),
			         VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE_TYPE_CODE] = 3
			     ),
			     DIVIDE([BALANCE],
			     COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_BDT], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[CURRENCY_RATE_KEY]), 1)
			     )
			 )
			
			 VAR __Unidades =
			 SUMX(
			     FILTER(FILTER(
			         SUMMARIZECOLUMNS(
			             VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[CURRENCY_RATE_KEY],
			             VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE_TYPE_CODE],
			             VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE],
			             "BALANCE", SUM(VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE])
			         ),
			         VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE_TYPE_CODE] = 3),
			         VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE] = 15
			     ),
			     DIVIDE([BALANCE],
			     COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_BDT], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[CURRENCY_RATE_KEY]), 1)
			     )
			 )
			 RETURN
			
			 IF(
			     SELECTEDVALUE(VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE]) = 15,
			     __Unidades,
			     __Valor - __Unidades
			 )
			```
		formatString: #,0
		isHidden
		displayFolder: FIN\DR PL\BDT\Budget
		lineageTag: 474003a4-3c72-4883-ba1d-68002067fea5

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'DR PL Bgt Adm (BDT)' =
			
			
			VAR __Valor =
			SUMX(
			    FILTER(
			        SUMMARIZECOLUMNS(
			            VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[CURRENCY_RATE_KEY],
			            VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE_TYPE_CODE],
			            "BALANCE", SUM(VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE])
			        ),
			        VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE_TYPE_CODE] = 4
			    ),
			    DIVIDE([BALANCE],
			    COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_BDT], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[CURRENCY_RATE_KEY]), 1)
			    )
			)
			
			VAR __Unidades =
			SUMX(
			    FILTER(FILTER(
			        SUMMARIZECOLUMNS(
			            VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[CURRENCY_RATE_KEY],
			            VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE_TYPE_CODE],
			            VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE],
			            "BALANCE", SUM(VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE])
			        ),
			        VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[VALUE_TYPE_CODE] = 4),
			        VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE] = 15
			    ),
			    DIVIDE([BALANCE],
			    COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_BDT], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_BI_TRANS_PL_BUDGET[CURRENCY_RATE_KEY]), 1)
			    )
			)
			RETURN
			
			IF(
			    SELECTEDVALUE(VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE]) = 15,
			    __Unidades,
			    __Valor - __Unidades
			)
		formatString: #,0
		isHidden
		displayFolder: FIN\DR PL\BDT\Budget
		lineageTag: c7c3e7fc-4e8f-4415-80c4-a5c126a59de7

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'DR PL CY (BDT)' = ```
			
			
			  VAR __Valor =
			 SUMX(
			     SUMMARIZECOLUMNS(
			         VIEW_NLR_FACT_BI_TRANS_PL[CURRENCY_RATE_KEY],
			         "BALANCE", SUM(VIEW_NLR_FACT_BI_TRANS_PL[VALUE])
			     ),
			     DIVIDE([BALANCE],
			     COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_BDT], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_BI_TRANS_PL[CURRENCY_RATE_KEY]), 1)
			     )
			 )
			
			 VAR __Unidades =
			 SUMX(
			     FILTER(
			         SUMMARIZECOLUMNS(
			             VIEW_NLR_FACT_BI_TRANS_PL[CURRENCY_RATE_KEY],
			             VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE],
			             "BALANCE", SUM(VIEW_NLR_FACT_BI_TRANS_PL[VALUE])
			         ),
			         VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE] = 15
			     ),
			     DIVIDE(
			         [BALANCE],
			         COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_BDT], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_BI_TRANS_PL[CURRENCY_RATE_KEY]), 1)
			     )
			 )
			
			 RETURN
			
			 IF(
			     SELECTEDVALUE(VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE]) = 15,
			     __Unidades,
			     __Valor - __Unidades
			 )
			```
		formatString: #,0
		isHidden
		displayFolder: FIN\DR PL\BDT\Real
		lineageTag: de8395a9-5f5a-4def-9077-884ac64423a0

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'DR PL Bgt (BDT) %' = ```
			
			
			VAR __Valor = [DR PL Bgt (BDT)]
			 
			VAR __ValorVendas =
			CALCULATE(
			    [DR PL Bgt (BDT)],
			    VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE] = 16,
			    ALL(VIEW_NLR_DIM_PL),
			    ALL(VIEW_NLR_DIM_ACTIVITIES)
			)
			VAR __ValorVendasWActivity =
			CALCULATE(
			    [DR PL Bgt (BDT)],
			    ALL(VIEW_NLR_DIM_PL),
			    VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE] = 16
			)
			 
			RETURN
			
			SWITCH(
			        TRUE(),
			        SELECTEDVALUE(VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE]) = 16, DIVIDE(__Valor, __ValorVendas),
			        SELECTEDVALUE(VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE]) <> 15, DIVIDE(__Valor, __ValorVendasWActivity)
			)
			```
		formatString: 0.0%;-0.0%;0.0%
		isHidden
		displayFolder: FIN\DR PL\BDT\Budget
		lineageTag: 7078013e-3857-496f-b063-2a48cb7d3fdf

		changedProperty = IsHidden

	measure 'DR PL Bgt Adm (BDT) %' = ```
			
			
			VAR __Valor = [DR PL Bgt Adm (BDT)]
			 
			VAR __ValorVendas =
			CALCULATE(
			    [DR PL Bgt Adm (BDT)],
			    VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE] = 16,
			    ALL(VIEW_NLR_DIM_PL),
			    ALL(VIEW_NLR_DIM_ACTIVITIES)
			)
			VAR __ValorVendasWActivity =
			CALCULATE(
			    [DR PL Bgt Adm (BDT)],
			    ALL(VIEW_NLR_DIM_PL),
			    VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE] = 16
			)
			 
			RETURN
			
			SWITCH(
			        TRUE(),
			        SELECTEDVALUE(VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE]) = 16, DIVIDE(__Valor, __ValorVendas),
			        SELECTEDVALUE(VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE]) <> 15, DIVIDE(__Valor, __ValorVendasWActivity)
			)
			```
		formatString: 0.0%;-0.0%;0.0%
		isHidden
		displayFolder: FIN\DR PL\BDT\Budget
		lineageTag: 011ac54d-f0c3-4690-9ff5-8bfabc3f174a

		changedProperty = IsHidden

	measure 'DR PL CY (BDT) %' = ```
			
			
			VAR __Valor = [DR PL CY (BDT)]
			 
			VAR __ValorVendas =
			CALCULATE(
			    [DR PL CY (BDT)],
			    VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE] = 16,
			    ALL(VIEW_NLR_DIM_PL),
			    ALL(VIEW_NLR_DIM_ACTIVITIES)
			)
			VAR __ValorVendasWActivity =
			CALCULATE(
			    [DR PL CY (BDT)],
			    ALL(VIEW_NLR_DIM_PL),
			    VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE] = 16
			)
			 
			RETURN
			
			SWITCH(
			        TRUE(),
			        SELECTEDVALUE(VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE]) = 16, DIVIDE(__Valor, __ValorVendas),
			        SELECTEDVALUE(VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE]) <> 15, DIVIDE(__Valor, __ValorVendasWActivity)
			)
			```
		formatString: 0.0%;-0.0%;0.0%
		isHidden
		displayFolder: FIN\DR PL\BDT\Real
		lineageTag: 42636d7d-133c-4331-8109-dadda5d5dcd2

		changedProperty = IsHidden

	measure 'DR PL Delta Bgt (BDT)' =
			
			
			VAR __bgt = [DR PL Bgt (BDT)]
			
			RETURN
			IF(
			    __bgt <> 0,
			    [DR PL CY (BDT)] - __bgt
			)
		formatString: #,0
		isHidden
		displayFolder: FIN\DR PL\BDT\Budget
		lineageTag: 05d62cc0-f0ae-4a6e-9150-29b6c73b2227

		changedProperty = IsHidden

	measure 'DR PL Delta Bgt (BDT) %' =
			
			
			DIVIDE(
			    TRUNC([DR PL Delta Bgt (BDT)]),
			    TRUNC(ABS([DR PL Bgt (BDT)])),
			    0
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: FIN\DR PL\BDT\Budget
		lineageTag: 27031825-da10-4987-9462-47e88145bebd

		changedProperty = IsHidden

	measure 'DR PL Delta Bgt Adm (BDT)' =
			
			
			VAR __bgt = [DR PL Bgt Adm (BDT)]
			
			RETURN
			IF(
			    __bgt <> 0,
			    [DR PL CY (BDT)] - __bgt
			)
		formatString: #,0
		isHidden
		displayFolder: FIN\DR PL\BDT\Budget
		lineageTag: a15f4875-25f5-4c35-b3f1-2389f3a2a3c5

		changedProperty = IsHidden

	measure 'DR PL Delta Bgt Adm (BDT) %' =
			
			
			DIVIDE(
			    TRUNC([DR PL Delta Bgt Adm (BDT)]),
			    TRUNC(ABS([DR PL Bgt Adm (BDT)])),
			    0
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: FIN\DR PL\BDT\Budget
		lineageTag: b34515e2-d3fe-403f-a0c6-11e9febf3714

		changedProperty = IsHidden

	measure 'DR PL Delta LY (BDT)' =
			
			
			VAR __ly = [DR PL LY (BDT)]
			
			RETURN
			IF(
			    __ly <> 0,
			    [DR PL CY (BDT)] - __ly
			)
		formatString: #,0
		isHidden
		displayFolder: FIN\DR PL\BDT\Real
		lineageTag: 162d9a2c-58f6-43ab-b427-37803f1c5070

		changedProperty = IsHidden

	measure 'DR PL Delta LY (BDT) %' =
			
			
			DIVIDE(
			    TRUNC([DR PL Delta LY (BDT)]),
			    TRUNC(ABS([DR PL LY (BDT)])),
			    0
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: FIN\DR PL\BDT\Real
		lineageTag: 07b0040b-8b42-481e-bb49-12d81b05cc0f

		changedProperty = IsHidden

	measure 'DR PL LY (BDT)' = ```
			
			
			-- Retorna os períodos fechados por plataforma
			VAR __ClosedPeriods = 
			    SUMMARIZECOLUMNS(
			        VIEW_GBL_DIM_CLIENTS[CLIENT_ID],
			        "CLOSED_PERIOD", MAX(VIEW_NLR_SETUP_CLOSED_PERIODS_USERS[NLR_CLOSEDDATE])
			    )
			-- Retorna os meses do calendário
			VAR __Calendar = 
			    SUMMARIZECOLUMNS(
			        VIEW_GBL_DIM_CALENDAR[SOMONTH]
			    )
			-- Cria uma tabela unindo as plataformas e os meses e em seguida retorna histórico dos meses fechados por plataforma
			VAR __FinalTable =
			    FILTER(
			        CROSSJOIN(
			            __ClosedPeriods,
			            __Calendar
			        ),
			        VIEW_GBL_DIM_CALENDAR[SOMONTH] <= [CLOSED_PERIOD]
			    )
			-- Armazena o valor dos períodos fechados
			VAR __ClosedPeriodValue =
			    SUMX(
			        __FinalTable,
			        CALCULATE(
			            [DR PL CY (BDT)],
			            SAMEPERIODLASTYEAR(VIEW_GBL_DIM_CALENDAR[DATE])
			        )
			    )
			-- Armazena o valor total
			VAR __TotalPeriodValue =
			    CALCULATE(
			        [DR PL CY (BDT)],
			        SAMEPERIODLASTYEAR(VIEW_GBL_DIM_CALENDAR[DATE])
			    )
			RETURN
			    
			IF(
			    SELECTEDVALUE(VIEW_NLR_DIM_CLOSED_PERIODS[CLOSED_PERIOD]) = 1,
			    __ClosedPeriodValue,
			    __TotalPeriodValue
			)        
			```
		formatString: #,0
		isHidden
		displayFolder: FIN\DR PL\BDT\Real
		lineageTag: 6a17c3ff-f6f9-4c23-a91b-e7325ef363e8

		changedProperty = IsHidden

	measure 'DR PL LY (BDT) %' = ```
			
			
			VAR __Valor = [DR PL LY (BDT)]
			 
			VAR __ValorVendas =
			CALCULATE(
			    [DR PL LY (BDT)],
			    VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE] = 16,
			    ALL(VIEW_NLR_DIM_PL),
			    ALL(VIEW_NLR_DIM_ACTIVITIES)
			)
			VAR __ValorVendasWActivity =
			CALCULATE(
			    [DR PL LY (BDT)],
			    ALL(VIEW_NLR_DIM_PL),
			    VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE] = 16
			)
			 
			RETURN
			
			SWITCH(
			        TRUE(),
			        SELECTEDVALUE(VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE]) = 16, DIVIDE(__Valor, __ValorVendas),
			        SELECTEDVALUE(VIEW_NLR_DIM_PL[PL_LEVEL_1_CODE]) <> 15, DIVIDE(__Valor, __ValorVendasWActivity)
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		isHidden
		displayFolder: FIN\DR PL\BDT\Real
		lineageTag: 4aa98c34-017d-4303-928b-fa3f62035a2b

		changedProperty = IsHidden

	measure 'Indicators DR PL (BDT)' = ```
			
			
			SWITCH(
			    SELECTEDVALUE('PARAMETER_DRPL_INDICADORES'[Id]),
			    1, [DR PL CY (BDT)],
			    2, [DR PL CY (BDT) %],
			    3, [DR PL Bgt (BDT)],
			    4, [DR PL Bgt (BDT) %],
			    5, [DR PL Delta Bgt (BDT)],
			    6, [DR PL Delta Bgt (BDT) %],    
			    7, [DR PL Bgt Adm (BDT)],
			    8, [DR PL Bgt Adm (BDT) %],
			    9, [DR PL Delta Bgt Adm (BDT)],
			    10, [DR PL Delta Bgt Adm (BDT) %],
			    11, [DR PL LY (BDT)],
			    12, [DR PL LY (BDT) %],
			    13, [DR PL Delta LY (BDT)],
			    14, [DR PL Delta LY (BDT) %]
			)
			```
		isHidden
		displayFolder: FIN\DR PL\BDT\Support Measures
		lineageTag: 7d34b727-f9c2-4370-8a2b-83caa711db96

		formatStringDefinition =
				SWITCH(
				    SELECTEDVALUE('PARAMETER_DRPL_INDICADORES'[Id]),
				    1, "#,###,###,###,###",
				    2, "#,##0..0%",
				    3, "#,###,###,###,###",
				    4, "#,##0..0%",
				    5, "#,###,###,###,###",
				    6, "#,##0..0%",
				    7, "#,###,###,###,###",
				    8, "#,##0..0%",
				    9, "#,###,###,###,###",
				    10, "#,##0..0%",
				    11, "#,###,###,###,###",
				    12, "#,##0..0%",
				    13, "#,###,###,###,###",
				    14, "#,##0..0%"
				)

		changedProperty = IsHidden

	measure 'Title - Report' =
			
			
			SWITCH(
			    SELECTEDVALUE(VIEW_GBL_DIM_USER_CULTURE[USER_CULTURE]),
			    "pt-PT", SELECTEDVALUE(PBI_TABLE_REPORTS[pt-PT]),
			    "en-US", SELECTEDVALUE(PBI_TABLE_REPORTS[en-US]),
			    "es-ES", SELECTEDVALUE(PBI_TABLE_REPORTS[es-ES]),
			    "fr-FR", SELECTEDVALUE(PBI_TABLE_REPORTS[fr-FR]),
			    SELECTEDVALUE(PBI_TABLE_REPORTS[en-US])
			)
		isHidden
		displayFolder: _UI\Titles
		lineageTag: faa4690b-6808-479d-9571-ccb82e99e2e5

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Empty Value' = ""
		isHidden
		displayFolder: _UI\Support Measures
		lineageTag: 7b772d0a-52be-49ad-b6f5-9b4b2f78805a

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Title - Vehicles Report' = ```
			
			
			VAR __Indicator =
			    CALCULATE(
			        ISFILTERED(VIEW_VHE_DIM_MEASURES),
			        REMOVEFILTERS(VIEW_VHE_DIM_MEASURES[MEASURE_HIDDEN])
			    )
			VAR __MeasureDesc = 
			    " " &
			    SWITCH(
			        SELECTEDVALUE(VIEW_GBL_DIM_USER_CULTURE[USER_CULTURE]),
			        "pt-PT", 
			            CONCATENATEX(
			                FILTER(
			                    VALUES(VIEW_VHE_DIM_MEASURES[PT_MEASURE_LEVEL_1_DESC]),
			                    NOT(ISBLANK(VIEW_VHE_DIM_MEASURES[PT_MEASURE_LEVEL_1_DESC]))
			                ),
			                VIEW_VHE_DIM_MEASURES[PT_MEASURE_LEVEL_1_DESC],
			                ", "
			            ),
			        "en-US", 
			            CONCATENATEX(
			                FILTER(
			                    VALUES(VIEW_VHE_DIM_MEASURES[EN_MEASURE_LEVEL_1_DESC]),
			                    NOT(ISBLANK(VIEW_VHE_DIM_MEASURES[EN_MEASURE_LEVEL_1_DESC]))
			                ),
			                VIEW_VHE_DIM_MEASURES[EN_MEASURE_LEVEL_1_DESC],
			                ", "
			            ),
			        "es-ES", 
			            CONCATENATEX(
			                FILTER(
			                    VALUES(VIEW_VHE_DIM_MEASURES[ES_MEASURE_LEVEL_1_DESC]),
			                    NOT(ISBLANK(VIEW_VHE_DIM_MEASURES[ES_MEASURE_LEVEL_1_DESC]))
			                ),
			                VIEW_VHE_DIM_MEASURES[ES_MEASURE_LEVEL_1_DESC],
			                ", "
			            ),
			        "fr-FR", 
			            CONCATENATEX(
			                FILTER(
			                    VALUES(VIEW_VHE_DIM_MEASURES[FR_MEASURE_LEVEL_1_DESC]),
			                    NOT(ISBLANK(VIEW_VHE_DIM_MEASURES[FR_MEASURE_LEVEL_1_DESC]))
			                ),
			                VIEW_VHE_DIM_MEASURES[FR_MEASURE_LEVEL_1_DESC],
			                ", "
			            )
			    )
			VAR __QuantityDesc = 
			    SWITCH(
			        SELECTEDVALUE(VIEW_GBL_DIM_USER_CULTURE[USER_CULTURE]),
			        "pt-PT", "Quantidade",
			        "en-US", "Quantity",
			        "es-ES", "Cantidad",
			        "fr-FR", "Quantity"
			    )
			RETURN
			
			COMBINEVALUES(
			    " | ",
			    [Title - Tables],
			    IF(
			        __Indicator,
			        __MeasureDesc,
			        __QuantityDesc
			    )
			)
			```
		isHidden
		displayFolder: _UI\Titles
		lineageTag: aaa32810-055a-4abb-bbb9-3032a5e5e9af

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'HRE_C Delta LY' =
			
			
			VAR __ly = [HRE_C LY]
			
			RETURN
			IF(
			    __ly <> 0,
			    [HRE_C CY] - __ly
			)
		formatString: #,0
		displayFolder: FIN\HRE COST\CR\Real
		lineageTag: 396da063-bec0-4bad-9baa-ced4ea28951c

	measure 'HRE_C Delta Bgt' =
			
			
			VAR __bgt = [HRE_C Bgt]
			
			RETURN
			IF(
			    __bgt <> 0,
			    [HRE_C CY] - __bgt
			)
		formatString: #,0
		displayFolder: FIN\HRE COST\CR\Budget
		lineageTag: 7ce50e8f-3935-4257-9040-95842052f7b2

	measure 'HRE_C Delta Bgt Adm' =
			
			
			VAR __bgt = [HRE_C Bgt Adm]
			
			RETURN
			IF(
			    __bgt <> 0,
			    [HRE_C CY] - __bgt
			)
		formatString: #,0
		displayFolder: FIN\HRE COST\CR\Budget
		lineageTag: 95dfc6bb-3149-4c37-bed9-4a35b04eeee5

	measure 'HRE_C Delta Bgt (EUR)' =
			
			
			VAR __bgt = [HRE_C Bgt (EUR)]
			
			RETURN
			IF(
			    __bgt <> 0,
			    [HRE_C CY (EUR)] - __bgt
			)
		formatString: #,0
		isHidden
		displayFolder: FIN\HRE COST\EUR\Budget
		lineageTag: 38597736-5e69-4df4-915d-1907a97bb7ee

		changedProperty = IsHidden

	measure 'HRE_C Delta Bgt Adm (EUR)' =
			
			
			VAR __bgt = [HRE_C Bgt Adm (EUR)]
			
			RETURN
			IF(
			    __bgt <> 0,
			    [HRE_C CY (EUR)] - __bgt
			)
		formatString: #,0
		isHidden
		displayFolder: FIN\HRE COST\EUR\Budget
		lineageTag: 16575510-94ec-4e00-97e0-21098efd2c55

		changedProperty = IsHidden

	measure 'HRE_C Delta LY (EUR)' =
			
			
			VAR __ly = [HRE_C LY (EUR)]
			
			RETURN
			IF(
			    __ly <> 0,
			    [HRE_C CY (EUR)] - __ly
			)
		formatString: #,0
		isHidden
		displayFolder: FIN\HRE COST\EUR\Real
		lineageTag: 71a8ee83-4d98-4923-8714-ec5e215eb084

		changedProperty = IsHidden

	measure 'Payment CY (EUR)' =
			
			
			SUMX(
			    SUMMARIZECOLUMNS(
			        VIEW_SLR_FACT_PAYMENT_METHOD[CURRENCY_RATE_KEY],
			        "BALANCE", SUM(VIEW_SLR_FACT_PAYMENT_METHOD[PAID_VALUE])
			    ),
			    DIVIDE([BALANCE],
			    COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_SLR_FACT_PAYMENT_METHOD[CURRENCY_RATE_KEY]), 1)
			    )
			)
		displayFolder: FIN\PAYMENT\EUR\Real
		lineageTag: c081ebe1-8ec1-4820-8312-26718934783a

	measure 'Payment CY % (EUR)' = ```
			
			VAR __total = 
			CALCULATE(
			    [Payment CY (EUR)],
			    ALL(VIEW_SLR_DIM_PAYMENT_METHODS[PT_PAYMENT_METHOD_DESC]),
			    ALL(VIEW_SLR_DIM_PAYMENT_METHODS[EN_PAYMENT_METHOD_DESC]),
			    ALL(VIEW_SLR_DIM_PAYMENT_METHODS[ES_PAYMENT_METHOD_DESC]),
			    ALL(VIEW_SLR_DIM_PAYMENT_METHODS[FR_PAYMENT_METHOD_DESC]),
			    ALL(VIEW_SLR_DIM_PAYMENT_METHODS[PT_PAYMENT_METHOD_SOURCE]),
			    ALL(VIEW_SLR_DIM_PAYMENT_METHODS[EN_PAYMENT_METHOD_SOURCE]),
			    ALL(VIEW_SLR_DIM_PAYMENT_METHODS[ES_PAYMENT_METHOD_SOURCE]),
			    ALL(VIEW_SLR_DIM_PAYMENT_METHODS[FR_PAYMENT_METHOD_SOURCE])
			)
			
			RETURN
			DIVIDE(
			    [Payment CY (EUR)],
			    __total
			)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: FIN\PAYMENT\EUR\Real
		lineageTag: e95cd7c6-9445-4d36-b825-b1ec6715d369

	measure 'BL ES Origin' = ```
			
			
			VAR __SelectedMonth = HASONEVALUE(VIEW_GBL_DIM_CALENDAR[MONTH]) -- Avalia se existe somente um mês contextualizado
			VAR __SelectedYear = HASONEVALUE(VIEW_GBL_DIM_CALENDAR[YEAR]) -- Avalia se existe somente um ano contextualizado
			
			VAR __Year = YEAR(MAX(VIEW_NLR_FACT_BI_BL[ANALYSIS_DATE])) -- Retorna o último ano contextualizado (Para contornar os casos onde o usuário selecionar mais de um ano)
			VAR __Month = MONTH(MAX(VIEW_NLR_FACT_BI_BL[ANALYSIS_DATE])) -- Retorna o último mês contextualizado (Para contornar os casos onde o usuário selecionar mais de um mês)
			
			RETURN
			
			SWITCH(
			    TRUE(),
			    -- Retorna o valor do mês/ano contextualizado, se estiver contextualizado/filtrado apenas um ano e mês.
			    __SelectedYear && __SelectedMonth,
			        SUM(VIEW_NLR_FACT_BI_BL[BALANCE_FISCAL_ES]),
			
			    -- Retorna o valor do último mês com dados do ano contextualizado, se estiver contextualizado/filtrado apenas um ano.
			    __SelectedYear && NOT(__SelectedMonth),
			        CALCULATE(
			            SUM(VIEW_NLR_FACT_BI_BL[BALANCE_FISCAL_ES]),
			            MONTH(VIEW_NLR_FACT_BI_BL[ANALYSIS_DATE]) = __Month
			        ),
			
			    -- Retorna o valor do mês contextualizado do ano atual, se estiver contextualizado/filtrado apenas um mês.
			    __SelectedMonth && NOT(__SelectedYear),
			        CALCULATE(
			            SUM(VIEW_NLR_FACT_BI_BL[BALANCE_FISCAL_ES]),
			            YEAR(VIEW_NLR_FACT_BI_BL[ANALYSIS_DATE]) = __Year
			        ),
			    
			    -- Retorna o valor do último mês com dados do ano atual, se não estiver contextualizado/filtrado apenas ano e mês.
			        CALCULATE(
			            SUM(VIEW_NLR_FACT_BI_BL[BALANCE_FISCAL_ES]),
			            YEAR(VIEW_NLR_FACT_BI_BL[ANALYSIS_DATE]) = __Year,
			            MONTH(VIEW_NLR_FACT_BI_BL[ANALYSIS_DATE]) = __Month
			        )
			)
			```
		displayFolder: FIN\BL ES\LC\Real
		lineageTag: e7a4b0c2-33ac-4edd-bb59-f4a975e468ed

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'BL ES Origin (EUR)' = ```
			
			 
			VAR __SelectedMonth = HASONEVALUE(VIEW_GBL_DIM_CALENDAR[MONTH]) -- Avalia se existe somente um mês contextualizado
			VAR __SelectedYear = HASONEVALUE(VIEW_GBL_DIM_CALENDAR[YEAR]) -- Avalia se existe somente um ano contextualizado
			
			VAR __Year = YEAR(MAX(VIEW_NLR_FACT_BI_BL[ANALYSIS_DATE])) -- Retorna o último ano contextualizado (Para contornar os casos onde o usuário selecionar mais de um ano)
			VAR __Month = MONTH(MAX(VIEW_NLR_FACT_BI_BL[ANALYSIS_DATE])) -- Retorna o último mês contextualizado (Para contornar os casos onde o usuário selecionar mais de um mês)
			
			RETURN
			
			SWITCH(
			    TRUE(),
			    -- Retorna o valor do mês/ano contextualizado, se estiver contextualizado/filtrado apenas um ano e mês.
			    __SelectedYear && __SelectedMonth,
			        SUMX(
			            SUMMARIZECOLUMNS(
			                VIEW_NLR_FACT_BI_BL[CURRENCY_RATE_KEY],
			                "BALANCE", SUM(VIEW_NLR_FACT_BI_BL[BALANCE_FISCAL_ES])
			            ),
			            DIVIDE(
			                [BALANCE],
			                COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_EOM], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_BI_BL[CURRENCY_RATE_KEY]), 1)
			            )
			        ),
			
			    -- Retorna o valor do último mês com dados do ano contextualizado, se estiver contextualizado/filtrado apenas um ano.
			    __SelectedYear && NOT(__SelectedMonth),
			        SUMX(
			            FILTER(
			                SUMMARIZECOLUMNS(
			                    VIEW_NLR_FACT_BI_BL[CURRENCY_RATE_KEY],
			                    VIEW_NLR_FACT_BI_BL[ANALYSIS_DATE],
			                    "BALANCE", SUM(VIEW_NLR_FACT_BI_BL[BALANCE_FISCAL_ES])
			                ),
			                MONTH(VIEW_NLR_FACT_BI_BL[ANALYSIS_DATE]) = __Month
			            ),
			            DIVIDE([BALANCE],
			            COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_EOM], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_BI_BL[CURRENCY_RATE_KEY]), 1)
			            )
			        ),
			
			    -- Retorna o valor do mês contextualizado do ano atual, se estiver contextualizado/filtrado apenas um mês.
			    __SelectedMonth && NOT(__SelectedYear),
			        SUMX(
			            FILTER(
			                SUMMARIZECOLUMNS(
			                    VIEW_NLR_FACT_BI_BL[CURRENCY_RATE_KEY],
			                    VIEW_NLR_FACT_BI_BL[ANALYSIS_DATE],
			                    "BALANCE", SUM(VIEW_NLR_FACT_BI_BL[BALANCE_FISCAL_ES])
			                ),
			                YEAR(VIEW_NLR_FACT_BI_BL[ANALYSIS_DATE]) = __Year
			            ),
			            DIVIDE([BALANCE],
			            COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_EOM], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_BI_BL[CURRENCY_RATE_KEY]), 1)
			            )
			        ),
			    
			    -- Retorna o valor do último mês com dados do ano atual, se não estiver contextualizado/filtrado apenas ano e mês.
			        SUMX(
			            FILTER(
			                SUMMARIZECOLUMNS(
			                    VIEW_NLR_FACT_BI_BL[CURRENCY_RATE_KEY],
			                    VIEW_NLR_FACT_BI_BL[ANALYSIS_DATE],
			                    "BALANCE", SUM(VIEW_NLR_FACT_BI_BL[BALANCE_FISCAL_ES])
			                ),
			            YEAR(VIEW_NLR_FACT_BI_BL[ANALYSIS_DATE]) = __Year && MONTH(VIEW_NLR_FACT_BI_BL[ANALYSIS_DATE]) = __Month
			            ),
			            DIVIDE([BALANCE],
			            COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_EOM], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_NLR_FACT_BI_BL[CURRENCY_RATE_KEY]), 1)
			            )
			        )
			)
			```
		isHidden
		displayFolder: FIN\BL ES\EUR\Real
		lineageTag: ecdd922a-1438-4faf-bf71-b9b8c51a6f7e

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'VHE Sales Bgt Origin' = ```
			
			
			VAR __Indicator =
			    CALCULATE(
			        ISFILTERED(VIEW_VHE_DIM_MEASURES),
			        REMOVEFILTERS(VIEW_VHE_DIM_MEASURES[MEASURE_HIDDEN])
			    )
			RETURN
			
			IF(
			    __Indicator, 
			    SWITCH(
			            SELECTEDVALUE(VIEW_VHE_DIM_MEASURES[MEASURE_CODE]),
			                -- Rúbricas calculadas
			                9962, [Gross Margin After Commissions and Others Bgt %],
			                9963, [Gross Margin Bgt % (Turnover/Sales)],
			                9964, [Gross Margin Bgt %],
			                9965, [Variable Margin Bgt %],
			                9966, [Variable Margin - Importer Bgt %],
			                9967, [Fixed Margin Bgt %],
			                9968, [Campaigns/Incentives Bgt %],
			                9969, [Invoice Discount Bgt %],
			                9970, [Net Discount Bgt %],
			                    
			                -- Rúbricas de valor
			
			                SWITCH(
			                    TRUE(),
			
			                    -- Level 3
			                    ISINSCOPE(VIEW_VHE_DIM_MEASURES[PT_MEASURE_LEVEL_3_DESC]) ||
			                    ISINSCOPE(VIEW_VHE_DIM_MEASURES[EN_MEASURE_LEVEL_3_DESC]) ||
			                    ISINSCOPE(VIEW_VHE_DIM_MEASURES[ES_MEASURE_LEVEL_3_DESC]) ||
			                    ISINSCOPE(VIEW_VHE_DIM_MEASURES[FR_MEASURE_LEVEL_3_DESC]),
			                    CALCULATE(
			                        SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE]),
			                        VIEW_VHE_DIM_MEASURES[REPORT_LEVEL] = 3
			                    ),
			
			                    -- Level 2
			                    ISINSCOPE(VIEW_VHE_DIM_MEASURES[PT_MEASURE_LEVEL_2_DESC]) ||
			                    ISINSCOPE(VIEW_VHE_DIM_MEASURES[EN_MEASURE_LEVEL_2_DESC]) ||
			                    ISINSCOPE(VIEW_VHE_DIM_MEASURES[ES_MEASURE_LEVEL_2_DESC]) ||
			                    ISINSCOPE(VIEW_VHE_DIM_MEASURES[FR_MEASURE_LEVEL_2_DESC]),
			                    CALCULATE(
			                        SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE]),
			                        VIEW_VHE_DIM_MEASURES[REPORT_LEVEL] = 2 || ISBLANK(VIEW_VHE_DIM_MEASURES[PARENT_MEASURE_CODE])
			                    ),
			
			                    -- Level 1
			                    ISINSCOPE(VIEW_VHE_DIM_MEASURES[PT_MEASURE_LEVEL_1_DESC]) ||
			                    ISINSCOPE(VIEW_VHE_DIM_MEASURES[EN_MEASURE_LEVEL_1_DESC]) ||
			                    ISINSCOPE(VIEW_VHE_DIM_MEASURES[ES_MEASURE_LEVEL_1_DESC]) ||
			                    ISINSCOPE(VIEW_VHE_DIM_MEASURES[FR_MEASURE_LEVEL_1_DESC]),
			                    CALCULATE(
			                        SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE]),
			                        VIEW_VHE_DIM_MEASURES[REPORT_LEVEL] = 1 || ISBLANK(VIEW_VHE_DIM_MEASURES[PARENT_MEASURE_CODE])
			                    )
			                )
			        ),
			    -- Se não houver nenhum indicador selecionado, retornará as quantidades.    
			    CALCULATE(
			        SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE]),
			        VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9973
			    )
			)
			```
		displayFolder: VHE\SALES\LC\Budget
		lineageTag: 81533e52-beb8-4d96-8f5d-a67ef0c066ca

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'VHE Sales Bgt Origin (EUR)' = ```
			
			
			VAR __Indicator =
			    CALCULATE(
			        ISFILTERED(VIEW_VHE_DIM_MEASURES),
			        REMOVEFILTERS(VIEW_VHE_DIM_MEASURES[MEASURE_HIDDEN])
			    )
			RETURN
			
			IF(
			    __Indicator, 
			    SWITCH(
			        SELECTEDVALUE(VIEW_VHE_DIM_MEASURES[MEASURE_CODE]),
			            -- Rúbricas calculadas
			            9962, [Gross Margin After Commissions and Others Bgt (EUR) %],
			            9963, [Gross Margin Bgt (EUR) % (Turnover/Sales)],
			            9964, [Gross Margin Bgt (EUR) %],
			            9965, [Variable Margin Bgt (EUR) %],
			            9966, [Variable Margin - Importer Bgt (EUR) %],
			            9967, [Fixed Margin Bgt (EUR) %],
			            9968, [Campaigns/Incentives Bgt (EUR) %],
			            9969, [Invoice Discount Bgt (EUR) %],
			            9970, [Net Discount Bgt (EUR) %],
			                
			            -- Rúbricas de valor
			            SWITCH(
			                TRUE(),
			                -- Level 3
			                ISINSCOPE(VIEW_VHE_DIM_MEASURES[PT_MEASURE_LEVEL_3_DESC]) ||
			                ISINSCOPE(VIEW_VHE_DIM_MEASURES[EN_MEASURE_LEVEL_3_DESC]) ||
			                ISINSCOPE(VIEW_VHE_DIM_MEASURES[ES_MEASURE_LEVEL_3_DESC]) ||
			                ISINSCOPE(VIEW_VHE_DIM_MEASURES[FR_MEASURE_LEVEL_3_DESC]),
			                SUMX(
			                    FILTER(
			                        SUMMARIZECOLUMNS(
			                            VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY],
			                            VIEW_VHE_FACT_SALES_BUDGET[VALUE_TYPE_CODE],
			                            VIEW_VHE_DIM_MEASURES[REPORT_LEVEL],
			                            "TOTAL", SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE])
			                        ),
			                        VIEW_VHE_DIM_MEASURES[REPORT_LEVEL] = 3
			                    ),
			                    DIVIDE(
			                        [TOTAL],
			                        COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY]), 1)
			                    )
			                ),
			
			                -- Level 2
			                ISINSCOPE(VIEW_VHE_DIM_MEASURES[PT_MEASURE_LEVEL_2_DESC]) ||
			                ISINSCOPE(VIEW_VHE_DIM_MEASURES[EN_MEASURE_LEVEL_2_DESC]) ||
			                ISINSCOPE(VIEW_VHE_DIM_MEASURES[ES_MEASURE_LEVEL_2_DESC]) ||
			                ISINSCOPE(VIEW_VHE_DIM_MEASURES[FR_MEASURE_LEVEL_2_DESC]),
			                SUMX(
			                    FILTER(
			                        SUMMARIZECOLUMNS(
			                            VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY],
			                            VIEW_VHE_FACT_SALES_BUDGET[VALUE_TYPE_CODE],
			                            VIEW_VHE_DIM_MEASURES[REPORT_LEVEL],
			                            VIEW_VHE_DIM_MEASURES[PARENT_MEASURE_CODE],
			                            "TOTAL", SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE])
			                        ),
			                        VIEW_VHE_DIM_MEASURES[REPORT_LEVEL] = 2 || ISBLANK(VIEW_VHE_DIM_MEASURES[PARENT_MEASURE_CODE])
			                    ),
			                    DIVIDE(
			                        [TOTAL],
			                        COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY]), 1)
			                    )
			                ),
			
			                -- Level 1
			                ISINSCOPE(VIEW_VHE_DIM_MEASURES[PT_MEASURE_LEVEL_1_DESC]) ||
			                ISINSCOPE(VIEW_VHE_DIM_MEASURES[EN_MEASURE_LEVEL_1_DESC]) ||
			                ISINSCOPE(VIEW_VHE_DIM_MEASURES[ES_MEASURE_LEVEL_1_DESC]) ||
			                ISINSCOPE(VIEW_VHE_DIM_MEASURES[FR_MEASURE_LEVEL_1_DESC]),
			                SUMX(
			                    FILTER(
			                        SUMMARIZECOLUMNS(
			                            VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY],
			                            VIEW_VHE_FACT_SALES_BUDGET[VALUE_TYPE_CODE],
			                            VIEW_VHE_DIM_MEASURES[REPORT_LEVEL],
			                            VIEW_VHE_DIM_MEASURES[PARENT_MEASURE_CODE],
			                            "TOTAL", SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE])
			                        ),
			                        VIEW_VHE_DIM_MEASURES[REPORT_LEVEL] = 1 || ISBLANK(VIEW_VHE_DIM_MEASURES[PARENT_MEASURE_CODE])
			                    ),
			                    DIVIDE(
			                        [TOTAL],
			                        COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY]), 1)
			                    )
			                )
			        )
			    ),
			    -- Se não houver nenhum indicador selecionado, retornará as quantidades.  
			    SUMX(
			        FILTER(
			            SUMMARIZECOLUMNS(
			                VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY],
			                VIEW_VHE_FACT_SALES_BUDGET[VALUE_TYPE_CODE],
			                VIEW_VHE_DIM_MEASURES[MEASURE_CODE],
			                "TOTAL", SUM(VIEW_VHE_FACT_SALES_BUDGET[VALUE])
			            ),
			            VIEW_VHE_DIM_MEASURES[MEASURE_CODE] = 9973
			        ),
			        DIVIDE(
			            [TOTAL],
			            COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_VHE_FACT_SALES_BUDGET[CURRENCY_RATE_KEY]), 1)
			        )
			    )
			)
			```
		displayFolder: VHE\SALES\EUR\Budget
		lineageTag: b90235fd-d2c8-4455-be22-e56fed80731c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'VHE PRD CY' = SUM(VIEW_VHE_FACT_PRODUCTION[QUANTITY])
		formatString: #,0
		displayFolder: VHE\PRD
		lineageTag: 1e5d63a8-e216-4d6b-8aac-d8c88c55eb7a

	measure 'Indicators VHE PRD' =
			
			
			SWITCH(
			    SELECTEDVALUE(PARAMETER_VHE_PRD_INDICADORES[Id]),
			    1, [VHE PRD CY],
			    2, [VHE PRD LY],
			    3, [VHE PRD Delta LY],
			    4, [VHE PRD Delta LY %]
			)
		displayFolder: VHE\PRD
		lineageTag: 7c8d94e4-0e10-47a4-852e-7a43ddde058a

		formatStringDefinition =
				SWITCH(
				    SELECTEDVALUE(PARAMETER_VHE_PRD_INDICADORES[Id]),
				    1, "#,###,###,###,###",
				    2, "#,###,###,###,###",
				    3, "#,###,###,###,###",
				    4, "#,##0.0%"
				)

	measure 'VHE PRD Delta LY' =
			
			[VHE PRD CY]-[VHE PRD LY]
		formatString: #,0
		displayFolder: VHE\PRD
		lineageTag: e2501b04-27e5-4621-b912-1cb7aa7d6e52

	measure 'VHE PRD Delta LY %' =
			
			DIVIDE(
			    [VHE PRD Delta LY],
			    [VHE PRD LY]
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		displayFolder: VHE\PRD
		lineageTag: 54592116-161f-48cc-97a0-11b1f5923714

	measure 'VHE PRD LY' =
			
			CALCULATE(
			    [VHE PRD CY],
			    SAMEPERIODLASTYEAR(VIEW_GBL_DIM_CALENDAR[DATE])
			)
		formatString: #,0
		displayFolder: VHE\PRD
		lineageTag: 49aab54e-14f3-4344-9aec-e7dbc9bfe4bc

	measure 'Cabeçalhos VHE PRD' =
			
			CALCULATE(
			    SUM(VIEW_VHE_FACT_PRODUCTION[QUANTITY]),
			    ALL(CALCGROUP_CURRENCY),
			    REMOVEFILTERS(CALCGROUP_CURRENCY)
			)
		displayFolder: _UI\Cabeçalhos
		lineageTag: 9ad2e857-7bd8-4f93-a293-8683cd5a7667

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Conditional Format - VHE PRD' =
			
			IF(
			    SELECTEDVALUE(PARAMETER_VHE_PRD_INDICADORES[Id]) IN {3, 4},
			    [Indicators VHE PRD]
			)
		displayFolder: _UI\Format
		lineageTag: adc6db45-69db-41f8-bc8d-6aaaa34ad287

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'VHE QTY CY' =
			
			CALCULATE(
			    SUM(VIEW_RTG_FACT_RENTING_SALES[QUANTITY_VEHICLES]),
			    VIEW_RTG_FACT_RENTING_SALES[VALUE_TYPE_CODE] = 2
			)
		formatString: #,0
		displayFolder: VHE\INVOICES\QTY
		lineageTag: dae94bea-8b25-431c-b50d-85fffff0a3ed

	measure 'VHE QTY LY' =
			
			CALCULATE(
			    [VHE QTY CY],
			    SAMEPERIODLASTYEAR(VIEW_GBL_DIM_CALENDAR[DATE])
			)
		formatString: #,0
		displayFolder: VHE\INVOICES\QTY
		lineageTag: ba0d431e-60d8-4020-ad50-6486ade2c3fa

	measure 'VHE DOC CY' =
			
			CALCULATE(
			    SUM(VIEW_RTG_FACT_RENTING_SALES[QUANTITY_DOCUMENTS]),
			    VIEW_RTG_FACT_RENTING_SALES[VALUE_TYPE_CODE] = 2
			)
		formatString: #,0
		displayFolder: VHE\INVOICES\DOC
		lineageTag: 13e5851d-921c-40e4-8de1-995e0338eed1

	measure 'VHE DOC LY' =
			
			CALCULATE(
			    [VHE DOC CY],
			    SAMEPERIODLASTYEAR(VIEW_GBL_DIM_CALENDAR[DATE])
			)
		formatString: #,0
		displayFolder: VHE\INVOICES\DOC
		lineageTag: ebfa8fb4-d5cd-42ea-92f3-6f8a5e01308c

	measure 'VHE Value CY' =
			
			CALCULATE(
			    SUM(VIEW_RTG_FACT_RENTING_SALES[SELL_NET_VALUE]),
			    VIEW_RTG_FACT_RENTING_SALES[VALUE_TYPE_CODE] = 2
			)
		formatString: #,0
		displayFolder: VHE\INVOICES\VALUE
		lineageTag: 43ac88d1-17b3-4ee3-a781-520c4e1a2cf5

	measure 'VHE Value LY' =
			
			CALCULATE(
			    [VHE Value CY],
			    SAMEPERIODLASTYEAR(VIEW_GBL_DIM_CALENDAR[DATE])
			)
		formatString: #,0
		displayFolder: VHE\INVOICES\VALUE
		lineageTag: 4af1e05f-74be-477f-b886-9653de8199b2

	measure 'VHE Value CY (EUR)' =
			
			SUMX(
			    FILTER(
			        SUMMARIZECOLUMNS(
			            VIEW_RTG_FACT_RENTING_SALES[CURRENCY_RATE_KEY],
			            VIEW_RTG_FACT_RENTING_SALES[VALUE_TYPE_CODE],
			            "TOTAL", SUM(VIEW_RTG_FACT_RENTING_SALES[SELL_NET_VALUE])
			        ),
			        VIEW_RTG_FACT_RENTING_SALES[VALUE_TYPE_CODE] = 2
			    ),
			    DIVIDE(
			        [TOTAL],
			        COALESCE(LOOKUPVALUE(VIEW_GBL_DTBI_RATES[CURRENCY_RATE_AVG_YTD], VIEW_GBL_DTBI_RATES[CURRENCY_RATE_KEY], VIEW_RTG_FACT_RENTING_SALES[CURRENCY_RATE_KEY]), 1)
			    )
			)
		formatString: #,0
		isHidden
		displayFolder: VHE\INVOICES\VALUE\EUR
		lineageTag: ea3cb9f2-d1b3-498c-9202-1cf86ee83280

		changedProperty = IsHidden

	measure 'VHE Value LY (EUR)' =
			
			CALCULATE(
			    [VHE Value CY (EUR)],
			    SAMEPERIODLASTYEAR(VIEW_GBL_DIM_CALENDAR[DATE])
			)
		formatString: #,0
		isHidden
		displayFolder: VHE\INVOICES\VALUE\EUR
		lineageTag: 0601147e-560b-4682-91cf-b5894df7b13c

		changedProperty = IsHidden

	measure 'Indicators VHE Invoices' = ```
			
			
			SWITCH(
			    SELECTEDVALUE(PARAMETER_VHE_INVOICES_INDICADORES[Id]),
			    1, [VHE QTY CY],
			    2, [VHE QTY LY],
			    3, [VHE Value CY],    
			    4, [VHE Value LY],
			    5, [VHE DOC CY],
			    6, [VHE DOC LY]
			)
			```
		formatString: #,0
		displayFolder: VHE\INVOICES\Support Measures
		lineageTag: 64e2fdfd-dc02-4693-acde-b38c786d8d28

	measure 'Indicators VHE Invoices (EUR)' = ```
			
			
			SWITCH(
			    SELECTEDVALUE(PARAMETER_VHE_INVOICES_INDICADORES[Id]),
			    1, [VHE QTY CY],
			    2, [VHE QTY LY],
			    3, [VHE Value CY (EUR)],    
			    4, [VHE Value LY (EUR)],
			    5, [VHE DOC CY],
			    6, [VHE DOC LY]
			)
			```
		formatString: #,0
		isHidden
		displayFolder: VHE\INVOICES\Support Measures
		lineageTag: ae7f9c29-e1ef-48bd-ac77-bd08b5541e54

		changedProperty = IsHidden

	measure 'HRE_C CY TESTE' =
			
			
			SUM(VIEW_NLR_FACT_HRE_COSTS[HRE_COST_VALUE])
		displayFolder: FIN\HRE COST\CR\Real
		lineageTag: c5602e18-3dbf-48b4-93f5-99c2d5269ace

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Conditional Format - HRE_C Indicators' =
			
			
			IF(
			    SELECTEDVALUE('PARAMETER_HRE_C_INDICADORES'[Id]) IN {3,6,9},
			    [Indicators HRE_C]
			)
			
			/*
			    1, [HRE_C CY],
			    2, [HRE_C Bgt],
			    3, [HRE_C Delta Bgt],
			    4, [HRE_C Delta Bgt %],
			    5, [HRE_C Bgt Adm],
			    6, [HRE_C Delta Bgt Adm],
			    7, [HRE_C Delta Bgt Adm %],
			    8, [HRE_C LY],
			    9, [HRE_C Delta LY],
			    10, [HRE_C Delta LY %]
			*/
		displayFolder: _UI\Format
		lineageTag: 884b3c75-d211-445d-8111-db9140d40eb6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MEASURE_TABLE
		dataType: string
		isHidden
		lineageTag: 68709c89-d2e3-4360-9fe8-e1779086f45d
		summarizeBy: none
		sourceColumn: MEASURE_TABLE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition MEASURE_TABLE = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [MEASURE_TABLE = _t])
				in
				    Source

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

	annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ENSURE_TABLES_HAVE_RELATIONSHIPS"]}

